### ISSUE TITLE
client side API requests CORS problem 

### ISSUE THREAD

**Issue by sponnet** [poanetwork/blockscout#1011]
the API endpoint should return a `Access-Control-Allow-Origin: *` header if you want to do cross-domain requests to the API.

### Steps to reproduce

Paste the below code in your browser console to reproduce

```javascript
var xhrObject = new XMLHttpRequest();

xhrObject.onreadystatechange = function() {
  if (xhrObject.readyState === 4) {
    if (xhrObject.status === 200 || xhrObject.status === 304) {
      
      // Success! Do stuff with data.
      console.log(xhrObject.responseText); 
      
    }
  }
};

xhrObject.open(
  "GET", 
  "https://blockscout.com/eth/ropsten/api?module=account&action=txlist&address=0xF7d934776Da4d1734f36d86002dE36954d7Dd528", 
  true
);
xhrObject.send();
```

This results into the following error:
 
`
Failed to load https://blockscout.com/eth/ropsten/api?module=account&action=txlist&address=0xF7d934776Da4d1734f36d86002dE36954d7Dd528: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://....' is therefore not allowed access.
`

### Expected behaviour

the API endpoint should return a `Access-Control-Allow-Origin: *` header in its response.

### Actual behaviour

The header is not present.

**Comment by rstormsf** [comment]
I think they have to implement some sort of API tokens

**Comment by evansjohnson** [comment]
Also running into this while trying to move from Etherscan to Blockscout

**Comment by rstormsf** [comment]
@acravenho 
please reopen this issue.

| Network | Status|
| ------------- | ------------- |
| Mainnet | :white_check_mark: |
| Kovan  | :white_check_mark:|
| Ropsten  | :white_check_mark:|
| POA Core  | :x: |
| POA Sokol  | :x: |
| Rinkeby  | :x: |
| xDai  | :x: |

**Comment by rstormsf** [comment]
```
from origin 'https://multisender.app' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

seems like you have 2 same headers now with same value. only 1 is allowed

**Comment by rstormsf** [comment]
| Network | Status|
| ------------- | ------------- |
| Mainnet | :white_check_mark: |
| Kovan  | :white_check_mark:|
| Ropsten  | :white_check_mark:|
| Görli  | :white_check_mark:|
| POA Core  | :white_check_mark: |
| POA Sokol  | :white_check_mark: |
| Rinkeby  | :white_check_mark: |
| xDai  | :white_check_mark: |

now everything works as expected. thanks @igorbarinov for fixing it up

**Comment by igorbarinov** [comment]
Fixed on haproxy side by replacing add-header to set-header
`http-response set-header Access-Control-Allow-Origin *`
which is replacing header added by blockscout 

No need to re-open it
