### ISSUE TITLE
Homepage Transactions List Flooded tiles

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#1016]
Previously, when more than 5 transactions came in on a single block the user would receive a Twitter-like notification that `n` number of transactions have come in. This feature is no longer seen on the homepage. Instead, we're seeing the page flicker out of control at times when several hundred transactions are coming in at once.

### Environment

* Operating System: Linux

### Steps to reproduce

1. View https://blockscout.com/eth/mainnet
2. Wait for a block to come in.

### Expected behaviour

The user should see the twitter notification.

**Comment by jimmay5469** [comment]
#1049 resolved this
