### ISSUE TITLE
Error fetching block reward contract beneficiaries

### ISSUE THREAD

**Issue by crossoveranx** [poanetwork/blockscout#1017]
Receiving error when initializing block explorer with 'mix phx.server'

11:17:09.776 application=indexer [error] failed to fetch beneficiaries for blocks 131344 - 131335: "Error fetching block reward contract beneficiaries". Retrying block range

Repeated for all blocks.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System: Ubuntu 16.06

### Steps to reproduce

I changed the configuration in indexer and explorer to match my local parity node, namely localhost:8545. I am using a previous version with the same setup and the same node that works fine.

### Expected behaviour

The block explorer should update appropriately on port 4000

### Actual behaviour

Nothing updates when visiting localhost:4000 and no blocks are displayed

**Comment by acravenho** [comment]
@crossoveranx We utilize Parity's `trace_block` to find block rewards and other contracts that may be rewarded for each collated block. You'll have to enable this on your node: https://wiki.parity.io/JSONRPC-trace-module#trace_block

**Comment by acravenho** [comment]
Closing this issue due to no new updates.
