### ISSUE TITLE
Improve token holders count query

### ISSUE THREAD

**Issue by feliperenan** [poanetwork/blockscout#1027]
Now that we have the table `address_current_token_balances` that stores only the current token balance, we can improve the query performance of counting the token holders querying from this table instead of using `address_token_balances`.

https://github.com/poanetwork/blockscout/blob/76d785afe4ac4f246bb1b422e8e9785f6812de3a/apps/explorer/lib/explorer/chain/address/token_balance.ex#L127

**Comment by pasqu4le** [comment]
This was done in #1291
