### ISSUE TITLE
Feature Show unit price with balance on Address Details page - upper-right corner

### ISSUE THREAD

**Issue by 6proof** [poanetwork/blockscout#1051]
*Blockscout no longer shows coin unit price with balance calculation - this was default in POA Explorer.*

### Environment
Any Web interface viewing e.g. https://blockscout.com/poa/core/address

*Please show unit price along with balance to double-check calculation and for posterity.*

**Comment by acravenho** [comment]
Hi @6proof,

Can you please explain the issue more? There is a USD price listed below the balance. Is this what you're referring to?

![price](https://user-images.githubusercontent.com/17620007/48032147-84ed0c00-e124-11e8-8971-7aade1dd9435.png)

**Comment by 6proof** [comment]
Current Balance display shows Total number of POA, Total price in USD.  Unit price (price per POA, for example 10.121323)  is not shown.  This was default behaviour in POA Explorer and useful to verify calculations are correct.  Can price per unit be added back in to balance display please?

**Comment by 6proof** [comment]
Yes, that's the right data.  Might be better to show on separate line with 'unit price' or similar label.
