### ISSUE TITLE
Improve performance - do not include 'tokens' when viewing initial address balance

### ISSUE THREAD

**Issue by 6proof** [poanetwork/blockscout#1054]
*Displaying individual wallet or lists  of  wallets in Blockscout is very slow.  Consider removing 'tokens' import and replacing with static link on initial display to reduce load and improve performance.*

### Environment
Any Operating system - web interface
### Steps to reproduce
access https://blockscout.com/poa/core/accounts - system often times  out completely.

### Expected behaviour
*Accessing above link should provide list of wallets or individual address if appended to link.  Returned data should show list or just single wallet and base coin for blockchain (ETH for Ethereum, POA for POA Network, etc.).*

### Actual behavior
* Current behavior adds "tokens" data in the balance section to show list of other tokens that may be held in wallet.  This seems to be having extreme performance impact.  Consider removing automatic import of 'tokens' and replace with static link button.  If user actually wants to  see tokens  balances, they can click 'tokens' link and information  will be pulled and displayed.*

**Comment by acravenho** [comment]
> I had typo'd the address above, sorry! Corrected above, and here is correct link:
> https://blockscout.com/poa/core/accounts
> Right now this is showing a time-out; link is not functioning.
> "Error 504 Ray ID: 47599aac586a4219 • 2018-11-06 18:26:07 UTC
> Gateway time-out"
This has been fixed on Master. A deployment should happen sometime this week.

**Comment by 6proof** [comment]
Sounds  good.  Will there be an easy way to see list of accounts and balances, perhaps 50 at a time  like POAExplorer had?  Very useful feature for trouble-shooting.

**Comment by acravenho** [comment]
Yes, this will be the end goal to have all addresses in an infinite scroll. For now, we have the top 250 addresses on this page.

**Comment by 6proof** [comment]
I think it would be simpler and less resource  intensive to show addresses 50 at a time with a 'next' button.  I don't think people mind hitting the 'reload' button to check status, which saves resources on both server and client side.

**Comment by acravenho** [comment]
There is no difference between infinite scroll and a next button with regards to resources. Pages will contain 50 addresses similar to all the other pages on the app.

**Comment by 6proof** [comment]
I see. Based on your post above you'd mentioned importing 250 addresses on the page, not 50.   Thank you  for clarification.   When will this list be again available?

**Comment by acravenho** [comment]
This will be available on the next deploy. The first iteration will only list 250 addresses. Following iterations will include the infinite scroll with 50 addresses per page.

**Comment by 6proof** [comment]
Great work Andrew and BlockScout Team!  Thanks for your work.
