### ISSUE TITLE
Pending transactions on address page causing slow page speed

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#1060]
The pending transactions list on the address page is causing extremely slow page load speed on Ethereum Mainnet. A future issue #60 will remove many of these "pending" transactions which are not actually "pending". Many of these transactions are dropped/replaced and would be removed from this list. 

A temporary/fast solution would be to remove these pending transactions from the address page and then add them back with a faster query after #60 is resolved.

* We know the overview section loads fast. It's a constant between fast and slow loading pages. 
* The transaction list on slow loading pages can now easily be tested by infinite scroll. Find a slow loading address page and scroll down to the where the second page should be, it now loads extremely fast. 

The outlier here is the pending transaction list.

### Environment

* Chain: Mainnet

### Steps to reproduce

View https://blockscout.com/eth/mainnet/address/0x4ac6307a85d83962503f86457de9c331a6926f48/transactions

### Expected behaviour

Load under 2 seconds

### Actual behaviour

Extremely slow

**Comment by brwatanabe** [comment]
I tested with this address mentioned in the description and the infinite scroll's page loading are mostly taking around 1.49 to 2.00 seconds.
