### ISSUE TITLE
Return token type from /tokenlist API

### ISSUE THREAD

**Issue by xUpsideDown** [poanetwork/blockscout#1075]
Hi there!

Is it possible to return token type (ERC-20/ERC-721) in the response from /tokenlist API?
If it doesn't bring performance issues to the backend it would be great to get this information from the API.

Thanks!

**Comment by valeryvaskabovich** [comment]
@sabondano Is there any way to get this info via GraphQL API instead of modifying existing REST?

**Comment by vbaranov** [comment]
@saneery let's extend /tokenlist with token type. I guess it shouldn't slow down the API request.

**Comment by saneery** [comment]
@vbaranov could we close this issue?
