### ISSUE TITLE
Add 4xx page for invalid hash error

### ISSUE THREAD

**Issue by brwatanabe** [poanetwork/blockscout#1077]
When someone tries to access a page using an invalid hash, the error below is printed on the screen.

![image](https://user-images.githubusercontent.com/39056251/48226936-20ca8200-e388-11e8-9d49-9a23d3320131.png).

A new behavior was implemented to the invalid transaction hash page that we can see in this PR:
https://github.com/poanetwork/blockscout/pull/1071

This kind treatment still needs to be applied to the following pages:

* Address;
* Token;
* Block;

Basically there are two options:
* Create individual pages for each of the them;
* Create a single template page and gives the title and main message as parameters.

### Steps to reproduce

* https://blockscout.com/eth/mainnet/blocks/0xfd03e727eb26715f73313e338c27e9554d641ba8b1298eb7136ae1420e6da66/transactions
* https://blockscout.com/eth/mainnet/address/0x7ecae7f0c3607564cf45c2761f385e7b6ba31a0/transactions
* https://blockscout.com/eth/mainnet/tokens/0x41a322b28d0ff354040e2cbc676f0320d8c8850/token_transfers

**Comment by acravenho** [comment]
Let's make a single page that reflects an overall message. We do have a custom 404 page design if you would like to use.
