### ISSUE TITLE
Uncle blocks error in indexer

### ISSUE THREAD

**Issue by APshenkin** [poanetwork/blockscout#1083]
*Describe your issue here.*

During explorer running on mainnet I faced error in indexer with uncle blocks. It tries to insert into transaction_forks. But there are already records, so new fail with error:
`iex(1)> 20:51:36.430 application=indexer [error] failed to import 10uncle blocks in step :derive_transaction_forks: %Postgrex.Error{connection_id: 13296, message: nil, postgres: %{code: :unique_violation, constraint: "transaction_forks_uncle_hash_index_index", detail: "Key (uncle_hash, index)=(\\x59d3bd7ddd2e398250b175af8239f6b7ce2364fe0d60e24700c068f941d518d9, 90) already exists.", file: "nbtinsert.c", line: "434", message: "duplicate key value violates unique constraint \"transaction_forks_uncle_hash_index_index\"", pg_code: "23505", routine: "_bt_check_unique", schema: "public", severity: "ERROR", table: "transaction_forks", unknown: "ERROR"}}`

Here is a list of failed uncle hashes:

0x59d3bd7ddd2e398250b175af8239f6b7ce2364fe0d60e24700c068f941d518d9
0x7ee3909c834e37669c2aa644c777082bf76eb471f877fa59eef668dfcfbbb684
0x9e8906abc24bc0c0ed94716a0dfadd470dd3678a3331ce23b23d508527a1ef2e
0xd8754f4b7bb25cad82342aff06dad52cd1e3068cdae6cbd5d8dce3c69f26d36c

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
```
Erlang/OTP 21 [erts-10.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.7.3 (compiled with Erlang/OTP 21)
```
* Operating System:
```
Debian GNU/Linux 9 (stretch)
```

### Steps to reproduce

Just syncing Ethereum mainnet

### Expected behaviour

Process duplicates in uncle blocks corretly (overwrite them or just skip)

### Actual behaviour

A lot of logs in console `duplicate key value violates unique constraint` :)

**Comment by acravenho** [comment]
@APshenkin Thanks for reporting the issue. We'll be covering this issue very soon most likely by dead lettering these blocks at first, marking them as bugs and then resolving the bugs after. 

In the meantime, you can delete these hashes from the `transaction_forks` table to resolve the issue temporarily.

**Comment by APshenkin** [comment]
@acravenho FYI this issue repeats today with uncle hashes:
0x431b83bedd41b5f4a92f2d4e2d72e9370830cdd6f5f03214d7a1805d2f9e7110
0x18e7db54cc90251b75358392567d86575fe35edf7fe464ef53a85a7b4db935e6


Also after several retries to insert this transactions application goes down with memory leak error:
```
iex(1)> eheap_alloc: Cannot allocate 6801972448 bytes of memory (of type "heap").
```

**Comment by acravenho** [comment]
You have to define the max amount of memory to use here: https://github.com/poanetwork/blockscout/blob/61cde269ba2845f30f7ac80b481ab76920b7603f/apps/indexer/config/config.exs#L11 This will check every minute and shrink processes where necessary.

We're aware of the uncle forks issue and have an open issue #919

**Comment by APshenkin** [comment]
Updating to latest release solves memory heap error. Will wait fix for uncle forks.

Thanks!
