### ISSUE TITLE
Stop indexing token balances that always raise errors

### ISSUE THREAD

**Issue by feliperenan** [poanetwork/blockscout#1093]
When fetching token balances, in some networks (e.g Sokol), there are tokens that always will raise errors and we will retry fetch those tokens every time. For instance:

```
16:10:55.745 application=indexer [debug] fetching 1 token balances:
token_hash: 0xacf5610bdc12e310b9b2e222b02b32f0b129694a address_hash: 0x00caa30bb79b3a1cdbdae146e17e0d7d8710b5ef block_number: 5554930

16:10:58.764 application=indexer [debug] fetching 2 token balances:
token_hash: 0xacf5610bdc12e310b9b2e222b02b32f0b129694a address_hash: 0x00caa30bb79b3a1cdbdae146e17e0d7d8710b5ef block_number: 5554796
token_hash: 0xacf5610bdc12e310b9b2e222b02b32f0b129694a address_hash: 0x27836ca9b60e2e1ae13852388edd9a130be81475 block_number: 5554796

16:22:23.392 application=indexer [debug] fetching 3 token balances:
token_hash: 0x7e3a547fdb30241cc91b13dfef83487a303b0193 address_hash: 0x0000000000000000000000000000000000000000 block_number: 5552271
token_hash: 0x7e3a547fdb30241cc91b13dfef83487a303b0193 address_hash: 0x0000000000000000000000000000000000000000 block_number: 5552355
token_hash: 0x7e3a547fdb30241cc91b13dfef83487a303b0193 address_hash: 0x0000000000000000000000000000000000000000 block_number: 5553552
```

For some reason, always that we try to fetch the balance from address: `0x00ca... ` in the smart contract: `0x7e3a...`, it doesn't matter the block number, we will receive the error: `(-32015) VM execution error`.

Also, this error should be logging in `logs/dev/indexer/token_balances/error.log`, but it wasn't.  

### Steps to reproduce

Index the Sokol network (or any other network that has tokens with errors) and look at `logs/dev/indexer.log`. You will see the message `indexer [debug] fetching 1 token balances` and the number `1` will be increased according to tokens that raise errors.

### Expected behavior
- It should be logged in the  `logs/dev/indexer/token_balances/error.log`
- We should stop trying to fetch those tokens

**Comment by acravenho** [comment]
@feliperenan Deadlettering for tokens. This feature is scheduled for the main indexer soon. If we encounter an error on a block instead of trying to fetch the block over and over encountering the same error it will be deadlettered and skipped. I'm not sure how this will be implemented but it will be nice to see on tokens as well :+1:
