### ISSUE TITLE
Infinite scroll does not loads for the first time without scrolling

### ISSUE THREAD

**Issue by amandasposito** [poanetwork/blockscout#1099]
The first one happens when the chrome isn't in full screen. Every time a user accesses a page with infinite scroll for the first time it shows a message that there are no entries for that page, even though it has. And only after the user scrolls the page the list loads.

![async](https://user-images.githubusercontent.com/840531/48506703-2f55e500-e831-11e8-8f62-fb8a491e9730.gif)

**Comment by acravenho** [comment]
Either way but I think it might be better to do it here since that branch is getting quite big. I'll send over some reviewers today for #1008.

**Comment by brwatanabe** [comment]
Since we are going to replace the infinite scroll feature with simple pagination, I'm closing this one because the problem will get solved by itself. (issue #1101 )
