### ISSUE TITLE
Replace infinite scroll of transactions with simple paging - Transaction tab at the address page

### ISSUE THREAD

**Issue by varasev** [poanetwork/blockscout#1101]
For addresses that produce a large number of transactions, it is inconvenient to see all transactions (especially the very first tx). E.g., for this address: https://blockscout.com/poa/core/address/0xb87b6077d59b01ab9fa8cd5a1a21d02a4d60d358/transactions

A user gets tired when he scrolls many times, and he doesn't see the progress (how long should I scroll to see the very first transaction?).

I think it's better to make simple paging as in etherscan.io, e.g., https://etherscan.io/txs?a=0xd819E948b14cA6AAD2b7Ffd333cCDf732b129EeD

The advantages of paging vs. scrolling:
- I see where I'm at the moment (in the middle of the list, in the end, etc.);
- I can quickly switch to the end of the list;
- my browser is not overloaded;
- a scroll bar is not decreased.

**Comment by igorbarinov** [comment]
I agree with Vadim on pagination for accounts with many transactions.
Can we add pagination as an option for accounts with more than n transactions?

**Comment by acravenho** [comment]
Pagination is being added back in on all pages along with our asynchronous loading issues. It was attempted but turns out to be a bad user experience. This issue can be expected to be resolved (PR) in 6-7 development days.
