### ISSUE TITLE
Connect to chain via url?

### ISSUE THREAD

**Issue by GregTheGreek** [poanetwork/blockscout#1110]
*Describe your issue here.*
Looking at how to connect the blockexplorer to a specified chain running on a url ex: `rpc.example.com`. I can't see any config for it within the project.
### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): 1.7.4
* Operating System: OSX

**Comment by acravenho** [comment]
@GregTheGreek 

You'll want to edit the following files to update the RPC Endpoints:

https://github.com/poanetwork/blockscout/blob/cc266dd72828c7efedafc19f18c4ccd3d302ebb1/apps/indexer/config/dev/parity.exs#L9-L23

and 

https://github.com/poanetwork/blockscout/blob/cc266dd72828c7efedafc19f18c4ccd3d302ebb1/apps/explorer/config/dev/parity.exs#L9-L23

It's listed in the README here:

https://github.com/poanetwork/blockscout#configuring-ethereum-classic-and-other-evm-chains

If you're using Geth, please let me know, there is a slight difference when configuring for Geth.

**Comment by GregTheGreek** [comment]
We're using Geth, could you point me in that direction. Are you planning on having a global config to change these settings? I could look into it if it's not already being looked at it.

**Comment by acravenho** [comment]
1. Change this line to `geth`: https://github.com/poanetwork/blockscout/blob/cc266dd72828c7efedafc19f18c4ccd3d302ebb1/apps/explorer/config/dev.exs#L25

2. Change this line to `geth`: https://github.com/poanetwork/blockscout/blob/cc266dd72828c7efedafc19f18c4ccd3d302ebb1/apps/indexer/config/dev.exs#L14

3. Update your RPC Endpoints: https://github.com/poanetwork/blockscout/blob/cc266dd72828c7efedafc19f18c4ccd3d302ebb1/apps/indexer/config/dev/geth.exs#L9-L18

4. Same as :point_up: https://github.com/poanetwork/blockscout/blob/cc266dd72828c7efedafc19f18c4ccd3d302ebb1/apps/explorer/config/dev/geth.exs#L8-L17

In the future, these configs will be located in the admin panel along with all other configuration options. We're currently working on more mission critical issues right now.

**Comment by GregTheGreek** [comment]
Thanks! :)

**Comment by acravenho** [comment]
Closing this issue in lieu of #1114

**Comment by GregTheGreek** [comment]
I noticed there is a `prod` file for all of these, should I be changing those files as well?

**Comment by acravenho** [comment]
If you're running BlockScout in a production environment `export MIX_ENV=prod` you'll want to update the `prod` folder. Otherwise, it will default to the `dev` folder.
