### ISSUE TITLE
Fix NaN in Accounts page

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/blockscout#1120]
![image](https://user-images.githubusercontent.com/9360827/48778196-5eb79680-ecf6-11e8-9ed1-ed62ebcae74d.png)

https://blockscout.com/eth/goerli/accounts

When there are huge account balances, it cannot calculate price in USD

**Comment by acravenho** [comment]
@rstormsf Do you think this should be blank instead, providing no USD value?

**Comment by brianmcmichael** [comment]
We are using ETH value on our network because we're not priced anywhere. Have been looking forward to an implementation of #1195
