### ISSUE TITLE
Postgres  ERROR:  canceling statement due to user request

### ISSUE THREAD

**Issue by wovvan** [poanetwork/blockscout#1132]
* Block explorer is down. error in postgres docker container.
`2018-11-24 13:29:16.523 UTC [11230] ERROR:  canceling statement due to user request
2018-11-24 13:29:16.523 UTC [11230] CONTEXT:  while inserting index tuple (5,31) in relation "addresses"
2018-11-24 13:29:16.523 UTC [11230] STATEMENT:  INSERT INTO "addresses" AS a0 ("hash","inserted_at","updated_at") VALUES ($1,$2,$3) ON CONFLICT ("hash") DO UPDATE SET "contract_code" = COALESCE(a0."contract_code", EXCLUDED.contract_code), "fetched_coin_balance" = CASE WHEN EXCLUDED.fetched_coin_balance_block_number IS NOT NULL AND
                  (a0."fetched_coin_balance_block_number" IS NULL OR
                   EXCLUDED.fetched_coin_balance_block_number >= a0."fetched_coin_balance_block_number") THEN
                    EXCLUDED.fetched_coin_balance
             ELSE a0."fetched_coin_balance"
        END
        , "fetched_coin_balance_block_number" = CASE WHEN EXCLUDED.fetched_coin_balance_block_number IS NOT NULL AND
                  (a0."fetched_coin_balance_block_number" IS NULL OR
                   EXCLUDED.fetched_coin_balance_block_number >= a0."fetched_coin_balance_block_number") THEN
                    EXCLUDED.fetched_coin_balance_block_number
             ELSE a0."fetched_coin_balance_block_number"
        END
         RETURNING "updated_at", "inserted_at", "contract_code", "fetched_coin_balance_block_number", "fetched_coin_balance", "hash"`
* Docker blockscout container has this error
`Function: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/2
    Args: [2237202, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://18.188.49.135:8501", method_to_url: [eth_getBalance: "http://18.188.49.135:8501", trace_replayTransaction: "http://18.188.49.135:8501"], http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Parity], receipts_batch_size: 250, receipts_concurrency: 10}]
16:53:08.538 application=plug request_id=d654f7h8l7ggobvliqp09hldm1gpgv2i [info] GET /
16:53:15.111 [error] Task #PID<0.18955.16> started from Indexer.Block.Realtime.Fetcher terminating
** (stop) exited in: :gen_server.call(Explorer.Repo.Pool, {:checkout, #Reference<0.1076527357.4107272193.86953>, true}, 5000)
    ** (EXIT) time out
    (stdlib) gen_server.erl:223: :gen_server.call/3
    (poolboy) src/poolboy.erl:55: :poolboy.checkout/3
    (db_connection) lib/db_connection/poolboy.ex:41: DBConnection.Poolboy.checkout/2
    (db_connection) lib/db_connection.ex:928: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:750: DBConnection.run/3
    (db_connection) lib/db_connection.ex:798: DBConnection.transaction/3
    (ecto) lib/ecto/repo/queryable.ex:23: Ecto.Repo.Queryable.transaction/4
    (explorer) lib/explorer/chain/import.ex:131: Explorer.Chain.Import.all/1`

### Environment

* your Docker containers

### Steps to reproduce

1. POA network with parity
2. mint blocks time 1sec
3. this error emerge until 1-2 days and eat all CPU.
4. help delete and restart containers

**Comment by KronicDeth** [comment]
As #1129 is now closed and this is related.  This can be closed too.
