### ISSUE TITLE
unknown accounts in private blockchain

### ISSUE THREAD

**Issue by AndreiD** [poanetwork/blockscout#1139]
Hello,
I have a newly created geth private blockchain
with just 1 address funded.

I configure it to it. 
and
it shows up " Indexing Tokens - We're indexing this chain right now. Some of the counts may be inaccurate. "
but I have no tokens to be indexed. 

and some strange accounts with some balances appear

![whatarethis](https://user-images.githubusercontent.com/542665/49078825-bf3f5a00-f247-11e8-9d91-dc2089261302.png)

I tried deleting the database too
mix do ecto.drop, ecto.create, ecto.migrate

no success

Any ideas ?

Thanks for your help

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): latest
* Operating System: ubuntu 16

### Steps to reproduce

connect to private geth blockchain (newly created, with just one address funded)

### Expected behaviour

not to have unknown accounts

### Actual behaviour

unknown accounts appear

**Comment by acravenho** [comment]
A couple questions:

1. Are you using a full Geth node?
2. Did you query the addresses in question using `eth_getBalance`?

The indexing tokens aspect is looking for the last internal transaction to index before removing these status messages.

**Comment by AndreiD** [comment]
1. yes, full geth node
2. for the addresses listed by the explorer they have 0. 
like I said the blockchain is new, and only one address is funded.

**Comment by AndreiD** [comment]
any hints on what's going on there?

**Comment by igorbarinov** [comment]
do you have a public RPC to the node? can use make e.g. u can open it from private network using https://github.com/inconshreveable/ngrok
