### ISSUE TITLE
Import block reward from beneficiaries 

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#1155]
We are querying the Parity `block_trace` call but are not extracting the block rewards from each block. We should start importing this data into the `block_rewards` table. This table should also include a `fetched_at` time which indicates if this process has been completed. `NULL` should be used if we have not received a block reward for a particular block. 

The catchup fetcher should run async looking for any missed block rewards.

**Comment by KronicDeth** [comment]
This has been implemented in #1184 and #1269.
