### ISSUE TITLE
Make the requirement for verifying a smart contract less harsh

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#1158]
On the transaction details page of a contract call, the user is prompted to verify a contract to view the decoded data in the 'Input' section. This message is currently using the `danger` style and because of this, the user may misunderstand its purpose.

Example: https://blockscout.com/eth/mainnet/tx/0x13ca221882a49858fc50fc4c7f33b5d6fdb81e6d56f02cd0b5e80819f5c6f23b/internal_transactions

### Current Behaviour

<img width="1111" alt="screen shot 2018-11-29 at 3 07 57 pm" src="https://user-images.githubusercontent.com/17620007/49248911-e5e8c680-f3e8-11e8-9335-9ce212de0537.png">

### Expected Behaviour

This should be changed to `info` style to appear less like an error.

**Comment by smoey** [comment]
How to verify a contract created by POA's token wizard, I'm a novice.

**Comment by smoey** [comment]
only "SafeMathLibExt" can be verified, CrowdsaleTokenExt and other three contracts can not be veriftied, it shown "here was an error validating your contract, please try again."
