### ISSUE TITLE
Specify the correct settings for each type of node

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#1171]
**Parity**

Enable
```
`--jsonrpc-interface all --jsonrpc-apis web3,eth,net,parity,pubsub,traces --ws-interface all --pruning=archive`
```
Disable
```
personal, signer, parity_accounts, secretstore
```

**Geth**

**Comment by fvictorio** [comment]
I made it work with this flags:

```
--chain chain.json --jsonrpc-interface all --jsonrpc-apis web3,eth,net,parity,pubsub,traces --ws-interface all
```

I think `--pruning=archive` wasn't necessary for me because I used a development chain. I can post the `chain.json` and the `Dockerfile` I'm using if you think it may be useful.

**Comment by acravenho** [comment]
@fvictorio You won't notice that pruning is needed until you get further back in the chain. Pruning is for old blocks which takes a while to notice. For newer chains (under 1M) blocks, pruning is not required.

**Comment by acravenho** [comment]
@natlg Could you provide the settings we use on our Geth nodes?

**Comment by acravenho** [comment]
Completed here: https://forum.poa.network/t/faq-what-settings-are-required-on-a-parity-or-geth-client/1805
