### ISSUE TITLE
Create reward data from the blockchain call

### ISSUE THREAD

**Issue by amandasposito** [poanetwork/blockscout#1177]
Related to #1149

As a developer, I need to start saving the info about the block reward into the database with the proper values received by the validator, emission funds (if any) and uncle (if any).

### How to get the block reward?

The process can change depending on which network we are indexing. For instance, the POA network has emission funds and there are no uncles. Ethereum mainnet, on the other hand, there is no emission funds but there are uncles.

#### POA network
First, we need to identify who is the validation reward and who is the emission reward to calculate their values properly. Given the output:

```
[
  {
    action:{
      callType:'call',
      from:'0x3bd248f352a043097d467ad07e5d5aeefe4ab0ae',
      gas:'0x7d0',
      input:'0x',
      to:'0xf04833ac59ee14227c3d83ad70bb43dcdf87459e',
      value:'0x34de2b29ea463'
    },
    blockHash:'0x546f5412647761251c2112df5e4abc31e32a0f2ba7e60a4df9d685980af423e2',
    blockNumber:5948296,
    result:{ gasUsed:'0x0', output:'0x' },
    subtraces:0,
    traceAddress:[ ],
    transactionHash:'0x0f558e717b1ec8876cc4638587d080fc252101e750611a9696f6e156bc26ae92',
    transactionPosition:0,
    type:'call'
  },
  {
    action:{
      author:'0x09cda85279d3ce6c40d324108197612372a6d132',
      rewardType:'external',
      value:'0xde0b6b3a7640000'
    },
    blockHash:'0x546f5412647761251c2112df5e4abc31e32a0f2ba7e60a4df9d685980af423e2',
    blockNumber:5948296,
    result:null,
    subtraces:0,
    traceAddress: [],
    transactionHash:null,
    transactionPosition:null,
    type:'reward'
  },
  {
    action: {
      author:'0x523b6539ff08d72a6c8bb598af95bf50c1ea839c',
      rewardType:'external',
      value:'0xde0b6b3a7640000'
    },
    blockHash:'0x546f5412647761251c2112df5e4abc31e32a0f2ba7e60a4df9d685980af423e2',
    blockNumber:5948296,
    result:null,
    subtraces:0,
    traceAddress:[],
    transactionHash:null,
    transactionPosition:null,
    type:'reward'
  }
]
```

We rely on the output order (the response from `block_trace` call). The first `action.author` that has the type `reward` is the validator (who mined the block) and the second `action.author` that also has the type `reward` is the emission fund.

In this case, this should be stored as follow:

* The validator will earn the `action.value` + gas in all transactions.
* The emission fund will earn the `action.value`.

#### Ethereum mainnet
Besides the validator, that in this case, is the `action.author` from `rewardType = "block"`, we must store who mined the uncles since they also earned rewards. See the output below as an example:

```
[%{
    "action" => %{
      "author" => "0xea674fdde714fd979de3edf0f56aa9716b898ec8",
      "rewardType" => "block",
      "value" => "0x2c3c465ca58ec000"
    },
    ...
    "blockNumber" => 6844374,
    "type" => "reward"
  },
  %{
    "action" => %{
      "author" => "0x829bd824b016326a401d083b33d092293333a830",
      "rewardType" => "uncle",
      "value" => "0x246ddf9797668000"
    },
    ...
    "blockNumber" => 6844374,
    "type" => "reward"
  },
  %{
    "action" => %{
      "author" => "0xb2930b35844a230f00e51431acae96fe543a0347",
      "rewardType" => "uncle",
      "value" => "0x246ddf9797668000"
    },
    ...
    "blockNumber" => 6844374,
    "type" => "reward"
  }]
```

 In this case, this should be stored as follow:

* The validator (the `action.author` from `rewardType = "block"`) will earn the `action.value` + gas from all transactions.
* Each uncle with their `action.value`

### Acceptance Criteria

* We need to be able to fetch the data below of block rewards from the database:
  * the value received from the validator (who mined the block)
  * the emission funds (if there is one)
  * the value received from who mined the uncle (if there is one)
* We need to store the correct value received by the emission funds, validator, and uncles.
  * The validator will receive 1 static block reward  + Gas used in all transactions mined in the block + uncle reward if any.
  * The emission fund will receive 1 static block reward.
  * The uncle reward when if any.

### Questions?

* ~Can we count that the reward value will always be `1 POA`?~
  * ~Does the emission reward consider the gas used to process the transaction?~
      * The value is the `action.value` from the response above. The emission funds don't earn the gas used, only the validator.
* ~Will the uncle data be in the same `block_trace` call that the transactions mined are?~
    * yes, it will.
* ~How do we populate this data in an indexed network?~
    * ~Do we have all data necessary indexed to make a script migration?~
      * It will be done in another issue https://github.com/poanetwork/blockscout/issues/1198

**Comment by w-sanches** [comment]
@acravenho I looked into the code and the Validator's address hash always comes as the first address in the response, the same that you showed in your comment.

The reason I was seeing a different order is how we transformed these values to be consumed in a later part of the code, so I think we can rely on the second address always being the EmissionFunds with the first being who received the reward.

**Comment by acravenho** [comment]
@feliperenan @w-sanches 

1. The uncle reward is included as `type=reward` in the `trace_block` call.

```
[ { author: '0xea674fdde714fd979de3edf0f56aa9716b898ec8',
    value: 3187500000000000000,
    block: 6844374,
    type: 'reward' },
  { author: '0x829bd824b016326a401d083b33d092293333a830',
    value: 2625000000000000000,
    block: 6844374,
    type: 'reward' },
  { author: '0xb2930b35844a230f00e51431acae96fe543a0347',
    value: 2625000000000000000,
    block: 6844374,
    type: 'reward' } ]
```
2. We may need to make another fetcher that checks the `block_rewards` table for every block number. Probably similar to how we do it with the catchup indexer.

**Comment by w-sanches** [comment]
@acravenho 
This uncle reward raised some new questions. Considering this response (it's the same that you showed, but expanded):

```
[%{
    "action" => %{
      "author" => "0xea674fdde714fd979de3edf0f56aa9716b898ec8",
      "rewardType" => "block",
      "value" => "0x2c3c465ca58ec000"
    },
    ...
    "blockNumber" => 6844374,
    "type" => "reward"
  },
  %{
    "action" => %{
      "author" => "0x829bd824b016326a401d083b33d092293333a830",
      "rewardType" => "uncle",
      "value" => "0x246ddf9797668000"
    },
    ...
    "blockNumber" => 6844374,
    "type" => "reward"
  },
  %{
    "action" => %{
      "author" => "0xb2930b35844a230f00e51431acae96fe543a0347",
      "rewardType" => "uncle",
      "value" => "0x246ddf9797668000"
    },
    ...
    "blockNumber" => 6844374,
    "type" => "reward"
  }]
```

1. The first author here is the block miner, but who are the other two authors? I tried to check the uncle block's page, but their miner was a different address.
2. What does the value where `rewardType => block` mean? Is it the gas used or something similar to emission on POA chain?
3. Is the uncle reward the sum of all the values where `rewardType => uncle`?
3.1. Is this value given to the first author in this example?
3.2. What about the other authors, do they get any reward?

**Comment by acravenho** [comment]
1. An uncle is a block that was mined simultaneously as the consensus block. The miner who won that block may choose to include this orphaned block as an uncle. This uncle miner receives a reward if it's included. This reward is calculated by the number of blocks it's been since it almost won the block. 

2. `rewardType => block` is the miner who collated the block. There is no need to calculate the gas fees for the PoW chains, it's automatically calculated.

3. The reward for the uncles is sent to the uncle author. There is no need to calculate anything for this. 
3.1 No, it's given to the author associated with the reward. 
3.2 Yes, they receive the full reward listed under their action.
