### ISSUE TITLE
Last Block Doesn't Show Via Explorer (Using Parity)

### ISSUE THREAD

**Issue by Dycedlp** [poanetwork/blockscout#1192]
Everything works perfectly, except the last block doesn't get added to the explorer.  

my parity flags are as follows: parity --geth --network-id "" --warp --tracing=on --fat-db=on --pruning=archive --no-discovery --config ~/ethereum/poa/node1.toml --min-gas-price 0 --reseal-max-period 5000000000

### Expected behaviour

To publish all blocks to the explorer, including the last.

### Actual behaviour

Published all blocks to the explorer except for the last.  The block goes through on parity, but doesn't show up on the explorer side.

**Comment by acravenho** [comment]
@Dycedlp There are two indexers, one that fetches previous blocks and another realtime indexer that looks for new blocks coming in through the `newHeads` subscription. The catchup indexer only looks for `block height - 1`. 

https://github.com/poanetwork/blockscout/blob/4701dc04d17b5165eadef357209a173b30a358e7/apps/indexer/lib/indexer/block/catchup/fetcher.ex#L70

It doesn't look like you don't have WebSockets enabled in your Parity config.

**Comment by Dycedlp** [comment]
@acravenho Awesome! Thanks.  Only thing is I have websockets enabled in my config for parity its running on 8456, unless its getting disabled by a flag I'm unaware of.  Should I fix this by changing the variable "first" = latest_block_number?

**Comment by acravenho** [comment]
The default WebSockets port on BlockScout is different `8546`. I would try adjusting that so you can see realtime events coming in on your instance. 

https://github.com/poanetwork/blockscout/blob/4701dc04d17b5165eadef357209a173b30a358e7/apps/indexer/config/dev/parity.exs#L23

https://github.com/poanetwork/blockscout/blob/4701dc04d17b5165eadef357209a173b30a358e7/apps/explorer/config/dev/parity.exs#L22

**Comment by Dycedlp** [comment]
Ok.  Thanks.  Just changed my websockets port to the 8546.  And now when I run the explorer w/ parity, it spams my parity console with:
2018-12-08 12:02:59  Blocked connection to WebSockets server with untrusted host: Some("localhost")
2018-12-08 12:02:59  Blocked connection to WebSockets server with untrusted host: Some("localhost")
2018-12-08 12:02:59  Blocked connection to WebSockets server with untrusted host: Some("localhost")
2018-12-08 12:02:59  Blocked connection to WebSockets server with untrusted host: Some("localhost")
-------------------------------------------------------------------------------------------------------------------
Any chance you'd know what that's caused by?

**Comment by Dycedlp** [comment]
Also heres my parity config just in case you think it could be caused by a configuration:
 [parity]
chain = "gen.json"
base_path = "~/ethereum/poa/node1/"
[network]
port = 30301
[rpc]
port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts", "all"]
cors = ["null","localhost:3000","localhost:3001","http://remix.ethereum.org","chrome-search://ae62fc16-c916-4c24-9a36-97f5a850f25c","all","https://www.myetherwallet.com/"]
interface = "all" #external access to rpc
hosts = ["all"]
[ui]
port = 8181
[websockets]
port = 8546
[ipc]
disable = false
[account]
unlock = [""]
password = ["pswds.pwds"]
[mining]
engine_signer = ""

**Comment by acravenho** [comment]
Your config looks fine. I would check the WebSocket connection of your node to make sure everything is operating correctly. We no longer enforce secure WebSockets.

**Comment by Dycedlp** [comment]
Ok.  Just added --ws-origins http://localhost:8546 --ws-interface all flags to my launch and stopped the errors... Just checked, still a block behind tho.  And I'm finally getting white letters in the console for blockscout!

**Comment by Dycedlp** [comment]
Changed first = last block number, works now! Cheers.  If theres a websocket issue you see please let me know.  Thanks for the help!
