### ISSUE TITLE
Add dark theme option

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#1193]
### Requirements
* Create light/dark switch in the Header.
* Compile light/dark CSS stylesheet in Webpack during build.
* When a user clicks the light/dark switch the theme switches from light to dark and back. This should be saved for each individual user so when they return to BlockScout there is no need to have to switch to their preference.

### Possible Color Option

<img width="1280" alt="49698402-eee94d00-fbcb-11e8-945a-fe0fefba89ee" src="https://user-images.githubusercontent.com/17620007/49699217-7323dc00-fb9c-11e8-914b-bf329f4fe842.png">

**Comment by pashagonchar** [comment]
@acravenho 

Update

<img width="1280" alt="blockscout_poa_dark_green_1" src="https://user-images.githubusercontent.com/16716926/49869134-24827600-fe18-11e8-8ee1-c5ec7cf89c9d.png">
<img width="1280" alt="blockscout_poa_dark_green_2" src="https://user-images.githubusercontent.com/16716926/49869135-251b0c80-fe18-11e8-820f-662f91bf34f0.png">
<img width="1280" alt="blockscout_poa_dark_green_3" src="https://user-images.githubusercontent.com/16716926/49869137-264c3980-fe18-11e8-9894-e77ba524081e.png">


Zeplin

https://zpl.io/andoERx

https://zpl.io/bWg40xp

https://zpl.io/beowjJN

Jast use one dark theme for all networks, only change logos (white)
