### ISSUE TITLE
Suggestion: Replace price metrics with gas metrics

### ISSUE THREAD

**Issue by fubuloubu** [poanetwork/blockscout#1195]
Prices are cool, cryptocurrencies are valuable digital assets after all, but there are 5 testnets where price doesn't actually matter (and one network where price also doesn't matter because it's 1 DAI = 1 DAI). What would be much more interesting and relevant would be gas price and fee information as well as gas usage metrics, which is something that also doesn't require an price feed oracle as it can be collected directly from the blockchain itself.

My suggestion would be to graph a month's worth of block gas usage, and put that over the 12hr SMA of gas price, and cost of a simple send transaction based on that price. Seeing those metrics when I pop in to BlockScout (which is the prettiest block explorer I've seen!) would be much more useful to me then seeing the price itself. Even if the simple transaction cost was denominated in dollars, this would still be useful I think.

Great job guys!

**Comment by vbaranov** [comment]
A few gas usage metrics were added:
- Gas usage per day
![Screenshot 2020-10-30 at 17 18 28](https://user-images.githubusercontent.com/4341812/97715881-f70a4880-1ad3-11eb-8069-fdff4634084e.png)

- Total gas usage per address (all time)
![Screenshot 2020-10-30 at 17 20 33](https://user-images.githubusercontent.com/4341812/97716091-3fc20180-1ad4-11eb-80f8-773e73bf3c6f.png)

- Total gas usage for all transactions (all time)
![Screenshot 2020-10-26 at 10 57 41](https://user-images.githubusercontent.com/4341812/97716346-8f083200-1ad4-11eb-940f-5788b2026513.png)
