### ISSUE TITLE
Question: How can I configure the web service's port?

### ISSUE THREAD

**Issue by rjl493456442** [poanetwork/blockscout#1201]
I try to integrate blockscout into puppeth, but I can't find how to configure web port.

### Expected behaviour

webport(default is 4000) is configurable

**Comment by acravenho** [comment]
Hey @rjl493456442, 

That sounds fantastic!! Here is where you would configure the port in development: https://github.com/poanetwork/blockscout/blob/5e795058a388c6c2ae28a38ee2cac2d733ec778c/apps/block_scout_web/config/dev.exs#L10

For production, you would update the variable here: https://github.com/poanetwork/blockscout/blob/5e795058a388c6c2ae28a38ee2cac2d733ec778c/apps/block_scout_web/config/prod.exs#L21

For Rinkeby, you'll want to change this:

https://github.com/poanetwork/blockscout/blob/5e795058a388c6c2ae28a38ee2cac2d733ec778c/apps/indexer/config/config.exs#L8

to `block_transformer: Indexer.Block.Transform.Clique,`

Please let me know if there are other issues you're experiencing.

**Comment by rjl493456442** [comment]
@acravenho Nice, appreciate it! Regarding the `block_transformer`,  Ethash based chain is `Indexer.Block.Transform.Base` and Clique based chain is `Indexer.Block.Transform.Clique` right?

**Comment by rjl493456442** [comment]
Btw do you know how to disable the price diagram :P? Puppeth is facing some private networks, so price information is useless.

**Comment by acravenho** [comment]
@rjl493456442 Correct, regarding the `block_transformer`. We have an issue that will remove this graph and USD prices with a configuration option. It's currently being worked on now. #811 should be ready in the next few weeks.
