### ISSUE TITLE
Fix tokens' query on the tokens tab at Address Page

### ISSUE THREAD

**Issue by feliperenan** [poanetwork/blockscout#1212]
The query to list tokens from a specific address is considering only the last block number from `address_token_balances` table and not ignoring token balances that weren't fetched yet (the ones that have value and value_fetched_at NULL).

That's bad because the list may not show some token that the address has balance because the last block indexed hadn't its value fetched yet. In addition, once this PR https://github.com/poanetwork/blockscout/pull/1197 is merged the user will see a difference between the tokens' list and the token balances dropdown due that the drop-down uses the `address_current_token_balances` as you can see in the screenshot below.

![image](https://user-images.githubusercontent.com/27698968/49881868-76c29780-fe16-11e8-8eb3-09cd619d82ff.png)

It is going to happen because the drop-down will use the `address_current_token_balance` which doesn't have this problem since there only blocks with values are stored.

One way to fix that is changing the query above to ignore blocks that haven't indexed their values yet.

https://github.com/poanetwork/blockscout/blob/2a64b4e77e5f4db05c817474490af75cf3f55118/apps/explorer/lib/explorer/chain/address/token.ex#L62

Another way is changing the query above to use the `address_current_token_balance` instead of `address_token_balance`, which may improve the query performance as well.

**Comment by acravenho** [comment]
@fvictorio After #1197 gets merged would you mind taking a look at this?
