### ISSUE TITLE
Address page: transactions sent not updating in realtime

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/blockscout#1225]
Transactions amount is not updated on address details page

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):Elixir 1.7.4 (compiled with Erlang/OTP 21)
* Operating System: MacOs

### Steps to reproduce
Tested with Ropsten, Sokol. 
Account `0x56b2e3c3cff7f3921dc2e0f8b8e20d1eec29216b `

1. Search account address in https://blockscout.com/eth/ropsten/ ,remember transaction amount
1. Transfer eth from this  account to any  other account
2. Search sender's account in https://blockscout.com/eth/ropsten/, observe transaction amount

### Expected behaviour
Transaction amount should increased
### Actual behaviour
Transaction amount isn't updated

<img width="1421" alt="screen shot 2018-12-13 at 09 51 52" src="https://user-images.githubusercontent.com/14067096/49958093-a331ee80-febe-11e8-89ce-95fa6b285bca.png">

<img width="1427" alt="screen shot 2018-12-13 at 10 08 09" src="https://user-images.githubusercontent.com/14067096/49958281-29e6cb80-febf-11e8-927d-43912e02dabb.png">

**Comment by zachdaniel** [comment]
I attempted to reproduce this just now using current master and sokol, and I could not. @dennis00010011b can you confirm that this bug is still happening using latest master?
