### ISSUE TITLE
[Question] Counters are extremely slow

### ISSUE THREAD

**Issue by APshenkin** [poanetwork/blockscout#1246]
*Describe your issue here.*

Currently we use this commit in our blockscout https://github.com/poanetwork/blockscout/commit/61cde269ba2845f30f7ac80b481ab76920b7603f. Yes, it's outdate but looks like code about fetching counters wasn't changed.

Using geth with disabled internal transactions. Synced 48%

We noticed that 
Explorer.Counters.TokenTransferCounter
Explorer.Counters.TokenHoldersCounter
Explorer.Counters.BlockValidationCounter

are extremely slow and create huge load postgres server after restarting blockscout. Selects with `count()` can't complete at all and stay in foreground. This causes blockscout get "freezed". After disabling this counters everything works fast.

Is there anything that we can to do with this counters? Will update to latest blockscout version solve this issue?

Thanks in advance

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
```
Erlang/OTP 21 [erts-10.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.7.3 (compiled with Erlang/OTP 21)
```
* Operating System:
```
Debian GNU/Linux 9 (stretch)
```

**Comment by acravenho** [comment]
Hey @APshenkin ,

#1229  was merged today for upgrading to ECTO 3.0. This should help with these types of counters. From my testing on our staging environment, this seemed to help. I'll be deploying later tonight and should be able to provide further info once this occurs.
