### ISSUE TITLE
Read contract: incorrect return value  if  function has input type `bytes`

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/blockscout#1258]
*Describe your issue here.*

I've tested function `returnBytes1` , contract `0x215b2ab35749e5a9f3efe890de602fb9844e842f`, Sokol
```
function returnBytes1(bytes arr) public view returns (bytes value) {
                 return arr;    }
```
Expected result:
 - output data of this function should be equal the input data

Actual result:
 - if input `0x01` then query has no respond at all
- if input `123` then output is `0x617267756d656e74206572726f72` (should be `0x7b`)

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): web 
* Operating System: MacOs

### Steps to reproduce
1. Open https://blockscout.com/poa/sokol/address/0x215b2ab35749e5a9f3efe890de602fb9844e842f/read_contract
2. Test function `returnBytes1`
<img width="1438" alt="screen shot 2018-12-18 at 23 09 55" src="https://user-images.githubusercontent.com/14067096/50205057-caa01580-031b-11e9-9962-b18a584da7b3.png">

**Comment by vbaranov** [comment]
The issue has been fixed with `ex_abi` 0.3.0 version. Related PRs are above.
