### ISSUE TITLE
Incomplete deployment instructions

### ISSUE THREAD

**Issue by d10r** [poanetwork/blockscout#1285]
I've recently set up blockscout on a machine with a fresh Ubuntu 18.04 installed.  
For doing so, I followed instructions in the top level README of this repo.  
This issue lists information I missed.

**prod deployment**  
First of all, https://github.com/poanetwork/blockscout#build-and-run nicely documents how to build and run blockscout in development mode. It doesn't however mention what's to be done differently for a production deployment.  
It's easy to understand that there's `prod` equivalents to the `dev` config files. Is setting them up the same and setting the env variable `MIX_ENV=prod` all there's needed?

**requirements**  
On a virgin Ubuntu 18.04 server install, I had to install a few packages not mentioned in the doc before building succeeded: `make gettext erlang-parsetools erlang-dev g++`  
I'm not 100% sure all of them were required - that's what my apt log includes additionally to the [listed requirements](https://github.com/poanetwork/blockscout#requirements) after succeeding.

**secret**  
In `apps/block_scout_web/config/prod.secret.exs` there's a variable `secret_key_base` with a key as value. I guess it should be replaced by a self-generated one - or shouldn't it?  
What's a convenient way to generate a new one (it's not self-evident to me which kind of character and length restrictions there may be for this value)?

**systemd unit**  
Finally, it would be nice if an example systemd unit for a production deployment were provided.  
I tried with something like that (with env vars set):
```
[Unit]
Description=blockscout
After=network.target
[Service]
User=blockscout
Group=blockscout
Environment=MIX_ENV=prod
Environment=COIN=
Environment=ETHEREUM_JSONRPC_VARIANT=parity
Environment=ETHEREUM_JSONRPC_TRACE_URL=
Environment=ETHEREUM_JSONRPC_HTTP_URL=
Environment=ETHEREUM_JSONRPC_WS_URL=
Environment=NETWORK=
Environment=SUBNETWORK=
Environment=LOGO=
# for display of validator names for block author
Environment=METADATA_CONTRACT=
Environment=VALIDATORS_CONTRACT=
WorkingDirectory=/home/blockscout
ExecStart=/usr/local/bin/mix phx.server
[Install]
WantedBy=multi-user.target
```
Doesn't yet work, because it can't find the `node` binary when started via systemd (I have it installed via nvm in user context, systemd doesn't have that location in PATH).  
I don't however know if this config (e.g. restart strategy) is adequate for blockscout.

**Comment by igorbarinov** [comment]
Thanks for the issue
We plan to review deployment documentation in the new year. Also, we plan to add an FAQ section based on repeating questions and troubleshooting on Gitter https://gitter.im/poanetwork/blockscout

**Comment by acravenho** [comment]
Hey @d10r, in the [Getting Started](https://github.com/poanetwork/blockscout#getting-started) section we discuss how we use Terraform for our production environment. Please take a look [here](https://github.com/poanetwork/blockscout-terraform) for our production setup.

As @igorbarinov mentioned, there will be further documentation in a few weeks and more thorough FAQ section.

In the meantime, here is the [script](https://github.com/poanetwork/blockscout-terraform/blob/master/modules/stack/libexec/init.sh) used from Terraform to set up the EC2 instances on Production.

**Comment by acravenho** [comment]
Regarding your questions. 

1. Yes, everything is the same for development and production. All environment variables are the same. The only difference is to use `MIX_ENV=prod` instead of `MIX_ENV=dev`.

2. There is no reason to generate a new `secret_key_base` string.

3. For the environment variables, please see the [Terraform example](https://github.com/poanetwork/blockscout-terraform/blob/master/main/variables.tf). For us, enter these variables in Parameter Store in AWS.

Some additional variables that will be added soon are:

```
# Restarts BlockScout on erlang crash
HEART_BEAT_TIMEOUT=30
# command used to restart explorer
HEART_BEAT_COMMAND

# POA Specific Environment Variables
METADATA_CONTRACT
VALIDATORS_CONTRACT
SUPPLY_MODULE
SOURCE_MODULE
```

**Comment by d10r** [comment]
thx @acravenho for this helpful input!
