### ISSUE TITLE
Internal Transaction Indexing

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#1287]
Index internal transactions that only meet the following requirements:
* parent transaction contains an input
* parent transaction has a status of `0` or contained an error

We're indexing a large number of internal transactions that will never be used. We should concentrate the indexing on only transactions that we use.

**Comment by KronicDeth** [comment]
> * parent transaction has a status of 0 or contained an error

To support pre-Byzantium transactions we only derive status and error once internal transactions are indexed.  We'll need to ensure the pre-Byzantium code still works even if we can exclude internal transactions for post-Byzantium transactions that are not of interest.

**Comment by KronicDeth** [comment]
Adding a new column to indicate that we won't get internal transactions is likely expensive for a table as large as `transactions`, so reuse of `internal_transactions_fetched_at` is likely the best bet.  These are the new rules for `internal_transactions_fetched_at` to encode the design in https://github.com/poanetwork/blockscout/issues/1287#issue-395246980:

| `status` | `input`   | `internal_transactioned_fetched_at`       | `internal_transactions` | Description                                                                                         |
|----------|-----------|-------------------------------------------|-------------------------|-----------------------------------------------------------------------------------------------------|
| `:ok`    | Empty     | `inserted_at`                             | Unfetched               | Simple `value` transfer transaction succeeded.  Internal transactions would be same value transfer. |
| `:ok`    | Non-Empty | When `internal_transactions` are fetched. | Fetched                 | A contract call that succeeded.                                                                     |
| `:error` | Empty     | `inserted_at`                             | Unfetched               | Simple `value` transfer transaction failed.                                                         |
| `:error` | Non-Empty | When `internal_transactions` are fetched. | Fetched                 | A contract call that failed.                                                                        |
