### ISSUE TITLE
TypeError: Cannot read property of `id` of undefined

### ISSUE THREAD

**Issue by dwalintukan** [poanetwork/blockscout#1298]
*Describe your issue here.*

![image](https://user-images.githubusercontent.com/4350404/50653241-b1af7b00-0f3d-11e9-93f5-d24476d6b5ba.png)

This issue is appearing on the main dashboard and the issue is with the `transactions` list. I have tracked the issue to this line:
```
# list_morph.js L45
currentList = currentList.map(({ el }, i) => ({
    id: overlap[i].id,
    el: el.outerHTML === overlap[i].el.outerHTML ? el : morph(el, overlap[i].el)
  }))

# oldElements
(2) [button.alert.alert-danger.col-12.text-left, div.tile.tile-muted.text-center.mt-3]
0: button.alert.alert-danger.col-12.text-left
1: div.tile.tile-muted.text-center.mt-3
length: 2
__proto__: Array(0)

# newElements
newElements 
(5) [div.tile.tile-type-transaction.fade-in.tile-status--success, div.tile.tile-type-token-transfer.fade-in.tile-status--success, div.tile.tile-type-transaction.fade-in.tile-status--success, div.tile.tile-type-token-transfer.fade-in.tile-status--success, div.tile.tile-type-token-transfer.fade-in.tile-status--success]
0: div.tile.tile-type-transaction.fade-in.tile-status--success
1: div.tile.tile-type-token-transfer.fade-in.tile-status--success
2: div.tile.tile-type-transaction.fade-in.tile-status--success
3: div.tile.tile-type-token-transfer.fade-in.tile-status--success
4: div.tile.tile-type-token-transfer.fade-in.tile-status--success
length: 5
__proto__: Array(0)

# overlap array has less than the currentList array
[{…}]
0:
el: div.tile.tile-type-transaction.fade-in.tile-status--success
id: undefined
__proto__: Object
length: 1
__proto__: Array(0)

# currentList
# (2) [{…}, {…}]
0:
el: button.alert.alert-danger.col-12.text-left
id: undefined
__proto__: Object
1:
el: div.tile.tile-muted.text-center.mt-3
id: undefined
__proto__: Object
length: 2
__proto__: Array(0)
```

So the problem is the `currentList.map()` call is trying to lookup `overlap[1].id` but the overlap array has only length of 1.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.7.4 (compiled with Erlang/OTP 21)
* Operating System: Mac OSX Mojave 10.14.2

### Steps to reproduce

Not sure if this is reproducible on another Clique network, but unfortunately we are currently closed source. I can PM someone with the IP to test this out to help debug. Possibly try first with the POA network. 

### Expected behaviour

No error when fetching the transactions.

### Actual behaviour

Error of trying to lookup an invalid index of the `overlap` array.

**Comment by vbaranov** [comment]
@dwalintukan we have no such issue with [Rinkeby](https://blockscout.com/eth/rinkeby) Blockscout instance (the chain with Clique). Do you still have this issue in your chain? And if yes did you try the latest release [1.3.10](https://github.com/poanetwork/blockscout/releases/tag/v1.3.10-beta) of Blockscout?

**Comment by dwalintukan** [comment]
@vbaranov will test on latest release.
