### ISSUE TITLE
Make coinmarketcap informations optional

### ISSUE THREAD

**Issue by SurfingNerd** [poanetwork/blockscout#1299]
We are working on a branding of Blockscout for our blockchain [ARTIS.eco](https://artis.eco).
Our cryptocurrency is not listed on [coinmarketcap.com](https://coinmarketcap.com) therefore this $$$ sections on Blockscout are very confusing for the users, so we decided to remove this sections.
We would be happy to provide a pull request for this "no coinmarketcap" feature, once we are done with it.

We chose to make the values invisible, in order to keep coding effort low and mergability high, living with the downsides that the $$$ values are still somehow in the HTML (CSS hidden).
We also accept the downside that there are some gaps and empty spaces.

as far we know now, most of the stuff can be done creating an additional SCSS file, that applies an invisible CSS Style.
in some rare cases we needed to add a new style in the html.eex file, so the section can be targeted.

I hope i can deliver a pull request soon.
Please let me know if this is interesting/uninteresting for you.

best regards, 
Thomas

**Comment by acravenho** [comment]
@SurfingNerd That would be fantastic. We've had a few requests for this feature and haven't been able to complete this yet. We look forward to the pull request when it's completed. 

We can also add your BlockScout implementation to our Readme so users can check it out.

**Comment by SurfingNerd** [comment]
sorry for the latency :/
is this still interesting ?
The changes are live at https://explorer.sigma1.artis.network. i just need to update it to 1.3.2. to be on a stable version, then i can create a pull request.

**Comment by acravenho** [comment]
Yes, this would be fantastic!!! Very excited to see this.  Great work on the explorer.
