### ISSUE TITLE
Hi, I try to run blockscout in docker container, the error log occurs:

### ISSUE THREAD

**Issue by KronicDeth** [poanetwork/blockscout#1301]
Hi, I try to run blockscout in docker container, the error log occurs:

```
Function: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3
    Args: [127070, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://localhost:8545", http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, false]
06:51:38.879 [error] Task #PID<0.6548.6> started from Indexer.Block.Realtime.Fetcher terminating
** (stop) exited in: :gen_server.call(Explorer.Repo.Pool, {:checkout, #Reference<0.3452034868.1585184770.68066>, true}, 5000)
    ** (EXIT) time out
    (stdlib) gen_server.erl:223: :gen_server.call/3
    (poolboy) src/poolboy.erl:55: :poolboy.checkout/3
    (db_connection) lib/db_connection/poolboy.ex:41: DBConnection.Poolboy.checkout/2
    (db_connection) lib/db_connection.ex:928: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:750: DBConnection.run/3
    (db_connection) lib/db_connection.ex:798: DBConnection.transaction/3
    (ecto) lib/ecto/repo/queryable.ex:23: Ecto.Repo.Queryable.transaction/4
    (explorer) lib/explorer/chain/import.ex:132: Explorer.Chain.Import.all/1
```

I test with latest master branch, could you please take a look? @acravenho

_Originally posted by @rjl493456442 in https://github.com/poanetwork/blockscout/issues/624#issuecomment-451372788_

**Comment by konstantinzolotarev** [comment]
@KronicDeth @rjl493456442
It seems that you run blockscount in docker container and chain outside of it.
because it try to fetch details from `url: "http://localhost:8545"` 

This is working only on Linux, if you using MacOS or Windows you have to set it up using: `http://host.docker.internal:8545`

[Details](https://github.com/poanetwork/blockscout/blob/master/docker/README.md)

**Comment by konstantinzolotarev** [comment]
@KronicDeth @acravenho BTW if there will be issues that are ganache/docker related feel free to ping me, I'll try to help ASAP

**Comment by rjl493456442** [comment]
@konstantinzolotarev 
I put all the stuff(geth node, postsql, blockscout) into a single container. So the error is weird here. Actually, this container works well about a month ago. When I try it again recently, it starts to print error logs.

You can check and play around the docker file here https://github.com/puppeth/blockscout/blob/master/Dockerfile.

**Comment by konstantinzolotarev** [comment]
@rjl493456442 Could you please show error messages ?
I'll try to set everything up using your Docker image.

**Comment by rjl493456442** [comment]
@konstantinzolotarev I use docker compose to start up the image, here is a relative PR to integrate blockscout into puppeth https://github.com/ethereum/go-ethereum/pull/18261.
