### ISSUE TITLE
Page performance - Minimize main-thread work

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#1306]
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fblockscout.com%2Fpoa%2Fsokol

`Script Evaluation` is currently taking ~ 3 seconds to process. Let's try and reduce this number.

**Comment by zachdaniel** [comment]
I've been working on this, and it comes down to splitting up the files and transpiling them via webpack. I'm not a webpack expert so I've had some learning to do. I'm close to a solution, just need to figure out how to transpile files from one folder to another folder while keeping their paths, using webpack's configuration.

**Comment by acravenho** [comment]
![score](https://user-images.githubusercontent.com/17620007/51138566-6d5e8d80-180f-11e9-8f79-fdd1986033a2.png)

Is the mobile side cached on Google's side. It's showing some of the scripts that have been removed.

**Comment by zachdaniel** [comment]
I can't see how. I'm not seeing the same thing on my end. Both mobile + desktop show only the `app.js`

**Comment by zachdaniel** [comment]
I think the javascript has been effectively optimized here, and that we can close this.
