### ISSUE TITLE
Copyright year is static and set to 2018

### ISSUE THREAD

**Issue by SiddigZeidan** [poanetwork/blockscout#1312]
Copyright year on BlockScout is hardcoded to 2018. Should be updated and even better made dynamic rather than hardcoded.

![image](https://user-images.githubusercontent.com/4807398/50739717-b0f04080-11ec-11e9-8da4-12e07866b431.png)

### Expected behaviour

Year should be set to the current year

### Actual behaviour

Year is hardcoded to 2018

**Comment by SiddigZeidan** [comment]
@barinov reckons we should remove the copyright from the footer altogether. Thoughts?

**Comment by acravenho** [comment]
It can be removed altogether.

**Comment by acravenho** [comment]
@SiddigZeidan 
Do you think the footer on xDai Chain should have a darker text color? I found the white difficult to read.

![footerdai](https://user-images.githubusercontent.com/17620007/51406110-241b8000-1b26-11e9-8ee7-9dd2ac19ccea.png)

**Comment by SiddigZeidan** [comment]
Lets make it white but bolded. Like the xDai topbar we have on the website at the moment. I think if bolded it will look good @acravenho 

![image](https://user-images.githubusercontent.com/4807398/51406744-fafbef00-1b27-11e9-92c9-60505e50e874.png)

**Comment by acravenho** [comment]
I'll be making this change very soon on the next deploy. Once completed and everyone is satisfied, I'll close the issue.
