### ISSUE TITLE
Error in tx not found message for RSK network

### ISSUE THREAD

**Issue by jonathansmirnoff** [poanetwork/blockscout#1339]
When a transaction is not found in RSK network the error message suggests to select another ETH node. This is an error. It shouldn't suggest that.

### Steps to reproduce

1. Generate a transaction with an incorrect nonce. So the transaction will be rejected.
2. Go to "Check Transaction Status" or "Recent Transactions"
3. Try to access to the transaction information.
4. You'll get the message "Transaction Not Found"

### Expected behaviour

It shouldn't suggest to connect to another ETH node: 
_"Please use the dropdown in the top-right & select a different ETH node (e.g. ETH (Etherscan.io) or ETH (Infura.io) or ETH (MyCrypto)) and check again."_

**Comment by acravenho** [comment]
Hi @jonathansmirnoff, 

Is this on your personalized implementation of BlockScout? I'm not seeing that text anywhere in our Repo. 

If a transaction is not found, this is the message we show:

<img width="1111" alt="screen shot 2019-01-11 at 2 42 39 pm" src="https://user-images.githubusercontent.com/17620007/51055881-3c801d80-15af-11e9-89be-bffbc7f20ce8.png">


Are you referring to the error message shown at the top of the transaction page where `Success` or `Error` should go? If so, this information is provided by the node.

**Comment by jonathansmirnoff** [comment]
Sorry. You're right.
I wanted to create an issue in MyCrypto.
