### ISSUE TITLE
Production Cleanup Items

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#1344]
Below is a list of small cleanup items to help make BlockScout a more complete application:

* Add `alt` tags to the header and footer logo image. Preferably use the `SUBNETWORK` environment variable.
* Footer Links should have `rel="noreferrer"` added to them.
* Footer date should use Timex instead of being static. #1312 
* Add csspurge to the postcss.config.js file

**Comment by igorbarinov** [comment]
Can we replace footer copyright to links to something more interesting

Some ideas:
- links to other explorers
- links to other instances of blockscout

@SiddigZeidan any other ideas?

**Comment by SiddigZeidan** [comment]
Links to other instances of BlockScout.

I think also a message emphasizing the open source nature of BlockScout (to replace the copyright text which @igorbarinov doesn't think makes sense in this case) with a CTA asking to contribute.

Thoughts?

**Comment by zachdaniel** [comment]
I'll look into `csspurge` as well.

**Comment by zachdaniel** [comment]
It is very difficult to *verify* the behavior of purgecss. I've got it integrated, but I'm trying to get a better idea of the impacts and make sure it hasn't screwed up the css. I'll have more info soon.

**Comment by acravenho** [comment]
<img width="1145" alt="screen shot 2019-01-15 at 4 48 13 am" src="https://user-images.githubusercontent.com/17620007/51172260-db8f6880-1880-11e9-902a-2840f6e04972.png">

Styles will need to be updated to include icons and better color contrast, but all the info that has been discussed is present. I do not think links to other explorers should be included in the default version of BlockScout, but can be added for production.

**Comment by zachdaniel** [comment]
I'm implementing the footer now.
