### ISSUE TITLE
"Unknown action" when retrieving ETC balances for some addresses but not others

### ISSUE THREAD

**Issue by alexeystepanyan** [poanetwork/blockscout#1346]
On some addresses ETC api returned 400 Bad Request for balance queries with "Unknown action" as the message in the response.

400 Client Error: Bad Request for url: https://blockscout.com/etc/mainnet/api?module=account&action=balance&address=<address>

{
    "status": "0",
    "result": null,
    "message": "Unknown action"
}

Same address shows proper balance with other ETC explorers and also querying eth_getBalance on https://web3.gastracker.io/ or https://etc-geth.0xinfra.com/ returns proper result.

My guess is that QUANTITY|TAG params are causing the issue

https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getbalance

At least 2 things would help:
- expose underlying exception from talking to ETC node in the error message
- document block tag/quantity to be able to easily repro

Thanks!

**Comment by acravenho** [comment]
Hi @alexeystepanyan,

Can you please provide some addresses where you're facing this issue?

Thank you.

**Comment by acravenho** [comment]
We do not query from the node directly during these calls. These calls are made directly to our storage layer.

**Comment by acravenho** [comment]
There is no way to debug this without the address. I ran 100s of addresses through a script without issue. Feel free to message me privately on Gitter if you would like me to debug this further.
