### ISSUE TITLE
Contracts deployed by factory are not detected

### ISSUE THREAD

**Issue by ewingrj** [poanetwork/blockscout#1349]
[Here](https://blockscout.com/eth/rinkeby/address/0x82fdd5db4186d6b39a26f3187c9f79e5e4367221/transactions) is a contract that was deployed via a factory contract, however blockscout does not recognize that there is a contract at this address.

[Here](https://rinkeby.etherscan.io/tx/0xb0ad3dee7d3a922f2366c2f5f594839e046891fcc0be8f377b9cd2dfc62733dd#internal) you can see the tx where this contract was deployed.

### Expected behaviour

blockscout should recognize contracts deployed via CREATE & CREATE2 opcodes and allow verification

**Comment by acravenho** [comment]
Hey @perissology,
This issue has more to do with our Geth node right now. In Geth v1.8.0 only 128 blocks are kept in memory which makes it difficult for block explorers who do not have the current history to go back and fetch these internal transactions. 

We're working on a solution at the moment and hopefully will this issue resolved soon.

**Comment by vbaranov** [comment]
Blockscout recognizes the contract mentioned in the issue now. If you have other examples, please let us know. I am closing this issue.
