### ISSUE TITLE
Blockscout UI doesn't Deploy

### ISSUE THREAD

**Issue by jalextowle** [poanetwork/blockscout#1351]
The blockscout UI isn't working correctly after I run the "install_blockscout.sh" script on the linux box. This was all that I did, so it is possible that I am missing some dependencies, although this script appears to install all of the relevant dependencies.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Erlang/OTP 21 [erts-10.2.1] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]
Elixir 1.8.0 (compiled with Erlang/OTP 20)

* Operating System: Ubuntu 16.05 

### Steps to reproduce

Follow the steps in setting up blockscout from https://github.com/Azure-Samples/blockchain/tree/master/ledger/template/ethereum-on-azure/technology-samples/blockscout. 

### Expected behaviour

The Blockscout UI should be started on the VM, and accessible via the Azure DNS service.

### Actual behaviour

502 Bad Gateway. The server appears to just be unresponsive.

**Comment by acravenho** [comment]
There have been many updates since the [install script](https://github.com/Azure-Samples/blockchain/blob/master/ledger/template/ethereum-on-azure/technology-samples/blockscout/install_blockscout.sh) was written to the core BlockScout Configuration.

I will take a look this week and create a PR with an updated version.

**Comment by jalextowle** [comment]
Thank you for the timely response. Sorry for the chore

**Comment by acravenho** [comment]
@jalextowle Pull request now open fixing the issue with the build script. I also bumped the BlockScout version to the latest: https://github.com/Azure-Samples/blockchain/pull/120

**Comment by jalextowle** [comment]
It seems that there were a lot of warnings, and at least one error. I'll run the script again and show you the logs.

**Comment by jalextowle** [comment]
This is the first error that it encounters. I'll link them as they come. 

"The following packages have unmet dependencies:
 npm : Depends: nodejs but it is not going to be installed
       Depends: node-abbrev (>= 1.0.4) but it is not going to be installed
       Depends: node-ansi (>= 0.3.0-2) but it is not going to be installed
       Depends: node-ansi-color-table but it is not going to be installed
       Depends: node-archy but it is not going to be installed
       Depends: node-block-stream but it is not going to be installed
       Depends: node-fstream (>= 0.1.22) but it is not going to be installed
       Depends: node-fstream-ignore but it is not going to be installed
       Depends: node-github-url-from-git but it is not going to be installed
       Depends: node-glob (>= 3.1.21) but it is not going to be installed
       Depends: node-graceful-fs (>= 2.0.0) but it is not going to be installed
       Depends: node-inherits but it is not going to be installed
       Depends: node-ini (>= 1.1.0) but it is not going to be installed
       Depends: node-lockfile but it is not going to be installed
       Depends: node-lru-cache (>= 2.3.0) but it is not going to be installed
       Depends: node-minimatch (>= 0.2.11) but it is not going to be installed
       Depends: node-mkdirp (>= 0.3.3) but it is not going to be installed
       Depends: node-gyp (>= 0.10.9) but it is not going to be installed
       Depends: node-nopt (>= 3.0.1) but it is not going to be installed
       Depends: node-npmlog but it is not going to be installed
       Depends: node-once but it is not going to be installed
       Depends: node-osenv but it is not going to be installed
       Depends: node-read but it is not going to be installed
       Depends: node-read-package-json (>= 1.1.0) but it is not going to be installed
       Depends: node-request (>= 2.25.0) but it is not going to be installed
       Depends: node-retry but it is not going to be installed
       Depends: node-rimraf (>= 2.2.2) but it is not going to be installed
       Depends: node-semver (>= 2.1.0) but it is not going to be installed
       Depends: node-sha but it is not going to be installed
       Depends: node-slide but it is not going to be installed
       Depends: node-tar (>= 0.1.18) but it is not going to be installed
       Depends: node-underscore but it is not going to be installed
       Depends: node-which but it is not going to be installed
E: Unable to correct problems, you have held broken packages."

**Comment by jalextowle** [comment]
"timex 3.1.25 RETIRED!
    (invalid) Incorrect Elixir version requirement"

**Comment by jalextowle** [comment]
"** (Mix) Unknown dependency libsecp256k1 for environment prod"

**Comment by jalextowle** [comment]
"./autogen.sh: 3: ./autogen.sh: autoreconf: not found
make: *** [priv/libsecp256k1_nif.so] Error 127
Makefile:30: recipe for target 'priv/libsecp256k1_nif.so' failed
==> libsecp256k1
warning: Mix compiler :make_bindings was supposed to return {:ok | :noop | :error, [diagnostic]} but it returned :error"

**Comment by acravenho** [comment]
Let me run the script again on a fresh build. All these issues should have been resolved.

**Comment by jalextowle** [comment]
"WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  ../fonts/fa-solid-900.svg (579 KiB)
  ../fonts/fa-brands-400.svg (608 KiB)
  app.js (836 KiB)
  ../css/app.css (269 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (1.08 MiB)
      app.js
      ../css/app.css


WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/postcss-loader/lib/index.js!node_modules/sass-loader/lib/loader.js??ref--5-4!css/app.scss:
     15 assets
    [17] ./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js??ref--5-4!./css/app.scss 285 KiB {0} [built]
        + 17 hidden modules"

**Comment by jalextowle** [comment]
Are any of those errors helpful for you? I can provide any other info that you need.

**Comment by jalextowle** [comment]
It is worth noting that I downloaded the script via: "curl -O https://raw.githubusercontent.com/Azure-Samples/blockchain/master/ledger/template/ethereum-on-azure/technology-samples/blockscout/install_blockscout.sh".

**Comment by acravenho** [comment]
Yes, most are warnings which aren't to worry about.

This is the correct location of the PR:

https://raw.githubusercontent.com/acravenho/blockchain/ac-fix-blockscout-install-script/ledger/template/ethereum-on-azure/technology-samples/blockscout/install_blockscout.sh

**Comment by jalextowle** [comment]
Okay, I will try that script and let you know how it goes.

**Comment by jalextowle** [comment]
I'm still getting this error: 

"./autogen.sh: 3: ./autogen.sh: autoreconf: not found
make: *** [priv/libsecp256k1_nif.so] Error 127
Makefile:30: recipe for target 'priv/libsecp256k1_nif.so' failed
==> libsecp256k1
warning: Mix compiler :make_bindings was supposed to return {:ok | :noop | :error, [diagnostic]} but it returned :error"

Could this be causing the 502 Bad gateway? I've been wondering if I did something incorrectly during the Azure setup, even though I followed the guide.

**Comment by acravenho** [comment]
I'll ping you when I get a chance to take a look again. ETA 24-48 hours.

**Comment by jalextowle** [comment]
Thank you very much! I will anticipate your response.

**Comment by jalextowle** [comment]
Let me know when you can take a look at this. I will be available for immediate feedback whenever you can get to it.

**Comment by acravenho** [comment]
Hey @jalextowle,

I've run the script on a few machines today and BlockScout runs with no problem. I did experience an issue with `libsecp256k1` which I'm working on a fix now for. However, this error doesn't stop the application from running. 

Please check your environment variables to make sure your node is working properly. The 502 error could easily be caused by this issue. 

Ping the node from your Ubuntu instance `curl "http://$CONSORTIUM_IP:$RPC_PORT"`

You should receive a response back from your node.

**Comment by jalextowle** [comment]
Hello, 

This issue can be closed. I got blockscout up and running yesterday after I set up a fresh POA Consortium. The install script works perfectly, and the blockscout UI looks great!

Thank you for all of the help @acravenho

**Comment by acravenho** [comment]
That's great to hear :+1:
