### ISSUE TITLE
DB Connection not available and request was dropped from queue

### ISSUE THREAD

**Issue by wovvan** [poanetwork/blockscout#1358]
I got this error `[error] Task #PID<0.19523.1> started from Indexer.Block.Realtime.Fetcher terminating
** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 413ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information` after start about ~5 min, then I get 500 error from server. Before all is good.
DB is empty after migrations. 

### Environment

* Parity  POA, private network
* Mint block per 1 sec
* dev environment
**./apps/explorer/config/dev.secret.exs**
```use Mix.Config
config :explorer, Explorer.Repo,
  adapter: Ecto.Adapters.Postgres,
  database: "explorer_dev",
  hostname: "localhost",
  username: "postgres",
  password: "",
  loggers: [],
  pool_size: 20,
  pool_timeout: 60_000,
  timeout: 80_000,
  queue_target: 200,
  queue_interval: 2000
```

### Steps to reproduce

Run service, all goes good. After ~5 min got error. I think, it's because we mint block per 1 sec. I try to change timeout in **./apps/explorer/config/dev.secret.exs**, but isn't help me.

**Comment by acravenho** [comment]
We're working on an enhancement that will allow you to turn off the new polling feature in the realtime indexer. 

This polling request was introduced to help with longer block times and missed `newHeads` subscription but is probably causing memory issues on your chain. You'll be able to turn the polling off very soon.
