### ISSUE TITLE
Search input on Ethereum Mainnet explorer on mobile devices

### ISSUE THREAD

**Issue by monosux** [poanetwork/blockscout#1369]
Hi folks,

you created an awesome tool, thank you! 

Please fix search input on Ethereum Mainnet explorer on mobile devices such as iPad.

![iPad](https://i.imgur.com/4mzVLVU.jpg)

Problem is at screen resolution from 992px till 1199px.

**Comment by acravenho** [comment]
No problem, we'll take care of it.

**Comment by acravenho** [comment]
Change padding from `.65rem` to `.6rem` . 
```
@media (min-width: 768px)
.navbar-expand-lg .navbar-nav .nav-link {
    padding-left: .6rem;
    padding-right: .6rem;
}
```
