### ISSUE TITLE
Each deployed blockscout.com instance should have deployed version number in the footer

### ISSUE THREAD

**Issue by igorbarinov** [poanetwork/blockscout#1377]
Problem:
It's hard to understand which version of the application is deployed on each of the instances. POA hosts 8 instances + test instances an and plans to host few more instances for the POSDAO network. There are different version deployed now.

Solution:
Each released version should have a release version in the footer.

Solution (specific to blockscout.com):
a. only a tagged version can be deployed on production.
b. if it's a hotfix a minor version should be released and tagged.

**Comment by acravenho** [comment]
This feature was added a few days ago, it will be available on the next deployment. The next deployment will occur after I figure out how to solve the overflow bug as seen on xDAI Chain:

https://github.com/poanetwork/blockscout/blob/b444ac26bd7738c1ccee0eb8c382ef2b34b7ef24/apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex#L89-L95

a. Sounds good.
b. Hotfixes usually occur in critical situations which makes it very difficult to get it merged and released. I would prefer deploying the Hotfix, then having it reviewed, merged, and released a short time later.

**Comment by acravenho** [comment]
It's set as an environment variable during deployment: https://github.com/poanetwork/blockscout/blob/b444ac26bd7738c1ccee0eb8c382ef2b34b7ef24/apps/block_scout_web/lib/block_scout_web.ex#L24
