### ISSUE TITLE
Developer API and Webhooks

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#138]
- account balance
- account transactions
- account internal transactions
- transaction logs
- token transfers
- all transactions
- pending transactions
- blocks
- query contract abi

**Comment by igorbarinov** [comment]
@acravenho should we have https://etherscan.io/apis as a baseline?

**Comment by acravenho** [comment]
@igorbarinov Yes, this should be our baseline, with very similar calls as provided by Etherscan. This will make it easy for any current applications utilizing Etherscan's APIs to make the switch to an Open Source solution.

**Comment by acravenho** [comment]
@sabondano The next API endpoint to tackle would be event logs. Dapps use events to easily provided logs of what occurred during a transaction. Here is an example of an event log:

```
address:"0x698bf6943bab687b2756394624aa183f434f65da"
blockHash:"0x4d7e9b7c757c7cd97fca78e8f35b2ea4ff4a23b44711e8561431b33804648e50"
blockNumber:4030250
data:"0x"
logIndex:1
topics:Array(3)
0:"0xad2dcd5a3dee6baf6acb4fb80c4065f702936b3fd4ae80e1ecb2d4bb8d8c6890"
1:"0x0000000000000000000000000000000000000000000000000000000000000007"
2:"0x00000000000000000000000000000000000000000000000000000000000001fc"
length:3
__proto__:Array(0)
transactionHash:"0xa8c2fb2d48e88c82c3f88f9d5aed19f93f778d6accb3c3dba3d5e971a3f08afc"
transactionIndex:0
transactionLogIndex:"0x1"
type:"mined"
```

The most important parts of an event are the `address`, `data`, and `topics`. The `topics` need to be decoded if possible.

**Comment by acravenho** [comment]
@nambrot Our first goal was to obtain Etherscan API compatibility which we achieved the other day. Our next goal is to create our own set of GraphQL API endpoints for the community. Another issue will be created when our developer returns vacation. This should occur next week.

**Comment by nambrot** [comment]
Awesome, y'all are great and appreciated!

**Comment by nambrot** [comment]
Is there a way to follow the conversation on GraphQL or Webhooks as it is something we are currently considering adding to Blockscout ourselves. That way we can avoid unnecessarily forking and possibly contributing?

**Comment by acravenho** [comment]
@sabondano @nambrot 

We will be setting up a Gitter account for BlockScout very soon which will allow all the developers to communicate on the project. Sebastian will be starting the GraphQL API very soon if you would like to communicate here regarding any questions.

If there is a specific endpoint you would like to see, feel free to make an issue and we can get working on these feature requests.
