### ISSUE TITLE
I'd like to add a new API.

### ISSUE THREAD

**Issue by hephaistosJo** [poanetwork/blockscout#1383]
I would like to add new APIs such as "eth_sendRawTransaction" and "eth_call."
What should I do? And do you have any way to communicate with DAEMON directly?

**Comment by acravenho** [comment]
Hey @hephaistosJo,

We do not currently support sending transactions through BlockScout. In our v2 this may be implemented. We currently do not support talking directly to the node except through either the `indexer` or `ethereum_jsonrpc` umbrella applications.
