### ISSUE TITLE
Unable to verify ERC-20 token contract. No Code tab.

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#1389]
I am unable to verify ERC-20 token contract because of the absence of **Code** tab.

![screenshot 2019-01-30 at 14 24 11](https://user-images.githubusercontent.com/4341812/51978249-c169a300-249a-11e9-9377-698127a146a8.png)

I am trying to verify POA20 smart-contract **0x6758b7d441a9739b98552b373703d8d3d14f9e62** in the Main Ethereum network

**Comment by acravenho** [comment]
I have a test build up now. Hopefully I can have this deployed to production later this evening.

**Comment by hadv** [comment]
@vbaranov @acravenho I deploy blockscout version `v1.3.3-beta` but still didn't see the code tab. Can  you confirm this problem?

**Comment by hadv** [comment]
Ah, enable debug RPC API then I can see the Code tab now
