### ISSUE TITLE
Public Blockscout API instances?

### ISSUE THREAD

**Issue by 7-of-9** [poanetwork/blockscout#1390]
Hi all, and thanks for making Blockscout open source, it's definitely filling a big hole in the Ethereum space. I'm developing a multi-asset wallet, which has led me to Blockscout. First impressions are extremely positive.

My question is: is it OK to use the public APIs (e.g. https://blockscout.com/eth/mainnet/api_docs) for a third-party wallet? I'm using etherscan at the moment, but of course am not happy with (a) the centralization and (b) the rate limits, that prevent it from being a scaleable solution.

I was considering setting up a full Blockscout instance(s) from source, but would rather avoid or defer that until the wallet is launched, or until and unless there is a real need from a resource utilization perspective. 

I can see that there is no API key needed to access the EVM APIs, and I can't see any obvious reference to rate or IP limitations -- but I would much prefer to hear from Blockscout directly on any policy or guidelines regarding use of the API. It goes without saying that all utilization and request frequencies would be in adherence to best practices and basic common sense! It's a web-based wallet, so request origin IP addresses would be varied, but request origin hosts would not be, if that makes a difference.

Many thanks, and great project!
D.

**Comment by igorbarinov** [comment]
> My question is: is it OK to use the public APIs (e.g. https://blockscout.com/eth/mainnet/api_docs) for a third-party wallet? 

Yes, it's fine. If you write about your case here https://forum.poa.network/c/blockscout we will include it into our marketing materials

> I was considering setting up a full Blockscout instance(s) from source, but would rather avoid or defer that until the wallet is launched, or until and unless there is a real need from a resource utilization perspective.

it could be your scaling solution later. Although, it's very resource consuming to host your very own instance of BlockScout.

> I can see that there is no API key needed to access the EVM APIs, and I can't see any obvious reference to rate or IP limitations -- but I would much prefer to hear from Blockscout directly on any policy or guidelines regarding use of the API. 

Thanks for the point. @SiddigZeidan please create a post of the forum regarding API rate limits of BlockScout. At the moment we have a rate limit of `10000 requests per 1 minute, Block for 1 minute` can be modified later.

**Comment by dmorris99** [comment]
@igorbarinov -- thank you, understood. 

That's a very decent API limit. I will for sure do a write-up on the use case, and of course include a credit to BlockScout when it's released!
