### ISSUE TITLE
Block 0 missing on Clique testnets

### ISSUE THREAD

**Issue by karalabe** [poanetwork/blockscout#1404]
Just noticed that the genesis blocks cannot be retrieved from Clique based networks:

 * Rinkeby: https://blockscout.com/eth/rinkeby/blocks/0/transactions
 * Goerli: https://blockscout.com/eth/goerli/blocks/0/transactions

**Comment by acravenho** [comment]
Hey @karalabe 

Thank you for pointing this out. We will be covering this issue next. I'll provide an update as we progress :+1:

**Comment by brianmcmichael** [comment]
One thing to note, our PoA block 0 has about 20 accounts which each have 0x200000000000000000000000000000000000000000000000000000000000000 poa eth in them. Large number support will be required in this feature.
