### ISSUE TITLE
Total Transactions is not updating. Store Total Transactions in ETS table

### ISSUE THREAD

**Issue by brianmcmichael** [poanetwork/blockscout#1405]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Erlang/OTP 21 [erts-10.2.3] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]

Elixir 1.8.1 (compiled with Erlang/OTP 20)

* Operating System: Ubuntu 18.04

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

Running clique-based testnet. 

### Expected behaviour

*Tell us what should happen.*

Total Transactions count on main page should update. 

### Actual behaviour

*Tell us what happens instead.*

Total Transactions number has remained the same for several days. No update to value since initial sync. CPU(s) are running 100% on the background the entire time. Not sure if related.

**Comment by acravenho** [comment]
Hi @brianmcmichael,

Can you please run `vacuum analyze transactions;` in Postgres?

**Comment by brianmcmichael** [comment]
Hi @acravenho  

I did this and now the total transactions lists the total at the time of the vacuum. I ran some new transactions on the network and those updated the 'total transactions' value on the client side in real time, however when I refreshed the page the total transactions reverted to the post-vacuum value.

**Comment by acravenho** [comment]
Did you restart blockscout after running the vacuum and analyze?

**Comment by acravenho** [comment]
We use `reltuples` for quick estimations of the total number of transactions. If this continues we can create an Erlang Term Storage table to pull this total transaction data from instead of using this reltuples count.

**Comment by brianmcmichael** [comment]
Yes, rebooted the server entirely.

**Comment by acravenho** [comment]
Okay, let's move forward with creating an `:ETS` table to store the total transactions in memory.

**Comment by brianmcmichael** [comment]
Ah, https://www.postgresql.org/docs/9.2/row-estimation-examples.html

`These numbers are current as of the last VACUUM or ANALYZE on the table.`

So we may need to increase autovacuum frequency.

**Comment by acravenho** [comment]
```
ALTER TABLE transactions SET (autovacuum_vacuum_scale_factor = 0.0);  
ALTER TABLE pg_settings SET (autovacuum_vacuum_threshold = 100);  
ALTER TABLE transactions SET (autovacuum_analyze_scale_factor = 0.0);  
ALTER TABLE transactions SET (autovacuum_analyze_threshold = 100);
```

**Comment by vbaranov** [comment]
Related PR: https://github.com/poanetwork/blockscout/pull/1634/files
