### ISSUE TITLE
Create GraphQL Playground Example 

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#1417]
Users should be shown an example when entering the GraphQL playground on BlockScout. This makes it much easier to interact with the chain and learn the potential that GraphQL has to offer. The example we should use is to get the transaction details from either a specific transaction or from a recent block.

**Comment by acravenho** [comment]
Here is an example query for a transaction in GraphQL

```
{
  transaction(hash: "0x69e3923eef50eada197c3336d546936d0c994211492c9f947a24c02827568f9f") {
    blockNumber
    toAddressHash
    fromAddressHash
    createdContractAddressHash
    value
    status
    nonce
    hash
    error
    gas
    gasPrice
    gasUsed
    cumulativeGasUsed
    id
    index
    input
    r
    s
    v
  }
}
```

**Comment by igorbarinov** [comment]
Add in comments a link to the article in the wiki on the forum from  #1420
