### ISSUE TITLE
How to add validators metadata tutorial

### ISSUE THREAD

**Issue by igorbarinov** [poanetwork/blockscout#1421]
how to add validators metadata e.g. on https://blockscout.com/poa/dai like on https://blockscout.com/poa/core

**Comment by acravenho** [comment]
https://forum.poa.network/t/how-to-add-validators-metadata-to-blockscout/1949

@igorbarinov Do we want to add this to the xDAI chain?

**Comment by igorbarinov** [comment]
Yes, please

validators of xDai can be found here https://validators.poa.network/poa-dapps-validators after switching to xDai Chain in Metamask/NiftyWallet

now there are four validators:
0x6dC0c0be4c8B2dFE750156dc7d59FaABFb5B923D - Giveth
0x9233042B8E9E03D5DC6454BBBe5aee83818fF103 - POA
0x9e41BA620FebA8198369c26351063B26eC5b7C9E - MakerDAO
0xA13D45301207711B7C0328c6b2b64862abFe9b7a - Protofire

**Comment by acravenho** [comment]
Validators have been updated. :+1:
