### ISSUE TITLE
The speed of xDAI is truly amazing.  Why not clearly show transaction times in Blockscout

### ISSUE THREAD

**Issue by davecraige** [poanetwork/blockscout#1428]
One of the most amazing value propositions for xDAI is the incredible speed of transactions.  ⚡️ Why not clearly highlight this in Blockscout on each transaction. Imagine being able to look up a transaction and see something like:

"**Transaction time: took 1.1045 seconds to complete**"

I believe that would really encourage more usage, and would set a very high bar for other chains and coins to follow.

**Comment by acravenho** [comment]
Hey @davecraige, 

Great example usage of [xDai and Alpha Wallet](https://twitter.com/davecraige/status/1094539744711630848). It would be great to show this type of statistics but we are limited in our ability to detect exactly when the transaction was initiated to when it was validated. We first see the transaction when it enters the pending tx pool which we fetch every 1,000ms on `xDAI`. This means on `xDAI` we first see 20% of the transactions when it's already validated meaning that we would display `0` seconds for the time it took to complete the transaction which is horribly inaccurate. 

I will keep thinking of possible ways to show this statistic in the UI.

**Comment by zhangzhongnan928** [comment]
> Hey @davecraige,
> 
> Great example usage of [xDai and Alpha Wallet](https://twitter.com/davecraige/status/1094539744711630848). It would be great to show this type of statistics but we are limited in our ability to detect exactly when the transaction was initiated to when it was validated. We first see the transaction when it enters the pending tx pool which we fetch every 1,000ms on `xDAI`. This means on `xDAI` we first see 20% of the transactions when it's already validated meaning that we would display `0` seconds for the time it took to complete the transaction which is horribly inaccurate.
> 
> I will keep thinking of possible ways to show this statistic in the UI.

How about
For those "0" display as "less than 1s"
For those above 1s, display the real time

**Comment by acravenho** [comment]
> > Hey @davecraige,
> > Great example usage of [xDai and Alpha Wallet](https://twitter.com/davecraige/status/1094539744711630848). It would be great to show this type of statistics but we are limited in our ability to detect exactly when the transaction was initiated to when it was validated. We first see the transaction when it enters the pending tx pool which we fetch every 1,000ms on `xDAI`. This means on `xDAI` we first see 20% of the transactions when it's already validated meaning that we would display `0` seconds for the time it took to complete the transaction which is horribly inaccurate.
> > I will keep thinking of possible ways to show this statistic in the UI.
> 
> How about
> For those "0" display as "less than 1s"
> For those above 1s, display the real time

Yes, we can do that. ETA 1-2 weeks for completion. I'll prioritize it now.

**Comment by davecraige** [comment]
Awesome!  Thanks so much @acravenho!

Thanks for the help @zhangzhongnan928!

**Comment by davecraige** [comment]
Awesome, thanks for adding this to `in progress`

**Comment by acravenho** [comment]
<img width="735" alt="screen shot 2019-02-15 at 8 30 58 am" src="https://user-images.githubusercontent.com/17620007/52859981-358f8200-30fc-11e9-88aa-1d932ff5578a.png">

We're very close to merging this PR. I'm trying to decide if `Time Elapsed` is the best description for this feature. `Transaction Speed` may be more appropriate.

**Comment by davecraige** [comment]
That looks great!  (and I agree that "Transaction speed: 2.9 seconds" is a nice way to phrase it)

**Comment by zachdaniel** [comment]
I'll update it to `Transaction Speed`

**Comment by davecraige** [comment]
Thank you everyone for your help on this.  Much appreciated.  🙏
