### ISSUE TITLE
Add large number support.

### ISSUE THREAD

**Issue by brianmcmichael** [poanetwork/blockscout#1431]
In PoA networks the number of tokens are pre-defined in the genesis block. Depending on the economics of the blockchain the number can be very high. This can cause some odd effects with javascript, seen below.

![largenumbers](https://user-images.githubusercontent.com/2374718/52589860-e997c100-2e0d-11e9-8520-a056fff6af91.png)

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): 

```
Erlang/OTP 21 [erts-10.2.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.8.1 (compiled with Erlang/OTP 20)
```

* Operating System: ` Ubuntu 18.04`

### Steps to reproduce

Create a clique-based poa blockchain in geth with a large balance genesis account, ie

```
"239f9569c7ddc251b551ef5a4bb2496b81432daf": {
      "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
    },
```

### Expected behaviour

Application should handle large numbers.

### Actual behaviour

Application displays interesting and unexpected things when confronted with large numbers. (See image, above)

**Comment by acravenho** [comment]
Similar issue but more descriptive as #1120. 

We will work on this feature soon.
