### ISSUE TITLE
Internal transaction should exist for transaction, but don't

### ISSUE THREAD

**Issue by korvindeson** [poanetwork/blockscout#1434]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
Erlang/OTP 21 [erts-10.2.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]
Elixir 1.8.1 (compiled with Erlang/OTP 20)

* Operating System:
Ubuntu 18.04

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

Transaction 0x445504c2c3fca3d75788a9bd0a9868743113e1861c67310d46fddc1c6291e8e5 should produce internal transactions totaling 0.01 Ether, but blockscout says "There are no internal transactions for this transaction."

Same situation for my local copy and below:
https://blockscout.com/eth/mainnet/tx/0x445504c2c3fca3d75788a9bd0a9868743113e1861c67310d46fddc1c6291e8e5/internal_transactions

Etherscan give me result for the same transaction:
https://etherscan.io/tx/0x445504c2c3fca3d75788a9bd0a9868743113e1861c67310d46fddc1c6291e8e5#internal

### Expected behaviour

Transaction have 0x445504c2c3fca3d75788a9bd0a9868743113e1861c67310d46fddc1c6291e8e5 internal transactions.

### Actual behaviour

There are no internal transactions for transaction 0x445504c2c3fca3d75788a9bd0a9868743113e1861c67310d46fddc1c6291e8e5 

Is that an issue in indexing or there are differences in what constitutes internal transaction in etherscan and here?

**Comment by acravenho** [comment]
We're still indexing internal transactions. It's a very slow process.

**Comment by korvindeson** [comment]
Thanks for response. What would be the process for me to understand what period or address were already indexed? Is there a way for me to specify block or date range that I am currently interested in?

**Comment by acravenho** [comment]
Unfortunately, not at this time. We're working on making this process faster in the future.
