### ISSUE TITLE
(Postgrex.Error) ERROR 42703 (undefined_column) column s0.constructor_arguments does not exist

### ISSUE THREAD

**Issue by mkrufky** [poanetwork/blockscout#1442]
Might there be a missing migration after today's merges?   Yesterday's master branch was fine, but today's is broken:

```
(Postgrex.Error) ERROR 42703 (undefined_column) column s0.constructor_arguments does not exist
```
query: SELECT s0."id", s0."name", s0."compiler_version", s0."optimization", s0."contract_source_code", s0."constructor_arguments", s0."abi", s0."address_hash", s0."inserted_at", s0."updated_at", s0."address_hash" FROM "smart_contracts" AS s0 WHERE (s0."address_hash" = $1)
```
     (ecto_sql) lib/ecto/adapters/sql.ex:620: Ecto.Adapters.SQL.raise_sql_call_error/1
     (ecto_sql) lib/ecto/adapters/sql.ex:553: Ecto.Adapters.SQL.execute/5
     (ecto) lib/ecto/repo/queryable.ex:147: Ecto.Repo.Queryable.execute/4
     (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
     (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
 Last message: :update_tokens
 State: %{update_interval: 7}

```

### Environment

I am using `make start` to build and run the docker container defined by `docker/Dockerfile`

**Comment by acravenho** [comment]
https://github.com/poanetwork/blockscout/blob/master/apps/explorer/priv/repo/migrations/20190207105501_add_constructor_arguments_to_smart_contracts.exs

It's there for me. 🤔 I'm not sure why it wouldn't work.

**Comment by mkrufky** [comment]
I believe the problem might be due to the fact that the new migration:
`20190207105501_add_constructor_arguments_to_smart_contracts.exs`

was merged *after* a migration (or migrations) that are named:
`20190208..........`

since the 20190208 migrations already ran on my setup, i think it skipped the 20190207* migration.

Should I just blow away my db and start over?

**Comment by acravenho** [comment]
No, I think we should rename the migration to today's date. This PR was created a few days ago which is probably causing the issue. If you change the date of the file, it should rerun that migration.

**Comment by acravenho** [comment]
I'll create a PR for this update

**Comment by mkrufky** [comment]
renaming it might screw over anybody that already ran it....

if it can drop the column if it already exists before creating it, that should be a nice one-size-fits-all fix

**Comment by acravenho** [comment]
Very good point. We'll have to keep an eye on this for all future migrations. Thanks for the heads up 👍

**Comment by acravenho** [comment]
Pull request has been created. I tried using 
`remove_if_exists(:constructor_arguments, :string)` but it didn't exist. 🤷‍♂️ 

https://hexdocs.pm/ecto_sql/Ecto.Migration.html#remove_if_exists/2
