### ISSUE TITLE
Deployment: v1.3.3 - POA Sokol

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#1448]
## Info
Network: **Sokol Network**
Date: **2019-02-15**
Version: **v1.3.3**

## Description
This issue is for approval of deploying v1.3.3 to POA Sokol Testnet. 

## Specific Directions
* Disable replaced transaction fetcher until the permanent solution is completed
    * Uncomment the following line to disable the dropped/replaced fetcher
https://github.com/poanetwork/blockscout/blob/9c7aff1ea745275901a5e4aee1abc131006a6d54/apps/indexer/config/config.exs#L38

## Approval
- [x] Igor Barinov (@igorbarinov)
- [x] Ayrat Badykov (@ayrat555)

**Comment by igorbarinov** [comment]
:heavy_check_mark:

**Comment by igorbarinov** [comment]
Please coordinate with @vbaranov and @andogro on deployment. They are working on documenting
