### ISSUE TITLE
Add incoming transaction count to contract pages

### ISSUE THREAD

**Issue by snailking** [poanetwork/blockscout#1450]
In Etherscan, incoming transactions are tallied up on the Transaction tab of any contract: “Latest 25 txs from a total of XXX transactions”, above the list of transactions.

![etherscan_tx](https://user-images.githubusercontent.com/39387494/52920187-2f6ef080-330a-11e9-95ec-0bf8de835a2d.jpg)

This can be an useful metric for smart contracts. This data could replace the current transactions sent field, as smart contracts don't send transactions.

### Steps to reproduce

Navigate to the transaction page of a contract. Example: https://blockscout.com/poa/core/address/0x13873fe7a0e2c82434fa7dcd3a08fbbd6ba00217/transactions

### Expected behaviour

Incoming transactions to the contract could show up next to contract name.
![blockscout_contract_suggested](https://user-images.githubusercontent.com/39387494/52920140-a952aa00-3309-11e9-85ce-1cf3b2095e59.jpg)

### Actual behaviour

Currently, the field next to a contract name shows "0 Transactions sent".
![blockscout_contract](https://user-images.githubusercontent.com/39387494/52920154-d8691b80-3309-11e9-8ab1-fe98efa02bc5.jpg)

**Comment by ellis2323** [comment]
Hello,

An API with transaction count would be great. Currently, I request the transactions to count them which is not great.

Best regards
