### ISSUE TITLE
Deployment v1.3.4 - xDAI

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#1453]
## Info
Network: **xDAI Network**
Date: **2019-02-18**
Version: **v1.3.4**

## Description
This issue is for approval of deploying v1.3.4 to POA xDAI Network. 

## Specific Directions
* Disable replaced transaction fetcher until the permanent solution is completed
    * Uncomment the following line to disable the dropped/replaced fetcher
https://github.com/poanetwork/blockscout/blob/9c7aff1ea745275901a5e4aee1abc131006a6d54/apps/indexer/config/config.exs#L38
* Bump version in footer

## Approval
- [x] Igor Barinov (@igorbarinov)
- [x] Ayrat Badykov (@ayrat555)

**Comment by ayrat555** [comment]
:+1:

**Comment by vbaranov** [comment]
xDai instance successfully updated up to `v1.3.4`.
