### ISSUE TITLE
Deployment v1.3.3- Kovan Testnet

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#1461]
## Info
Network: **Kovan Testnet**
Date: **2019-02-20**
Version: **v1.3.3**

## Description
This issue is for approval of deploying v1.3.3 to Kovan Testnet. 

## Specific Directions
* Disable replaced transaction fetcher until the permanent solution is completed
    * Uncomment the following line to disable the dropped/replaced fetcher
https://github.com/poanetwork/blockscout/blob/9c7aff1ea745275901a5e4aee1abc131006a6d54/apps/indexer/config/config.exs#L38
* Bump version in footer

## Approval
- [ ] Igor Barinov (@igorbarinov)
- [ ] Ayrat Badykov (@ayrat555)

**Comment by vbaranov** [comment]
Kovan instance has been updated to `v1.3.3-beta`
