### ISSUE TITLE
Deployment v1.3.4- Rinkeby Testnet

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#1467]
## Info
Network: **Rinkeby Testnet**
Date: **2019-02-21**
Version: **v1.3.4**

## Description
This issue is for approval of deploying [v1.3.4](https://github.com/poanetwork/blockscout/releases/tag/v1.3.4-beta) to Rinkeby Testnet. 

## Specific Directions
* Disable replaced transaction fetcher until the permanent solution is completed
    * Uncomment the following line to disable the dropped/replaced fetcher
https://github.com/poanetwork/blockscout/blob/9c7aff1ea745275901a5e4aee1abc131006a6d54/apps/indexer/config/config.exs#L38
* Bump version in footer

## Approval
- [ ] Igor Barinov (@igorbarinov)
- [ ] Ayrat Badykov (@ayrat555)
- [x] Andrew Cravenho (@acravenho)

**Comment by ArseniiPetrovich** [comment]
v1.3.4 were deployed and available at blockscout.com/eth/rinkeby

**Comment by vbaranov** [comment]
Thanks! I will add missing favicon and version in footer soon.

**Comment by vbaranov** [comment]
Missing favicon has been added. The version added in the footer. The versions table has been updated https://forum.poa.network/t/deployed-instances-on-blockscout-com/1938.
