### ISSUE TITLE
Deployment v1.3.4- Goerli Testnet

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#1472]
## Info
Network: **Goerli Testnet**
Date: **2019-02-22**
Version: **v1.3.4**

## Description
This issue is for approval of deploying [v1.3.4](https://github.com/poanetwork/blockscout/releases/tag/v1.3.4-beta) to Goerli Testnet. 

## Specific Directions
* Disable replaced transaction fetcher until the permanent solution is completed
    * Uncomment the following line to disable the dropped/replaced fetcher
https://github.com/poanetwork/blockscout/blob/9c7aff1ea745275901a5e4aee1abc131006a6d54/apps/indexer/config/config.exs#L38
* Bump version in footer

## Approval
- [x] Igor Barinov (@igorbarinov)
- [ ] Ayrat Badykov (@ayrat555)
- [x] Andrew Cravenho (@acravenho)

**Comment by acravenho** [comment]
We need to add other explorers:

* https://goerli.etherscan.io/
* https://explorer.goerli.net/
* https://lite.ethstats.io/

https://github.com/poanetwork/blockscout/blob/5b7567ed575d2c1d9624630245951f7fd1076a88/apps/block_scout_web/config/config.exs#L22-L26

Also, we need to add the environment variable `BLOCK_TRANSFORMER = clique` to AWS. 

https://github.com/poanetwork/blockscout/blob/5b7567ed575d2c1d9624630245951f7fd1076a88/apps/indexer/config/config.exs#L13

**Comment by acravenho** [comment]
I added the `BLOCK_TRANSFORMER` to the Parameter Store.
