### ISSUE TITLE
An error occurred while validating the contract

### ISSUE THREAD

**Issue by smoey** [poanetwork/blockscout#1481]
An error occurred while validating the contract. The page displays "Internal Server Error"
<img width="747" alt="wx20190223-150313 2x" src="https://user-images.githubusercontent.com/4184607/53283124-7599d900-377c-11e9-8da0-47d7441f63d2.png">
<img width="519" alt="wx20190223-150323 2x" src="https://user-images.githubusercontent.com/4184607/53283130-7a5e8d00-377c-11e9-8705-743b1bd62953.png">

**Comment by acravenho** [comment]
Most likely related to #1497

**Comment by smoey** [comment]
fixed, thx.
