### ISSUE TITLE
Add support for AERUM Live net

### ISSUE THREAD

**Issue by REPTILEHAUS** [poanetwork/blockscout#1491]
_Describe your issue here._

Currently Blockscout does not support the Aerum network. 

We are preparing to launch in the coming weeks and we are 100% compatible with the EVM. We would love to be included, the team really likes your explorer solution and we think it would be a good fit.

Need any more info feel free to contact me directly.

More info:
https://aerum.com/en
https://aerum.com/en/white-paper
https://aerum.com/en/lite-paper
https://aerum.com/en/one-pager

**Comment by vbaranov** [comment]
https://blockscout.com/aerum/mainnet
