### ISSUE TITLE
Not starting up for geth(Ethereum mainnet).

### ISSUE THREAD

**Issue by Monarth-s** [poanetwork/blockscout#1495]
Not starting up for `geth`.

`first_block_number` showing `0`.

I had changed the geth.exs file (for both explorer & indexer) as below:

```
use Mix.Config

config :explorer,
  json_rpc_named_arguments: [
    transport: EthereumJSONRPC.HTTP,
    transport_options: [
      http: EthereumJSONRPC.HTTP.HTTPoison,
      url: System.get_env("ETHEREUM_JSONRPC_HTTP_URL") || "http://localhost:8545",
      http_options: [recv_timeout: :timer.minutes(1), timeout: :timer.minutes(1), hackney: [pool: :ethereum_jsonrpc]]
    ],
    variant: EthereumJSONRPC.Geth
  ],
  subscribe_named_arguments: [
    transport: EthereumJSONRPC.WebSocket,
    transport_options: [
      web_socket: EthereumJSONRPC.WebSocket.WebSocketClient,
      url: System.get_env("ETHEREUM_JSONRPC_WS_URL") || "ws://localhost:8546"
    ],
    variant: EthereumJSONRPC.Geth
  ]

```

But, it's showing this error:

```
2019-02-27T19:01:39.569 [error] Task #PID<0.879.0> started from #PID<0.872.0> terminating
** (FunctionClauseError) no function clause matching in EthereumJSONRPC.integer_to_quantity/1
    (ethereum_jsonrpc) lib/ethereum_jsonrpc.ex:351: EthereumJSONRPC.integer_to_quantity(-1)
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/block/by_number.ex:9: EthereumJSONRPC.Block.ByNumber.request/1
    (elixir) lib/enum.ex:1326: anonymous fn/3 in Enum.map/2
    (stdlib) maps.erl:257: :maps.fold_1/3
    (elixir) lib/enum.ex:1950: Enum.map/2
    (ethereum_jsonrpc) lib/ethereum_jsonrpc.ex:425: EthereumJSONRPC.fetch_blocks_by_params/3
    (indexer) lib/indexer/block/fetcher.ex:104: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer) lib/indexer/block/realtime/fetcher.ex:264: Indexer.Block.Realtime.Fetcher.do_fetch_and_import_block/3
    (indexer) lib/indexer/logger.ex:14: Indexer.Logger.metadata/2
    (indexer) lib/indexer/block/realtime/fetcher.ex:247: Indexer.Block.Realtime.Fetcher.fetch_and_import_block/4
    (indexer) lib/indexer/block/realtime/consensus_ensurer.ex:27: Indexer.Block.Realtime.ConsensusEnsurer.perform/3
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Indexer.Block.Realtime.ConsensusEnsurer.perform/3
    Args: [%Explorer.Chain.Hash{byte_count: 32, bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>}, -1, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://localhost:8545", http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}]

2019-02-27T19:02:44.083 application=indexer fetcher=block_catchup first_block_number=0 last_block_number=0 missing_block_count=0 shrunk=false [info] Index already caught up.
```

### Environment

* Elixir & Erlang/OTP versions (`elixir --version`): **Elixir 1.9.0-dev** & **Erlang/OTP 21**
* Operating System: **Linux Mint 18.3**

**Comment by acravenho** [comment]
@Monarth-s  I believe your issue is that BlockScout is unable to communicate with your node. The easiest approach to debug this would be to define the environment variables such as below:

```
export ETHEREUM_JSONRPC_HTTP_URL=http://localhost:8545
export ETHEREUM_JSONRPC_TRACE_URL=http://localhost:8545
export ETHEREUM_JSONRPC_WS_URL=ws://localhost:8546
export ETHEREUM_JSONRPC_VARIANT=geth
```

**Comment by Monarth-s** [comment]
Tried that, but still same output.

**Comment by acravenho** [comment]
Do you have a public RPC endpoint that I can try?

**Comment by Monarth-s** [comment]
Sorry, I'm runnig `geth` in my local PC, 

I had started geth by using following command:

```
geth --rpc --rpcaddr 0.0.0.0 --rpcapi "debug,net,eth,shh,web3,txpool" --rpccorsdomain "*" --wsapi "eth,net,web3,network,debug,txpool" --ws --wsaddr 0.0.0.0 --wsport 8546 --wsorigins "*" --rpcvhosts "*" --syncmode "full" 
```

Already synced full node:

```
> eth.syncing
{
  currentBlock: 7277397,
  highestBlock: 7277476,
  knownStates: 23677620,
  pulledStates: 23677620,
  startingBlock: 7277397
}
```

**Comment by hadv** [comment]
@Monarth-s If I remove the `--ws` then node can sync the data but explorer web cannot refresh to the latest data. User have to manually refresh browser. Can you confirm this? Thanks!

**Comment by eduardonunesp** [comment]
Same here with ganache

**Comment by saneery** [comment]
I get same error with ganache.

It seems like `ConsensusEnsurer` try to fetch block with `-1` number during the first synchronization
https://github.com/poanetwork/blockscout/blob/24350c1192880722ffc2ab2d46af09a2b2dde1e8/apps/indexer/lib/indexer/block/realtime/fetcher.ex#L266-L269

I think we can ignore such block with guard:
```elixir
def perform(_, number, _) when not is_integer(number) or number < 0, do: :ok
```

**Comment by lightninggalaxy** [comment]
I am getting the same error message with geth.

**Comment by vbaranov** [comment]
@saneery I repeated the problem with ganache. You suggestion looks reasonable. Could you check it locally? And if it eliminates the issue, could you create a PR?

**Comment by saneery** [comment]
@vbaranov, yes sure

**Comment by durgeshEthx** [comment]
** (MatchError) no match of right hand side value: {:error, :econnrefused}
    (indexer) lib/indexer/block/catchup/fetcher.ex:75: Indexer.Block.Catchup.Fetcher.task/1
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Indexer.Block.Catchup.Fetcher.task/1
    Args: [%Indexer.Block.Catchup.Fetcher{block_fetcher: %Indexer.Block.Fetcher{broadcast: :catchup, callback_module: Indexer.Block.Catchup.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://localhost:7545", http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Ganache], receipts_batch_size: 250, receipts_concurrency: 10}, blocks_batch_size: 10, blocks_concurrency: 10, memory_monitor: Indexer.Memory.Monitor}]

 i am using variant as geth , but it is showing ganache in error
