### ISSUE TITLE
[Suggestion] Exact Date and Time

### ISSUE THREAD

**Issue by marcelaopimenta** [poanetwork/blockscout#1506]
Hi, i have a suggestion. Show a exact date time in timestamp field in transaction view.

In etherscan - **3 days 15 hrs ago (Feb-25-2019 04:50:38 PM +UTC)**
In Blockscout - **a day ago**

I use POA for authenticate documents and my user see information in blockscout. Not having the complete date causes much confusion for them.

Thanks!

**Comment by vbaranov** [comment]
Could you provide the link to tx?

**Comment by marcelaopimenta** [comment]
Hi!

https://blockscout.com/poa/core/tx/0x4d3725a310b26c3aa8d453dab9acc655f9c733faeb51cce2bf946856c0ef26a6

**Comment by vbaranov** [comment]
Etherscan doesn't support POA chain. What do you compare with this tx in Etherscan?

**Comment by marcelaopimenta** [comment]
No no, I'm not comparing the transaction. I just asked for the TimeSpan field in Blockscout to have all the date information, not just "3 days ago". Be equal to Etherscan 
"3 days 15 hrs ago (Feb-25-2019 04:50:38 PM +UTC)"

**Comment by marcelaopimenta** [comment]
![image](https://user-images.githubusercontent.com/3244062/53627956-1586b500-3c0a-11e9-904b-a39c121461c2.png)

**Comment by vbaranov** [comment]
Ah, makes sense. Thanks for the feedback. Will include exact time in the future releases.

**Comment by marcelaopimenta** [comment]
Thanks! :-D
