### ISSUE TITLE
block_reward failed to fetch

### ISSUE THREAD

**Issue by LucasGmm** [poanetwork/blockscout#1526]
*Describe your issue here.*

   application=indexer fetcher=block_reward count=10 error_count=10 [error] failed to fetch: @�: (404) Not Found

![image](https://user-images.githubusercontent.com/40879103/53800847-a3e79780-3f78-11e9-99f4-eeb17d542f01.png)

### Environment
Centos 7

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System:
Erlang/OTP 21
Elixir 1.7.4
blockscout-1.3.4-beta

### Steps to reproduce
I use the parity normal sync block, everything is built according to the steps, the web can also access, but I have been reporting the error that block_reward can't get.

Please help me, thank you

**Comment by vbaranov** [comment]
What the chain you are connected to?
