### ISSUE TITLE
Incorrect total transaction number

### ISSUE THREAD

**Issue by rjl493456442** [poanetwork/blockscout#1530]
There are two transactions while the total number is 0.
And the wallet count is also weird. 

![image](https://user-images.githubusercontent.com/5959481/53853030-f4093d00-3ffe-11e9-8e32-e3cf79d62233.png)

**Comment by hadv** [comment]
I think that we need to wait some times to allow blockscout to able to index the data

**Comment by vbaranov** [comment]
That is right. It needs some time to index txs. @rjl493456442 did txs and wallets appear in your case finally?

**Comment by rjl493456442** [comment]
But 6hours later, the transaction number is still 0. (The wallets appears finally)

**Comment by vbaranov** [comment]
What commit did you build Blockscout from?

**Comment by rjl493456442** [comment]
`434b4455a1c882d03d10ee35a44406fe196b4ae8`

**Comment by vbaranov** [comment]
We are using table statistics estimation for total transactions count to increase performance. See related PR where it was introduced: https://github.com/poanetwork/blockscout/pull/256. It means, that the estimated values come not immediately.

**Comment by rjl493456442** [comment]
Weird. Actually, the tx count is still 0. Am I missing something?

**Comment by acravenho** [comment]
@rjl493456442 Run a `vacuum analyze transactions;`

**Comment by vbaranov** [comment]
@rjl493456442 does it work finally? could we close this issue?

**Comment by rjl493456442** [comment]
@vbaranov Really sorry for the late reply. Regarding the transaction number, no it is still zero.

**Comment by rjl493456442** [comment]
@acravenho The sql output

```
/opt/app # psql postgresql://postgres:@localhost:5432/explorer
psql (11.1)
Type "help" for help.

explorer=# vacuum analyze transactions;
VACUUM
explorer=#
```

**Comment by acravenho** [comment]
This issue is related to #1405. I would suggest storing the total transactions in an `ETS` (Erlang Term Storage) table vs querying an estimated amount from Postgres. There may be an issue with v11. Storing the total transactions in an `ETS` should solve all issues related to this.

**Comment by rjl493456442** [comment]
@acravenho Appreciate for the solution. Please ping me when you fix this issue.

**Comment by vbaranov** [comment]
@rjl493456442 total txs count has been configured with an `ETS`: https://github.com/poanetwork/blockscout/pull/1634

The schedule of filling `ETS` with total txs count is configured through `TXS_COUNT_CACHE_PERIOD` env var. It is measured in hours. For example, if `export TXS_COUNT_CACHE_PERIOD=2`, it means, that the task to update `ETS` will start every 2 hours.

**Comment by rjl493456442** [comment]
@vbaranov Do you have any recommendation for this env var? Or in another word, will it introduce a lot overhead if I configure this var much smaller, e.g. `TXS_COUNT_CACHE_PERIOD = 5MIN`(Or only hours supported).

And appreciate for fixing this issue!

**Comment by vbaranov** [comment]
It depends on the size of `transactions` table. For Mainnet with a half a billion of txs you want to set not less then 2 hrs. This var support only hours.

**Comment by rjl493456442** [comment]
@vbaranov Thanks.
