### ISSUE TITLE
Error message that has the code in tracer.js as param

### ISSUE THREAD

**Issue by lightninggalaxy** [poanetwork/blockscout#1536]
I am getting an odd error with my private blockchain.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
Erlang/OTP 21 [erts-10.0.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.7.1 (compiled with Erlang/OTP 19)

Geth 1.8 private network

I am using an old version of Blockscout (cloned in mid January)

* Operating System:
Ubuntu 18.04.01 LTS

### Steps to reproduce
Started a fresh blockchain network
Sent a few transactions

### Expected behaviour
Transaction is successful and do not create any error messages.

### Actual behaviour
Transaction is successful but this error keeps popping up every few seconds in the logs:

    2019-03-07T08:29:02.091 fetcher=internal_transaction count=2 [error] Task #PID<0.5267.0> started 
    from Indexer.InternalTransaction.Fetcher terminating
    ** (EthereumJSONRPC.DecodeError) Failed to decode Ethereum JSONRPC response:

    request:

    url: << RPC I am using >>

    body: [{"id":0,"jsonrpc":"2.0","method":"debug_traceTransaction","params":["0x599c5fdb825742ed5f2216448cdd2d05fe29bd610e44ff9ac560eadad2f54b6d",{"tracer":"// tracer allows Geth's `debug_traceTransaction` to mimic the output of Parity's `trace_replayTransaction`\n{\n    // The call stack of the EVM execution.\n    callStack: [{}],\n\n    // step is invoked for every opcode that the VM executes.\n    step(log, db) {\n        // Capture any errors immediately\n        const error = log.getError();\n\n        if (error !== undefined) {\n            this.fault(log, db);\n        } else {\n            this.success(log, db);\n        }\n    },\n\n    // fault is invoked when the actual execution of an opcode fails.\n    fault(log, db) {\n        // If the topmost call already reverted, don't handle the additional fault again\n        if (this.topCall().error === undefined) {\n            this.putError(log);\n        }\n    },\n\n    putError(log) {\n        if (this.callStack.length > 1) {\n            this.putErrorInTopCall(log);\n        } else {\n            this.putErrorInBottomCall(log);\n        }\n    },\n\n    putErrorInTopCall(log) {\n        // Pop off the just failed call\n        const call = this.callStack.pop();\n        this.putErrorInCall(log, call);\n        this.pushChildCall(call);\n    },\n\n    putErrorInBottomCall(log) {\n        const call = this.bottomCall();\n        this.putErrorInCall(log, call);\n    },\n\n    putErrorInCall(log, call) {\n        call.error = log.getError();\n\n        // Consume all available gas and clean any leftovers\n        if (call.gasBigInt !== undefined) {\n            call.gasUsedBigInt = call.gasBigInt;\n        }\n\n        delete call.outputOffset;\n        delete call.outputLength;\n    },\n\n    topCall() {\n        return this.callStack[this.callStack.length - 1];\n    },\n\n    bottomCall() {\n        return this.callStack[0];\n    },\n\n    pushChildCall(childCall) {\n        const topCall = this.topCall();\n\n        if (topCall.calls === undefined) {\n            topCall.calls = [];\n        }\n\n        topCall.calls.push(childCall);\n    },\n\n    success(log, db) {\n        const op = log.op.toString();\n\n        this.beforeOp(log, db);\n\n        switch (op) {\n            case 'CREATE':\n                this.createOp(log);\n                break;\n            case 'SELFDESTRUCT':\n                this.selfDestructOp(log, db);\n                break;\n            case 'CALL':\n            case 'CALLCODE':\n            case 'DELEGATECALL':\n            case 'STATICCALL':\n                this.callOp(log, op);\n                break;\n            case 'REVERT':\n                this.revertOp();\n                break;\n        }\n    },\n\n    beforeOp(log, db) {\n        /**\n         * Depths\n         * 0 - `ctx`.  Never shows up in `log.getDepth()`\n         * 1 - first level of `log.getDepth()`\n         *\n         * callStack indexes\n         *\n         * 0 - pseudo-call stand-in for `ctx` in initializer (`callStack: [{}]`)\n         * 1 - first callOp inside of `ctx`\n         */\n        const logDepth = log.getDepth();\n        const callStackDepth = this.callStack.length;\n\n        if (logDepth < callStackDepth) {\n            // Pop off the last call and get the execution results\n            const call = this.callStack.pop();\n\n            call.gasUsedBigInt = call.gasBigInt.subtract(log.getGas());\n\n            const ret = log.stack.peek(0);\n\n            if (!ret.equals(0)) {\n                if (call.type === 'create') {\n                    call.createdContractAddressHash = toHex(toAddress(ret.toString(16)));\n                    call.createdContractCode = toHex(db.getCode(toAddress(ret.toString(16))));\n                } else {\n                    call.output = toHex(log.memory.slice(call.outOff, call.outOff + call.outLen));\n                }\n            } else if (call.error === undefined) {\n                call.error = 'internal failure';\n            }\n\n            delete call.outputOffset;\n            delete call.outputLength;\n\n            this.pushChildCall(call);\n        }\n    },\n\n    createOp(log) {\n        const inputOffset = log.stack.peek(1).valueOf();\n        const inputLength = log.stack.peek(2).valueOf();\n        const inputEnd = inputOffset + inputLength;\n        const stackValue = log.stack.peek(0);\n\n        const call = {\n            type: 'create',\n            from: toHex(log.contract.getAddress()),\n            init: toHex(log.memory.slice(inputOffset, inputEnd)),\n            gasBigInt: bigInt(log.getGas()),\n            valueBigInt: bigInt(stackValue.toString(10))\n        };\n        this.callStack.push(call);\n    },\n\n    selfDestructOp(log, db) {\n        const contractAddress = log.contract.getAddress();\n\n        this.pushChildCall({\n            type: 'selfdestruct',\n            from: toHex(contractAddress),\n            to: toHex(toAddress(log.stack.peek(0).toString(16))),\n            gasBigInt: bigInt(log.getGas()),\n            valueBigInt: db.getBalance(contractAddress)\n        });\n    },\n\n    callOp(log, op) {\n        const to = toAddress(log.stack.peek(1).toString(16));\n\n        // Skip any pre-compile invocations, those are just fancy opcodes\n        if (!isPrecompiled(to)) {\n            this.callCustomOp(log, op, to);\n        }\n    },\n\n    callCustomOp(log, op, to) {\n        const stackOffset = (op === 'DELEGATECALL' || op === 'STATICCALL' ? 0 : 1);\n\n        const inputOffset = log.stack.peek(2 + stackOffset).valueOf();\n        const inputLength = log.stack.peek(3 + stackOffset).valueOf();\n        const inputEnd = inputOffset + inputLength;\n\n        const call = {\n            type: 'call',\n            callType: op.toLowerCase(),\n            from: toHex(log.contract.getAddress()),\n            to: toHex(to),\n            gasBigInt: bigInt(log.getGas()),\n            input: toHex(log.memory.slice(inputOffset, inputEnd)),\n            outputOffset: log.stack.peek(4 + stackOffset).valueOf(),\n            outputLength: log.stack.peek(5 + stackOffset).valueOf()\n        };\n\n        switch (op) {\n            case 'CALL':\n            case 'CALLCODE':\n                call.valueBigInt = bigInt(log.stack.peek(2));\n                break;\n            case 'DELEGATECALL':\n                // value inherited from scope during call sequencing\n                break;\n            case 'STATICCALL':\n                // by definition static calls transfer no value\n                call.valueBigInt = bigInt.zero;\n                break;\n            default:\n                throw \"Unknown custom call op \" + op;\n        }\n\n        this.callStack.push(call);\n    },\n\n    revertOp() {\n        this.topCall().error = 'execution reverted';\n    },\n\n    // result is invoked when all the opcodes have been iterated over and returns\n    // the final result of the tracing.\n    result(ctx, db) {\n        const result = this.ctxToResult(ctx, db);\n        const filtered = this.filterNotUndefined(result);\n        const callSequence = this.sequence(filtered, [], filtered.valueBigInt, filtered.gasUsedBigInt, []).callSequence;\n        return this.encodeCallSequence(callSequence);\n    },\n\n    ctxToResult(ctx, db) {\n        var result;\n\n        switch (ctx.type) {\n            case 'CALL':\n                result = this.ctxToCall(ctx);\n                break;\n            case 'CREATE':\n                result = this.ctxToCreate(ctx, db);\n                break;\n        }\n\n        return result;\n    },\n\n    ctxToCall(ctx) {\n        const result = {\n            type: 'call',\n            callType: 'call',\n            from: toHex(ctx.from),\n            to: toHex(ctx.to),\n            valueBigInt: bigInt(ctx.value.toString(10)),\n            gasBigInt: b (truncated)

As you can see, the error message has what's in /geth/debug_traceTransaction/tracer.js. The "0x599c5fdb825742ed5f2216448cdd2d05fe29bd610e44ff9ac560eadad2f54b6d" you see is the very first transaction of the chain.

Please let me know if you need any more information. Thanks.

**Comment by vbaranov** [comment]
Could you please try with the latest code from master branch or at least with the latest release https://github.com/poanetwork/blockscout/releases/tag/v1.3.4-beta? Do you have the same issue with there?

**Comment by lightninggalaxy** [comment]
I can't try it today but I will report back once I have.

**Comment by lightninggalaxy** [comment]
I have tried with v1.3.4 and glad to report that I am not seeing the error message that I have reported. I'll be switching to this version. Thanks!
