### ISSUE TITLE
Pending transaction in block scout but no pending transaction in parity

### ISSUE THREAD

**Issue by 0x-genesys** [poanetwork/blockscout#1538]
*Describe your issue here.*

### Environment
Operating System: Ubuntu

### Steps to reproduce

Send transaction with nonce more than actual nonce. It goes into pending state. transaction shows on blockscout pending tab. Once removed from Parity mem pool , transaction still shows.

### Expected behaviour

Transaction removed from pending pool should be removed from blockscout

### Actual behaviour

Transaction is not removed from blockscout pending table/view

Parity has no pending transactions:

<img width="1086" alt="screenshot 2019-03-07 at 7 37 20 pm" src="https://user-images.githubusercontent.com/40688233/53962313-bd234c00-4110-11e9-810a-9f768d80d2ab.png">

Blockscout has over 1100 : https://explorer.springrole.com/pending_transactions

**Comment by zachdaniel** [comment]
Hello @0x-genesys, thanks for the issue report! The PR that resolves this has already been merged to master #1496. It might be a bit before that gets deployed to master, as we are working through some performance issues, but it should resolve your issue once we do.
