### ISSUE TITLE
repeating error on blockscout log

### ISSUE THREAD

**Issue by LiorRabin** [poanetwork/blockscout#1549]
We've deployed the latest version of blockscout and constantly an error in the log:

> Failing row contains (\x3f424682d35e8734e9f5a1134d0ef11bac07eada, INT, null, 2019-03-12 
> 09:48:27.654335, 2019-03-12 09:48:27.654335, null).
>     (ecto_sql) lib/ecto/adapters/sql.ex:620: Ecto.Adapters.SQL.raise_sql_call_error/1
>     (ecto) lib/ecto/repo/schema.ex:651: Ecto.Repo.Schema.apply/4
>     (ecto) lib/ecto/repo/schema.ex:264: anonymous fn/15 in Ecto.Repo.Schema.do_insert/3
>     (explorer) lib/explorer/chain.ex:2338: anonymous fn/3 in Explorer.Chain.update_token/2
>     (ecto) lib/ecto/multi.ex:580: Ecto.Multi.apply_operation/5
>     (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
>     (ecto) lib/ecto/multi.ex:564: anonymous fn/5 in Ecto.Multi.apply_operations/5
>     (ecto_sql) lib/ecto/adapters/sql.ex:814: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
>     (db_connection) lib/db_connection.ex:1349: DBConnection.run_transaction/4
>     (ecto) lib/ecto/repo/transaction.ex:16: Ecto.Repo.Transaction.transaction/3
>     (explorer) lib/explorer/chain.ex:2341: Explorer.Chain.update_token/2
>     (indexer) lib/indexer/token/fetcher.ex:77: Indexer.Token.Fetcher.catalog_token/1
>     (indexer) lib/indexer/token/fetcher.ex:56: Indexer.Token.Fetcher.run/2
>     (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
>     (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
>     (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
> Function: &Indexer.BufferedTask.log_run/1
>     Args: [%{batch: [%Explorer.Chain.Hash{byte_count: 20, bytes: <<63, 66, 70, 130, 211, 94, 135, 52, 233, 245, 161, 19, 77, 14, 241, 27, 172, 7, 234, 218>>}], callback_module: Indexer.Token.Fetcher, callback_module_state: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "https://rpc.fuse.io", method_to_url: [eth_getBalance: "https://explorer-node.fuse.io", trace_block: "https://explorer-node.fuse.io", trace_replayTransaction: "https://explorer-node.fuse.io"], http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Parity], metadata: []}]

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
`Elixir 1.7.2 (compiled with Erlang/OTP 19)`
* Operating System:
`Linux version 4.14.88-88.76.amzn2.x86_64`
### Steps to reproduce

Just follow the deployment and installation steps in README and start run blockscout

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
It looks like DB migrations did not take place. Did you run `mix ecto.create && mix ecto.migrate`? In addition, the latest version of Blockscout from `master` branch is not compatible with Elixir `1.7.2`. You should build with `1.8.1.`.

**Comment by LiorRabin** [comment]
Yes, I've run the DB migrations. I will try to upgrade the elixir version but I don't think it's related.
Maybe I should drop the DB and let it re-index again? But in that case I will lose all the verified contracts right?

**Comment by vbaranov** [comment]
Yes, if you will drop DB, you will loose verified smart-contracts

**Comment by LiorRabin** [comment]
mix ecto.create && mi ecto. migrate should keep all the verifications right?

**Comment by vbaranov** [comment]
Right, it will not drop DB. It is safe to execute `mix ecto.create && mix ecto.migrate`.

**Comment by vbaranov** [comment]
@LiorRabin does migration execution help?

**Comment by LiorRabin** [comment]
Didn't try it yet, I will update

**Comment by LiorRabin** [comment]
@vbaranov running migration fixed the issue, thanks
