### ISSUE TITLE
token details display

### ISSUE THREAD

**Issue by LiorRabin** [poanetwork/blockscout#1550]
We're running an older version of the blockscout as well as the latest one and we encountered a behaviour we're trying to understand.

A token's name is not showing and in transactions history the value is with all the 18 decimals instead of showing the human-readable value.

New version: https://explore.fuse.io/tokens/0x7d319b6bf7ca1a6d75add79326ad3bf31dca6166/token_transfers

Old version: https://explorer.fuse.io/tokens/0x7d319b6bf7ca1a6d75add79326ad3bf31dca6166/token_transfers

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
`Elixir 1.7.2 (compiled with Erlang/OTP 19)`
* Operating System:
`Linux version 4.14.88-88.76.amzn2.x86_64`

### Steps to reproduce

Just follow the deployment and installation steps in README and start run blockscout

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Do both instances use the same database?
If yes, we recently issued the release [1.3.5-beta](https://github.com/poanetwork/blockscout/releases/tag/v1.3.5-beta). Try to build with it your new version and please let us know the results.

**Comment by LiorRabin** [comment]
The instances use different DBs

**Comment by LiorRabin** [comment]
@vbaranov fixed when deployed new version.
