### ISSUE TITLE
Difference of internal transactions between etherscan and blockscout

### ISSUE THREAD

**Issue by FuZuK** [poanetwork/blockscout#1565]
Hello!
We have an instance of the blockout on our machine and use geth. When executing a request to geth using debug_traceTransaction for transaction 0x288d7c6017ef596c05ad3a27404684c48ed065442ba228e895dc30b37f3231c6 (using the same tracer as blockscount, [request to geth](https://github.com/poanetwork/blockscout/files/2967046/debug_curl.txt)), a list of two internal transactions is returned:
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": [
    {
      "type": "call",
      "callType": "call",
      "from": "0x16ec672039a8515a16b3e0195068fc8630f3ed22",
      "to": "0xc2f949ffa650c8909baed7eccd35def31532990c",
      "input": "0x",
      "output": "0x",
      "traceAddress": [],
      "value": "0x2386f26fc10000",
      "gas": "0xd2f0",
      "gasUsed": "0x2855"
    },
    {
      "type": "call",
      "callType": "call",
      "from": "0xc2f949ffa650c8909baed7eccd35def31532990c",
      "to": "0xa0fdbf3404d39caf3f1b3a4dfebc07b3409221a2",
      "input": "0x",
      "output": "0x",
      "traceAddress": [
        0
      ],
      "value": "0x2386f26fc10000",
      "gas": "0xcd2d",
      "gasUsed": "0x1ce8"
    }
  ]
}
But at the same time etherscan display only one internal transaction:
https://etherscan.io/tx/0x288d7c6017ef596c05ad3a27404684c48ed065442ba228e895dc30b37f3231c6
A public blockscount generally displays an empty list:
https://blockscout.com/eth/mainnet/tx/0x288d7c6017ef596c05ad3a27404684c48ed065442ba228e895dc30b37f3231c6/internal_transactions
What is the reason for this behavior?

**Comment by vbaranov** [comment]
As for the Blockscout we are in the process of reindexing of internal transactions. This is why you can see this message:

![Screenshot 2019-03-15 at 14 44 22](https://user-images.githubusercontent.com/4341812/54429207-e8b9be00-4730-11e9-8015-973a74e8be5c.png)

Hopefully, the missing internal txs will come after the reindexing will finish.

**Comment by FuZuK** [comment]
> As for the Blockscout we are in the process of reindexing of internal transactions. This is why you can see this message:
> 
> ![Screenshot 2019-03-15 at 14 44 22](https://user-images.githubusercontent.com/4341812/54429207-e8b9be00-4730-11e9-8015-973a74e8be5c.png)
> 
> Hopefully, the missing internal txs will come after the reindexing will finish.

Thanks! Do you have any ideas about blockscout returning two internal translations?

**Comment by vbaranov** [comment]
Internal transactions appeared for the aforementioned transaction. I will close the issue when reindexing will fully be finished.
