### ISSUE TITLE
Create API endpoint: a list of all smart-contracts

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#1569]
Module: **Contract**
Endpoint: a list of all smart-contracts addresses from the chain

Input parameters:
 - `batch_size` - batch size
 - `page` - number of page (from 1)
~~`secret_key` - alphanumeric string~~
 - `filter` - the value from the list: verified\decompiled\unverified\not_decompiled (or the numbers (1\2\3\4))

Secret key should store in DB or in ENV variable to be able to change it without redeploying the application.

**Comment by igorbarinov** [comment]
This API should be public and with pagination to prevent DoS

**Comment by kolinko** [comment]
With not_decompiled, it would be good to have a "with_version" parameter. When a new version of the decompiler comes up, when updating the records, we'll need to have a list of contracts that weren't yet decompiled with this new version.

**Comment by vbaranov** [comment]
Thanks for mentioning that. We will add "with_version" parameter.

**Comment by kolinko** [comment]
Thanks!

**Comment by zachdaniel** [comment]
This was completed by #1608
