### ISSUE TITLE
Create API endpoint: upload decompiled smart-contract code

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#1570]
Module: **Contract**

upload API, with the following fields:
- address (with checksum)
- decompiler version (a short string of a few characters, with info on what decompiler version was used)
- decompiled contract as plain text
- secret key

Secret key should store in DB or in ENV variable to be able to change it without redeploying the application.

*Notice*: If upload is called, and there is already a contract in the database with a different version, replace it with the new one.

**Comment by igorbarinov** [comment]
This functionality should be disabled but default
