### ISSUE TITLE
Extend smart-contracts table for storing decompiled code

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#1571]
Extend `smart-contracts` table.

Add new fields:
- `decompiler_version` of type varchar(40)
- `decompiled_code` of type text
- `decompiled` of type Boolean

**Comment by vbaranov** [comment]
Just for the record: instead of extending `smart-contracts` table, the decision was made to create a separate table for decompiled smart-contracts: `decompiled_smart_contracts`

**Comment by kolinko** [comment]
Good choice re: a new table. Decompiled contracts can take some space, so it's probably better to keep them in a separate table.
