### ISSUE TITLE
EIP Voting Mechanism

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#159]
Our goal here is to provide a voting mechanism for users to vote on topics such as Ethereum Improvement Proposals. These votes will be weighted by the balance of coins associated with an address at the time of the vote.  

Casting a vote requires the user to sign a message from the address they will be voting with. 

Here is an example of such a system: https://www.etherchain.org/coinvote

**Comment by KronicDeth** [comment]
The results page use this phrase "All votes are weighted by the Ether balance of the voted accounts at the time the vote closed.", so it's not when each account votes (which is how I would interpret "time of the vote."), but when the voting window closes according to the results page wording.

**Comment by acravenho** [comment]
I agree weighting should occur when the vote closes otherwise, votes can be manipulated by sending funds from address to address.
