### ISSUE TITLE
Missing trie node error from 0x00... account tx's [geth/clique]

### ISSUE THREAD

**Issue by brianmcmichael** [poanetwork/blockscout#1593]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): `1.8.1`
* Operating System: Ubuntu 18.04

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

Running a Clique POA network on geth. Updated from a previous version and updated dependencies and dropped/created/migrated db. Errors appear to stem from tx's eminating from the 0x000... account.

### Expected behaviour

No errors

### Actual behaviour

Logs are filled with errors.

```
2019-03-18T19:11:43.550 application=indexer fetcher=coin_balance count=500 error_count=500 [error] failed to fetch: 0x0000000000000000000000000000000000000000@🋏: (-32000) missing trie node d871c28827dfe1ddeb882ba6ec6b72084e2d148dda287f161b1c4402571f899e (path )
0x0000000000000000000000000000000000000000@𠙳: (-32000) missing trie node d871c28827dfe1ddeb882ba6ec6b72084e2d148dda287f161b1c4402571f899e (path )
0x0000000000000000000000000000000000000000@𚶟: (-32000) missing trie node 802a4a63849b492306e1a62510f3898ec0eddab974adf12cd58011484687db29 (path )
0x0000000000000000000000000000000000000000@𚙆: (-32000) missing trie node 802a4a63849b492306e1a62510f3898ec0eddab974adf12cd58011484687db29 (path )
...
..
.
0x0000000000000000000000000000000 (truncated)
```

**Comment by nrg-jeff** [comment]
I am also having this error running on geth. Ping me if you found a solution @brianmcmichael ?

**Comment by brianmcmichael** [comment]
No solution. I filled up a 200GB disk in the past 24 hours with all of the logs though. As of right now I've resorted to cron jobs trimming the log files every hour.

**Comment by igorbarinov** [comment]
We are  looking into the problem

**Comment by nrg-jeff** [comment]
awesome thanks for the update

**Comment by nrg-jeff** [comment]
I am still receiving this error (using a private ethereum network). Any ideas?

**Comment by ayrat555** [comment]
@nrg-jeff are you using the latest version of blockscout? is your geth node archive node?

**Comment by nrg-jeff** [comment]
@ayrat555 Yes, I am using the latest version of blockscout. My geth node is default (--gcmode full), not archive. Should I use --gcmode archive? Thanks!

**Comment by ayrat555** [comment]
@nrg-jeff yes you should resync your node with `--gcmode=archive`
