### ISSUE TITLE
Handling Contract Address Kill Functionality

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#160]
If a Contract is `created` and then `killed`, balances need to be tracked from the `refundAddress` value. A notification should also be displayed alerting users that this contract is no longer functional.

- [x] Add `refund_address_hash` to `internal_transactions` table
- [ ] Display a notification that the contract has been killed and is no longer functioning on the Contract Details page.
- [ ] If `kill` was executed, keep track of balances

**Comment by KronicDeth** [comment]
For `:suicide` `type` `t:Explorer.Chain.Transactions.t/0` `to_address_hash` stores `["acton"]["refundAddress"]` from the Parity trace replay in #162.
