### ISSUE TITLE
Improve performance of pending txs page

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#1612]
**Problem**: `/pending_transactions` page often causes `Internal server error` on opening for big chains like Ethereum Mainnet

**Solution**: Increase the performance of the page. Maybe to decrease the number of pending txs on the page?

**Comment by vbaranov** [comment]
To have pagination would be awesome.

**Comment by andogro** [comment]
It also throws an error on xDai chain, Sokol
![xdai_pending](https://user-images.githubusercontent.com/14284654/56431588-7b490200-6287-11e9-8d60-d99ea4108056.jpg)
![sokol pending](https://user-images.githubusercontent.com/14284654/56431591-7dab5c00-6287-11e9-9ae7-337be389e825.jpg)
