### ISSUE TITLE
Missing favicon on every deployment

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#1620]
**Problem**: favicon.ico is missing with every deployment of a new Blockscout version to each instance

**Solution**: fix the path for favicon

**Comment by vbaranov** [comment]
We have a workaround for this in BS instance deployment script https://github.com/poanetwork/blockscout-terraform/pull/96. But I'd like to keep it open until we fix it in Blockscout repo.

**Comment by ArseniiPetrovich** [comment]
Actually, it's not in https://github.com/poanetwork/blockscout-terraform#96, but in the new PR I'm preparing for https://github.com/poanetwork/blockscout-terraform#97 issue.
