### ISSUE TITLE
New style for Lukso network

### ISSUE THREAD

**Issue by pashagonchar** [poanetwork/blockscout#1638]
Zeplin:
https://zpl.io/25OzjRn

<img width="1280" alt="lukso_3_3" src="https://user-images.githubusercontent.com/16716926/54830260-d9062080-4cc0-11e9-8c6a-1062e0e82b51.png">

**Comment by frozeman** [comment]
Awesome!
We are currently looking into adding metadata for the validators, so we might need to add that fields later, or on start.

**Comment by frozeman** [comment]
Thanks @pashagonchar

**Comment by pashagonchar** [comment]
@gabitoesmiapodo 

Updates
------
Zeplin:

https://zpl.io/bPPRWYM

https://zpl.io/b61pZvm

https://zpl.io/2v7Q1WQ

https://zpl.io/VOPrNmX

https://zpl.io/aR1ArEK

----------------

![accounts](https://user-images.githubusercontent.com/16716926/55062822-678eef00-507f-11e9-9277-c48298348f6a.png)
![blocks](https://user-images.githubusercontent.com/16716926/55062823-678eef00-507f-11e9-8776-fcc9f932f0f8.png)
![main](https://user-images.githubusercontent.com/16716926/55062825-678eef00-507f-11e9-9e39-a2cb6746c8b4.png)
![transaction_details](https://user-images.githubusercontent.com/16716926/55062827-678eef00-507f-11e9-89bc-23c7d30c6e37.png)
![transactions](https://user-images.githubusercontent.com/16716926/55062830-68278580-507f-11e9-8613-d6f96f3364e6.png)

**Comment by frozeman** [comment]
Very nice!
We would need to change the coin name to **LYX** and remove the USD value parts for now (its a testnet :) )
We also need to be in the list fo the other testnets in the footer i think. "LUKSO L14"

**Comment by gabitoesmiapodo** [comment]
@pashagonchar 

Question: Why isn't there a graph on the main page, like in the other themes? I mean, like in https://zpl.io/V4Ol5MX or https://zpl.io/bWqy9n7

I can change colors and some images for each theme, but that's mostly it. I don't know if it is possible to have radically different pages for different versions.

**Comment by igorbarinov** [comment]
@gabitoesmiapodo which other changes are breaking?
we plan to have the support of the graph with price as it is now, with transactions per second, and without graph at all.

**Comment by gabitoesmiapodo** [comment]
@igorbarinov 

I think the main page would be the only place where there's that kind of branching (one section doing multiple things). Maybe it will change according to some configuration?

Anyway, I just wanted to be sure it wasn't a mistake or and outdated version.

The _Accounts_ section here seems to add a few components and some new functionality which isn't present on the POSDAO designs. I don't know if that will be available for all networks or only here but, in any case, I will add the new features and I think it will be all sorted out with some extra logic later.

**Comment by vbaranov** [comment]
Deployed to the BS LUKSO instance
