### ISSUE TITLE
Blockscout container shutting down

### ISSUE THREAD

**Issue by YumingHe** [poanetwork/blockscout#1645]
I'm wondering what the system requirement is needed for running blockscout. I'm currently experimenting with blockscout on a private Parity PoA network. I am using the dockerized setup. However, I am noticing that the blockscout container will shutdown randomly after couple hours of running, and the CPU consumption is always at ~90%. 

The machine spec I have been running the container under is:
- Ubunto 18.04 2 x64
- 8GB memory
- 4 CPU
- 100 GB SSD

**Comment by acravenho** [comment]
You should have no problems running BlockScout. Are you receiving any errors?

**Comment by YumingHe** [comment]
@acravenho I'm running against a pruning parity node, so i do warinings on not being able to fetch internal transactions and asking me to run an archive node. Other than that nothing, the container just shuts down after a while.

**Comment by vbaranov** [comment]
It depends on the size of the chain, which you are interested in the indexing in Blockscout. For example, in the case of ETH Mainnet chain, the current spec is close to https://github.com/poanetwork/blockscout/issues/2013#issuecomment-495189456. In your case of PoA-based chain, if assume it has much less capacity than Mainnet, the spec would be much lighter. I encourage you to play with the parameters.
