### ISSUE TITLE
Queue at maximum, entries could not be added

### ISSUE THREAD

**Issue by kunpoolsion** [poanetwork/blockscout#1646]
Indexer is refusing to add entries.

### Environment

* Elixir & Erlang/OTP versions :1.8.1 / 21
* Operating System: 16.04

### Steps to reproduce

After index the blockchain, while waiting for new blocks the indexer starts to return the errors.

### Expected behaviour

Add all entries

### Actual behaviour

Refuse to add them. The total ammount of account are decreasing quickly.

`2019-03-24T00:56:27.405 application=indexer fetcher=internal_transaction [warn] BufferedTask #PID<0.26339.13> (Indexer.InternalTransaction.Fetcher) bound queue is at maximum size (12156) and 10 entries could not be added.
2019-03-24T00:56:27.413 application=indexer fetcher=coin_balance [warn] BufferedTask #PID<0.26314.13> (Indexer.CoinBalance.Fetcher) bound queue is at maximum size (1152) and 500 entries could not be added.`

**Comment by acravenho** [comment]
You need to increase your memory limit: https://github.com/poanetwork/blockscout/blob/b4de943cdd034680750a12c829645bdc947e2be2/apps/indexer/config/config.exs#L36

**Comment by kunpoolsion** [comment]
thx, done, looks right
