### ISSUE TITLE
Ethereum Mainnet: <how to verify my token exchange? >

### ISSUE THREAD

**Issue by Chongfeitoo** [poanetwork/blockscout#1648]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System:

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
@Chongfeitoo please elaborate what is your issue about?

**Comment by Chongfeitoo** [comment]
I have problems with my Etherscan account token verification and exchange to my wallet.

**Comment by vbaranov** [comment]
This is a Blockscout repo. If you have any problems with verification of smart-contract in Blockscout, please describe your issue in details using the template.
