### ISSUE TITLE
"Unknown Action" when getting account balance for a specific address (ETH Mainnet)

### ISSUE THREAD

**Issue by pedrouid** [poanetwork/blockscout#1655]
I'm using `blockscout.com` API and I'm getting very similar issue to #1346 but I have it for a different address and network.

Whenever I try to get the account balance for `0x6e4d387c925a647844623762ab3c4a5b3acd9540` on ETH Mainnet using the following request.

```sh
GET https://blockscout.com/eth/mainnet/api?module=account&action=balance&address=0x6e4d387c925a647844623762ab3c4a5b3acd9540
```

I get the `Unknown Action` error response

```json
{
    "status": "0",
    "result": null,
    "message": "Unknown action"
}
```

However I don't get this issue with other addresses as for example: `0xcBec15583A21C3ddAD5fab658be5b4FE85Df730b`

**Comment by vbaranov** [comment]
Just for the record: from my tests, this issue can spontaneously appear/disappear for any address on every chain.

**Comment by pedrouid** [comment]
Could we get a different error message for what's causing this issue?

**Comment by vbaranov** [comment]
We will figure out what is the root cause and will try to eliminate this.

**Comment by FuZuK** [comment]
I think this is due to the fact that fetched_coin_balance for this address is null in the addresses table.
