### ISSUE TITLE
Feature request: transaction traces

### ISSUE THREAD

**Issue by d10r** [poanetwork/blockscout#1656]
Sometimes it would be useful to view (raw) transaction traces. Examples on other explorers:
* etherscan: https://etherscan.io/vmtrace?txhash=0x1c9679c0f6e1539075b5c52939ec72eef5995c69c571f9f84f599768cc479707&type=parity#raw
* etherchain-light: https://light.etherchain.org/tx/raw/0xb685caa9686474cbc9d6e577845cf617c9992c04e2bfca1fd3f8248460c1b365

**Comment by igorbarinov** [comment]
We don't store this data in the database afaik
There are possible ways to get the data 
- from the node on request
- add additional fetcher and persist it
