### ISSUE TITLE
Edit colors for ETC theme

### ISSUE THREAD

**Issue by pashagonchar** [poanetwork/blockscout#1664]
Zeplin:

https://zpl.io/aNPWNvN

<img width="1280" alt="blockscout_etc" src="https://user-images.githubusercontent.com/16716926/55101055-e90c6e80-50cb-11e9-9dcd-b7e6c9316618.png">

**Comment by gabitoesmiapodo** [comment]
I think the header should have a white background and the rest of the elements should be positioned according to the new base design which is being developed.

https://app.zeplin.io/project/5a6053176eb2bda2cf9379be/screen/5c6f9e55e0abfe1aded444b3

**Comment by vbaranov** [comment]
Done here https://github.com/poanetwork/blockscout/pull/1922
