### ISSUE TITLE
Deployment v1.3.8- Sokol, xDai

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#1666]
## Info
Networks: **Sokol**, **xDai**
Date: **2019-03-28**
Version: **v1.3.8**

## Motivation
In order to fix contracts verification for `petersburg` EVM version https://github.com/poanetwork/blockscout/issues/1641

## Description
This issue is for approval of deploying [v1.3.8](https://github.com/poanetwork/blockscout/releases/tag/v1.3.8-beta) to Sokol and xDai. 

## Specific Directions
* Disable replaced transaction fetcher until the permanent solution is completed
    * Uncomment the following line to disable the dropped/replaced fetcher
https://github.com/poanetwork/blockscout/blob/9c7aff1ea745275901a5e4aee1abc131006a6d54/apps/indexer/config/config.exs#L38
* update `BLOCKSCOUT_VERSION` and `RELEASE_LINK` env vars

## Approval
- [x] Igor Barinov (@igorbarinov)
- [ ] Ayrat Badykov (@ayrat555)
- [x] Victor Baranov

**Comment by igorbarinov** [comment]
Let's replace telegram link to https://t.me/poa_network here and in other instances too
