### ISSUE TITLE
Design for RSK Network

### ISSUE THREAD

**Issue by pashagonchar** [poanetwork/blockscout#1672]
Zeplin
-----
https://zpl.io/aXPd8wj

https://zpl.io/2p4Zewj

https://zpl.io/anpW45n

https://zpl.io/2yOpeKL

https://zpl.io/aw4jez1

https://zpl.io/agzMdxA

-------------------------------------

<img width="1280" alt="accounts@2x" src="https://user-images.githubusercontent.com/16716926/55157968-74d2d900-5166-11e9-8a41-09b917475f99.png">
<img width="1280" alt="blocks@2x" src="https://user-images.githubusercontent.com/16716926/55157969-756b6f80-5166-11e9-9526-95bee33e25a7.png">
<img width="1280" alt="choose_network@2x" src="https://user-images.githubusercontent.com/16716926/55157970-756b6f80-5166-11e9-99be-32f7260f55d6.png">
<img width="1280" alt="main@2x" src="https://user-images.githubusercontent.com/16716926/55157972-76040600-5166-11e9-9d94-67676ddd44e5.png">
<img width="1280" alt="transactions@2x" src="https://user-images.githubusercontent.com/16716926/55157973-76040600-5166-11e9-8d97-4e0bb1b427b8.png">
<img width="1280" alt="transaction_details@2x" src="https://user-images.githubusercontent.com/16716926/55157994-81573180-5166-11e9-86c1-dffb4fed2615.png">

**Comment by vbaranov** [comment]
Done here https://github.com/poanetwork/blockscout/pull/1903

**Comment by vbaranov** [comment]
Implemented https://github.com/poanetwork/blockscout/issues/2104
