### ISSUE TITLE
Not all logs in api are returned for a transaction

### ISSUE THREAD

**Issue by FuZuK** [poanetwork/blockscout#1674]
A request in api for a single transaction (?module=transaction&action=gettxinfo&txhash={transactionHash}) returns an incomplete list of logs. Only a maximum of 50 items are returned. Example transaction: 0x0c61db4e3e40eb58fe9378c1ed7a611205ca8d49fb87f3f153051ccaa9b40147

**Comment by ayrat555** [comment]
@FuZuK which network are you using?

**Comment by igorbarinov** [comment]
> @FuZuK which network are you using?

There is a tx on Mainnet https://etherscan.io/tx/0x0c61db4e3e40eb58fe9378c1ed7a611205ca8d49fb87f3f153051ccaa9b40147

@zachdaniel can you look into the issue?

**Comment by ayrat555** [comment]
There is no pagination for this endpoint

**Comment by FuZuK** [comment]
> There is no pagination for this endpoint

Thanks! Then I think it's worth adding it.
