### ISSUE TITLE
Token list popover for an address isn't visible in Firefox

### ISSUE THREAD

**Issue by goodsoft** [poanetwork/blockscout#1686]
![image](https://user-images.githubusercontent.com/2828228/55280618-c3cc6a00-5330-11e9-9d64-13c1687b536d.png)

### Environment

* Operating System: Linux
* Browser: Firefox 64.0.2

### Steps to reproduce

1. Open any address page, e.g. https://blockscout.com/eth/mainnet/address/0xea674fdde714fd979de3edf0f56aa9716b898ec8/transactions
2. Click token count in the top right corner

### Expected behaviour

The token list is visible.

### Actual behaviour

The token list is hidden under other content, if the page is opened in Firefox.
When viewed in Chrome, the token list is visible as expected.

**Comment by vbaranov** [comment]
It will be fixed in the upcoming release `2.0.0`
