### ISSUE TITLE
Old block is still not processed

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#1687]
Affected block: https://blockscout.com/poa/dai/blocks/2932019/transactions
Affected tx from block: https://blockscout.com/poa/dai/tx/0xda8be13de4919dd12a9ca4c00becce82b384a1eceed701d1a4da2ea97b7c5d60

Block is still not processed.

**Comment by goodsoft** [comment]
Any log lines containing the block number?
`DELETE * FROM internal_transactions WHERE block_number = 2932019`?

**Comment by phahulin** [comment]
@goodsoft here are logs that I found:
[block-2932019.log.gz](https://github.com/poanetwork/blockscout/files/3028374/block-2932019.log.gz)

Block and tx are processed now

**Comment by goodsoft** [comment]
Did it get processed without restarting app server and running any database queries?

**Comment by phahulin** [comment]
> Did it get processed without restarting app server and running any database queries?
Yes

> Logs are totally unrelated, BTW.
Anything else I can grep for?

**Comment by goodsoft** [comment]
I guess, it's not a bug then, just slow indexing.
