### ISSUE TITLE
Please Add new Sokol Validator https://blockscout.com/poa/sokol

### ISSUE THREAD

**Issue by 6proof** [poanetwork/blockscout#1694]
*New Sokol Validator Kiryl Ihnatsyeu has been added to Sokol.  Please add MetaData to BlockScout.*

When new Validators are voted in to any POA Network BlockChain, those Validators are responsible for adding their MetaData using the Validators DApp.  See https://sokol-validators.poa.network/poa-dapps-validators as an example.

Instead of increasing load by forcing BlockScout to scan each block manually to determine if a new Validator has been added, Validator MetaData is added by the BlockScout team manually as new Validators provide and update their information.

Please add New Sokol Validator Kiryl Ihnatsyeu MetaData to the Sokol BlockScout found at https://blockscout.com/poa/sokol . Kiryl's MetaData is found at the bottom of the Validator's page at   https://sokol-validators.poa.network/poa-dapps-validators

Please let me know if there is anything I can do to help.  Thanks!

**Comment by ArseniiPetrovich** [comment]
https://blockscout.com/poa/sokol/address/0x130930e3e3d30bf8f975a729e948cdcc212ecfbb/transactions
Metadata updated automatically, can be closed now.
