### ISSUE TITLE
Incorrect contract creation code generated in latest changes. 

### ISSUE THREAD

**Issue by nervehammer** [poanetwork/blockscout#1707]
### Incorrect bytecode generated for deployed smart contract

Smart contract bytecode is incorrectly generated in the latest version of the blockscout. This issue makes contract code verification impossible for the deployed smart contract. 

### Environment

* Erlang/OTP 21 [erts-10.3.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
* Elixir 1.8.1 (compiled with Erlang/OTP 20)

* Operating System: Kubuntu 18.04.1-amd64

### Steps to reproduce

[Spring Explorer](https://explorer.springrole.com) currently running forked [blockscout](https://github.com/SpringRole/blockscout/tree/d80f0b2f29ebad43ebaeb0e4001a06da9ee22e6a)  
and the smart contract [VanityURL](https://explorer.springrole.com/address/0x8cafc3eb956b95a3a0bccbc31cedd8042b2c45a8/contracts) contract creation code is inline with compiled bytecode via solc, but with latest changes merged from blockscout's master branch it produces entirely different bytecode and hence throws `Bytecode does not match, please try again`.

### Expected behaviour

Contract creation code should be generated properly and hence allow verification of smart contract.

### Actual behaviour
Due to incorrect bytecode, explorer can't verify smartcontract and throws **Bytecode does not match, please try again.** error.

**Comment by ayrat555** [comment]
@nervehammer what version of blockscout are you using?

**Comment by ayrat555** [comment]
your code verification interface doesn't have  `petersburg` evm version which is default in the latest version of blockscout

**Comment by nervehammer** [comment]
yes, the old version is working fine https://github.com/SpringRole/blockscout/commits/d80f0b2f29ebad43ebaeb0e4001a06da9ee22e6a but with new changes from your master branch seems to break this.

**Comment by nervehammer** [comment]
I have the latest changes from your master branch locally and it is still the same.

**Comment by nervehammer** [comment]
Maybe this might help:
**correct contract creation code**: https://hastebin.com/fubameboco
**incorrect contract creation code with latest changes**: https://hastebin.com/eyeqesidun
**smartcontract used**: https://raw.githubusercontent.com/SpringRole/smart-contracts/master/contracts/VanityURL.sol

**Comment by ayrat555** [comment]
Thanks. I'll look into your example now

**Comment by ayrat555** [comment]
@nervehammer can please send all fields that you entered to your verification form

**Comment by nervehammer** [comment]
contract name: VanityURL
compiler version: v0.4.24+commit.e67f0147
EVM Version: byzantium
Optimization: No

**Comment by ayrat555** [comment]
@nervehammer do you receive `Constructor arguments do not match, please try again.`?

**Comment by ayrat555** [comment]
I checked your contract verification locally. It verified successfully.

**Comment by nervehammer** [comment]
@ayrat555 nope not receive this kind of error: "Constructor arguments do not match, please try again.?" and that contract doesn't have any constructor. And I will try to rebuild from scratch in a different environment. Will update you asap.

**Comment by nervehammer** [comment]
@ayrat555 our chain doesn't distribute block rewards and has emptySteps enabled, its a parity variant. 
I hosted a temporary explorer of our chain based on the latest [commit](https://github.com/poanetwork/blockscout/tree/42f8e72e80a3e483fa52dbde3c5c32f7d7d83efe), http://128.199.253.218/address/0x8cafc3eb956b95a3a0bccbc31cedd8042b2c45a8/contract_verifications/new as you can try here, it will fail and throw `bytecode does not match`.

Here is the same contract verified in the old version, https://explorer.springrole.com/address/0x8cafc3eb956b95a3a0bccbc31cedd8042b2c45a8/contracts

**Comment by ayrat555** [comment]
@nervehammer I checked verification again and it works. can you host your explorer one more time?

**Comment by nervehammer** [comment]
it is up: http://206.189.148.100/address/0x8cafc3eb956b95a3a0bccbc31cedd8042b2c45a8/contract_verifications/new

**Comment by ayrat555** [comment]
I can't access it

**Comment by nervehammer** [comment]
it's working fine here.

**Comment by ayrat555** [comment]
can we move our discussion to the project's gitter https://gitter.im/poanetwork/blockscout?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge
