### ISSUE TITLE
Internal Server Error when looking for a Token Symbol

### ISSUE THREAD

**Issue by mgarciap** [poanetwork/blockscout#1725]
I entered `DAI` into the search box as the token symbol I want to search. This is the result:

![image](https://user-images.githubusercontent.com/201871/55834835-21ab3f80-5af1-11e9-8b0a-2c7f506015b1.png)

URL: https://blockscout.com/eth/mainnet/search?q=dai

**Comment by igorbarinov** [comment]
It's fixed in https://github.com/poanetwork/blockscout/pull/1669 
and will be deployed on Eth mainnet soon
