### ISSUE TITLE
Add 'Download CSV Export' to the Transactions list in the 'Address Details' page

### ISSUE THREAD

**Issue by mgarciap** [poanetwork/blockscout#1730]
In the **Address Details** page when I am taking a look at the **Transactions** list I would like to be able to **download a CVS export** with all the transactions, not only the one shown in the first transactions page, so I can work with the full list of transactions outside of the explorer.

I would like the CVS export to contain a row for each TX with all the details already available. For example:
```
Txhash
Block#
UnixTimestamp
DateTime
From
To
ContractAddress <- If Any
Type  <-  IN or OUT
Value_IN(ETH)
Value_OUT(ETH)
ETHCurrentValue(USD/ETH)
TxnFee(ETH)
TxnFee(USD)  <- At the time it was executed
ETHValueAtTxDate(USD/ETH) <- At the time it was executed
Status
ErrCode
```

**Comment by mgarciap** [comment]
thank you @vbaranov for including the feature in the roadmap. Any ETA?

**Comment by vbaranov** [comment]
Hi @mgarciap. We have no ETA on this. But I hope it could be included into the next release. Usually, we issue a new release every 2-3 weeks.

**Comment by mgarciap** [comment]
Hi @vbaranov any updates?

**Comment by ayrat555** [comment]
@mgarciap I am starting working on it today. I'm sorry for the delay
