### ISSUE TITLE
Show Token specific details in the Transfer Details page if it was a token's operation

### ISSUE THREAD

**Issue by mgarciap** [poanetwork/blockscout#1732]
When I browse to a Transaction Details page which is related to a Token Transfer not a ETH transfer the only difference I see is the label used for the TX status (success/failure): _Token Transfer_ for Tokens and Transaction_ for ETH. The rest is the same.

Example for a DAI transfer TX: https://blockscout.com/eth/mainnet/tx/0x5503de1d0340c039956ea39103116791657a1b20547d6710fe16d784c15e6234

I would like to see the following information depending on the token type instead of ETH which will be 0:
- ERC-20: amount of tokens transferred
- ERC-721: TokenID with the link to the contract

![image](https://user-images.githubusercontent.com/201871/55877154-afc60b00-5b6f-11e9-9cbf-06d7cf315c44.png)

Similar to the data in the [Etherscan TX Detail page](https://etherscan.io/tx/0x5503de1d0340c039956ea39103116791657a1b20547d6710fe16d784c15e6234) but simplified.

**Comment by igorbarinov** [comment]
Good issue
