### ISSUE TITLE
Invalid arithmetic expression

### ISSUE THREAD

**Issue by rjl493456442** [poanetwork/blockscout#1737]
**Latest master branch**

```
Request: GET /address/0xb674cac98f179f2caf34d5cd37cf0a7f46690984/transactions
** (exit) an exception was raised:
    ** (ArithmeticError) bad argument in arithmetic expression
        :erlang.div(86400000, 0)
        (indexer) lib/indexer/coin_balance/on_demand_fetcher.ex:177: Indexer.CoinBalance.OnDemandFetcher.stale_balance_window/1
        (indexer) lib/indexer/coin_balance/on_demand_fetcher.ex:44: Indexer.CoinBalance.OnDemandFetcher.trigger_fetch/1
        (block_scout_web) lib/block_scout_web/controllers/address_transaction_controller.ex:94: BlockScoutWeb.AddressTransactionController.index/2
        (block_scout_web) lib/block_scout_web/controllers/address_transaction_controller.ex:1: BlockScoutWeb.AddressTransactionController.action/2
        (block_scout_web) lib/block_scout_web/controllers/address_transaction_controller.ex:1: BlockScoutWeb.AddressTransactionController.phoenix_controller_pipeline/2
        (block_scout_web) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:275: Phoenix.Router.__call__/1
```

**Comment by rjl493456442** [comment]
@ayrat555 Could you please take a look? It should be a trivial fix :)

**Comment by ayrat555** [comment]
@rjl493456442 just to be sure. it means that your average block time is 0. is this correct?

**Comment by rjl493456442** [comment]
Weird. The average block time is 15 seconds. Now the errors disappear.

Any idea about it? E.g. some indexing data has been finished, so the error occurs.  But later it works.

**Comment by ayrat555** [comment]
maybe your database didn't have any blocks? @rjl493456442

**Comment by rjl493456442** [comment]
@ayrat555 No, I have 8 transactions and 9 address at that time.

**Comment by ayrat555** [comment]
I think you had only one block. I'll create a fix now

**Comment by rjl493456442** [comment]
@ayrat555 Actually there are a lot of blocks already. But appreciate for your fix. I can help the testing, not sure the issue can be reproduced.

**Comment by rjl493456442** [comment]
@ayrat555 I'm really sorry. Test the latest master branch, now no panic, everything works well. BUT the average block time seems invalid.

![image](https://user-images.githubusercontent.com/5959481/56025312-798db480-5d44-11e9-94cc-87ecbc02baed.png)

**Comment by ayrat555** [comment]
@rjl493456442 it looks like your database has a small number (one?) of blocks. the value is updated every 30 minutes.

**Comment by rjl493456442** [comment]
@ayrat555 Yes, this now 15 seconds. Sorry for the nitpicks :)
