### ISSUE TITLE
Websocket for newHeads, need to keep the connection alive

### ISSUE THREAD

**Issue by eduardonunesp** [poanetwork/blockscout#1738]
Need help to create a method to keep the socket for `netHeads` alive, in my case the socket for the `newHeads` after open needs to ping the node at a certain time for instance each `600 seconds` or the node will close de connection by not receive any `ping`. It's not a bug is just a question what is the best way to implement that feature. Thanks

**Comment by zachdaniel** [comment]
I think the best way to do it would be to start a process responsible only for polling in that appropriate interval.

**Comment by zachdaniel** [comment]
I'll look into how we might add that as a sibling process to the realtime fetcher :+1:

**Comment by zachdaniel** [comment]
So typically the server would be responsible for pinging the client, not the other way around. Are you looking for a way to have your node ping blockscout periodically? Currently, the websocket connection in blockscout will respond appropriately to pings. Is there a way to set up your node to ping in an appropriate interval?

**Comment by eduardonunesp** [comment]
hey @zachdaniel thanks for the answers, well the idea is to have a way to the blockscout ws connection to ping the node server at a certain interval or the node will close the socket conneciton by considering that connection is dead since the blockscout only receives the newHeads notification but doesn't send any message, probably this thing works under the hood for the ws connection.

**Comment by zachdaniel** [comment]
Got it, well it took some digging because the library we use for web sockets is rather obscure, but I found an option we can set to give it a keep alive ping. And we know that, in all other cases, it really doesn’t hurt to send a long every couple of minutes, so I’ll just add it, and let the period be configurable. I’ll start off with 2.5 minutes, which can be changed with configuration.

**Comment by eduardonunesp** [comment]
Super cool thanks for the help
