### ISSUE TITLE
Contributor sees live value updates of value and market cap on homepage

### ISSUE THREAD

**Issue by tmecklem** [poanetwork/blockscout#174]
The exchange rates are fetched every 5 minutes in the backend. Those values should be refreshed live on the home page chart as they are updated.

**Comment by KronicDeth** [comment]
Phoenix Channel broadcast can be used for this, but Phoenix should not be mixed into the backend contexts that currently don't depend on it, so there may need to be an event system that something in the `explorer_web` can subscribe to that then does the broadcast to ensure the backend in `explorer` stays separated from Phoenix in `explorer_web`.
