### ISSUE TITLE
Design errors pages

### ISSUE THREAD

**Issue by pashagonchar** [poanetwork/blockscout#1747]
Zeplin:
-------------
https://zpl.io/beAg4rY

https://zpl.io/Vqv6xB6

https://zpl.io/2GGzmBj

<img width="1280" alt="block_not_found_2@2x" src="https://user-images.githubusercontent.com/16716926/56041136-b061cb80-5d40-11e9-8018-323c93a6083e.png">
![there_are_no_matching_entries](https://user-images.githubusercontent.com/16716926/56041137-b061cb80-5d40-11e9-8e17-fe5d9508afd7.png)
<img width="1280" alt="tx_not_found" src="https://user-images.githubusercontent.com/16716926/56041139-b0fa6200-5d40-11e9-805b-c7ca6f30592d.png">

**Comment by pashagonchar** [comment]
Animations
------

[animations.zip](https://github.com/poanetwork/blockscout/files/3073712/animations.zip)

**Comment by vbaranov** [comment]
@pashagonchar do we have a design for "page not found" error?

**Comment by pashagonchar** [comment]
@vbaranov  I'll provide design for "page not found"
