### ISSUE TITLE
Edit dropdown list for Networks

### ISSUE THREAD

**Issue by pashagonchar** [poanetwork/blockscout#1752]
Add titles Mainnet and Testnet 
Add line beetwen mainnet and testnet networks

![main_test_net_2](https://user-images.githubusercontent.com/16716926/56114614-167d6700-5f6a-11e9-901a-34bad80ddd40.png)

**Comment by igorbarinov** [comment]
Let's order networks in each list in alphabetical order.
e.g.
```
Ethereum Classic
Ethereum Mainnet
POA Core Mainnet
RSK Mainnet
xDai Chain Mainnet
```

```
Goerli Testnet
Kovan Testnet
POA Sokol Testnet
Rinkeby Testnet
Ropsten Testnet
```

**Comment by pashagonchar** [comment]
@igorbarinov 

![main_test_net_3](https://user-images.githubusercontent.com/16716926/56115819-00bd7100-5f6d-11e9-8765-25fef238c50e.png)
