### ISSUE TITLE
interpolate balance chart on x axis

### ISSUE THREAD

**Issue by ayrat555** [poanetwork/blockscout#1754]
![img](https://i.imgur.com/5AXMd2p.png)

If there is only one point on chart, the chart is not interpolated.

**Comment by vbaranov** [comment]
Maybe we should display `blockNumber` instead of `date` on `x` axis?

**Comment by ayrat555** [comment]
@vbaranov We can do that. But for the end user, it may be more obvious if we use date?

**Comment by vbaranov** [comment]
So, you will display an actual date of block creation on `x` axis, right?

**Comment by ayrat555** [comment]
@vbaranov  I was planning to just interpolate chart to `x` axis without changing anything. But I'm open to suggestions

**Comment by vbaranov** [comment]
Could you elaborate on how you plan to interpolate having only one point?

**Comment by vbaranov** [comment]
Got it. Sounds good.
