### ISSUE TITLE
API timing out with txlistinternal

### ISSUE THREAD

**Issue by FrederikBolding** [poanetwork/blockscout#1765]
API seems to timeout when using `txlistinternal` passing an address instead of a txhash.

Example:
https://blockscout.com/eth/mainnet/api?module=account&action=txlistinternal&txhash=0xef1c316dca37949aef94bf3d76efa1e21813ea9f5533e7bc5d93af98862d8dea - works

https://blockscout.com/eth/mainnet/api?module=account&action=txlistinternal&address=0xe77162b7d2ceb3625a4993bab557403a7b706f18 - times out

**Comment by vbaranov** [comment]
Both API links respond in time now. I am closing this issue.
