### ISSUE TITLE
Update footer icon links

### ISSUE THREAD

**Issue by andogro** [poanetwork/blockscout#1772]
Footer icons go to outdated resources:

Github: Currently linked to general POA network github, should go to blockscout github: https://github.com/poanetwork/blockscout

Twitter: Currently linked to POA network twitter. New official twitter for BlockScout is https://twitter.com/_blockscout

Telegram: Community channel may not be best resource. Add discord instead? https://discordapp.com/channels/502416149343109121/502432256011272195

**Comment by vbaranov** [comment]
@andogro thank you, we updated 
- twitter acc to official blockscout twitter acc
- telegram acc to offcial POA announcements channel
- we will update Github link to Blockscout repo soon

All updates will be included to a new release 1.3.10
