### ISSUE TITLE
Create Test Chain for Indexer Tests

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#179]
In order to quickly test our new indexer, we should create a new test chain with minimal transactions and blocks to quickly test the indexer going from Genesis to current block height and switching to live indexing.

**Comment by igorbarinov** [comment]
We can give a try to our new deployment tool to deploy that chain

**Comment by acravenho** [comment]
@igorbarinov That would be great. Who should I speak with about getting this started?

**Comment by igorbarinov** [comment]
Let's assign it to me and I'll figure out resources

**Comment by KronicDeth** [comment]
@igorbarinov I may need both Parity and Geth client exposed chains since Infura doesn't supply `debug_traceTransactions`.  Would it be more helpful if I open a separate issue for Geth/Ethereum Mainnet and leave this just for Parity/Test chain?

**Comment by acravenho** [comment]
As mentioned in today's standup we need the test chain for multiple scenarios including `pending transactions`, `uncles`, and `transactions` with several `internal transactions`.
