### ISSUE TITLE
Show the summary of total tokens transferred for 1 tx

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#1792]
Inspired by https://github.com/poanetwork/blockscout/issues/1732

From this PR https://github.com/poanetwork/blockscout/pull/1777 we show the number of transferred ERC-20 tokens in the right box, if there was 1 transfer in tx. The suggestion is to show the summary of token transfers if the transaction has multiple transfers, like this:

![Screenshot 2019-04-19 at 14 05 48](https://user-images.githubusercontent.com/4341812/56421663-43a08100-62ac-11e9-9dea-85271a7f6210.png)

**Comment by igorbarinov** [comment]
It's important for users of tools like Disperse https://disperse.app/
or Token Multisender https://multisender.app/
where many erc20 token transfers can be compressed in one transaction 

also for swap dapps like uniswap where swaps are atomic in one tx
