### ISSUE TITLE
Internal Server Error on All Contract Verification Pages

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#1796]
Here is an example: https://blockscout.com/eth/mainnet/address/0x755f4a948446076169416465bb8f6ac8b16e3edf/contract_verifications/new

### Steps to reproduce

Tried verifying a contract for this address: 0x755f4a948446076169416465bb8f6ac8b16e3edf and received an internal server error. I will pass along other addresses with the same issues.

**Comment by acravenho** [comment]
This appears to be occurring for every contract address. I've attempted to verify contracts on several other addresses but all pages have an internal server error.

**Comment by acravenho** [comment]
This appears to be fixed now. Starting verification again.

**Comment by Roongrote** [comment]
contract_verifications 
Internal server error
