### ISSUE TITLE
Improve decompiled code highlighting

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#1820]
- it's not matching colour scheme in Verified contracts
- some comments lines highlighted not like comments
- some not comments lines highlighted like comments
- some function names highlighted as comments
![Screenshot 2019-04-23 at 18 57 55](https://user-images.githubusercontent.com/4341812/56596710-b89bef80-65f9-11e9-969a-81e97e637fbf.png)

**Comment by vbaranov** [comment]
PR above covers these issues:

>some comments lines highlighted not like comments
>some not comments lines highlighted like comments

Regarding 
1. >some function names highlighted as comments

we need to distinguish function names from the comments - I suppose we need an additional colour anchor for that.

2. > it's not matching the colour scheme in verified contracts

@ayrat555 can we create a dictionary and wrap reserved words with the styles, that we have for verified smart-contracts? The matching is below:

a) for `def`, `require`, `revert`, 'revert with Error', `return`, `assembly`, `memory` and for all Solidity types (https://solidity.readthedocs.io/en/v0.5.7/types.html) use `.hljs-keyword` style  (see `function` reserved word in verified smart-contract code) (if they are not in comments)

b) for integers/hex, `payable`, `public`, `view`, 'pure', 'returns', `internal` use `.hljs-title` style  (see `public` reserved word in verified smart-contract code)

**Comment by ayrat555** [comment]
> can we create a dictionary and wrap reserved words with the styles
yes
