### ISSUE TITLE
Update chains logos to fit new design

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#1836]
Relates to https://github.com/poanetwork/blockscout/pull/1807

https://github.com/poanetwork/blockscout/blob/master/apps/block_scout_web/assets/static/images/blockscout_logo.svg
https://github.com/poanetwork/blockscout/blob/master/apps/block_scout_web/assets/static/images/callisto_logo.svg
https://github.com/poanetwork/blockscout/blob/master/apps/block_scout_web/assets/static/images/classic_ethereum_logo.svg
https://github.com/poanetwork/blockscout/blob/master/apps/block_scout_web/assets/static/images/dai_logo.svg
https://github.com/poanetwork/blockscout/blob/master/apps/block_scout_web/assets/static/images/ethereum_logo.svg
https://github.com/poanetwork/blockscout/blob/master/apps/block_scout_web/assets/static/images/goerli_logo.png
https://github.com/poanetwork/blockscout/blob/master/apps/block_scout_web/assets/static/images/kovan_logo.svg
https://github.com/poanetwork/blockscout/blob/master/apps/block_scout_web/assets/static/images/poa_logo.svg
https://github.com/poanetwork/blockscout/blob/master/apps/block_scout_web/assets/static/images/rinkeby_logo.svg
https://github.com/poanetwork/blockscout/blob/master/apps/block_scout_web/assets/static/images/ropsten_logo.svg
https://github.com/poanetwork/blockscout/blob/master/apps/block_scout_web/assets/static/images/sokol_logo.svg

**Comment by pashagonchar** [comment]
@vbaranov 

https://zpl.io/VDAd6dv

https://zpl.io/29wE6EA

https://zpl.io/VKDLAvE

https://zpl.io/VOxnj7P

https://zpl.io/brvpgXX

https://zpl.io/V1O561X

![aerum_main](https://user-images.githubusercontent.com/16716926/56944595-a3105380-6b2c-11e9-8e62-87336b64ec15.png)
![callisto_main](https://user-images.githubusercontent.com/16716926/56944597-a3105380-6b2c-11e9-8eb9-f62be63b9aa7.png)
![main_etc](https://user-images.githubusercontent.com/16716926/56944598-a3a8ea00-6b2c-11e9-8443-9a0d9cdaaa34.png)
![main_eth](https://user-images.githubusercontent.com/16716926/56944599-a3a8ea00-6b2c-11e9-941d-407909e3da7b.png)
![main_rsk](https://user-images.githubusercontent.com/16716926/56944600-a3a8ea00-6b2c-11e9-9bca-7c2b0ccb1e68.png)
![main_xdai](https://user-images.githubusercontent.com/16716926/56944601-a3a8ea00-6b2c-11e9-8397-d0b15d28b438.png)

**Comment by pashagonchar** [comment]
@vbaranov 

update:

https://zpl.io/VDAd6dv

https://zpl.io/29wE6EA

https://zpl.io/VKDLAvE

https://zpl.io/VOxnj7P

https://zpl.io/brvpgXX

https://zpl.io/V1O561X

https://zpl.io/VQv73k5

https://zpl.io/bJpxmJD

https://zpl.io/bWN0Okj

https://zpl.io/b64mWLg

https://zpl.io/bJpxkDx

https://zpl.io/bWN0p8x

![aerum_main](https://user-images.githubusercontent.com/16716926/57010344-d1616200-6c04-11e9-806b-c1a2774abe81.png)
![callisto_main](https://user-images.githubusercontent.com/16716926/57010345-d1f9f880-6c04-11e9-9384-e010ec63ac6c.png)
![main_etc](https://user-images.githubusercontent.com/16716926/57010346-d1f9f880-6c04-11e9-969c-878c02d03df3.png)
![main_eth](https://user-images.githubusercontent.com/16716926/57010347-d2928f00-6c04-11e9-91d7-25324e3f5b50.png)
![main_kovan](https://user-images.githubusercontent.com/16716926/57010349-d2928f00-6c04-11e9-9ce5-dfd3ed3c633b.png)
![main_poa](https://user-images.githubusercontent.com/16716926/57010350-d2928f00-6c04-11e9-8940-3f0781dc506e.png)
![main_rinkeby](https://user-images.githubusercontent.com/16716926/57010351-d32b2580-6c04-11e9-8b5c-8c6566bd3506.png)
![main_ropsten](https://user-images.githubusercontent.com/16716926/57010352-d32b2580-6c04-11e9-98c6-73f16e513a45.png)
![main_rsk](https://user-images.githubusercontent.com/16716926/57010353-d32b2580-6c04-11e9-94c0-e51c08348e2e.png)
![main_sokol](https://user-images.githubusercontent.com/16716926/57010354-d3c3bc00-6c04-11e9-9e8a-2ba747c84e92.png)
![main_xdai](https://user-images.githubusercontent.com/16716926/57010355-d3c3bc00-6c04-11e9-99d3-f5ec2991dd20.png)
