### ISSUE TITLE
cannot verify smart contract 0.5.3

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/blockscout#1843]
I can't seem to be able to verify the following smart contract

![image](https://user-images.githubusercontent.com/9360827/56756887-acbe4380-6747-11e9-8f6e-a098abbd9e1b.png)
https://blockscout.com/poa/dai/address/0x5cd5bb3ec13ce31771b63632ddc2eb36e300b96c/contract_verifications

Verified on other sources:
https://etherscan.io/address/0x595a47e57b3ec34031429d2abf9c941e4e3a8d99#code
solc: 0.5.3
optimizer: 200
constructor params:
0000000000000000000000000039f22efb07a647557c7c5d17854cfd6d489ef30000000000000000000000000000000000000000000000000000000000000000

**Comment by vbaranov** [comment]
I was able to verify it with evm version: `byzantium`: https://blockscout.com/poa/dai/address/0x5cd5bb3ec13ce31771b63632ddc2eb36e300b96c/contracts

Enjoy.

**Comment by igorbarinov** [comment]
@vbaranov I remember we discussed to have a fallback to previous EVM version if the latest one is not successful. Do we have a PR or an issue for it?

**Comment by vbaranov** [comment]
Yes, we discussed it. And we had an issue for that. It wasn't solved correctly. I reopened it: https://github.com/poanetwork/blockscout/issues/1653

**Comment by rstormsf** [comment]
thank you @vbaranov
