### ISSUE TITLE
Cannot verify smart contract 0.4.24 in Kovan testnet

### ISSUE THREAD

**Issue by varasev** [poanetwork/blockscout#1847]
Can't verify this one: https://blockscout.com/eth/kovan/address/0xae71807c1b0a093cb1547b682dc78316d945c9b8/contracts

It is verified successfully in etherscan: https://kovan.etherscan.io/address/0xae71807c1b0a093cb1547b682dc78316d945c9b8#code

**Comment by varasev** [comment]
Also, when I try to verify another contract https://blockscout.com/eth/kovan/address/0xe8f4819a0c7f7b918c4f1ab801b0745604bdfd38/contract_verifications I see the `Error 504 Gateway time-out`:

![image](https://user-images.githubusercontent.com/33550681/56809697-30a62780-683d-11e9-95d9-c0204b092a88.png)

**Comment by varasev** [comment]
Both these contracts are verified in `kovan.etherscan.io`.

**Comment by acravenho** [comment]
Most likely related to #1790

**Comment by zachdaniel** [comment]
This should be resolved when #1875 is deployed.

**Comment by vbaranov** [comment]
@varasev Update installed to the Kovan instance.
Both contracts have been verified: https://blockscout.com/eth/kovan/address/0xae71807c1b0a093cb1547b682dc78316d945c9b8/contracts
https://blockscout.com/eth/kovan/address/0xe8f4819a0c7f7b918c4f1ab801b0745604bdfd38/contracts
