### ISSUE TITLE
Deployment v1.3.11: Ropsten, ETH Mainnet

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#1860]
## Info
Networks: **Ropsten**, **ETH Mainnet**
Date: **2019-04-30**
Version: **[https://github.com/poanetwork/blockscout/releases/tag/v1.3.11-beta](v1.3.11)**

## Motivation
- Fix for uncle blocks with null size 

## Description
This issue is for approval of deploying [v1.3.11](https://github.com/poanetwork/blockscout/releases/tag/v1.3.11-beta) to **Ropsten**, **ETH Mainnet**.
## Specific Directions
* Disable replaced transaction fetcher until the permanent solution is completed
    * Uncomment the following line to disable the dropped/replaced fetcher
https://github.com/poanetwork/blockscout/blob/9c7aff1ea745275901a5e4aee1abc131006a6d54/apps/indexer/config/config.exs#L38
* Update `BLOCKSCOUT_VERSION` and `RELEASE_LINK` env vars

## Approval
* [ ]  Igor Barinov (@igorbarinov)
* [ ]  Ayrat Badykov (@ayrat555)
* [x]  Victor Baranov

**Comment by matawinb** [comment]
# config :indexer, Indexer.ReplacedTransaction.Supervisor, disabled?: true
