### ISSUE TITLE
Invalid marketcap for RSK

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#1864]
![Screenshot 2019-04-30 at 13 29 23](https://user-images.githubusercontent.com/4341812/56956201-1d040500-6b4c-11e9-94b2-98e1f3eb329c.png)

**Comment by saneery** [comment]
That's right, the market cap is ~ $0
![image](https://user-images.githubusercontent.com/11743366/57014970-14c6cb00-6c1b-11e9-85c2-f5492d406af9.png)

**Comment by vbaranov** [comment]
Then looks like this is not a bug.

**Comment by igorbarinov** [comment]
What is the formula for markecap calculation?
all RBTC balances excluding https://blockscout.com/rsk/mainnet/address/0x0000000000000000000000000000000001000006/transactions ?

**Comment by zachdaniel** [comment]
@saneery I'll make start working on this once the above is confirmed, or if a different calculation is provided.

**Comment by vbaranov** [comment]
Yes @zachdaniel the calculation is correct. Plus obviously, we shouldn't consider `0x0` address in calculations too.

**Comment by vbaranov** [comment]
I suggest to calculate it:

RSK marketcap = BTC marketcap - 0x0000000000000000000000000000000001000006.balance - 0x0000000000000000000000000000000000000000.balance

where BTC marketcap = 21 mln BTC

**Comment by alepc253** [comment]
`21000000 - balanceOf(0x0000000000000000000000000000000001000006)` is the amount of BTC locked in RSK bridge, so that would be the RBTC circulation and, therefore, the "market cap".
