### ISSUE TITLE
There was an error compiling your contract.

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#1873]
`0x68d0657245d7bb542ce8910a49e34d1ad12e792b` fails to verify. There is nothing special about this contract to warrant it not to verify.

* 0x57d1585168bccafd2475a53cc8b519b78cdf5fa0
* 0x68d0657245d7bb542ce8910a49e34d1ad12e792b
* 0x3b005f89571d44b9335b0b397997165e605fa6e6
* 0x22ecd603fdb52d59090ffb9e6fb3b67ad0a29d4f

### Steps to reproduce

1. Attempt to verify `0x68d0657245d7bb542ce8910a49e34d1ad12e792b`
2. Receive the message `There was an error compiling your contract.`

### Expected behaviour

Verify Contract

### Actual behaviour

Error

**Comment by acravenho** [comment]
@vbaranov I think the issue here is that we're using the string `0029` to identify constructor arguments which are creating false positives if `0029` occurs multiple times within the bytecode. 

We should be splitting the final instance of the `0029` string.

Here is the function I use to identify constructor arguments:

```
function parseConstructorFromBytecode (data) {
  let split = data.split('0029')
  if (split.length > 1) {
    return split[split.length - 1]
  } else {
    return false
  }
}
```

**Comment by acravenho** [comment]
It appears this is what is happening. All these contracts have multiple occurrences of `0029` in the bytecode.

**Comment by zachdaniel** [comment]
@acravenho so we just want to split on the *last* occurrence of "0029", correct? I'll get that going.
