### ISSUE TITLE
Slow performance of the main page: use ETS

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#1880]
The page loading is rather slow: ~ 1sec

<img width="1280" alt="Screenshot 2019-05-02 at 14 02 02" src="https://user-images.githubusercontent.com/4341812/57071361-e6142780-6ce2-11e9-84d4-b31afda04dfc.png">

The steps to improve this could be using of ETS for all main page blocks

- [x] chart data https://github.com/poanetwork/blockscout/pull/2182
- [x] average block time https://github.com/poanetwork/blockscout/pull/1714
- [x] total transactions https://github.com/poanetwork/blockscout/pull/1634
- [x] total blocks https://github.com/poanetwork/blockscout/pull/1848, https://github.com/poanetwork/blockscout/pull/1876
- [x] wallet addresses https://github.com/poanetwork/blockscout/pull/1170
- [x] blocks https://github.com/poanetwork/blockscout/pull/2075
- [x] transactions https://github.com/poanetwork/blockscout/issues/2250

**Comment by ayrat555** [comment]
all data already cached except for broken block count cache  and transactions/market history which fetched from db.

**Comment by rstormsf** [comment]
![blockscout](https://user-images.githubusercontent.com/9360827/60638824-c2e62100-9dd4-11e9-916e-c8cbfaaa41ca.gif)
@vbaranov @ayrat555

**Comment by rstormsf** [comment]
```bash
curl 'https://blockscout.com/poa/core/address/0xbc70e7a838ef3d468e25efa5ecb8946d3d0f913b/transactions?type=JSON' -H 'Referer: https://blockscout.com/poa/core/address/0xbc70e7a838ef3d468e25efa5ecb8946d3d0f913b/transactions' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3842.0 Safari/537.36' --compressed
```
16.850s total

unacceptable performance if blockscout wants to beat etherscan

![blockscout2](https://user-images.githubusercontent.com/9360827/60638987-75b67f00-9dd5-11e9-9a2e-f79c44f1ef73.gif)

**Comment by rstormsf** [comment]
sometimes it doesn't even load it

![image](https://user-images.githubusercontent.com/9360827/60639092-ee1d4000-9dd5-11e9-9a0c-af78fbc54baf.png)

https://blockscout.com/poa/core/address/0xbc70e7a838ef3d468e25efa5ecb8946d3d0f913b/transactions

**Comment by vbaranov** [comment]
@rstormsf wrong issue. I've created a new one with referring to your comments https://github.com/poanetwork/blockscout/issues/2306. All optimizations for the main page were implemented in frames of the current one.
