### ISSUE TITLE
New pagination view

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#1893]
We have now a new look of pagination in the embedded staking dapp. We need the same pagination for other pages:

- [ ] blocks page
- [ ] transactions page
- [ ] addresses page

Here is how pagination  looks like now https://github.com/poanetwork/blockscout/pull/1812#issuecomment-486185638

Here is how pagination should look:

![Screenshot 2019-05-06 at 13 07 00](https://user-images.githubusercontent.com/4341812/57219231-179d3380-7000-11e9-9c24-75628f0c49a8.png)

The layout with a new pagination style: https://app.zeplin.io/project/5a6053176eb2bda2cf9379be/screen/5cc18a81e528ae3da56ddcdc

**Comment by saneery** [comment]
@gabitoesmiapodo @vbaranov I think we need also add new paginations into `production-posdao` branch

**Comment by vbaranov** [comment]
@saneery feel free to get upstream from master to POSDAO branch
