### ISSUE TITLE
Slow performance of contracts list endpoint with an included filter

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#1894]
The list of contracts endpoint with an included *verified* filter falls to error when trying to return more than 7 entries in ETH Mainnet instance.

For example, https://blockscout.com/eth/mainnet/api?module=contract&action=listcontracts&offset=7&filter=1 works fine

whereas https://blockscout.com/eth/mainnet/api?module=contract&action=listcontracts&offset=8&filter=1 (and more offset value) returns 504 error

Meanwhile, It returns data with the even higher offsets (tens, hundreds) without the filter included.

**Comment by zachdaniel** [comment]
This must just be a problem with the query design. I will address it.
