### ISSUE TITLE
Please add smart contract event logs on the contract details page

### ISSUE THREAD

**Issue by busypeter** [poanetwork/blockscout#1927]
When looking at a smart contract details page (e.g. https://blockscout.com/poa/core/address/0xab2f2dd3120de530d38936ee09a74a6d17e3da44/transactions), please add a tab for Events. The tab should contain event logs (e.g. listing the last x number of events emitted by this contract) and a search function. Users should be able to search for event logs by topic across the full blockchain (emitted by this contract only).

### Environment

https://blockscout.com

### Steps to reproduce

Navigate to https://blockscout.com/poa/core/address/0xab2f2dd3120de530d38936ee09a74a6d17e3da44/transactions.

### Expected behaviour

There should be an Events tab or another way to view contract event logs.

### Actual behaviour

No Events tab. No way to search for events of a contract.

**Comment by ayrat555** [comment]
logs tab is merged. I'll work on a search button now

**Comment by vbaranov** [comment]
The issue will be closed with the new update of POA Core instance
