### ISSUE TITLE
Txs with errors design

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#1934]
For the upcoming design of Blosckscout we have not provided styles for txs with the errors.

![Screenshot 2019-05-13 at 13 13 44](https://user-images.githubusercontent.com/4341812/57614934-24cb9c80-7583-11e9-87f3-99664fcd08b1.png)

**Comment by gabitoesmiapodo** [comment]
Hi @vbaranov were could I see this error working?

**Comment by vbaranov** [comment]
Hi @gabitoesmiapodo. In the current design, it looks like this 
![Screenshot 2019-05-13 at 14 04 53](https://user-images.githubusercontent.com/4341812/57616947-2fd4fb80-7588-11e9-8a8f-ec0bfb203210.png)

https://blockscout.com/eth/mainnet/blocks/7751639/transactions

I suppose, how it should look in the new design, @pashagonchar will share the mockup here.

**Comment by pashagonchar** [comment]
@vbaranov 

<img width="1280" alt="error" src="https://user-images.githubusercontent.com/16716926/57768142-a9e5bb80-7713-11e9-9574-db8b62e7d67b.png">

**Comment by vbaranov** [comment]
@gabitoesmiapodo ☝️ here a new design for error is

**Comment by zachdaniel** [comment]
There are other issues w/ the txlist page (not returning the correct data), so we'll leave this open, and resolve this when I fix it.

**Comment by vbaranov** [comment]
@zachdaniel I guess you are about that issue https://github.com/poanetwork/blockscout/issues/1938. I keep it open. I will close the current one.

**Comment by zachdaniel** [comment]
Sorry about the confusion there!
