### ISSUE TITLE
Exclude smart-contracts with empty bytecode from the listcontracts API endpoint

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#1942]
**Problem**: 
There are self-destructed smart-contracts. For example, these
https://blockscout.com/eth/mainnet/address/0xe555122e2a2b68a5d26785e0cbb66e891b7fcf8a/contracts
https://blockscout.com/eth/mainnet/address/0x1a970127f9e7e131ba4fdb99e93b5e5bb2dd7d78/contracts

Their bytecode is empty. And, for example, for ETH Mainnet `listcontracts` endpoint returns all of them on the first page with `not_decompiled ` filter and `10_000` offset. Meanwhile, the current version of the decompiler has no decompiled code for those self-destructed contracts. Thus, uploading script skips those contracts to upload, and they infinitely returning in the endpoint causing slowness of uploading process of non-empty smart-contracts.

**Solution**:

- [ ] to exclude contracts with empty code from `not_decompiled` and `unverified` filters
- [ ] and create a separate filter: `empty`, with which the endpoint will return those contracts

**Comment by kolinko** [comment]
Just to clarify.

It's not that they are selfdestroyed (those we handle now - we will upload the sources for selfdestructed contracts as well), it's that some of them never acctually had an actual runtime bytecode in the first place :)

It seems there is a series of contracts that have constructor that does something like this:
https://eveem.org/code/0xa9f61750caf50e6
So - it does some stuff, then selfdestructs within the transaction, never actually creating the contract.
