### ISSUE TITLE
Raw trace breaks on the staging server

### ISSUE THREAD

**Issue by kolinko** [poanetwork/blockscout#1950]
On the current staging server, going to this url:

/tx/0xef27c8ef9a9fce726afab44ab228d31688b15299ed554326a9977be8d184e799/raw_trace

Results in Internal Server Error

**Comment by vbaranov** [comment]
The related application error to the opening of that `raw_trace` page:
```
$ tail -f /opt/app/logs/prod/error.log| grep UndefinedError
    ** (Protocol.UndefinedError) protocol Jason.Encoder not implemented for %Explorer.Chain.Data{bytes: ""}, Jason.Encoder protocol must always be explicitly implemented.
```
