### ISSUE TITLE
Rerun or Check blocks to update addresses tables

### ISSUE THREAD

**Issue by eduardonunesp** [poanetwork/blockscout#1961]
Is there a way to rerun the `Indexer.Fetcher.ContractCode` to going through the blocks and fetch again the `addresses` with `contract_code` that failed previously?

**Comment by ayrat555** [comment]
@eduardonunesp I think the only way is to reindex block

**Comment by eduardonunesp** [comment]
@ayrat555 and reindex the block requires to drop the database, right ?

**Comment by vbaranov** [comment]
If there are several blocks, you might repeat index them with:

**Note:** please make sure you have a dump of the database before doing these steps

1. `DELETE FROM internal_transactions WHERE block_number in (..., ..., ...);`
2. `UPDATE blocks SET consensus = false WHERE consensus AND number in (..., ..., ...);`

where `..., ..., ...` are the comma-separated block numbers

**Comment by eduardonunesp** [comment]
Thanks, @vbaranov I'll try soon and post the results and the thoughts here 🙏

**Comment by eduardonunesp** [comment]
@vbaranov after delete the `internal_transactions` and `updated` `blocks.consensus`, I noticed that the `addresses.contract_code` wasn't fetched, probably there's another field blocking to refetch and update maybe on `transactions` table

**Comment by eduardonunesp** [comment]
Looks like the trick is to clear out `transactions.created_contract_address_hash` too

**Comment by ayrat555** [comment]
@eduardonunesp you're right

**Comment by eduardonunesp** [comment]
Yay! it works, thanks for the help, so to the `SQL` commands are:

> Disclaimer: those commands were run on a controlled environment, it was a test and worked, so before running commands like that are sure to have a backup

```sql
DELETE FROM internal_transactions;
UPDATE blocks SET consensus = FALSE;
UPDATE addresses SET contract_code = NULL;
```
