### ISSUE TITLE
Connect to chain via REST API

### ISSUE THREAD

**Issue by lightninggalaxy** [poanetwork/blockscout#1971]
I am wondering if it is possible to connect to a chain via REST API. If so, how can I go about doing it? Thank you.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
Erlang/OTP 21 [erts-10.0.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
Elixir 1.7.1 (compiled with Erlang/OTP 19)

* Operating System:
Ubuntu 18.04

**Comment by vbaranov** [comment]
@lightninggalaxy we have an advanced API to get the data from Blockscout DB for all chains, for example for ETH Mainnet https://blockscout.com/eth/mainnet/api_docs. What do you mean "to connect to a chain". Please describe your use case.

**Comment by lightninggalaxy** [comment]
@vbaranov , sorry, I should have been more specific. I meant that I was wondering if it was possible to connect via REST API instead of the standard connection via JSON RPC Endpoint.

**Comment by igorbarinov** [comment]
> @vbaranov , sorry, I should have been more specific. I meant that I was wondering if it was possible to connect via REST API instead of the standard connection via JSON RPC Endpoint.

Interesting. which clients support REST API?

**Comment by lightninggalaxy** [comment]
I was asking for a private mainnet that connects via REST API, but now things have changed so I will be closing this issue. Thank you.
