### ISSUE TITLE
Missing new pagination on some pages

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#1972]
Relates to https://github.com/poanetwork/blockscout/pull/1928

+ New pagination view is missing on some pages
+ we should hide a pagination view if there are no items in the list.

The full list of old pagination occurrences in the code is here:
```
/blockscout/apps/block_scout_web/lib/block_scout_web/templates/address_coin_balance/index.html.eex:
   57:           <%= gettext("Older") %>

/blockscout/apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/index.html.eex:
   81:           <%= gettext("Older") %>

/blockscout/apps/block_scout_web/lib/block_scout_web/templates/address_token_transfer/index.html.eex:
   38:           <%= gettext("Older") %>

/blockscout/apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex:
   80:           <%= gettext("Older") %>

/blockscout/apps/block_scout_web/lib/block_scout_web/templates/address_validation/index.html.eex:
   38:           <%= gettext("Older") %>

/blockscout/apps/block_scout_web/lib/block_scout_web/templates/block/index.html.eex:
   30:         <%= gettext("Older") %>

/blockscout/apps/block_scout_web/lib/block_scout_web/templates/block_transaction/index.html.eex:
   50:             gettext("Older"),

/blockscout/apps/block_scout_web/lib/block_scout_web/templates/pending_transaction/index.html.eex:
   39:         <%= gettext("Older") %>

/blockscout/apps/block_scout_web/lib/block_scout_web/templates/tokens/transfer/index.html.eex:
   43:           <%= gettext("Older") %>

/blockscout/apps/block_scout_web/lib/block_scout_web/templates/transaction/index.html.eex:
   45:         <%= gettext("Older") %>

/blockscout/apps/block_scout_web/lib/block_scout_web/templates/transaction_token_transfer/index.html.eex:
   38:           gettext("Older"),
```

**Comment by gabitoesmiapodo** [comment]
@vbaranov 

The new pagination should be there since the latest modifications (for example lines 6 and 41 on `apps/block_scout_web/lib/block_scout_web/templates/transaction/index.html.eex`)

The code you are referring to is commented out, I think it won't render? I just left it there in case the next developer needs it for something.

Also, I'd propose that `we should hide a pagination view if there are no items in the list.` be addressed on https://github.com/poanetwork/blockscout/issues/1930 as it belongs more into logic than presentation.

**Comment by vbaranov** [comment]
@gabitoesmiapodo 
Indeed, they are all comments. But I started to find old pagination in the code when I accidentally saw the old pagination in our staging server. But I need to check it once more. If I will not find old pagination visually, I will close the issue. And I suppose @ayrat555 will take care of pagination hiding.
