### ISSUE TITLE
Missing tx hashes for multiple token transfers in a new design

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#1981]
How it looks in the current design:
![Screenshot 2019-05-20 at 13 45 26](https://user-images.githubusercontent.com/4341812/58017615-53102580-7b09-11e9-9184-40c368101a32.png)

The missing tx hash in the new design:
![Screenshot 2019-05-20 at 13 31 47](https://user-images.githubusercontent.com/4341812/58017643-63c09b80-7b09-11e9-9ad1-e74ad641371d.png)

Actually, a tx hash is in html, but it is invisible.

**Comment by gabitoesmiapodo** [comment]
How can I test this, or reproduce it locally?

**Comment by vbaranov** [comment]
@gabitoesmiapodo please check Slack
