### ISSUE TITLE
Geth Clique mined by 0x000

### ISSUE THREAD

**Issue by lightninggalaxy** [poanetwork/blockscout#1990]
### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
Erlang/OTP 21 [erts-10.0.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
Elixir 1.8.1 (compiled with Erlang/OTP 20)

* Operating System:
Ubuntu 18.04

* Blockscout Version:
BlockScout v1.3.14-beta

### Steps to reproduce
Started up private chain (Geth Clique), then followed instructions here: https://forum.poa.network/t/manual-blockscout-deployment/2458

### Expected behaviour
Miner should show the signer address, address should not be 0x000

### Actual behaviour
Miner address shown as 0x000 for all blocks

Same issue as mentioned in the following:
#1548 , #1659 
Yet, I cannot find a way to have this sorted. I have checked https://forum.poa.network/t/deployment-differences-between-each-blockscout-chain/1950
but I think the line where one needs to change the settings is missing? (First file is poanetwork/blockscout/blob/12aa15671142af00b35ff05aeac107c2c686c4c8/apps/block_scout_web/priv/gettext/default.pot without #L?)

Please let me know what I must change in order to see the addresses of the signer. Thank you.

**Comment by lightninggalaxy** [comment]
@acravenho Thanks for your response. I hadn't seen those settings, but now that I have changed it, I can no longer see any blocks or transactions. If it makes any difference, I did do a mix do ecto.drop, ecto.create, ecto.migrate before running the server again. I am getting this error: 

`[warn] The on_load function for module libsecp256k1 returned:
{:error, {:load_failed, 'Failed to load NIF library: \'/block_viewer/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so: cannot open shared object file: No such file or directory\''}}

[error] Task #PID<0.1259.0> started from Indexer.Block.Realtime.Fetcher terminating
** (UndefinedFunctionError) function :libsecp256k1.ecdsa_recover_compact/4 is undefined (module :libsecp256k1 is not available)
    (libsecp256k1) :libsecp256k1.ecdsa_recover_compact(<<103, 136, 38, 81, 151, 33, 145, 134, 222, 107, 101, 91, 103, 87, 200, 150, 155, 16, 225, 152, 218, 223, 139, 154, 47, 242, 59, 185, 73, 209, 166, 66>>, <<213, 52, 116, 30, 162, 3, 68, 199, 146, 158, 168, 25, 48, 178, 63, 107, 136, 108, 222, 21, 208, 159, 60, 179, 248, 148, 110, 248, 97, 179, 125, 43, 47, 49, 41, 90, 241, 37, 95, 107, 20, 12, 244, 192, 22, 187, 19, 181, 88, 40, ...>>, :uncompressed, 0)
    (indexer) lib/indexer/block/util.ex:67: Indexer.Block.Util.recover_pub_key/2
    (indexer) lib/indexer/block/transform/clique.ex:14: Indexer.Block.Transform.Clique.transform/1
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    (indexer) lib/indexer/block/fetcher.ex:105: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer) lib/indexer/block/realtime/fetcher.ex:264: Indexer.Block.Realtime.Fetcher.do_fetch_and_import_block/3
    (indexer) lib/indexer/logger.ex:14: Indexer.Logger.metadata/2
    (indexer) lib/indexer/block/realtime/fetcher.ex:247: Indexer.Block.Realtime.Fetcher.fetch_and_import_block/4
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3
    Args: [16434, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://localhost:8545", http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, false]
`

Did I do something wrong during setup?

**Comment by lightninggalaxy** [comment]
I found this and I am trying it now. 
https://github.com/poanetwork/blockscout/issues/1352#issuecomment-454958263

**Comment by northeusunshine** [comment]
@acravenho, I have similar problem. and have set the BLOCK_TRANSFORMER in /etc/profile and source the file. but in the browser, the miner address data still is all zero number.
is there some other configuration parameter should be changed?

**Comment by acravenho** [comment]
As a side note, the miner address is calculated during block indexing. This is not done on the UI side. Any previous blocks that were indexed prior to making this change will retain the `0x000` miner address. If new imported blocks are still having this issue then this issue should probably be escalated.

**Comment by northeusunshine** [comment]
thanks for comment, could you please point out which code file is to do the miner address resolving.I'm interested to go through it and understand the block indexing process. thanks again.

**Comment by lightninggalaxy** [comment]
> @acravenho Thanks for your response. I hadn't seen those settings, but now that I have changed it, I can no longer see any blocks or transactions. If it makes any difference, I did do a mix do ecto.drop, ecto.create, ecto.migrate before running the server again. I am getting this error:
> 
> ```
> [warn] The on_load function for module libsecp256k1 returned:
> {:error, {:load_failed, 'Failed to load NIF library: \'/block_viewer/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so: cannot open shared object file: No such file or directory\''}}
> 
> [error] Task #PID<0.1259.0> started from Indexer.Block.Realtime.Fetcher terminating
> ** (UndefinedFunctionError) function :libsecp256k1.ecdsa_recover_compact/4 is undefined (module :libsecp256k1 is not available)
>     (libsecp256k1) :libsecp256k1.ecdsa_recover_compact(<<103, 136, 38, 81, 151, 33, 145, 134, 222, 107, 101, 91, 103, 87, 200, 150, 155, 16, 225, 152, 218, 223, 139, 154, 47, 242, 59, 185, 73, 209, 166, 66>>, <<213, 52, 116, 30, 162, 3, 68, 199, 146, 158, 168, 25, 48, 178, 63, 107, 136, 108, 222, 21, 208, 159, 60, 179, 248, 148, 110, 248, 97, 179, 125, 43, 47, 49, 41, 90, 241, 37, 95, 107, 20, 12, 244, 192, 22, 187, 19, 181, 88, 40, ...>>, :uncompressed, 0)
>     (indexer) lib/indexer/block/util.ex:67: Indexer.Block.Util.recover_pub_key/2
>     (indexer) lib/indexer/block/transform/clique.ex:14: Indexer.Block.Transform.Clique.transform/1
>     (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
>     (indexer) lib/indexer/block/fetcher.ex:105: Indexer.Block.Fetcher.fetch_and_import_range/2
>     (indexer) lib/indexer/block/realtime/fetcher.ex:264: Indexer.Block.Realtime.Fetcher.do_fetch_and_import_block/3
>     (indexer) lib/indexer/logger.ex:14: Indexer.Logger.metadata/2
>     (indexer) lib/indexer/block/realtime/fetcher.ex:247: Indexer.Block.Realtime.Fetcher.fetch_and_import_block/4
>     (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
>     (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
> Function: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3
>     Args: [16434, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://localhost:8545", http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, false]
> ```
> 
> Did I do something wrong during setup?

I am still having this issue. What else can I try?

**Comment by vbaranov** [comment]
@lightninggalaxy try new setup from scratch following these steps:

1. make sure, that your geth node is running with `--gcmode=archive` flag
2. clear your build environment with `./rel/commands/clear_build.sh -f`
3. set correct ENV vars https://forum.poa.network/t/faq-blockscout-environment-variables/1814 including `BLOCK_TRANSFORMER`. The minimum set in your case will be:
```
export ETHEREUM_JSONRPC_HTTP_URL=http://XXX
export ETHEREUM_JSONRPC_TRACE_URL=http://XXX
export ETHEREUM_JSONRPC_WS_URL=ws://XXX
export ETHEREUM_JSONRPC_VARIANT=geth
export BLOCK_TRANSFORMER=clique
```

replace `XXX` with the endpoint of your archive node
4. clear database with `mix do ecto.drop, ecto.create, ecto.migrate`
5. and follow instructions to run the application https://forum.poa.network/t/manual-blockscout-deployment/2458

Also, check the releases: we have an update for indexing of geth chains in [1.3.15](https://github.com/poanetwork/blockscout/releases/tag/v1.3.15-beta)

**Comment by lightninggalaxy** [comment]
Thank you @vbaranov , after following your instructions, the miner is no longer 0x000! I'll close this issue.
I will be sure to check out 1.3.15.
Please keep up the good work.

**Comment by luckyyang** [comment]
`export BLOCK_TRANSFORMER=clique` fixed my issue, thanks @vbaranov !
