### ISSUE TITLE
Checkmark is invisible on selected tab in the new design

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#1993]
<img width="239" alt="Screenshot 2019-05-22 at 01 24 59" src="https://user-images.githubusercontent.com/4341812/58134796-91543480-7c30-11e9-9438-6dfc5b5a82cb.png">

**Comment by gabitoesmiapodo** [comment]
After changes introduced on https://github.com/poanetwork/blockscout/pull/2072 it's now possible to change the checkmark's color according to each theme's needs.
