### ISSUE TITLE
Search tokens on address doesn't work

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#1994]
<img width="495" alt="Screenshot 2019-05-22 at 01 27 07" src="https://user-images.githubusercontent.com/4341812/58134877-daa48400-7c30-11e9-9244-0a5b455faef4.png">

Example: `./address/0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2`

**Comment by ayrat555** [comment]
@vbaranov what environment is this? It works for me both on staging and production

**Comment by vbaranov** [comment]
@ayrat555 yes, it works with the updated stg. I will close this.

**Comment by ayrat555** [comment]
it's weird javascript issue. it's happening on socket disconnect. It can be manually reproduced by triggering `CHANNEL_DISCONNECTED` event in `address/transactions.js`
with
```
store.dispatch({ type: 'CHANNEL_DISCONNECTED' })
```
