### ISSUE TITLE
Show data from postgres without RPC/WS connection

### ISSUE THREAD

**Issue by lightninggalaxy** [poanetwork/blockscout#1996]
Is it possible to use blockscout without a RPC/WS connection? All the data would come from a postgres database.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
Erlang/OTP 21 [erts-10.0.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
Elixir 1.8.1 (compiled with Erlang/OTP 20)

* Operating System:
Ubuntu 18.04

* Blockscout Version:
BlockScout v1.3.14-beta

**Comment by vbaranov** [comment]
You can start Blockscout without websockets https://github.com/poanetwork/blockscout/pull/1778. Though, RPC is still required. If there will be no RPC and WS, how do you plan to fill up the database?

**Comment by lightninggalaxy** [comment]
Thank you for your response. It wasn't my query originally so I am not entirely sure, but my understanding was that the database would be filled up through other means outside of Blockscout.
