### ISSUE TITLE
System enquiries.

### ISSUE THREAD

**Issue by ysbae0928** [poanetwork/blockscout#2013]
I'm starting "parity" and "BlockScout" and "postgresql" with AWS r5.2xlarge.
But is there a way to speed up BlockScout's block sync process when it's slow?
Also, what is the server size of BlockScout Ethereum Core in operation?
Is it too much to run parity, blockScout, postgresql in one place like me?

Here is my instance specification.
cpu:8 core
memory:64 gb
ssd: 4TB, 300GB

**Comment by igorbarinov** [comment]
@ysbae0928 running Mainnet is quite expensive and takes time. Why not to use hosted one on blockscout.com?

regarding specs:

**parity archive node**:
we are using `r5.xlarge` and `r5a.2xlarge` with 3.3 Tb attached drives each

**blockscout RDS (Hosted Postgres)**
`db.m5.2xlarge` and `db.m5.xlarge` for staging

we can discuss making a snapshot and sharing it with you so you can cut your costs.

**Comment by ysbae0928** [comment]
I am currently building a development environment with BlockScout.
If I had "r5a.2xlarge" and "db.m5.xlarge" to run the system, would it be possible to operate without problems?
And how do we get snapshots?
If I can get a snapshot by mail, please send it to ysbae0928@gmail.com

**Comment by hadv** [comment]
@hadv
