### ISSUE TITLE
Running indexer and block_scout_web on different pods

### ISSUE THREAD

**Issue by eduardonunesp** [poanetwork/blockscout#2026]
We're running the Dockerized image of the `blockscout`, however, we would like to run the indexer on a docker host and the web interface on another docker host, I wonder if is possible to run the web interface without call the indexer and run the indexer alone on a different host.

I did a few experiments on the terminal, so in order to run the `indexer` only:
```bash
# If run without the iex -S mix the indexer process will not hold the process
mix cmd --app indexer iex -S mix
```

However when running a similar command for the web interface on another terminal like
```bash
mix cmd --app block_scout_web mix phx.server
```
Looks like the `indexer` is running twice, I would like to know how to run those process separately and running only one if necessary on different machines, thanks :)

**Comment by vbaranov** [comment]
@eduardonunesp 

>Looks like the indexer is running twice

Why do you think so?

This way, that you've run indexer and web application, is absolutely correct for separate launch. When you stop indexer, the web application should work and no news blocks should appear in the db. This is what I see in my test with this setup.

**Comment by eduardonunesp** [comment]
Actually, the `indexer` isn't running twice using the configuration above, I noticed that when run `mix cmd --app block_scout_web mix phx.server` on `macOS` even with `Ctrl+C` to cancel the process it still needs some `killall beam.smp` to completely remove the process. 

So the configuration above works to run both separately, just a small thing that I noticed is when running both separately (index and web interface) the web interface blocks didn't update automatically, looks like the WebSocket is inactivated

**Comment by eduardonunesp** [comment]
Hey @vbaranov thanks for your answer, are you able to reproduce the issue above?

**Comment by vbaranov** [comment]
@eduardonunesp yes, I can confirm that websocket doesn't work in a separate launch. I've created an issue. We will try to fix a websocket in this case.

**Comment by eduardonunesp** [comment]
@vbaranov that's great thanks for the feedback

**Comment by vbaranov** [comment]
The issue with websocket was fixed https://github.com/poanetwork/blockscout/pull/2449. Now it is possible to divide indexer and web application. It is managed by env vars:

To run web application without indexer:
```
export DISABLE_INDEXER=true
```

To run indexer only (without web app):
```
export DISABLE_WEBAPP=true
```

Reference https://app.gitbook.com/@poa/s/blockscout/for-developers/information-and-settings/env-variables
