### ISSUE TITLE
ON CONFLICT DO UPDATE... Error....

### ISSUE THREAD

**Issue by ysbae0928** [poanetwork/blockscout#2048]
I'm organizing my environment with BlockScout Master Branch.
However, the following error occurs suddenly during normal synchronization.
How do I deal with this?
I think you've read that the issue has been resolved before, but the same issue has occurred.

### Error
2019-05-29T00:30:28.747 fetcher=block_uncle count=10 [error] Task #PID<0.13140.10> started from Indexer.Fetcher.UncleBlock terminating
** (Postgrex.Error) ERROR 21000 (cardinality_violation) ON CONFLICT DO UPDATE command cannot affect row a second time

    hint: Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
    (ecto_sql) lib/ecto/adapters/sql.ex:620: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql) lib/ecto/adapters/sql.ex:529: Ecto.Adapters.SQL.insert_all/8
    (ecto) lib/ecto/repo/schema.ex:56: Ecto.Repo.Schema.do_insert_all/6
    (explorer) lib/explorer/repo.ex:45: anonymous fn/5 in Explorer.Repo.safe_insert_all/3
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (explorer) lib/explorer/chain/import.ex:285: Explorer.Chain.Import.insert_changes_list/3
    (ecto) lib/ecto/multi.ex:580: Ecto.Multi.apply_operation/5
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/multi.ex:564: anonymous fn/5 in Ecto.Multi.apply_operations/5
    (ecto_sql) lib/ecto/adapters/sql.ex:814: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection) lib/db_connection.ex:1349: DBConnection.run_transaction/4
    (ecto) lib/ecto/repo/transaction.ex:16: Ecto.Repo.Transaction.transaction/3
    (stdlib) timer.erl:197: :timer.tc/3
    (explorer) lib/explorer/repo.ex:21: anonymous fn/2 in Explorer.Repo.logged_transaction/2
    (explorer) lib/explorer/logger.ex:14: Explorer.Logger.metadata/2
    (explorer) lib/explorer/chain/import.ex:316: anonymous fn/3 in Explorer.Chain.Import.import_transactions/2
    (elixir) lib/enum.ex:3317: Enumerable.List.reduce/3
    (elixir) lib/enum.ex:1990: Enum.reduce_while/3
    (explorer) lib/explorer/chain/import.ex:315: Explorer.Chain.Import.import_transactions/2
    (explorer) lib/explorer/logger.ex:14: Explorer.Logger.metadata/2
Function: &Indexer.BufferedTask.log_run/1

### Environment
* Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.8.1 (compiled with Erlang/OTP 20)
* Operating System: r5.2xlarge

**Comment by vbaranov** [comment]
@ysbae0928 in order to reproduce this I have questions.
- Which chain are you connected to?
- Does it have public RPC/WebSocket endpoints?

>I think you've read that the issue has been resolved before, but the same issue has occurred.

How it was resolved before?

How many blocks your BlockScout instance already indexed?

**Comment by ysbae0928** [comment]
- The chain is connected to the Eth Core that I own.

- I thought it was resolved after seeing it. https://github.com/poanetwork/blockscout/issues/309

- It is currently indexed to 1,888,307.

apps/explorer/config/dev.secret.exs
pool_timeout: 60_000,
queue_target: 600,
queue_interval: 20000
No error is generated by adding the above content. Is the solution correct?

**Comment by vbaranov** [comment]
Is indexing stuck on `1888307` on block?
Are you sure that you are using the latest version of Blockscout?
We have no such issue for our ETH Mainnet instance: https://blockscout.com/eth/mainnet.

**Comment by ysbae0928** [comment]
Is indexing stuck on 1888307 block?
==>The settings were changed and the synchronization was normal.

Are you sure that you are using the latest version of Blockscout?
==> I'm already using the latest blockscout.

**Comment by pasqu4le** [comment]
Hi @ysbae0928, the problem you encountered is indeed similar to the one handled by the PR you have found, but for a different fetcher/table.

As such there is a similar solution and it's now in a PR
