### ISSUE TITLE
Question: I am looking to add more columns to the db

### ISSUE THREAD

**Issue by lightninggalaxy** [poanetwork/blockscout#2078]
Environment
Elixir & Erlang/OTP versions (elixir -version):
Erlang/OTP 21 [erts-10.0.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
Elixir 1.8.1 (compiled with Erlang/OTP 20)

Operating System:
Ubuntu 18.04

Blockscout Version:
BlockScout v1.3.14-beta

Hi, I am looking to add a few columns to the transactions table. For any transactions that come in, I want to be able to parse the raw input to check if it includes something then if it does, add a value to the newly added column. Adding the new columns should be easy enough, but whereabouts can I look to be able to add the aforementioned value to the newly added column in the db? Thank you.

**Comment by ayrat555** [comment]
@lightninggalaxy take a look https://hexdocs.pm/phoenix/ecto.html#content if you're not familiar with migrations.
