### ISSUE TITLE
Log eating space

### ISSUE THREAD

**Issue by bellaj** [poanetwork/blockscout#2087]
I have deployed blockscout on azure with a Poa network. I have faced few issues, but I've managed to get the explorer working but I am getting still a repetitive error in the log :

![err](https://user-images.githubusercontent.com/16008163/58797278-823d9100-85f7-11e9-9099-57218ead8556.png)
therefore the log file's size is quickly becoming huge (X Gigbytes).
Am wondering how can i redirect the log or disable it?

**Comment by ayrat555** [comment]
@bellaj which version of parity are you using?

**Comment by vbaranov** [comment]
@bellaj also, logs rotation is configured for production environment:
https://github.com/poanetwork/blockscout/blob/81179f9459fc6a80944d8490a331c9160d85ecdd/apps/explorer/config/prod.exs#L16

**Comment by bellaj** [comment]
> @bellaj which version of parity are you using?

I am using :

Parity v1.10.6-stable-bc0d134-20180605

**Comment by bellaj** [comment]
Thanks @vbaranov 
would you please explain what does it max_bytes and keep
I presume its max size (Gb) and how many days to keep the log, right?

**Comment by ayrat555** [comment]
there is an issue https://github.com/paritytech/parity-ethereum/issues/8725 that was fixed in  v2.0.0. I believe it's causing your issue

**Comment by vbaranov** [comment]
@bellaj 

>I presume it's max size (Gb) and how many days to keep the log, right?

No, this is the size of each file in bytes and the maximum number of files to keep.

Logs rotation was introduced here https://github.com/poanetwork/blockscout/pull/958

>Editing the logger backends to do file rotation every 50mb and keep
the last 19 log files per logger backend. 50mb * 20 = ~1gb

**Comment by damianlluch** [comment]
Sorry, I read your reply in the other issue and it was not clear to me. Can I delete that folder yes or no? I don't know what you mean by log rotation.
