### ISSUE TITLE
today's master branch breaks color schemes

### ISSUE THREAD

**Issue by mkrufky** [poanetwork/blockscout#2114]
today's master branch breaks color schemes.  See https://blocks.ether1.wattpool.net

![image](https://user-images.githubusercontent.com/1062488/59097588-f627b400-88eb-11e9-9f89-bd262293944f.png)

That purple shouldn't be there :-/

**Comment by vbaranov** [comment]
@mkrufky what is your `apps/block_scout_web/assets/css/theme/_variables.scss` file does look like? Please remove `@import "neutral_variables";` from it. Only `
@import "theme/base_variables";` and your theme file should be there

**Comment by mkrufky** [comment]
Indeed - that was the issue.  Thanks @vbaranov
