### ISSUE TITLE
"fetcher=block_uncle count=10" Error

### ISSUE THREAD

**Issue by jsd9399** [poanetwork/blockscout#2126]
Jun 08 21:23:37 ip-172-31-41-232 iex[19720]: 2019-06-08T21:23:37.433 fetcher=block_uncle count=10 [error] Task #PID<0.1147.0> started from Indexer.Fetcher.UncleBlock terminating
Jun 08 21:23:37 ip-172-31-41-232 iex[19720]: ** (FunctionClauseError) no function clause matching in Indexer.Fetcher.UncleBlock.error_to_entry/1
Jun 08 21:23:37 ip-172-31-41-232 iex[19720]:     (indexer) lib/indexer/fetcher/uncle_block.ex:238: Indexer.Fetcher.UncleBlock.error_to_entry(%{code: 404, data: %{index: 0, nephew_hash: "0xa0814f0478fe90c82852f812fd74c96df148654c326d2600d836e6908ebb62b4"}, message: "Not Found"})
Jun 08 21:23:37 ip-172-31-41-232 iex[19720]:     (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
Jun 08 21:23:37 ip-172-31-41-232 iex[19720]:     (indexer) lib/indexer/fetcher/uncle_block.ex:208: Indexer.Fetcher.UncleBlock.retry/1
Jun 08 21:23:37 ip-172-31-41-232 iex[19720]:     (indexer) lib/indexer/fetcher/uncle_block.ex:84: Indexer.Fetcher.UncleBlock.run/2
Jun 08 21:23:37 ip-172-31-41-232 iex[19720]:     (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
Jun 08 21:23:37 ip-172-31-41-232 iex[19720]:     (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
Jun 08 21:23:37 ip-172-31-41-232 iex[19720]:     (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Jun 08 21:23:37 ip-172-31-41-232 iex[19720]: Function: &Indexer.BufferedTask.log_run/1
.
.
.

eheap_alloc: Cannot allocate 11753808384 bytes of memory (of type "heap").
[1B blob data]

### Environment
* Operating System: Elixir 1.8.1 (compiled with Erlang/OTP 20)
* The Blockscout version was downloaded to the master branch two weeks ago.
* Coin : Ethereum Mainnet

The above error occurs the same every three seconds. And eventually the system stops with a warning message that it lacks system memory.
How do I deal with this?

**Comment by vbaranov** [comment]
@jsd9399 This issue should be fixed here https://github.com/poanetwork/blockscout/pull/2108. Try with the latest updates from master branch.

**Comment by jsd9399** [comment]
@vbaranov  I've run a test with the latest Master Branch, but there's an error.

2019-06-10T08:17:17.313 fetcher=block_uncle count=10 [error] Task #PID<0.1842.0> started from Indexer.Fetcher.UncleBlock terminating
** (FunctionClauseError) no function clause matching in Indexer.Fetcher.UncleBlock.error_to_entry/1
    (indexer) lib/indexer/fetcher/uncle_block.ex:238: Indexer.Fetcher.UncleBlock.error_to_entry(%{code: 404, data: %{index: 0, nephew_hash: "0xa0814f0478fe90c82852f812fd74c96df148654c326d2600d836e6908ebb62b4"}, message: "Not Found"})
    (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
    (indexer) lib/indexer/fetcher/uncle_block.ex:208: Indexer.Fetcher.UncleBlock.retry/1
    (indexer) lib/indexer/fetcher/uncle_block.ex:84: Indexer.Fetcher.UncleBlock.run/2
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Indexer.BufferedTask.log_run/1

**Comment by ayrat555** [comment]
@jsd9399 https://github.com/poanetwork/blockscout/pull/2128 this PR should fix your error

**Comment by jsd9399** [comment]
@ayrat555 @vbaranov 
I've patched both of them... but the results are the same...

Jun 10 09:02:24 ip-172-31-41-232 iex[2256]: 2019-06-10T09:02:24.305 fetcher=block_uncle count=10 [error] Task #PID<0.3159.0> started from Indexer.Fetcher.UncleBlock terminating
Jun 10 09:02:24 ip-172-31-41-232 iex[2256]: ** (FunctionClauseError) no function clause matching in Indexer.Fetcher.UncleBlock.error_to_entry/1
Jun 10 09:02:24 ip-172-31-41-232 iex[2256]:     (indexer) lib/indexer/fetcher/uncle_block.ex:238: Indexer.Fetcher.UncleBlock.error_to_entry(%{code: 404, data: %{index: 0, nephew_hash: "0xa0814f0478fe90c82852f812fd74c96df148654c326d2600d836e6908ebb62b4"}, message: "Not Found"})
Jun 10 09:02:24 ip-172-31-41-232 iex[2256]:     (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
Jun 10 09:02:24 ip-172-31-41-232 iex[2256]:     (indexer) lib/indexer/fetcher/uncle_block.ex:208: Indexer.Fetcher.UncleBlock.retry/1
Jun 10 09:02:24 ip-172-31-41-232 iex[2256]:     (indexer) lib/indexer/fetcher/uncle_block.ex:84: Indexer.Fetcher.UncleBlock.run/2
Jun 10 09:02:24 ip-172-31-41-232 iex[2256]:     (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
Jun 10 09:02:24 ip-172-31-41-232 iex[2256]:     (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
Jun 10 09:02:24 ip-172-31-41-232 iex[2256]:     (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Jun 10 09:02:24 ip-172-31-41-232 iex[2256]: Function: &Indexer.BufferedTask.log_run/1
Jun 10 09:02:24 ip-172-31-41-232 iex[2256]:     Args: [%{batch: [{<<103, 62, 126, 22, 104, 39, 162, 127, 54, 54, 54, 37, 79, 254, 74, 68, 43, 51, 196, 126, 226, 245, 123, 21, 53, 88, 242, 249, 139, 248, 116, 219>>, 0}, {<<13, 10, 215, 181, 137, 103, 212, 38, 226, 14, 92, 70, 178, 112, 79, 79, 181, 222, 179, 130, 195, 25, 121, 210, 242, 46, 4, 189, 200, 31, 12, 139>>, 0}, {<<244, 14, 244, 69, 179, 1, 1, 145, 194, 59, 79, 204, 126, 129, 156, 226, 183, 149, 203, 74, 223, 111, 181, 99, 79, 235, 26, 54, 215, 168, 223, 112>>, 0}, {<<160, 129, 79, 4, 120, 254,144, 200, 40, 82, 248, 18, 253, 116, 201, 109, 241, 72, 101, 76, 50, 109, 38, 0, 216, 54, 230, 144, 142, 187, 98, 180>>, 0}, {<<137, 187, 24, 22, 26, 224, 219, 186, 133, 64, 179, 234, 218, 102, 41, 72, 183, 218, 31, 240, 139, 25, 117, 245, 235, 174, 126, 143, 172, 114, 21, 188>>, 0}, {<<75, 179, 121, 215, 199, 141, 80, 229, 40, 224, 72, 104, 95, 166, 113, 136, 236, 16, 173, 234, 125, 133, 218, 197, 124, 237, 139, 71, 133, 63, 118, 59>>, 0}, {<<11, 212, 5, 136, 216, 50, 99, 118, 92, 34, 168, 220, 248, 218, 56, 66, 172, 208, 28, 147, 52, 149, 146, 154, 114, 121, 136, 162, 249, 232, 53, 224>>, 0}, {<<137, 201, 156, 165, 218, 26, 150, 201, 75, 147, 66, 66, 181, 242, 1, 62, 105, 198, 240, 148, 19, 248, 51, 83, 42, 150, 223, 190, 230, 186, 160, 130>>, 0}, {<<107, 140, 251, 44, 64, 29, 147, 169, 94, 195, 195, 171, 157, 255, 203, 143, 224, 84, 243, 201, 95, 67, 88, 139, 99, 43, 163, 7, 248,158, 66, 221>>, 0}, {<<69, 207, 37, 129, 39, 235, 101, 168, 162, 37, 198, 169, 253, 110, 108, 93, 209, 155, 71,228, 17, 43, 21, 179, 40, 76, 13, 5, 71, 92, 137, 211>>, 0}], callback_module: Indexer.Fetcher.UncleBlock, callback_module_state: %Indexer.Block.Fetcher{broadcast: :uncle, callback_module: Indexer.Fetcher.UncleBlock, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options:

**Comment by ayrat555** [comment]
@jsd9399  I added one more missing function to my PR. Can you please check?

**Comment by jsd9399** [comment]
@ayrat555 
Results of patching.


Jun 10 09:39:14 ip-172-31-41-232 iex[5241]: 2019-06-10T09:39:14.227 fetcher=block_uncle count=5 [error] Task #PID<0.1438.0> started from Indexer.Fetcher.UncleBlock terminating
Jun 10 09:39:14 ip-172-31-41-232 iex[5241]: ** (FunctionClauseError) no function clause matching in Indexer.Fetcher.UncleBlock.entry_to_params/1
Jun 10 09:39:14 ip-172-31-41-232 iex[5241]:     (indexer) lib/indexer/fetcher/uncle_block.ex:98: Indexer.Fetcher.UncleBlock.entry_to_params("0xa0814f0478fe90c82852f812fd74c96df148654c326d2600d836e6908ebb62b4")
Jun 10 09:39:14 ip-172-31-41-232 iex[5241]:     (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
Jun 10 09:39:14 ip-172-31-41-232 iex[5241]:     (indexer) lib/indexer/fetcher/uncle_block.ex:80: Indexer.Fetcher.UncleBlock.run/2
Jun 10 09:39:14 ip-172-31-41-232 iex[5241]:     (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
Jun 10 09:39:14 ip-172-31-41-232 iex[5241]:     (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
Jun 10 09:39:14 ip-172-31-41-232 iex[5241]:     (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Jun 10 09:39:14 ip-172-31-41-232 iex[5241]: Function: &Indexer.BufferedTask.log_run/1
Jun 10 09:39:14 ip-172-31-41-232 iex[5241]:     Args: [%{batch: [{<<50, 163, 194, 250, 115, 107, 242, 185, 165,102, 10, 189, 251, 247, 15, 226, 153, 187, 76, 192, 101, 80, 126, 173, 88, 36, 52, 161, 150, 240, 136, 134>>, 0}, {<<103, 62, 126, 22, 104, 39, 162, 127, 54, 54, 54, 37, 79, 254, 74, 68, 43, 51, 196, 126, 226, 245, 123, 21,53, 88, 242, 249, 139, 248, 116, 219>>, 0}, {<<13, 10, 215, 181, 137, 103, 212, 38, 226, 14, 92, 70, 178, 112, 79, 79, 181, 222, 179, 130, 195, 25, 121, 210, 242, 46, 4, 189, 200, 31, 12, 139>>, 0}, {<<244, 14, 244, 69, 179, 1, 1, 145, 194, 59, 79, 204, 126, 129, 156, 226, 183, 149, 203, 74, 223, 111, 181, 99, 79, 235, 26, 54, 215, 168, 223, 112>>, 0}, "0xa0814f0478fe90c82852f812fd74c96df148654c326d2600d836e6908ebb62b4"], callback_module: Indexer.Fetcher.UncleBlock, callback_module_state: %Indexer.Block.Fetcher{broadcast: :uncle, callback_module: Indexer.Fetcher.UncleBlock, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options

**Comment by ayrat555** [comment]
@jsd9399 can you please check one more time?

**Comment by jsd9399** [comment]
@ayrat555 
It's the result of the patch you recommended..

Jun 10 15:23:16 ip-172-31-41-232 iex[31605]: 2019-06-10T15:23:16.387 fetcher=block_uncle count=10 [error] Task #PID<0.1509.0> started from Indexer.Fetcher.UncleBlock terminating
Jun 10 15:23:16 ip-172-31-41-232 iex[31605]: ** (FunctionClauseError) no function clause matching in Indexer.Fetcher.UncleBlock.error_to_entry/1
Jun 10 15:23:16 ip-172-31-41-232 iex[31605]:     (indexer) lib/indexer/fetcher/uncle_block.ex:238: Indexer.Fetcher.UncleBlock.error_to_entry(%{code: 404, data: %{index: 0, nephew_hash: "0xa0814f0478fe90c82852f812fd74c96df148654c326d2600d836e6908ebb62b4"}, message: "Not Found"})
Jun 10 15:23:16 ip-172-31-41-232 iex[31605]:     (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
Jun 10 15:23:16 ip-172-31-41-232 iex[31605]:     (indexer) lib/indexer/fetcher/uncle_block.ex:208: Indexer.Fetcher.UncleBlock.retry/1
Jun 10 15:23:16 ip-172-31-41-232 iex[31605]:     (indexer) lib/indexer/fetcher/uncle_block.ex:84: Indexer.Fetcher.UncleBlock.run/2
Jun 10 15:23:16 ip-172-31-41-232 iex[31605]:     (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
Jun 10 15:23:16 ip-172-31-41-232 iex[31605]:     (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
Jun 10 15:23:16 ip-172-31-41-232 iex[31605]:     (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Jun 10 15:23:16 ip-172-31-41-232 iex[31605]: Function: &Indexer.BufferedTask.log_run/1
Jun 10 15:23:16 ip-172-31-41-232 iex[31605]:     Args: [%{batch: [{<<244, 14, 244, 69, 179, 1, 1, 145, 194, 59, 79, 204, 126, 129, 156, 226, 183, 149, 203, 74, 223, 111, 181, 99, 79, 235, 26, 54, 215, 168, 223, 112>>, 0}, {<<160, 129, 79, 4, 120, 254, 144, 200, 40, 82, 248, 18, 253, 116, 201, 109, 241, 72, 101, 76, 50, 109, 38, 0, 216, 54, 230, 144, 142, 187, 98, 180>>, 0}, {<<137, 187, 24, 22, 26, 224, 219, 186, 133, 64, 179, 234, 218, 102, 41, 72, 183, 218, 31, 240, 139, 25, 117, 245, 235, 174, 126, 143, 172, 114, 21, 188>>, 0}, {<<75, 179, 121, 215, 199, 141, 80, 229, 40, 224, 72, 104, 95, 166, 113, 136, 236, 16, 173, 234, 125, 133, 218, 197, 124, 237, 139, 71, 133, 63, 118, 59>>, 0}, {<<11, 212, 5, 136, 216, 50, 99, 118, 92, 34, 168, 220, 248, 218, 56, 66, 172, 208, 28, 147, 52, 149, 146, 154, 114, 121, 136, 162, 249, 232, 53, 224>>, 0}, {<<137, 201, 156, 165, 218, 26, 150, 201, 75, 147, 66, 66, 181, 242, 1, 62, 105, 198, 240, 148, 19, 248, 51, 83, 42, 150, 223, 190, 230, 186, 160, 130>>, 0}, {<<107, 140, 251, 44, 64, 29, 147, 169, 94, 195, 195, 171, 157, 255, 203, 143, 224, 84, 243, 201, 95, 67, 88, 139, 99, 43, 163, 7, 248, 158, 66, 221>>, 0}, {<<69, 207, 37, 129, 39, 235, 101, 168, 162, 37, 198, 169, 253, 110, 108, 93, 209, 155, 71, 228, 17, 43, 21, 179, 40, 76, 13, 5, 71, 92, 137, 211>>, 0}, {<<69, 207, 37, 129, 39, 235, 101, 168, 162, 37, 198, 169, 253, 110, 108, 93, 209, 155, 71, 228, 17, 43, 21, 179, 40, 76, 13, 5, 71, 92, 137, 211>>, 1}, {<<166, 78, 12, 123, 217, 200, 24, 4, 193, 8, 111, 178, 134, 50, 19, 156, 228, 116, 234, 133, 122, 71, 188, 244, 59, 224, 79, 143, 48, 191, 131, 209>>, 1}], callback_module: Indexer.Fetcher.UncleBlock, callback_module_state: %Indexer.Block.Fetcher{broadcast: :uncle, callback_module: Indexer.Fetcher.UncleBlock, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [

**Comment by ayrat555** [comment]
@jsd9399 I'm sorry for the inconvenience. Apparently, retries from json rpc errors weren't working at all. Can you please check that everything is working

**Comment by jsd9399** [comment]
@ayrat555 
All my systems are functioning normally. Parity also works with recommended specifications.

**Comment by ayrat555** [comment]
@jsd9399 can we move our conversion to blockscout's gitter? https://gitter.im/poanetwork/blockscout?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge
