### ISSUE TITLE
We need a way to hide links to other BS instances

### ISSUE THREAD

**Issue by ArseniiPetrovich** [poanetwork/blockscout#2132]
*Describe your issue here.*

I've setup a new BlockScout instance (not for POA), that should not lead to other POA-hosted BlockScout instances. As such - I didn't set the `SUPPORTED_CHAINS` variable.
When I compiled the BS and deployed it, I've found that all the links to other networks still exists.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): 21.1
* Operating System: Amazon Linux 2

### Steps to reproduce
https://github.com/symanovich-a/blockscout
Branch: production_tenda
But I don't think this is related to code changes we did at BS (coin symbol customization).

1. Compile BS
2. Do not set SUPPORTED_CHAINS

### Expected behaviour

No links to other BlockScout instances should be shown.

### Actual behaviour

https://tenda.network - all the links are present.

**Comment by saneery** [comment]
@ArseniiPetrovich @vbaranov what if we add new variable `LINK_TO_OTHER_NETWORKS` to show or hide links to other BlockScout instances?

**Comment by saneery** [comment]
@ArseniiPetrovich `LINK_TO_OTHER_EXPLORERS` hides links to explorers, not to networks

![Screenshot from 2019-06-12 16 14 19](https://user-images.githubusercontent.com/11743366/59354274-7ce5f200-8d2d-11e9-96d8-580151fb4a6d.png)

Do you want to hide links to networks?

![image](https://user-images.githubusercontent.com/11743366/59354332-9c7d1a80-8d2d-11e9-84f6-de4913e3aa89.png)

**Comment by vbaranov** [comment]
@ArseniiPetrovich if you need to hide networks in the menu you should set SUPPORTED_CHAINS="[]"

**Comment by saneery** [comment]
After set `SUPPORTED_CHAINS="[]"` I got this:

![image](https://user-images.githubusercontent.com/11743366/59358146-b5d59500-8d34-11e9-8c5e-db8d6d422bac.png)

Maybe, we should remove the dropdown menu?

**Comment by vbaranov** [comment]
@saneery good idea. Let's hide menu if the array is empty in SUPPORTED_CHAINS

**Comment by ArseniiPetrovich** [comment]
Please, reopen the issue. 
See https://tenda.network
LINK_TO_OTHER_EXPLORERS does not hide links tp other explorers at footer there.

**Comment by saneery** [comment]
>Please, reopen the issue.
See https://tenda.network
LINK_TO_OTHER_EXPLORERS does not hide links tp other explorers at footer there.

There isn't **epxlorers** list, there is **networks** list.

![image](https://user-images.githubusercontent.com/11743366/59360208-5bd6ce80-8d38-11e9-954b-36ee13e4684e.png)

**explorers list** looks like this

![image](https://user-images.githubusercontent.com/11743366/59360510-e0295180-8d38-11e9-8d1d-90c5878132f4.png)

**Comment by vbaranov** [comment]
@ArseniiPetrovich I guess, you should edit the content of the issue. `LINK_TO_OTHER_EXPLORERS` doesn't hide links to networks and it shouldn't. It is for other explorers only. I suppose we could implement this feature (hiding of networks) with `SUPPORTED_CHAINS` env var.

**Comment by ArseniiPetrovich** [comment]
Oh, now i clearly get it. Thanks. Yes, I'll change the issue title

**Comment by saneery** [comment]
@vbaranov @ArseniiPetrovich I think we can close this issue, because then `SUPPORTED_CHAINS="[]"` there aren't links to other BS instances in the footer
![image](https://user-images.githubusercontent.com/11743366/61440859-30ee2480-a94d-11e9-865c-b7b80278a2a8.png)

**Comment by saneery** [comment]
@vbaranov looks like there were changes after my PR, now there are opens menu with an empty list

![image](https://user-images.githubusercontent.com/11743366/61442329-14072080-a950-11e9-9111-2f1c7eeaaa57.png)

I'll disable this button :ok_hand:

**Comment by saneery** [comment]
@vbaranov @ArseniiPetrovich could we close this issue?
