### ISSUE TITLE
`mix do deps.get, local.rebar --force, deps.compile, compile` fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by mfahampshire** [poanetwork/blockscout#2150]
Following the manual installation instructions (https://forum.poa.network/t/manual-blockscout-deployment/2458) on a DigitalOcean VM. 

Currently getting the following readout and error on step 6 when running `mix do deps.get, local.rebar --force, deps.compile, compile`:

```
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  abnf2 0.1.2
  absinthe 1.4.14
  absinthe_relay 1.4.6
  accept 0.3.3
  artificery 0.2.6
  bcrypt_elixir 1.1.1
  benchee 0.13.2
  benchee_csv 0.8.0
  binary 0.0.5
  bunt 0.2.0
  bypass 1.0.0
  certifi 2.5.1
  combine 0.10.0
  comeonin 4.1.2
  con_cache 0.13.1
  connection 1.0.4
  cors_plug 2.0.0
  cowboy 2.6.1
  cowlib 2.7.0
  credo 1.0.0
  csv 2.1.1
  dataloader 1.0.6
  db_connection 2.0.3
  decimal 1.6.0
  decorator 1.3.0
  deep_merge 0.2.0
  dialyxir 0.5.1
  distillery 2.0.12
  earmark 1.3.1
  ecto 3.0.7
  ecto_sql 3.0.4
  elixir_make 0.4.2
  ex_abi 0.1.18
  ex_cldr 1.3.2
  ex_cldr_numbers 1.2.0
  ex_cldr_units 1.1.1
  ex_doc 0.19.2
  ex_machina 2.2.2
  ex_rlp 0.5.2
  exactor 2.2.4
  exjsx 4.0.0
  exth_crypto 0.1.6
  exvcr 0.10.3
  file_system 0.2.6
  floki 0.20.4
  flow 0.14.3
  gen_stage 0.14.1
  gettext 0.16.1
  hackney 1.15.1
  html_entities 0.4.0
  httpoison 1.5.0
  idna 6.0.0
  jason 1.1.2
  jsx 2.8.3
  junit_formatter 3.0.0
  keccakf1600_orig 2.0.0
  libsecp256k1 0.1.10
  logger_file_backend 0.0.10
  makeup 0.8.0
  makeup_elixir 0.13.0
  math 0.3.0
  meck 0.8.12
  metrics 1.0.1
  mime 1.3.1
  mimerl 1.2.0
  mix_erlang_tasks 0.1.0
  mochiweb 2.18.0
  mock 0.3.2
  mox 0.4.0
  msgpax 2.2.2
  nimble_parsec 0.5.0
  optimal 0.3.6
  parallel_stream 1.0.6
  parse_trans 3.3.0
  phoenix 1.4.0
  phoenix_ecto 4.0.0
  phoenix_form_awesomplete 0.1.4
  phoenix_html 2.13.1
  phoenix_live_reload 1.2.0
  phoenix_pubsub 1.1.1
  plug 1.7.2
  plug_cowboy 2.0.1
  plug_crypto 1.0.0
  poison 3.1.0
  poolboy 1.5.2
  postgrex 0.14.1
  prometheus 4.2.0
  prometheus_ex 3.0.3
  prometheus_phoenix 1.2.1
  prometheus_plugs 1.1.5
  prometheus_process_collector 1.4.0
  qrcode 0.1.4
  ranch 1.7.1
  sobelow 0.7.4
  spandex_datadog 0.4.0
  spandex_ecto 0.4.0
  spandex_phoenix 0.3.1
  ssl_verify_fun 1.1.4
  telemetry 0.3.0
  timex 3.5.0
  tzdata 0.5.19
  unicode_util_compat 0.4.1
  wallaby 0.22.0
  websocket_client 1.3.0
* creating /root/.mix/rebar
* creating /root/.mix/rebar3
warning: variable "description" does not exist and is being expanded to "description()", please use parentheses to remove the ambiguity or change the variable name
  /root/blockscout/blockscout/deps/mix_erlang_tasks/mix.exs:9

warning: variable "package" does not exist and is being expanded to "package()", please use parentheses to remove the ambiguity or change the variable name
  /root/blockscout/blockscout/deps/mix_erlang_tasks/mix.exs:10

===> Compiling parse_trans
===> Compiling websocket_client
===> Compiling mimerl
==> libsecp256k1
could not compile dependency :libsecp256k1, "mix compile" failed. You can recompile this dependency with "mix deps.compile libsecp256k1", update it with "mix deps.update libsecp256k1" or clean it with "mix deps.clean libsecp256k1"
** (ErlangError) Erlang error: :enoent
    (elixir) lib/system.ex:634: System.cmd("make", [], [into: %IO.Stream{device: :standard_io, line_or_bytes: :line, raw: false}])
    /root/blockscout/blockscout/deps/libsecp256k1/mix.exs:3: Mix.Tasks.Compile.MakeBindings.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.all.ex:68: Mix.Tasks.Compile.All.run_compiler/2
    (mix) lib/mix/tasks/compile.all.ex:52: Mix.Tasks.Compile.All.do_compile/4
    (mix) lib/mix/tasks/compile.all.ex:23: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
    (mix) lib/mix/tasks/compile.all.ex:39: Mix.Tasks.Compile.All.with_logger_app/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
```
### Environment

running ubuntu 18.04 DigitalOcean droplet with
Erlang/OTP 22 [erts-10.4.1] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1]
Elixir 1.8.2 (compiled with Erlang/OTP 20)

### Expected behaviour

Project compiles 

### Actual behaviour

Error message above stops compilation

**Comment by vbaranov** [comment]
@mfahampshire we do not support `Erlang/OTP 22` yet. Try with Erlang/OTP 21. https://github.com/poanetwork/blockscout#requirements. Also, use the latest BS release to deploy https://github.com/poanetwork/blockscout/releases

**Comment by vbaranov** [comment]
Please reopen if you have problems with `Erlang/OTP 21`

**Comment by rrodriguezreche** [comment]
> @mfahampshire we do not support `Erlang/OTP 22` yet. Try with Erlang/OTP 21. https://github.com/poanetwork/blockscout#requirements. Also, use the latest BS release to deploy https://github.com/poanetwork/blockscout/releases

Hi, I am having issues compiling too. I am using Erlang 22, but only because my 21 installation gets overwritten when I install Elixir 1.9.0, as per the documentation. Is Erlang 22 supported now?

**Comment by vbaranov** [comment]
Elixir version 1.9.1 and Erlang/OTP 22 should work fine with the latest commit on master branch https://github.com/poanetwork/blockscout/commit/6caefe3566fef5e878f085b9a4b285cf6ef03c37 and with the latest stable release too https://github.com/poanetwork/blockscout/releases/tag/v2.1.0-beta

**Comment by rrodriguezreche** [comment]
> Elixir version 1.9.1 and Erlang/OTP 22 should work fine with the latest commit on master branch [6caefe3](https://github.com/poanetwork/blockscout/commit/6caefe3566fef5e878f085b9a4b285cf6ef03c37) and with the latest stable release too https://github.com/poanetwork/blockscout/releases/tag/v2.1.0-beta

Installing elixir 1.9.1 specifically seems to have solved it. I targeted 1.9.0 (as the docs recommended) and 1.9.4 before, without success, on ubuntu 18.04. Leaving this here for anyone who might be running into the same issue.

**Comment by vbaranov** [comment]
Thanks for pointing me out to outdated docs. Fixed that.

**Comment by soumen29121997** [comment]
@vbaranov please help me out
could not compile dependency :libsecp256k1, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile libsecp256k1", update it with "mix deps.update libsecp256k1" or clean it with "mix deps.clean libsecp256k1"
** (ErlangError) Erlang error: :enoent
    (elixir 1.13.4) lib/system.ex:1044: System.cmd("make", [], [into: %IO.Stream{device: :standard_io, line_or_bytes: :line, raw: false}])
    e:/Phoniex/trial 2/blockscout-2.1.0-beta/deps/libsecp256k1/mix.exs:3: Mix.Tasks.Compile.MakeBindings.run/1
    (mix 1.13.4) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.13.4) lib/mix/tasks/compile.all.ex:92: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.13.4) lib/mix/tasks/compile.all.ex:72: Mix.Tasks.Compile.All.compile/4
    (mix 1.13.4) lib/mix/tasks/compile.all.ex:59: Mix.Tasks.Compile.All.with_logger_app/2
    (mix 1.13.4) lib/mix/tasks/compile.all.ex:36: Mix.Tasks.Compile.All.run/1
    (mix 1.13.4) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
