### ISSUE TITLE
Show transaction input similar to how a hex editor would

### ISSUE THREAD

**Issue by jimmay5469** [poanetwork/blockscout#217]
We should drop the `0x` from the input field and format it similarly to how a hex editor would:
![](https://cdn.discordapp.com/attachments/426494988759859200/449651055245131786/Screen_Shot_2018-05-25_at_3.12.06_PM.png)

**Comment by KronicDeth** [comment]
Not just as a hex editor, but specifically the width should be 256 bits because that in the native word size in the Ethereum Virtual Machine.

**Comment by jimmay5469** [comment]
@arthurra that would be 8 of those 8 digit groupings as you see above per line. We may have to go full width instead of just the right side or put it in a tab.
