### ISSUE TITLE
Blockscout web information Unable to update automatically

### ISSUE THREAD

**Issue by northeusunshine** [poanetwork/blockscout#2187]
### Environment
* Blockscout version: latest release version` BlockScout v2.0.0-beta`
* Elixir & Erlang/OTP versions (elixir -version): 
`Erlang/OTP 21 [erts-10.0.5] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
Elixir 1.8.1 (compiled with Erlang/OTP 21)
`
* Operating System:`Linux Centos 7`

After install required software:
### Steps to reproduce
* Step1 get latest blockscout:
`wget  https://github.com/poanetwork/blockscout/archive/v2.0.0-beta.tar.gz` and unzip
* Step2
`cp apps/explorer/config/dev.secret.exs.example apps/explorer/config/dev.secret.exs`
`cp apps/block_scout_web/config/dev.secret.exs.example apps/block_scout_web/config/dev.secret.exs`
* Step3
Update the database username and password configuration of `apps/explorer/config/dev.secret.exs` (username=postgres:password:postgres)
* Step4 
`mix do deps.get, local.rebar --force, deps.compile, compile`
* Step5 : start postgresql database service
```
su - postgres
initdb -E UNICODE -D /mnt/pgsql/data
pg_ctl -D /mnt/pgsql/data/ -l logfile start
```
* Step6
`mix do ecto.create, ecto.migrate`
* Step7
`cd apps/block_scout_web/assets; npm install`
`cd apps/explorer && npm install`
* Step8
```
cd apps/block_scout_web
mix phx.gen.cert blockscout blockscout.local; cd -
Add blockscout and blockscout.local to your /etc/hosts
   127.0.0.1       localhost blockscout blockscout.local
    255.255.255.255 broadcasthost
   ::1             localhost blockscout blockscout.local
```
* Step9:  set enviroment varaibles.
```
export PGDATA=/mnt/pgsql/data
export PGLOG=/mnt/pgsql/pgsql.log
export ETHEREUM_JSONRPC_VARIANT=geth
export ETHEREUM_JSONRPC_HTTP_URL=http://192.168.43.87:8545
export ETHEREUM_JSONRPC_TRACE_URL=http://192.168.43.87:8545
export ETHEREUM_JSONRPC_WS_URL=ws://192.168.43.87:8546
export DB_HOST=192.168.43.87
export DB_PASSWORD=postgres
export DB_PORT=5432
export DB_USERNAME=postgres
export BLOCK_TRANSFORMER=clique
```
* Step11: launch a private clique POA ethereum node by geth command
`geth --networkid 123456 --rpc --rpcport "8545" --rpccorsdomain "*" --datadir ./node1/data --syncmode 'full' --port "30301"  --rpcaddr "0.0.0.0" --rpcapi "admin,db,eth,miner,web3,net,personal,txpool,clique" --ws --wsport "8546" --gcmode "archive" --unlock '0x****' --password password.txt --mine`
* Step12
`cd /root/sw/blockscout-2.0.0-beta/`
`mix phx.server`

### Expected behaviour
1 BlockScout data on web can update itself when new block is signed.
2 No error printed  in console.

### Actual behaviour
1 BlockScout  web can not synchronize block information itself.
the new block information can be loaded only when click on "update" button of explorer.
2 the console log show error like below:
```
2019-06-17T08:34:05.599 fetcher=block_realtime [error] GenServer Indexer.Block.Realtime.Fetcher terminating
** (stop) exited in: GenServer.call(Indexer.Block.Realtime.WebSocket, {:subscribe, "newHeads", []}, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:989: GenServer.call/3
    (indexer) lib/indexer/block/realtime/fetcher.ex:138: Indexer.Block.Realtime.Fetcher.subscribe_to_new_heads/2
    (indexer) lib/indexer/block/realtime/fetcher.ex:71: Indexer.Block.Realtime.Fetcher.handle_continue/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:388: :gen_server.loop/7
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:continue, {:init, [transport: EthereumJSONRPC.WebSocket, transport_options: %EthereumJSONRPC.WebSocket{url: "ws://192.168.43.87:8546", web_socket: EthereumJSONRPC.WebSocket.WebSocketClient, web_socket_options: %EthereumJSONRPC.WebSocket.WebSocketClient.Options{event: nil, params: nil, web_socket: Indexer.Block.Realtime.WebSocket}}]}}
State: %Indexer.Block.Realtime.Fetcher{block_fetcher: %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://192.168.43.87:8545", http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, max_number_seen: nil, previous_number: nil, subscription: nil, timer: nil}
 
2019-06-17T08:34:07.256 application=indexer fetcher=block_catchup first_block_number=919 last_block_number=0 missing_block_count=1 shrunk=false [info] Index had to catch up.
2019-06-17T08:34:07.256 application=indexer fetcher=block_catchup [info] Checking if index needs to catch up in 2500ms.
2019-06-17T08:34:09.779 application=indexer fetcher=block_catchup first_block_number=920 last_block_number=0 missing_block_count=1 shrunk=false [info] Index had to catch up.
2019-06-17T08:34:09.779 application=indexer fetcher=block_catchup [info] Checking if index needs to catch up in 2500ms.
```

**Comment by ayrat555** [comment]
@northeusunshine request is timing out. are you that you set a node url correcttly?

**Comment by northeusunshine** [comment]
what I configure the system has been described in the post, what do you mean by "set a node url correcttly"? thanks!

**Comment by vbaranov** [comment]
@northeusunshine websocket endpoint is configured with `export ETHEREUM_JSONRPC_WS_URL=...`. Is the problem still actual?

**Comment by northeusunshine** [comment]
After I reconfigured the websocket parameter in geth node launching command like below:
`--ws --wsaddr 0.0.0.0 --wsport 8546 --wsorigins "*" --wsapi "admin,db,eth,miner,web3,net,personal,txpool,debug"`
From my test of BlockScout today, the blockscount is able to work.Thanks.
