### ISSUE TITLE
About "Total transactions" Number

### ISSUE THREAD

**Issue by northeusunshine** [poanetwork/blockscout#2195]
I set up blocksout using v2.0.0 beta(latest release version).
I notice that if I close explorer and reconnect to server, the ` Total transactions ` number sometimes starts from zero, not include history transaction, and is able to update with transaction.

**Comment by vbaranov** [comment]
Total transactions counter is displayed from ETS. It needs time to fill a cache with the number of transactions. Depending on the number of txs in blockchain you are trying to explore, it can be from minutes to hours. Update of the cache is managed by `TXS_COUNT_CACHE_PERIOD` env var. The default value for it is 2 hours https://forum.poa.network/t/faq-blockscout-environment-variables/1814.
