### ISSUE TITLE
Minimum CPU/Memory requirements?

### ISSUE THREAD

**Issue by dwalintukan** [poanetwork/blockscout#2200]
Couldn't find this on the readme anywhere.

Can you post the minimum/recommended requirements for running Blockscout as well as for the Postgres server?

Primarily for my case I would like to know in regards to AWS/RDS instances.

**Comment by vbaranov** [comment]
It depends on the chain you're trying to observe. In case of ETH Mainnet you should build on these parameters https://github.com/poanetwork/blockscout/issues/2013#issuecomment-495189456
