### ISSUE TITLE
Able to run migrations without having to drop all tables?

### ISSUE THREAD

**Issue by dwalintukan** [poanetwork/blockscout#2202]
I recently rebased with 2.0.0-beta release since my last rebase which was about 3-4 months ago so much has changed.

I was wondering if we are able to run the migrations and get the DB schema up-to-date without having to drop all the tables and re-sync from scratch. Thanks.

**Comment by vbaranov** [comment]
Yes, you do not need to drop all the tables and resync from scratch. But some migrations can take hours depending on the amount of data in the chain and your Blockscout instance can have downtime. Please take it in mind.

**Comment by dwalintukan** [comment]
@vbaranov Just need to run `mix do ecto.migrate`?

**Comment by vbaranov** [comment]
@dwalintukan yes, `mix do ecto.migrate`

**Comment by dwalintukan** [comment]
Would suggest to add that to the Readme. Especially for Elixir noobs like myself 😆 
![image](https://user-images.githubusercontent.com/4350404/59843019-f3b06a00-9381-11e9-9f92-73f5f0681528.png)

**Comment by vbaranov** [comment]
@dwalintukan we collected all docs about Blockscout in the GitHub pages: https://poanetwork.github.io/blockscout/#/manual-deployment
