### ISSUE TITLE
[Callisto] Inconsistency in account balance

### ISSUE THREAD

**Issue by yograterol** [poanetwork/blockscout#2209]
Someone reported me about an inconsistency in balance, check it out:

- https://blockscout.com/callisto/mainnet/search?q=0x7b3408d23d891edcdfca65c1ccab212290267c24
- https://explorer2.callisto.network/addr/0x7b3408d23d891edcdfca65c1ccab212290267c24

Wallet shows the second balance using public RPC node.

### Expected behaviour

It should show 1,208.3350 CLO

### Actual behaviour

It shows 840.835034732184317658

May, should BlockScout round the balance to 4 decimals.

**Comment by vbaranov** [comment]
The inconsistency has been disappeared. Thanks for the noticing that. And we slightly updated Calisto instance from the current master branch to make it more reliable https://github.com/poanetwork/blockscout/pull/2218.

@ayrat555 do you think we could update Callisto instance to round balance to 4 decimals?

**Comment by yograterol** [comment]
@vbaranov thank you!

The new HF requires this Parity chain file https://github.com/EthereumCommonwealth/rust-callisto/blob/4a5801b2e8dc42dcd98b5b76222fe8990a0e82f3/ethcore/res/ethereum/callisto.json

Are you using Geth or Parity?

**Comment by vbaranov** [comment]
>Are you using Geth or Parity?

We use Geth for Callisto instance

**Comment by yograterol** [comment]
@vbaranov oh, you're a wrong chain. https://github.com/EthereumCommonwealth/go-callisto/releases/tag/1.1

**Comment by igorbarinov** [comment]
> @vbaranov oh, you're a wrong chain. https://github.com/EthereumCommonwealth/go-callisto/releases/tag/1.1

why are we on a fork? because of a protocol upgrade?

**Comment by yograterol** [comment]
Yes, forked on block  2,900,001
and we will fork on block 3,100,000

Both forks will not affect BlockScout because we will not change RPC API or block headers.

**Comment by yograterol** [comment]
@vbaranov @igorbarinov I guess that you could remove blocks and transactions up to 2,900,000, however Geth could be resync from scratch.

**Comment by vbaranov** [comment]
@yograterol Yes, we will reindex blocks from genesis block up to 2,900,000 and let you know when it will be finished.

**Comment by vbaranov** [comment]
@yograterol I've checked blocks before 2,900,000 and the hashes match in Blockscout in callistoexplorer and from the new Geth node synced from scratch. What do we need to reindex?

**Comment by yograterol** [comment]
@vbaranov thank you for your answer, about reindex, I'm not sure how could you reindex in Blockscout only from block 2,900,000. Sorry if I don't know well how to help you with BlockScout, I'm looking how to reindex BlockScout with the new Geth synced.

Importan thing, you must run https://github.com/EthereumCommonwealth/go-callisto/releases/tag/1.1.

**Comment by vbaranov** [comment]
@yograterol yes, we already use that updated Geth client. We resynced it from scratch and we don't see any differences in hashes between Blockscout, update Geth node and another Callisto explorer. We know how to reindex Blosckout. However, we don't see any mismatches to reindex. If you could point us out, it would be awesome.

**Comment by vbaranov** [comment]
@yograterol and we constantly have performance issues with this release
>https://github.com/EthereumCommonwealth/go-callisto/releases/tag/1.1

go-callisto node consumes 100% CPU and all 8Gb memory every ~14 hours. Are you familiar with this performance issue? How can we deal with it?

**Comment by yograterol** [comment]
@vbaranov Blockscout is up to date.

About  second report is a bit weird, first report with that issue, could you give me more details of your server please?

In our servers it's everything ok however we have a lot of memory and CPU.

**Comment by vbaranov** [comment]
>About second report is a bit weird, first report with that issue, could you give me more details of your server please?

2 vCPU, 8Gb memory
Ubuntu 18.04.2 LTS

**Comment by vbaranov** [comment]
I am closing this since no more inconsistency in the balances. @yograterol if you will have thoughts about the Callisto node performance issue, please, let us know
