### ISSUE TITLE
Ethereum Classic: <ETC sent to ETH adress>

### ISSUE THREAD

**Issue by stanjel** [poanetwork/blockscout#2210]
*hi, I sent ETC to adress that supports only ETH. please, how can I get back my coins now?*

### Environment
* Elixir Version: 1.8.1
* Erlang Version: 21
* BlockScout Version: v2.0.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Wrong repo
