### ISSUE TITLE
Add Swagger API documentation

### ISSUE THREAD

**Issue by alexgaribay** [poanetwork/blockscout#224]
Expose an endpoint that document's the explorer's API with Swagger

Any exposed API should be documented and all new APIs should have documentation as a requirement before merging.

**Comment by LittleUmbrella** [comment]
if this is done, what is the endpoint?

**Comment by ulyanas** [comment]
@LittleUmbrella Hi! The reason for not implementing Swagger was added to this issue: 
https://github.com/blockscout/blockscout/commit/4e9dcced6c10c0c2da6e9a5a838b5f98d848b107 

Current API doc: https://github.com/blockscout/blockscout/issues/224
