### ISSUE TITLE
POA Core: missing my POAtokens 

### ISSUE THREAD

**Issue by fikio** [poanetwork/blockscout#2245]
Dear Poa

I transfer some poa into my eth  0x971E1C7e68163d337Cef67948c7509e5Ed253Be9
into my mycrypto- using Ledger x 
HASH 0x3ed36e04ff3115a69f9b4ba0baa27f85b1650368d1307df63761271a66088af8
However I can not see my coins 
this link was sent from mycrypto support and ask me to get in contact with you

https://blockscout.com/poa/core/address/0x971e1c7e68163d337cef67948c7509e5ed253be9/transactions

Can you please help me how to transfer my tokens into my POA in Ledger live??

Many thanks for your time
f

**Comment by igorbarinov** [comment]
Tokens are on the same address as you mentioned. 

Check instruction here https://forum.poa.network/t/wallet-ledger-nano-s-hardware/1816
for `Using Ledger Nano with MyEtherWallet (MEW)`

**Comment by fikio** [comment]
Great Thank you for your 
Support and fast respond 
love POA

**Comment by fikio** [comment]
Thank you so much for your fast and awesome supportI find my POA tokens know I can send more POA and store them safety Thank u    On Wednesday, 26 June 2019, 07:46:43 BST, Igor Barinov <notifications@github.com> wrote:  
 
 
Closed #2245.
