### ISSUE TITLE
Blockscout Crash!!!

### ISSUE THREAD

**Issue by ysbae0928** [poanetwork/blockscout#2300]
My BlockScout sometimes ends with a memory problem.
The attached file is the related dump file, and how should it be resolved?

[erl_crash.zip](https://github.com/poanetwork/blockscout/files/3361070/erl_crash.zip)

### Environment
* Elixir & Erlang/OTP versions (`elixir -version`): 
Erlang/OTP 21 [erts-10.0.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.8.1 (compiled with Erlang/OTP 20)

* Operating System: 
Ubuntu 18.04

* Chain
Ethereum Mainnet

* Blockscout indexer memory
memory_limit: 22 <<< 30

**Comment by vbaranov** [comment]
Try to increase it. For example, for ETH Mainnet it is 42 Gb configured
https://github.com/poanetwork/blockscout/blob/04d692ecda1f6b455660665230aed28a66417a58/apps/indexer/config/config.exs#L37

**Comment by ysbae0928** [comment]
@vbaranov
We tested it by changing the options, but the same thing happens. An error occurs with the same message.

eheap_alloc: Cannot allocate 16925484064 bytes of memory (of type "heap").
