### ISSUE TITLE
Information missing

### ISSUE THREAD

**Issue by rjl493456442** [poanetwork/blockscout#2309]
A few fields are missing:

1. `Average block time`
2. `Price chart`

![image](https://user-images.githubusercontent.com/5959481/60786351-ddc7e500-a188-11e9-8529-aa54a02b6c13.png)

**Comment by vbaranov** [comment]
Price chart is updating once in 6 hours. It is configured here:
https://github.com/poanetwork/blockscout/blob/8bcb31912b1dc700d2b6e7ba4e915ded30e44c9e/apps/explorer/lib/explorer/market/market_history_cache.ex#L15

Calculating of average time is performed from 100 latest blocks

https://github.com/poanetwork/blockscout/blob/8bcb31912b1dc700d2b6e7ba4e915ded30e44c9e/apps/explorer/lib/explorer/counters/average_block_time.ex#L67

**Comment by rjl493456442** [comment]
@vbaranov Thanks. Do we have any env can config the `price chart`. 

Btw my average block time is still 0 after 100k blocks.

**Comment by vbaranov** [comment]
>Do we have any env can config the price chart.

Unfortunately, there is no env var to manage the frequency of price chart changes. We will take care of it. I've created an issue https://github.com/poanetwork/blockscout/issues/2343

>Btw my average block time is still 0 after 100k blocks.

Refreshing period of avg time is also hardcoded to 30 minutes
https://github.com/poanetwork/blockscout/blob/4444f15e62d2955371f9ac9941cd6527966dfa18/apps/explorer/lib/explorer/counters/average_block_time.ex#L14
We will add ability to manage this period https://github.com/poanetwork/blockscout/issues/2344

**Comment by rjl493456442** [comment]
@vbaranov Appreciate!
