### ISSUE TITLE
Auto-appending of constructor arguments on verification page

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#2338]
Constructor arguments auto-appending ~~is broken  in v2.0.x~~ or has never been implemented before. Users need to manually append constructor arguments to verification form of contract. They should be appended automatically. Let's return back this feature.

**Comment by ayrat555** [comment]
should we allow to skip constructor arguments verification?

**Comment by vbaranov** [comment]
@ayrat555 what do you mean?

**Comment by ayrat555** [comment]
@vbaranov disable contructor arguments verification
