### ISSUE TITLE
Divide API and web application

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#2364]
We should be able to launch Blockscout API endpoints separately from the web application. Perhaps, in order to have a strong logical separation, it worth to implement API endpoints as a separate Umbrella project.

**Comment by saneery** [comment]
@vbaranov I've some question
* If we run blockscout as API only instance, should we have API's docs pages there?
* If we run blockscout as WebApp only, should we hide `APIs` dropdown menu in the navbar?

**Comment by vbaranov** [comment]
@saneery 

>If we run blockscout as API only instance, should we have API's docs pages there?

yes, since it is API description, we should show it

>If we run blockscout as WebApp only, should we hide APIs dropdown menu in the navbar?

I think so

**Comment by saneery** [comment]
@vbaranov 
>> If we run blockscout as API only instance, should we have API's docs pages there?

> yes, since it is API description, we should show it

I think we could display API's doc by root path `/`, but what about footer and navbar, there're many links to WebApp?

![image](https://user-images.githubusercontent.com/11743366/61442035-7dd2fa80-a94f-11e9-84d6-26a89efb60bc.png)

**Comment by saneery** [comment]
@vbaranov
I suppost what `/api/v1/health` is should be able in both instances?
What about `/api/v1/supply` ?

**Comment by vbaranov** [comment]
>I suppose what /api/v1/health is should be able in both instances?

yes

>What about /api/v1/supply ?

do we need it for explorer application? if no, it should be only on API instance as other methods

**Comment by saneery** [comment]
@vbaranov I finished PR, could you test it locally?
