### ISSUE TITLE
Indexer.Fetcher.CoinBalance Terminating Error

### ISSUE THREAD

**Issue by ysbae0928** [poanetwork/blockscout#2372]
My Blockscout often has "Indexer.Fetcher.CoinBalance Terminating" error.How do I fix it?

2019-07-17T08:49:52.376 fetcher=coin_balance [error] Task #PID<0.12710.249> started from Indexer.Fetcher.CoinBalance terminating
** (stop) exited in: GenServer.call(#PID<0.12754.249>, {:push_back, [{<<147, 95, 147, 158, 42, 209, 208, 254, 102, 90, 244, 129, 79, 175, 114, 6, 111, 92, 216, 143>>, 7290825}, {<<147, 237, 63, 190, 33, 32, 126, 194, 232, 242, 211, 195, 222, 110, 5, 140, 183, 59, 192, 77>>, 7290818}, {<<147, 237, 63, 190, 33, 32, 126, 194, 232, 242, 211, 195, 222, 110, 5, 140, 183, 59, 192, 77>>, 7290826}, {<<147, 238, 124, 243, 21, 37, 254, 208, 212, 232, 47,83, 119, 171, 56, 210, 50, 237, 133, 116>>, 7290825}, {<<148, 62, 216, 82, 218, 219, 92, 57, 56, 236, 220, 104,131, 113, 141, 248, 20, 45, 228, 200>>, 7290822}, {<<148, 185, 66, 39, 0, 203, 55, 165, 129, 160, 151, 27, 84, 149, 213, 85, 122, 156, 160, 132>>, 7290823}, {<<148, 185, 66, 39, 0, 203, 55, 165, 129, 160, 151, 27, 84, 149, 213, 85, 122, 156, 160, 132>>, 7290825}, {<<148, 222, 26, 231, 37, 95, 91, 118, 140, 42, 97, 240, 28, 97, 5, 15,137, 37, 88, 99>>, 7290823}, {<<148, 254, 58, 217, 29, 172, 186, 142, 196, 184, 47, 86, 255, 124, 18, 33, 129, 241, 83, 93>>, 7290822}, {<<149, 57, 224, 177, 64, 33, 164, 60, 222, 65, 217, 212, 93, 195, 73, 105, 190, 156, 124, 176>>, 7290819}, {<<149, 65, 73, 201, 254, 186, 222, 81, 43, 27, 108, 86, 69, 188, 122, 173, 4, 5, 58, 88>>,7290822}, {<<149, 136, 252, 36, 169, 121, 111, 189, 135, 9, 81, 162, 205, 84, 198, 241, 242, 75, 46, 124>>, 7290822}, {<<149, 151, 224, 15, 61, 222, 237, 169, 138, 155, 189, 64, 240, 184, 7, 75, 102, 179, 153, 217>>, 7290823}, {<<149, 233, 38, 79, 170, 254, 19, 200, 221, 24, 13, 174, 38, 21, 138, 217, 83, 98, 201, 212>>, 7290825}, {<<150, 11, 35, 106, 7, 207, 18, 38, 99, 196, 48, 51, 80, 96, 154, 102, 167, 178, 136, 192>>, 7290826}, {<<150, 107, 106, 213, 116, 81, 195, 105, 206, 190, 165, 77, 158, 249, 21, 248, 204, 196, 52, 66>>, 7290820}, {<<150, 166,44, 237, 62, 183, 143, 253, 14, 4, 160, 28, 18, 165, 147, 233, 200, 237, 11, 182>>, 7290824}, {<<150, 202, 46, 78, 198, 212, 51, 214, 217, 176, 137, 10, 119, 16, 230, 158, 191, 201, 66, 82>>, 7290826}, {<<150, 250, 174, 239, 211, 218, 189, 209, 13, 190, 146, 141, 117, 136, 78, 242, 46, 193, 87, 219>>, 7290825}, {<<151, 29, 191, 74, 20, 116, 71, 73, 134, 199, 209, 115, 118, 16, 128, 145, 136, 249, 6, 127>>, 7290820}, {<<151, 29, 191, 74, 20, 116, 71, 73, 134, 199, 209, 115, 118, 16, 128, 145, 136, 249, 6, 127>>, 7290824}, {<<151, 29, 191, 74, 20, 116, 71, 73, 134, 199, 209, 115, 118, 16, 128, 145, 136, 249, 6, 127>>, 7290825}, {<<151, 32, 180, 103, 167, 16, 56, 42, 35, 42, 50, 245, 64, 189, 206, 215, 214, 98, 161, 11>>, 7290823}, {<<151, 69, 3, 217, 107, 140, 110, 123, 80, 27, 89, 148, 174, 223, 246, 238, 53, 251, 4, 175>>, 7290826}, {<<151, 73, 198, 22, 231, 13, 168, 250, 215, 76, 74, 178, 125, 104, 150, 199, 207, 151, 141, 150>>, 7290819}, {<<151, 74, 189, 49, 130, 57, 215, 254, 164, 120, 168, 228, 210, 117, 73, 200, 70, 14, 37, 224>>, 7290824}, {<<151, 99, 149, 58, 186, 86, 94, 137, 20, 92, 76, 175, 7, 159, 203, 45, 252, 239, 32, 72>>, 7290818}, {<<151, 100, 37, 205, 122, 230, 16, 33, 150, 200, 105, 13, 177, 208, 103, 130, 58, 137, 229, ...>>, 7290824}, {<<151, 126, 144, 150, 205, 101, 248, 171, 63, 16, 213, 213, 46, 41, 236, 245, 8, 62, ...>>, 7290825}, {<<151, 127, 72, 142, 246, 222, 146, 139, 161, 119, 80, 131, 132, 204, 240, 253, 64, ...>>, 7290821}, {<<151, 128, 208, 162, 19, 153, 252, 52, 6, 84, 96, 103, 18, 8, 238, 105, ...>>, 7290825}, {<<152, 98, 208, 116, 227, 48, 3, 114, 111, 160, 92, 116, 240, 20, 41, ...>>, 7290824}, {<<152, 216, 209, 70, 230, 68, 23, 28, 212, 127, 248, 88, 137, 135, ...>>, 7290822}, {<<153, 77, 59, 46, 86, 103, 100, 174, 58, 247, 131, 130, 172, ...>>, 7290818}, {<<153, 153, 153, 198, 5, 102, 224, 167, 141, 241, 127, 113, ...>>, 7290818}, {<<153, 153, 153, 198, 5, 102, 224, 167, 141, 241, 127, ...>>, 7290822}, {<<153, 153, 153, 198, 5, 102, 224, 167, 141, 241, ...>>, 7290824}, {<<153, 153, 153, 198, 5, 102, 224, 167, 141, ...>>, 7290825}, {<<153, 234, 77, 185, 238, 119, 172, 212, ...>>, 7290821}, {<<153, 254, 93, 99, 131, 40, 156, ...>>, 7290819}, {<<153, 254, 93, 99, 131, 40, ...>>, 7290821}, {<<154, 98, 78, 174, 74, ...>>, 7290820}, {<<154, 155, 185, 237, ...>>, 7290820}, {<<154, 225, 85, ...>>, 7290825}, {<<154, 226, ...>>, 7290818}, {<<154, ...>>, 7290820}, {<<...>>, ...}, {...}, ...]}, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:989: GenServer.call/3
    (indexer) lib/indexer/buffered_task.ex:361: anonymous fn/4 in Indexer.BufferedTask.do_initial_stream/1
    (elixir) lib/enum.ex:3015: anonymous fn/3 in Enum.reduce/3
    (elixir) lib/stream.ex:1556: anonymous fn/3 in Enumerable.Stream.reduce/3
    (elixir) lib/enum.ex:3317: Enumerable.List.reduce/3
    (elixir) lib/stream.ex:911: Stream.do_list_transform/7
    (elixir) lib/stream.ex:1568: Enumerable.Stream.do_each/4
    (elixir) lib/enum.ex:3015: Enum.reduce/3
    (ecto_sql) lib/ecto/adapters/sql.ex:814: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection) lib/db_connection.ex:1349: DBConnection.run_transaction/4
    (indexer) lib/indexer/fetcher/coin_balance.ex:63: Indexer.Fetcher.CoinBalance.init/3
    (indexer) lib/indexer/buffered_task.ex:357: anonymous fn/5 in Indexer.BufferedTask.do_initial_stream/1
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<1.88830767/0 in Indexer.BufferedTask.do_initial_stream/1>
    Args: []

### Environment
* Elixir & Erlang/OTP versions (`elixir -version`): 
Erlang/OTP 21 [erts-10.0.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.8.1 (compiled with Erlang/OTP 20)

* Operating System: 
Ubuntu 18.04

* Chain
Ethereum Mainnet

**Comment by vbaranov** [comment]
@ysbae0928 you should consider increasing resources on your DB instance. The starting point of resources estimation you need to support ETH Mainnet is here https://github.com/poanetwork/blockscout/issues/2013#issuecomment-495189456
