### ISSUE TITLE
Address name overlaps `to` address in token transfer

### ISSUE THREAD

**Issue by ayrat555** [poanetwork/blockscout#2396]
![img](https://i.imgur.com/dPaqqhN.png)

Address name overlaps `to` address in token transfer when address name is too long. Also `to` address is not clickable (maybe it's a separate issue)

**Comment by vbaranov** [comment]
The page to reproduce this bug: https://blockscout.com/eth/mainnet/address/0xa5025faba6e70b84f74e9b1113e5f7f4e7f4859f/transactions

**Comment by vbaranov** [comment]
One more example https://blockscout.com/poa/xdai/address/0x7301CFA0e1756B71869E93d4e4Dca5c7d0eb0AA6/token_transfers

<img width="1092" alt="Screenshot 2020-04-21 at 11 42 29" src="https://user-images.githubusercontent.com/4341812/79845058-33424b00-83c5-11ea-813d-b7e19dcb427b.png">
