### ISSUE TITLE
Need a design for 422 page

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#2415]
https://developer.mozilla.org/ru/docs/Web/HTTP/Status/422

![Screenshot 2019-07-23 at 16 33 10](https://user-images.githubusercontent.com/4341812/61716374-a7cd5800-ad67-11e9-86c5-daf9779d53c4.png)

**Comment by pashagonchar** [comment]
@vbaranov 

zeplin - https://zpl.io/awOdnqM

![poa_422](https://user-images.githubusercontent.com/16716926/63019342-afce7280-bea3-11e9-8244-436f8059f6f1.png)

**Comment by YegorSan** [comment]
@vbaranov Hello Victor. I want to clarify one question. We can provide an update regarding this issue in a shortest terms, but I guess we need to prepare a new controller and view for 422 page. Could you help with this please? Thank you in advance.

**Comment by vbaranov** [comment]
@YegorSan please make the changes to the front-end stuff to this branch `https://github.com/poanetwork/blockscout/tree/422-page`. We will take care of the rest.

**Comment by YegorSan** [comment]
@vbaranov Ok Victor. Thank you for the clarification. Working on that issue right now.
