### ISSUE TITLE
Add ability to index blocks in the range

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#2443]
**Problem:** We previously added the ability to indicate the block from which to start index https://github.com/poanetwork/blockscout/pull/1611. However, sometimes, we need to reindex a single block or blocks in the range. It is hard to accomplish reindex with having an only left border of the range because the right border by default is the current block. And a block, that we want to reindex can be far from the current block. This is why it would be very handy to have an ability to set `LAST_BLOCK` ENV variable to reindex the chain in the range [`FIRST_BLOCK`, `LAST_BLOCK`]

**Solution:** Add `LAST_BLOCK` ENV variable

**Comment by pasqu4le** [comment]
@vbaranov I have a question on this:

AFAIU `Indexer.Block.Catchup.Fetcher` beside fetching older blocks also serves the purpose of fetching blocks that `Indexer.Block.Realtime.Fetcher` has imported without consensus/with errors.
By imposing a right limit wouldn't we lose the ability to refetch these blocks?

**Comment by vbaranov** [comment]
@pasqu4le I came to registering that issue when I was thinking how to find the way to quickly reindex a definite block, that is far from the current block. And I'd consider this reindexing in the range configuration as a temporary setup.

The use case I having in mind:
1. Temporary set the range and restart the application => chosen block/s reindexed.
2. Remove the range => return to normal configuration with the right border equal to the current block.

Could you please elaborate on how in this case it can break reindex of "lost" by `Indexer.Block.Realtime.Fetcher` blocks?

**Comment by pasqu4le** [comment]
Ok, thanks.
In this case it does not cause any problem and will keep working fine.
