### ISSUE TITLE
(Mix) Could not compile dependency :keccakf1600

### ISSUE THREAD

**Issue by hadv** [poanetwork/blockscout#2447]
It happen again on `v2.0.2-beta` when build docker image along with **postgresql**

https://github.com/hadv/blockscout/blob/testnet-nexty/Dockerfile

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): `bitwalker/alpine-elixir-phoenix:1.9.0`
* Operating System: `bitwalker/alpine-elixir-phoenix:1.9.0`

### Steps to reproduce

- building docker image

### Actual behaviour

```
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lerl_interface
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lei

** (Mix) Could not compile dependency :keccakf1600, "/opt/mix/rebar3 bare compile --paths="/opt/app/_build/prod/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile keccakf1600", update it with "mix deps.update keccakf1600" or clean it with "mix deps.clean keccakf1600"
```

**Comment by tlxnithin** [comment]
Facing the same issue. Any update or suggestion to overcome this??

**Comment by chainsulting** [comment]
Did you follow the install guide for your OS ?
https://elixir-lang.org/install.html 

Ubuntu 14.04/16.04/17.04/18.04/19.04 or Debian 7/8/9
Add Erlang Solutions repo: `wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb && sudo dpkg -i erlang-solutions_1.0_all.deb`
Run: `sudo apt-get update`
Install the Erlang/OTP platform and all of its applications: `sudo apt-get install esl-erlang`
Install Elixir: `sudo apt-get install elixir`

**Comment by hadv** [comment]
@chainsulting we face the problem when building the docker along with posgressql, blockscout alone is not the problem

**Comment by hadv** [comment]
It'd better to separate the postgresql like in https://github.com/poanetwork/blockscout/blob/master/docker/Makefile
