### ISSUE TITLE
Dark theme UI bugs

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#2451]
![Screenshot 2019-07-26 at 17 19 31](https://user-images.githubusercontent.com/4341812/61958273-b5821800-afc9-11e9-869c-429cafc818d2.png)

**Comment by vbaranov** [comment]
![Screenshot 2019-07-26 at 17 23 28](https://user-images.githubusercontent.com/4341812/61958501-24f80780-afca-11e9-893b-257033a87424.png)

**Comment by vbaranov** [comment]
![Screenshot 2019-07-26 at 17 24 24](https://user-images.githubusercontent.com/4341812/61958574-435e0300-afca-11e9-8e77-7f0ad511516c.png)

**Comment by vbaranov** [comment]
https://blockscout.com/poa/dai/address/0x7301cfa0e1756b71869e93d4e4dca5c7d0eb0aa6/logs:

<img width="1179" alt="Screenshot 2019-07-26 at 21 35 16" src="https://user-images.githubusercontent.com/4341812/61973703-58985900-afed-11e9-8cf6-219f79a567a4.png">

**Comment by maxgrapps** [comment]
@vbaranov resolved by pr https://github.com/poanetwork/blockscout/pull/2463 can I mark it as resolved?

**Comment by vbaranov** [comment]
@maxgrapps I found one more issue with dark mode:
![Screenshot 2019-08-06 at 20 04 04](https://user-images.githubusercontent.com/4341812/62560315-73888a00-b885-11e9-8ede-50d20ec7f95e.png)

**Comment by vbaranov** [comment]
And more:
![Screenshot 2019-08-06 at 20 05 57](https://user-images.githubusercontent.com/4341812/62560493-c9f5c880-b885-11e9-83ae-5ae95ea28b54.png)


You can repeat those issues, for instance, here with dark mode enabled: https://blockscout.com/poa/sokol/address/0x4e20226355b4464cf8f3b67fc318b753a7c125b3/transactions and your previous PR doesn't cover these issues
