### ISSUE TITLE
Both RPC menu items are chosen

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#2466]
Both RPC menu items are chosen if I am on `./api_docs` page

![Screenshot 2019-07-30 at 11 17 41](https://user-images.githubusercontent.com/4341812/62112614-b5309800-b2bb-11e9-93c1-a2203fa8a139.png)

**Comment by maxgrapps** [comment]
@vbaranov maybe there is something wrong with eex logic for active class? it's similar for both nav items...
<img width="619" alt="Screen Shot 2019-08-05 at 18 31 52" src="https://user-images.githubusercontent.com/50101080/62476273-53869700-b7af-11e9-9096-772f5ac1c000.png">
