### ISSUE TITLE
Reindexing in the blocks range in Geth-driven chains

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#2469]
Reindexing in the blocks range from Parity archive node can be done with using of `FIRST_BLOCK` https://github.com/poanetwork/blockscout/pull/1611, `LAST_BLOCK` https://github.com/poanetwork/blockscout/pull/2458 env vars. Let's migrate the same functionality to Geth-driven chains

**Comment by ayrat555** [comment]
I am checking Geth range indexing. It works fine for me for Goerli. Can you please check one more time?
