### ISSUE TITLE
token name gets out of boundaries

### ISSUE THREAD

**Issue by ayrat555** [poanetwork/blockscout#2474]
if a token name is too large it gets out of boundaries

![img](https://i.imgur.com/yw62Wf6.png)

**Comment by vbaranov** [comment]
Let's crop Token ID value with `...` in the middle if it is too big

**Comment by maxgrapps** [comment]
@vbaranov this issue was fixed in https://github.com/poanetwork/blockscout/pull/2463 in the file apps/block_scout_web/lib/block_scout_web/templates/transaction/_token_transfer.html.eex Can I mark it as resolved?

**Comment by vbaranov** [comment]
@maxgrapps the issue has not been solved

It looks like this now:

![Screenshot 2019-08-06 at 21 55 20](https://user-images.githubusercontent.com/4341812/62567965-f402b700-b894-11e9-9d9e-a96291f170ca.png)

But I meant
>Let's crop Token ID value with ... in the middle if it is too big

something like this: `TokenID [94108918001...810105644]`

Example of ERC-721 token: `/address/0xfac7bea255a6990f749363002136af6556b31e04/transactions`

**Comment by maxgrapps** [comment]
@vbaranov I created new branch from my master for this issue, when I clone it and run "mix do deps.get, local.rebar --force, deps.compile, compile" there is an error:
<img width="619" alt="Screen Shot 2019-08-07 at 20 15 45" src="https://user-images.githubusercontent.com/50101080/62643280-481ea180-b950-11e9-9e02-f407db23e65d.png">

Can you help me, please. Why this happens?

**Comment by vbaranov** [comment]
@maxgrapps please get upstream from the master branch. Just updated it to fix this error.
