### ISSUE TITLE
getblockreward api return something wrong

### ISSUE THREAD

**Issue by ellis2323** [poanetwork/blockscout#2489]
I try to use the getblock with getblockreward API. When i use the online API, it returns an error (on mainnet, poacore and anyelse network).
I try the API with curl and node with the same result: something got wrong. Just try this url
`
https://blockscout.com/eth/mainnet/api?module=block&action=getblockreward&blockno=8
`

**Comment by ayrat555** [comment]
It looks like `emission_rewards` table is always empty. that's why the endpoint always fails. Digging into the issue it seems the feature is not finished
https://github.com/poanetwork/blockscout/pull/223:
```Block rewards have a static reward given to the miner of the block. This static reward can vary through the life of chain. Explorer.Chain.BlockReward was added to represent this value. Since each chain can have different reward values, we will need some sort of admin configuration panel to update this values or set it initially in a wizard. Additionally, uncles are part of the reward calculation. Since POA doesn't support uncles, we'll need to go back and update these features to include uncles once supported.```
I'll work on it as part of this issue

@ellis2323 thanks for creating an issue
