### ISSUE TITLE
getminedblocks API endpoint doesn't work

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#2493]
https://blockscout.com/eth/mainnet/api?module=account&action=getminedblocks&address=0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5

**Comment by vbaranov** [comment]
{"status":"0","result":[],"message":"No blocks found"}

**Comment by ayrat555** [comment]
@vbaranov this issue is related to https://github.com/poanetwork/blockscout/issues/2489. there are no records in `emission_rewards` table. the query joins `blocks` with `emission_rewards`
