### ISSUE TITLE
Görli Testnet: <Signer-0x9d525E28Fe5830eE92d7Aa799c4D21590567B595-naming>

### ISSUE THREAD

**Issue by roninkaizen** [poanetwork/blockscout#2511]
account naming, not a real issue

### Environment
* Elixir Version: 1.9.0
* Erlang Version: 22
* BlockScout Version: v2.0.2-beta

* User Agent: `Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0`

### Actual Behaviour

no real issue,
0x9d525E28Fe5830eE92d7Aa799c4D21590567B595
is me, roninkaizen ;-)
as there is a second or two, i was voted as validator and i cannot change the displayed name.
shown  on following screen
https://matrix.org/_matrix/media/r0/download/matrix.org/krkAjhTfjhpGrGedCUhxEeVU
thx

ps: as there is something to be done by me, i use gitter :)

**Comment by vbaranov** [comment]
@roninkaizen 

> i was voted as validator

Has voting been carried out internally? Is there any public information on that voting? maybe @igorbarinov is aware

**Comment by vbaranov** [comment]
We interrupted to host Goerli instance https://twitter.com/blockscoutcom/status/1186270904692674560 for a while. I will close it for now.
