### ISSUE TITLE
Loader is not removed on loading error

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#2513]
https://blockscout.com/poa/sokol/address/0x4e20226355b4464cf8f3b67fc318b753a7c125b3/transactions

![Screenshot 2019-08-06 at 20 09 53](https://user-images.githubusercontent.com/4341812/62560647-2eb12300-b886-11e9-93fb-b355076e634d.png)

**Comment by saneery** [comment]
@vbaranov It should look like this?
![image](https://user-images.githubusercontent.com/11743366/62623013-725c6900-b928-11e9-85cb-631bcb3593db.png)

**Comment by vbaranov** [comment]
@saneery, yes, I suppose, we should hide when the error returned and show it again if we clicked to the error.
