### ISSUE TITLE
Broken view for long contract names

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#2527]
https://blockscout.com/poa/sokol/address/0x72a3b6f5d5a6b8204ee7202d1d9d967ed0489ca9/contracts

![Screenshot 2019-08-08 at 11 57 25](https://user-images.githubusercontent.com/4341812/62689559-b6f10e80-b9d3-11e9-975b-aa337f73fc25.png)

**Comment by vbaranov** [comment]
The same for transaction/internal transaction tile:

![Screenshot 2019-08-08 at 12 07 48](https://user-images.githubusercontent.com/4341812/62690310-2ca9aa00-b9d5-11e9-8cd2-df30f7780162.png)

**Comment by YegorSan** [comment]
@vbaranov Hello Victor. I think this issue should be fixed by simply adding truncation for string from backend side. As I've checked elixir solution for this issue is **slice** method. ( String.slice(0..29) )
