### ISSUE TITLE
Wrong alignment in logs entry

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#2533]
![Screenshot 2019-08-09 at 12 06 01](https://user-images.githubusercontent.com/4341812/62768008-93df6100-ba9e-11e9-9b7a-67f5f4c10b89.png)

https://blockscout.com/eth/mainnet/tx/0x3fe073df958d46e852cf264ff73d45b2dda7ceb5f140be3886f7763c3a84cccc/logs

**Comment by YegorSan** [comment]
@vbaranov Hello Victor. I suppose this issue can be closed as I have already prepared fix, and you merged a branch with the update related to it.
