### ISSUE TITLE
Unnecessary short address on token -> transfer page

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#2536]
https://blockscout.com/eth/mainnet/address/0x3468706ae1f5ffb660601aacfb7f8fe60b166ea2/tokens/0x4f4a591dfa6bb5ca83f996195654cf7fddd43433/token_transfers

![Screenshot 2019-08-09 at 13 15 49](https://user-images.githubusercontent.com/4341812/62772312-e1140080-baa7-11e9-9712-72de0ad7088c.png)

**Comment by vbaranov** [comment]
`/address/0x3468706ae1f5ffb660601aacfb7f8fe60b166ea2/tokens`

![Screenshot 2019-08-09 at 13 29 03](https://user-images.githubusercontent.com/4341812/62772998-b1fe8e80-baa9-11e9-81bb-c468ab00bac5.png)

**Comment by YegorSan** [comment]
@vbaranov Hello Victor. I am sure this issue should be checked from backend side as truncation added in one of the actions in .ex files. I may be wrong, but correct action can be found in helpers.ex file : 

defp contract_address_hash_truncated(address_hash) do
    address_hash
    |> to_string()
    |> String.slice(0..6)
  end

**Comment by vbaranov** [comment]
Fresh examples:
https://blockscout.com/poa/xdai/address/0xC2B0673C03307A7079A16D188C53E60aF8Ed3eA0/internal-transactions
https://blockscout.com/poa/xdai/address/0xA1df63107F0d858aaC2D618f5A32e4e103aE3C4c/tokens/0xC2B0673C03307A7079A16D188C53E60aF8Ed3eA0/token-transfers
https://blockscout.com/poa/xdai/address/0xA1df63107F0d858aaC2D618f5A32e4e103aE3C4c/tokens
