### ISSUE TITLE
ERC-721 token instance page

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#2541]
A part of https://github.com/poanetwork/blockscout/issues/463

Add ERC-721 token instance page.

Use case:

- A user clicks to the id of NFT-token (from token transfer tile, token transfer summary or wherever else)
- ERC-721 token instance page opens similar to ERC-721 page with some changes:

![Screenshot 2019-08-09 at 14 30 29](https://user-images.githubusercontent.com/4341812/62776576-a021e900-bab3-11e9-9828-0b7abf4939d7.png)

*Note*: NFT image should be getting from `tokenURI` contract method https://github.com/ethereum/EIPs/blob/master/EIPS/eip-721.md

While the asset is loading we should show a stub image.

@pashagonchar please take a look form a design perspective. Also, I suppose we need a stub image.

**Comment by vbaranov** [comment]
@ayrat555 let's also add *Metadata* tab to token instance page in order to show a raw JSON, that is behind URI from *tokenURI* getter

**Comment by vbaranov** [comment]
@ayrat555 please also make sure that solution, that shows metadata and icon, supports *CryptoKitties* token (`0x06012c8cf97bead5deae237070f9587f8e7a266d`). It has different from a current standard of ERC-721 token getter to retrieve metadata

**Comment by vbaranov** [comment]
@pashagonchar should we change anything?

![instance11](https://user-images.githubusercontent.com/4341812/65027151-7fff0880-d942-11e9-9a76-35a694a45dfc.png)

**Comment by ayrat555** [comment]
One more example
![car_ins](https://user-images.githubusercontent.com/6567687/65030381-1aae1600-d948-11e9-8190-27debc2ebe48.png)

**Comment by pashagonchar** [comment]
@ayrat555
zeplin:

https://zpl.io/bJ1mj8J
https://zpl.io/aBZxenm
https://zpl.io/b6BzOeR
https://zpl.io/2ZXEvPd

![erc721_1](https://user-images.githubusercontent.com/16716926/65223193-4f95a680-dac9-11e9-8f87-f5687ddb9bcd.png)

![erc721_](https://user-images.githubusercontent.com/16716926/65223365-bb780f00-dac9-11e9-8947-44a838f7255a.png)

![erc721_dark_empty](https://user-images.githubusercontent.com/16716926/65223367-bb780f00-dac9-11e9-968f-2b18707d3e40.png)

![erc721_dark](https://user-images.githubusercontent.com/16716926/65223368-bc10a580-dac9-11e9-85c2-0b442c6630d2.png)

![erc721_empty](https://user-images.githubusercontent.com/16716926/65223369-bc10a580-dac9-11e9-8112-dc5f283c152e.png)
