### ISSUE TITLE
genesis blocks have wrong timestamp

### ISSUE THREAD

**Issue by ayrat555** [poanetwork/blockscout#2546]
all genesis blocks have the wrong timestamp of `January-01-1970 03:00:00 AM +3 UTC`

https://blockscout.com/poa/core/blocks/0/transactions
https://blockscout.com/eth/mainnet/blocks/0/transactions

https://github.com/poanetwork/blockscout/pull/2499#issuecomment-519982195

**Comment by ayrat555** [comment]
it looks like `"timestamp"` field is not set for genesis block in parity chain spec

**Comment by vbaranov** [comment]
All instances updated with the correct genesis block timestamp
