### ISSUE TITLE
Make an option to fetch an arbitrary block

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#2578]
**Problem**: BS provides an option to index in the range of blocks but it implies that block is already in Blockscout DB. That may be a problem when a user wants to get locally a block, that is far from the latest block. Because of catchup fetcher will consistently go from the latest to target block and it can take a lot of time.

**Solution**: Provide an ability to fetch an arbitrary block for testing purposes. It will speedup of testing updates on specific blocks

**Comment by ayrat555** [comment]
Initially I thought the issue requires to refetch blocks that already in the database refetching all their associations (transactions, internal transactions etc) without modifying db by hand but reading the issue one more time
```
 BS  provides an option to index in the range of blocks but it implies that block is already in Blockscout DB
```
Actually no, you can set env vars to fetch blocks that are not in the database. So should we close this issue?

**Comment by vbaranov** [comment]
@ayrat555 yes, indeed, it works: block is fetched and then indexed. Thanks for the clarification. Apparently, I tested this feature while creating this issue with a block that couldn't be processed by other reasons: due to node request timeout. I am closing this issue.
