### ISSUE TITLE
CoinMarketCap API is Deprecated

### ISSUE THREAD

**Issue by ajhodges** [poanetwork/blockscout#2579]
Related to #234 (was not properly addressed).

The CMC 'ticker' endpoint that blockscout currently polls (`Explorer.ExchangeRates.Source.CoinMarketCap`) uses a deprecated API. See the warning posted here: https://api.coinmarketcap.com/

> WARNING: This API is now deprecated and will be taken offline soon. Please switch to the new CoinMarketCap API to avoid interruptions in service. (https://pro.coinmarketcap.com/migrate/)

It looks like the CMC API will now require an API key. Here is the documentation for the new API: https://coinmarketcap.com/api/documentation/v1/

And the endpoint will now be: https://pro-api.coinmarketcap.com/v1/

**Comment by vbaranov** [comment]
Thank you for heads up. We will consider exchange rate API update.
