### ISSUE TITLE
Contract Verification requires solc to be installed

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#258]
`solc` will need to be built on deployment. I'll test deployment once #182 is merged.

**Comment by vbaranov** [comment]
Since https://github.com/poanetwork/blockscout/pull/1881 has been implemented, Blockscout download solc compiler on demand if it doesn't exist in `./apps/explorer/priv/solc_compilers/`. Otherwise, downloaded previously compiler is used.
