### ISSUE TITLE
Getting transactions by address returns 504

### ISSUE THREAD

**Issue by akolotov** [poanetwork/blockscout#2582]
Several times tried to get transactions by an address through the GET request:

```
https://blockscout.com/eth/mainnet/api?module=account&action=txlist&address=0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359&filterby=to&starttimestamp=1565290140
```

It returns the error 504:
![image](https://user-images.githubusercontent.com/20793260/63127194-66247b80-bfba-11e9-8251-0ce8b6727d4a.png)

**Comment by vbaranov** [comment]
The fix deployed to the Blckscout ETH Mainnet instance
