### ISSUE TITLE
Contract verification failed when using compiler v0.5.11+commit.c082d0b4

### ISSUE THREAD

**Issue by zulhfreelancer** [poanetwork/blockscout#2584]
I have a [verified contract on Goerli Etherscan](https://goerli.etherscan.io/address/0x8b406b4708a45f115347fc2d020735196f994c5f#code) and it was deployed using the following settings:

- Compiler version: v0.5.11+commit.c082d0b4
- Contract name: FixedSupplyToken
- Optimization: No
- Runs: 200
- Evm version: Byzantium

When I tried to verify the same contract on [Goerli Blockscout](https://blockscout.com/eth/goerli/address/0x8b406b4708a45f115347fc2d020735196f994c5f/contract_verifications/new), I got _Bytecode does not match, please try again_ error.

### Environment

N/A

### Steps to reproduce

1. Visit [contract verification page](https://blockscout.com/eth/goerli/address/0x8b406b4708a45f115347fc2d020735196f994c5f/contract_verifications/new) on Goerli Blockscout

2. Enter the following details:

- Compiler version: v0.5.11+commit.c082d0b4
- Contract name: FixedSupplyToken
- Optimization: No
- Runs: 200
- Evm version: Byzantium
- Solidity contract code: copy and paste from [Etherscan contract page](https://goerli.etherscan.io/address/0x8b406b4708a45f115347fc2d020735196f994c5f#code)
- ABI-encoded Constructor Arguments: leave blank
- Contract libraries: leave blank

3. Hit the _Verify & publish_ button

### Expected behaviour

The contract get verified successfully

### Actual behaviour

Got _Bytecode does not match, please try again_ error

### Notes

This issue might be related to https://github.com/poanetwork/blockscout/issues/2580

**Comment by vbaranov** [comment]
@zulhfreelancer update is delivered to all instances and your contract is verified now: https://blockscout.com/eth/goerli/address/0x8b406b4708a45f115347fc2d020735196f994c5f/contracts
