### ISSUE TITLE
Calling view function returns '(-32015) VM execution error' when using v0.5.10+commit.5a6ea5b1 compiler

### ISSUE THREAD

**Issue by zulhfreelancer** [poanetwork/blockscout#2609]
![image](https://user-images.githubusercontent.com/3416976/63397718-1dc3ee00-c3fe-11e9-93bb-e5aa46c3b001.png)

I have a verified [contract](https://pastebin.com/raw/cmdtA95U) on my PoA Parity based private blockchain. This contract was compiled using `v0.5.10+commit.5a6ea5b1` with no optimization.

When I clicked the _Read Contract_ tab, I saw the error above.

When I use `v0.4.26+commit.4563c3fc` compiler with no optimization, I didn't see the error. I can see the `storedData` value.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe] Elixir 1.9.1 (compiled with Erlang/OTP 21)
* Operating System: Ubuntu 16.04.6 LTS x86_64
* Blockscout Version/branch: 27dff9b

### Steps to reproduce (not-OK path)

1. Copy this [contract](https://pastebin.com/raw/cmdtA95U)
2. Deploy it to a PoA Parity based network (I'm using Remix) using `v0.5.10+commit.5a6ea5b1` with no optimization
3. Verify the contract
4. Visit the _Read Contract_ tab inside the contract page
5. You should see `(-32015) VM execution error`

### Steps to reproduce (OK path)

1. Copy this [contract](https://pastebin.com/raw/dtY6QVp7)
2. Deploy it to a PoA Parity based network (I'm using Remix) using `v0.4.26+commit.4563c3fc` with no optimization
3. Verify the contract
4. Visit the _Read Contract_ tab inside the contract page
5. You should _not_ see the `(-32015) VM execution error`

### Expected behaviour

I'm expecting no errors. I'm expecting something like this:

![image](https://user-images.githubusercontent.com/3416976/63398257-95dee380-c3ff-11e9-846c-73d77faf8ec3.png)

### Actual behaviour

![image](https://user-images.githubusercontent.com/3416976/63397718-1dc3ee00-c3fe-11e9-93bb-e5aa46c3b001.png)

**Comment by ayrat555** [comment]
@zulhfreelancer What hardfork is your chain on?

**Comment by zulhfreelancer** [comment]
@ayrat555 how to check?

**Comment by ayrat555** [comment]
by the version of Parity I think

**Comment by zulhfreelancer** [comment]
Thanks @ayrat555. I'm using Parity v2.5.6-stable.

**Comment by ayrat555** [comment]
it's not a blocksout's issue. I see a lot of issues in parity repo similar to yours.
https://github.com/paritytech/parity-ethereum/issues/10502
https://github.com/paritytech/parity-ethereum/issues/10959

**Comment by zulhfreelancer** [comment]
Thanks for the links @ayrat555. But I'm not really here what I need to do here. Please help.

**Comment by zulhfreelancer** [comment]
Fixed after I added few more lines inside my _spec.json_ file:

```
---
ORIGINAL
---
"gasLimitBoundDivisor": "0x400",
"maximumExtraDataSize": "0x20",
"minGasLimit": "0x1388",
"networkID": "0x1111",
"eip155Transition": 0,
"validateChainIdTransition": 0,
"eip140Transition": 0,
"eip211Transition": 0,
"eip214Transition": 0,
"eip658Transition": 0

---
ADDED
---
"eip150Transition": "0x0",
"eip160Transition": "0x0",
"eip161abcTransition": "0x0",
"eip161dTransition": "0x0",
"eip98Transition": "0x7fffffffffffff",
"maxCodeSize": 24576,
"maxCodeSizeTransition": "0x0",
"eip145Transition": "0x0",
"eip1014Transition": "0x0",
"eip1052Transition": "0x0",
"wasmActivationTransition": "0x0"
```
