### ISSUE TITLE
Wrong color of validator address tooltip on xDai chain

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#2622]
https://blockscout.com/poa/dai/blocks/5406414/transactions

<img width="452" alt="Screenshot 2019-08-24 at 18 55 02" src="https://user-images.githubusercontent.com/4341812/63639805-cf824980-c6a0-11e9-8c2a-f1ad78ff681d.png">

**Comment by YegorSan** [comment]
This task is related to the following issue : #1771

Was already resolved by adding a new custom white tooltip for validator address on Block Details page in the following PR :  #2625
