### ISSUE TITLE
Görli Testnet: Duplicate Token Transfer Events

### ISSUE THREAD

**Issue by davesque** [poanetwork/blockscout#2627]
I was poking around on Goerli and I found a transaction that reports different token transfer events on Blockscout and Etherscan: https://blockscout.com/eth/goerli/tx/0x543f1e1838cba637d9604abfe6546b7d9cdf0d3a1d161a292641baad19a270a2/token_transfers

The above transaction (I believe) should only be showing one transfer event as is reported by Etherscan.  However, on Blockscout, there are two.  Not sure what's causing this because the transaction input data shows that the `burn(uint256 _value)` method is being called with `_value = 10000` and I think that should only result in a single transfer event to `0x00...`.

### Environment

* Elixir Version: 1.9.1
* Erlang Version: 22
* BlockScout Version: v2.0.3-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko/20100101 Firefox/68.0`

### Expected Behaviour

Only one transfer event should be reported as seen here: https://goerli.etherscan.io/tx/0x543f1e1838cba637d9604abfe6546b7d9cdf0d3a1d161a292641baad19a270a2

### Actual Behaviour

Two transfer events are being reported as seen here: https://blockscout.com/eth/goerli/tx/0x543f1e1838cba637d9604abfe6546b7d9cdf0d3a1d161a292641baad19a270a2/token_transfers

**Comment by ayrat555** [comment]
I found a reorganization - https://blockscout.com/eth/goerli/blocks/0xcd0e1f4eb3259dcbb376cb272f1669e5ebe9013f191f97a400ff7e60c09bf0a0/transactions.
I that's caused an issue. I'll work on a fix

**Comment by vbaranov** [comment]
@davesque thanks for posting this problem. You're correct - it should be only one transfer in this tx. Thanks to this issue, we found other duplicates in the Goerli Blockscout DB. We have eliminated all these inconsistencies.

**Comment by SurenFTN** [comment]
@vbaranov I have Same issue while checking on the new frontend its showing one token transfer while on old Ui its duplicated backend is same for both actual porblem is while trying to download CSV its showing duplicate values. I have tried to force update the blocks with this trx but problem remains 
trx -0xfa83367a3ede8f54943634acf27bcb5e3d4fd54ccb065205a72fbcbf725e7fa9
https://dep.ftnscan.com/address/0xeF680e90b8ca5b399525f072A1Fe1e7789943531/token-transfers#address-tabs
https://ftnscan.com/address/0xeF680e90b8ca5b399525f072A1Fe1e7789943531/token-transfers#address-tabs
