### ISSUE TITLE
Issue with generating csv of transactions

### ISSUE THREAD

**Issue by raoden1** [poanetwork/blockscout#2643]
The issue is with generating csv file with list of transactions.
![image](https://user-images.githubusercontent.com/8611369/63864620-025c6400-c965-11e9-8809-39f8c39f409e.png)

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System:
* Blockscout Version/branch: 

### Steps to reproduce

Go to: https://blockscout.com/etc/mainnet/address/{your_etc_wallet}/transactions
Select filter all and go to the bottom of page, click **download csv**

### Expected behaviour

After download should be the same values in columns Value and Fee as is visible on wbesiate:
![image](https://user-images.githubusercontent.com/8611369/63864833-5bc49300-c965-11e9-84ef-a2231bed6a98.png)

### Actual behaviour
But instead it is:
![image](https://user-images.githubusercontent.com/8611369/63864880-7434ad80-c965-11e9-93d9-9e48d748df08.png)

**Comment by ayrat555** [comment]
@raoden1 I took a look at some generated files. they look ok to me. The values are the same as on the website. Values in CSV are in Wei. Can you give examples of errors?

**Comment by raoden1** [comment]
@ayrat555 Thanks for that info that values are **in Wei**. I couldn't find hint about it. 
Issue solved. But I would suggest to add *Some units provided in Wei.* 
Thanks
