### ISSUE TITLE
Saving dashboard chart fetched data to local storage and rendering chart data from local storage.

### ISSUE THREAD

**Issue by YegorSan** [poanetwork/blockscout#2705]
@vbaranov 
Hello Victor. I got task to save fetched chart data to local storage, and then render it from there. So firstly we still must to fetch data remotely, then save it to local storage, and then render from local storage. Here the steps I performed in order to do this: 

**1) I've added already fetched data to local storage:**

$.getJSON(dataPath, {type: 'JSON'})
    .done(data => {
      const availableSupply = JSON.parse(data.supply_data)
      const marketHistoryData = humps.camelizeKeys(JSON.parse(data.history_data))
      **localStorage.setItem('supplyStorage', JSON.stringify(availableSupply))
      localStorage.setItem('marketStorage', JSON.stringify(marketHistoryData))**
      **var retrievedSupply = JSON.parse(localStorage.getItem('supplyStorage'))
      var retrievedMarket = JSON.parse(localStorage.getItem('marketStorage'))**
      $(el).show()
      chart.update(**retrievedSupply, retrievedMarket**)
    })

 And as you can see chart should update from local storage now.

**2) I've added new function in order to map elements in local storage array:**

function getRetrievedMarketData(retrievedMarket, retrievedSupply) {
      var retrievedSupply = JSON.parse(localStorage.getItem('supplyStorage'))
      var retrievedMarket = JSON.parse(localStorage.getItem('marketStorage'))
  if (retrievedSupply !== null && typeof retrievedSupply === 'object') {
    return retrievedMarket.map(({ date, closingPrice }) => ({x: date, y: closingPrice * retrievedSupply[date]}))
  } else {
    return retrievedMarket.map(({ date, closingPrice }) => ({x: date, y: closingPrice * retrievedSupply}))
  }
}

**3) In chart constructor class update method I've added new values for rendered data:**

update (availableSupply, marketHistoryData) {
    this.price.data = getPriceData(marketHistoryData)
    if (this.availableSupply !== null && typeof this.availableSupply === 'object') {
      const today = new Date().toJSON().slice(0, 10)
      this.availableSupply[today] = availableSupply
      **var retrievedSupply = JSON.parse(localStorage.getItem('supplyStorage'))
      var retrievedMarket = JSON.parse(localStorage.getItem('marketStorage'))**
      **this.marketCap.data = getRetrievedMarketData(retrievedMarket, this.retrievedSupply)**
    } else {
      **this.marketCap.data = getRetrievedMarketData(retrievedMarket, retrievedSupply)**
    }
    this.chart.update()
  }

I've tested , and checked if data loaded from local storage, added to constructor class return statement for local storage data without map method, and received the first element of local storage array, but still - it took several seconds to render data. 

### Expected behaviour

Expected fast loading of chart data.

### Actual behaviour

Actually nothing happens, chart loading didn't speed up.

**Comment by vbaranov** [comment]
@YegorSan but the chart points should appear immediately (from local storage) if I open the main page on the same day second time and further, right? If yes, please make a PR to touch it.
