### ISSUE TITLE
Verification of contracts with sourcify utility

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#2713]
Verify deployed contract with `source-verify` tool:
- contract address (, metadata, source code) as an input. Later metadata/source code will be retrieved from Swarm
- it downloads compiler of the right version (retrieved from metadata), compiles the source code, checks the generated bytecode w/ that one, deployed to the blockchain.

Blockscout can benefit from using of `source-verify` by:
1. providing decentralized verification of smart-contracts
2. using of parsed NatSpec user comments in `Read contract` page

Source code of the verifier: https://github.com/ethereum/source-verify/blob/master/verify.js

Inspired by https://twitter.com/ethchris/status/1172532788559523840

**Comment by chriseth** [comment]
We recently published a similar tool that can help with contract verification, especially of multi-file contracts: https://www.npmjs.com/package/@ethereum-sourcify/validation

You can pass it either a zip-file containing the full project tree or a directory to the project tree. This directory needs to contain a build folder with the metadata files (truffle and buidler should work). The output of the script is a json file per contract that contains all sources and can be fed to the Solidity compiler.

The idea is that the complicated verification form is reduced to a simple file upload where you do not have to specify any of the settings.

**Comment by vbaranov** [comment]
Integration with Sourcify implemented at xDai instance.
