### ISSUE TITLE
Balance shows 0 if only incoming transaction is internal transaction

### ISSUE THREAD

**Issue by ligi** [poanetwork/blockscout#2715]
I see the internat tx in the tx list - but the balance shows as 0

**Comment by vbaranov** [comment]
@ligicould could you please give us an example page where do you see 0 balance? Am I correct that you see a single incoming tx on the address but the balance of it is 0 whereas you expect to see non-zero balance?

**Comment by ligi** [comment]
Unfortunately I cannot share the address as I need to protect the privacy of one of my user here (will ask him if he is OK with sharing the address though)
But yes there is exactly one internal incoming tx which is >0ETH - but the balance is 0ETH
![image](https://user-images.githubusercontent.com/111600/65253751-779dfd80-dafb-11e9-8795-b305d9c8e873.png)

**Comment by ligi** [comment]
also the balance shows correctly on etherchain.org - https://etherscan.io and https://blockchair.com

**Comment by vbaranov** [comment]
@ligi could you please ask your user to check if the problem eliminated? We installed an update to ETH Mainnet instance https://github.com/poanetwork/blockscout/pull/2696. Possibly, it is a culprit of the issue.

**Comment by ligi** [comment]
yes - seems to be solved now - closing
