### ISSUE TITLE
Blockscout optimization tips. 

### ISSUE THREAD

**Issue by YegorSan** [poanetwork/blockscout#2716]
@vbaranov 

I've got a task to make an audit of Blockscout app, and provide some optimization tips. I've tested website with a multiple speed and optimization checking tools, as well as checked how website loads from different countries.

Here are some most necessary steps which can be performed in order to reduce loading speed : 

1) **Enable gzip compression on server side**  -  https://varvy.com/pagespeed/enable-compression.html
**You can check the expected result via** - https://varvy.com/tools/gzip/
I am almost sure this procedure should increase page loading speed. 

2) **Avoid URL redirects**   -    https://www.giftofspeed.com/avoid-redirects/
 
We need to reduce amount of redirects (**if it's acceptable for sure**).

3) **Add Expires headers**   -   Expires Headers tell the web browser how long to store a file in the cache. Keeping the files in the cache of your computer means on future visits to that page the browser will not need to download the file again. Expires Headers don’t improve page speed for a first visit, after all you need to have downloaded the files at least once to reference them again. But for return visitors, page load times will be faster.
**Additional info:**
https://www.seeme-media.com/add-expires-headers-to-your-htaccess-file/

**There are 7 static components without a far-future expiration date:**
https://ajax.cloudflare.com/cdn-cgi/scripts/95c75768/cloudflare-static/rocket-loader.min.js
https://blockscout.com/poa/core/css/awesomplete.css
https://blockscout.com/poa/core/css/non-critical.css
https://fonts.googleapis.com/css?family=Nunito:200,300,400,600,700
https://fonts.googleapis.com/css?family=Roboto
https://blockscout.com/poa/core/js/awesomplete-util.min.js
https://blockscout.com/poa/core/js/awesomplete.min.js

https://blockscout.matomo.cloud/piwik.js  getting 403 error in console.

According to GTMetrix and Google Page Speed test results, mentioned above issues are mostly affecting page loading speed. 

**Here some information from MXToolbox** - https://mxtoolbox.com/domain/blockscout.com/
They suggesting to add DMARC DNS Records.

**Full GTMetrix report:** 
[GTmetrix-report-blockscout.com-20190920T030239-j8XDTbik-full.pdf](https://github.com/poanetwork/blockscout/files/3635614/GTmetrix-report-blockscout.com-20190920T030239-j8XDTbik-full.pdf)

**Full Dotcom-Tools report:**
[WaterFall_1.pdf](https://github.com/poanetwork/blockscout/files/3635624/WaterFall_1.pdf)

I've also checked page loading speed from different locations : 
Here some slowest results :  
San Francisco 3.8 sec
**Hong Kong 6.5 sec**
Frankfurt 2.9 sec
**Brisbane 9.5 sec**
Amsterdam 2.7 sec
Tel-Aviv 4.7 sec
**Buenos Aires 5.6 sec**
Tokyo 4.2 sec
Johannesburg 5.1 sec
Paris 2.5 sec
**Mumbai 9.9 sec**
Warsaw 3.4 sec
**Madrid 5.0 sec**

Here is the report of Etherscan.io website: 
[GTmetrix-report-etherscan.io-20190920T043526-MPVGtQN8-full.pdf](https://github.com/poanetwork/blockscout/files/3635687/GTmetrix-report-etherscan.io-20190920T043526-MPVGtQN8-full.pdf)
They have A(93%) score on Google Page Speed. (we have 78%)

I think firstly we should perform the mentioned above steps in order to see some positive effect, as they have a highest priority according to audit results.

**Comment by vbaranov** [comment]
<img width="434" alt="Screenshot 2020-06-05 at 20 17 11" src="https://user-images.githubusercontent.com/4341812/83904993-8e5bb180-a769-11ea-944d-8d08106bf463.png">
