### ISSUE TITLE
Split js logic into multiple files specific to concrete pages

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#2721]
## Problem
Blockscout's js logic is in a single js file (except staking dapp part). It loads synchronously significantly contributing to the page loading time.

<img width="726" alt="Screenshot 2019-09-22 at 22 36 44" src="https://user-images.githubusercontent.com/4341812/65393503-f3ad7500-dd89-11e9-98f4-7832e56bae7f.png">

## Solution

Extract the common part from the client's code logic to load on every page. And split the rest of js logic into multiple files in order to load them only on the pages where it is required. Also, consider a possibility to make some code to load asynchronously, if it is not required for page rendering. The changes should decrease the time of js code loading increasing the speed of pages opening.

**Comment by YegorSan** [comment]
@vbaranov Hello Victor. I am currently working on this problem. Will try to resolve in the shortest possible terms.
