### ISSUE TITLE
Contract image for NFT-token instance doesn't comply with themes

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#2725]
Contract image for NFT-token instance doesn't comply with non-default themes

![Screenshot 2019-09-23 at 16 27 11](https://user-images.githubusercontent.com/4341812/65435556-5f92ea80-de29-11e9-93b5-31f001c9cdb2.png)

Page example: `/tokens/0x06012c8cf97bead5deae237070f9587f8e7a266d/instance/99628/token_transfers` on stg application

whereas it looks fine with a default theme. Please, make compliance for other themes.

It is a part of https://github.com/poanetwork/blockscout/pull/2642. The fix should be made to `ab-erc-721-coin-instance-page` branch

**Comment by YegorSan** [comment]
@vbaranov Hello Victor. I think this issue can be closed as I have already prepared fix, and you  already merged a branch with the update related to it.
