### ISSUE TITLE
got "Something went wrong while publishing the contract." when use API to verify contract

### ISSUE THREAD

**Issue by gt299792** [poanetwork/blockscout#2728]
*Describe your issue here.*

### Environment
https://blockscout.com/eth/kovan
* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System:
* Blockscout Version/branch: v2.0.3-beta

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*
Use remix to deploy a contract to Kovan testnet (compiler version v0.5.4+commit.9549d8ff)
```
pragma solidity ^0.5.4;
contract Test {
    address private owner;
    string public mystring;
        constructor() public{
        mystring = "Hello, World!";
    }
    function setString(string memory x) public {
        mystring = x;
    }
}
```
The deployed contract is here: 
https://blockscout.com/eth/kovan/address/0xd6984e092b51337032cf0300c7291e4839be37e1
I try to use GET api to verify and publish this code with Postman
The url with params is below
```
https://blockscout.com/eth/kovan/api?module=contract&action=verify&addressHash=0xd6984e092b51337032cf0300c7291e4839be37e1&name=Test&compilerVersion=v0.5.4+commit.9549d8ff&optimization=false&contractSourceCode=pragma solidity ^0.5.4;
contract Test {
    address private owner;
    string public mystring;
        constructor() public{
        mystring = "Hello, World!";
    }
    function setString(string memory x) public {
        mystring = x;
    }
}
```

### Expected behaviour

*Tell us what should happen.*
Publish the contract and I can view it on website.
### Actual behaviour

*Tell us what happens instead.*
Got this error after sending
```
{
    "status": "0",
    "result": null,
    "message": "Something went wrong while publishing the contract."
}
```

**Comment by gt299792** [comment]
> 
> 
> @gt299792
> I could successfully verify it with
> 
> ```
> curl -d '{"addressHash":"0xd6984e092b51337032cf0300c7291e4839be37e1","compilerVersion":"v0.5.4+commit.9549d8ff","contractSourceCode":"pragma solidity ^0.5.4;\ncontract Test {\n    address private owner;\n    string public mystring;\n        constructor() public{\n        mystring = \"Hello, World!\";\n    }\n    function setString(string memory x) public {\n        mystring = x;\n    }\n}\n","name":"Test","optimization":false}'  -H "Content-Type: application/json" -X POST  "https://blockscout.com/eth/kovan/api?module=contract&action=verify"
> ```

I copy and paste the curl console, But I still got
{"status":"0","result":null,"message":"Something went wrong while publishing the contract."}

**Comment by gt299792** [comment]
> 
> 
> > @gt299792
> > I could successfully verify it with
> > ```
> > curl -d '{"addressHash":"0xd6984e092b51337032cf0300c7291e4839be37e1","compilerVersion":"v0.5.4+commit.9549d8ff","contractSourceCode":"pragma solidity ^0.5.4;\ncontract Test {\n    address private owner;\n    string public mystring;\n        constructor() public{\n        mystring = \"Hello, World!\";\n    }\n    function setString(string memory x) public {\n        mystring = x;\n    }\n}\n","name":"Test","optimization":false}'  -H "Content-Type: application/json" -X POST  "https://blockscout.com/eth/kovan/api?module=contract&action=verify"
> > ```
> 
> I copy and paste the curl console, But I still got
> {"status":"0","result":null,"message":"Something went wrong while publishing the contract."}

I got it! A address can be verify one time.

**Comment by gt299792** [comment]
Absolutely helpful!
I have tried to use GET for many times. But it doesn't work. 
I know from the api_docs page that I can use POST, but I don't know how to actually use it .

**Comment by vbaranov** [comment]
@gt299792 thanks for your suggestion. I've created the issue https://github.com/poanetwork/blockscout/issues/2732
