### ISSUE TITLE
Verify & publish yields "The requested path was not found" error

### ISSUE THREAD

**Issue by PaulRBerg** [poanetwork/blockscout#2741]
Contract source code cannot be verified on the xdai explorer on blockscout.

### Environment

* Operating System: macOS 10.14.6
* Brave 0.68.141 + Safari 13.0.1
* Blockscout Version/branch: the latest website version as of Sep 29, 2019

### Steps to reproduce

1. Go to [the verify & publish page of this this contract](https://blockscout.com/poa/xdai/address/0x09b6c7ea60e1e261ae8bd16dac4aae894e54cb2a/contract_verifications/new)
2. Set the name to "CTokenManager"
3. Set the compiler version to "0.5.11.c082d0b4"
4. Fill in this [source code](https://gist.github.com/PaulRBerg/b8c3cde850f2fee04a4089cebcfe6a38)
5. Set "Optimization" to "Yes"
6. Leave all other fields to their default value and hit "Verify & Publish"

### Expected behaviour

The contract source code should be verified. [It worked well on Etherscan](https://kovan.etherscan.io/address/0x2d69ad895797c880abce92437788047ba0eb7ff6#code).

### Actual behaviour

The contract source code is not verified and blockscout shows me this error page.

<img width="1680" alt="Screen Shot 2019-09-29 at 18 28 11" src="https://user-images.githubusercontent.com/8782666/65834756-e989fa00-e2e6-11e9-9841-bf9fb7f7e491.png">

**Comment by vbaranov** [comment]
@PaulRBerg thank you for the issue. It was fixed and your contract is verified: https://blockscout.com/poa/xdai/address/0x09b6c7ea60e1e261ae8bd16dac4aae894e54cb2a/contracts.

**Comment by LJ404now** [comment]
The requested path was not found on BlockScout.
