### ISSUE TITLE
internal_transactions_indexed_at is filled but internal transactions are missing

### ISSUE THREAD

**Issue by FuZuK** [poanetwork/blockscout#2743]
The field `transactions.internal_transactions_indexed_at` is filled but internal transactions are missing for the transaction `0x1f17794ca72a172e060bcc1e50dec9656c739095b35d647084f0fd00be5ef116`. Internal transactions are present in the public blockscout and etherscan:
https://blockscout.com/eth/mainnet/tx/0x1f17794ca72a172e060bcc1e50dec9656c739095b35d647084f0fd00be5ef116/internal_transactions
https://etherscan.io/tx/0x1f17794ca72a172e060bcc1e50dec9656c739095b35d647084f0fd00be5ef116
Queries & results (output format is unaligned):
```
> select hash, internal_transactions_indexed_at from transactions where hash = '\x1f17794ca72a172e060bcc1e50dec9656c739095b35d647084f0fd00be5ef116';

hash|\x1f17794ca72a172e060bcc1e50dec9656c739095b35d647084f0fd00be5ef116
internal_transactions_indexed_at|2019-09-24 10:27:32.84647
```
```
> select count(*) from internal_transactions where transaction_hash = '\x1f17794ca72a172e060bcc1e50dec9656c739095b35d647084f0fd00be5ef116';

count|0
```
Method `debug_traceTransaction` returns not empty list for this transaction:
```json5
[
  {
    "jsonrpc": "2.0",
    "id": 1,
    "result": [
      {
        "type": "call",
        "callType": "call",
        "from": "0x6aa641b2f91d4c822107cb08313922b9e912bc90",
        "to": "0x31a240648e2baf4f9f17225987f6f53fceb1699a",
        "input": "0x3971ee420000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001400000000000000000000000016e8c215102aa079eca9d5ac184c211cb20fba9900000000000000000000000016e94e2d18df20fa5c2a2a7c51006492fb8b734600000000000000000000000016e96a8bf7d6519ba2f246e794ebbad51a870bc100000000000000000000000016e9931e8b3e8cf5515b180be460bf980aad056200000000000000000000000016e9a9938d81e2d63e78b65219a0ab4a8bca649500000000000000000000000016ea1f673e01419ba9af51365b88138ac492489a00000000000000000000000016ea4702410c2854dea0d2f753a0e75cd42ba4af00000000000000000000000016eabf434ce0df1388801c6d99e50abf3c79f85200000000000000000000000016eb154cd1bb6be83f9a476cf2d549938dbe430700000000000000000000000016eb1d09fba78b94a73b30a935fc8367de97ee4700000000000000000000000016eb39afd1e559d2088406ac5e6a2d37bd50bc6a00000000000000000000000016ebfe8387b462fd182e3aeca81e925956d09d9200000000000000000000000016ec085cb9f86e12044d5fcb8c874704d3f7d74100000000000000000000000016ec11b70a190b22d2fcbc6c849ffa1e97a4609f00000000000000000000000016ec2b83210a27cd686c36e5a04b2a43f6364f2100000000000000000000000016ec672039a8515a16b3e0195068fc8630f3ed2200000000000000000000000016ec68b8697e20cfb9beb49215d463deed49082500000000000000000000000016ec701f2005986237ef280d4d50249119d25d8a00000000000000000000000016ec845a42050ac9c95e82eae38f411fd276c85a00000000000000000000000016ecdf1c6b2fca4ee9cdd1a087a67867f24f01a8",
        "output": "0x",
        "traceAddress": [],
        "value": "0x0",
        "gas": "0x3d188",
        "gasUsed": "0x2ea18"
      },
      {
        "type": "call",
        "callType": "call",
        "from": "0x31a240648e2baf4f9f17225987f6f53fceb1699a",
        "to": "0x16e8c215102aa079eca9d5ac184c211cb20fba99",
        "input": "0x",
        "output": "0x",
        "traceAddress": [
          0
        ],
        "value": "0x1cf977871",
        "gas": "0x0",
        "gasUsed": "0x0"
      },
      {
        "type": "call",
        "callType": "call",
        "from": "0x31a240648e2baf4f9f17225987f6f53fceb1699a",
        "to": "0x16e94e2d18df20fa5c2a2a7c51006492fb8b7346",
        "input": "0x",
        "output": "0x",
        "traceAddress": [
          1
        ],
        "value": "0x1cf977871",
        "gas": "0x0",
        "gasUsed": "0x0"
      },
      {
        "type": "call",
        "callType": "call",
        "from": "0x31a240648e2baf4f9f17225987f6f53fceb1699a",
        "to": "0x16e96a8bf7d6519ba2f246e794ebbad51a870bc1",
        "input": "0x",
        "output": "0x",
        "traceAddress": [
          2
        ],
        "value": "0x1cf977871",
        "gas": "0x0",
        "gasUsed": "0x0"
      },
      ...
]
```
Does anyone know the reason for this behavior? Is it related to #2694?

### Environment
* Elixir & Erlang/OTP versions (`elixir -version`):
Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:36:36] [ds:36:36:10] [async-threads:1] [hipe]
Elixir 1.9.0 (compiled with Erlang/OTP 20)
* Operating System:
Debian GNU/Linux 9.5 (stretch)
* Blockscout Version/branch: 
v2.0.4-beta
* ETH client
geth v1.9.2-stable
* geth command
`/opt/ethereum/bin/geth --config /ethereum/geth.toml --metrics --gcmode archive --syncmode full --ethash.dagdir /ethereum/.ethash --datadir /ethereum/.ethereum --maxpeers 4096 --cache 23450 --ethash.cachesinmem 1024 --txpool.accountslots 128 --txpool.accountqueue 512 --rpc --rpcport 8545 --rpcaddr 0.0.0.0 --ws --wsaddr 0.0.0.0 --rpcvhosts=* --wsorigins=* --rpcapi eth,web3,debug,txpool --graphql --graphql.addr 0.0.0.0 --graphql.port 8547 --graphql.vhosts=* --nat none --nousb --verbosity 3`

**Comment by ayrat555** [comment]
@FuZuK  this field is only used for `parity`. 
Did you set `export ETHEREUM_JSONRPC_VARIANT=geth`?
For geth internal transaction are fetched not on block level.

**Comment by FuZuK** [comment]
> @FuZuK this field is only used for `parity`.
> Did you set `export ETHEREUM_JSONRPC_VARIANT=geth`?
> For geth internal transaction are fetched not on block level.

Thank you for reply!
Yes, I set the value for this environment variable to `geth`. As I understand, you are talking about the `blocks` table, but I meant the `transactions` table.

**Comment by ayrat555** [comment]
I tried importing internal transaction for Goerli (because we're running geth node for it). Looks ok.

Can you give access to your geth node? So I can try importing internal transactions for this transaction.

**Comment by FuZuK** [comment]
> I tried importing internal transaction for Goerli (because we're running geth node for it). Looks ok.
> 
> Can you give access to your geth node? So I can try importing internal transactions for this transaction.

Sorry, but it is not possible. I believe that you have imported internal transactions for this transaction since they are also present on the public blockscout. How can I repeat the same steps as you did? Do I need to direct the indexer to the block the transaction is in?

**Comment by ayrat555** [comment]
You can try re-importing the whole block. just set `consensus=false` to the required block.

**Comment by FuZuK** [comment]
I set the value for this field to true and re-import was completed. The field `internal_transactions_indexed_at` was updated for the given transaction, but the list of internal transactions is still empty.
Btw there are many other transactions with the simillar problem.

**Comment by ayrat555** [comment]
ok. Let met sync my geth instance to this block

**Comment by ayrat555** [comment]
Unfortunately, it will take days (weeks) to sync the whole chain. It would be great if you open a port of your node.

**Comment by FuZuK** [comment]
Sorry, I cannot open the port due to the confidentiality of the project. I tried to limit indexing range by `FIRST_BLOCK` & `LAST_BLOCK` env. variables:
```bash
export FIRST_BLOCK=5417177
export LAST_BLOCK=5417188
```
After that I created empty database and started the blockscout indexer. All blocks from the specified range were imported. The value of `internal_transactions_indexed_at` was setted for the transaction 0x1f17794ca72a172e060bcc1e50dec9656c739095b35d647084f0fd00be5ef116 but list of internal transactions was empty. After that I setted the value of `internal_transactions_indexed_at` field to null and restarted the indexing process with the expectation that the process that imports internal transactions for transactions for which this field is empty will import internal transactions. And so it happened, internal transactions appeared. It turns out that for some reason internal transactions were not imported when importing the block itself.

**Comment by ayrat555** [comment]
I removed internal transactions by hand and set consensus of the block to false. and internal transactions were successfully re-fetched.

**Comment by FuZuK** [comment]
> I removed internal transactions by hand and set consensus of the block to false. and internal transactions were successfully re-fetched.

Did you do re-import for block 5417187?

**Comment by ayrat555** [comment]
No, I did it for the block Goerli

**Comment by FuZuK** [comment]
> No, I did it for the block Goerli

Can I connect to the same goerli testnet as you? Is there is any public endpoint?

**Comment by pricillapb** [comment]
how do I fix this

**Comment by pricillapb** [comment]
Yes you can

**Comment by FuZuK** [comment]
Hi @ayrat555
Could you please share connection info to your Goerli core so i can check is the will be same behavior with internal transactions?

@pricillapb Do you have any fix?

**Comment by ayrat555** [comment]
@FuZuK 
Unfortunately, it's a private node. I can't share it.

**Comment by FuZuK** [comment]
@ayrat555
Okay, but i think it should not be the problem with core. Because, as i mentioned before i manually checked information in core and also internal transactions successfully synced when i set 'internal_transactions_indexed_at' to NULL. Probebly it should be the problem with synchornization process.

**Comment by vbaranov** [comment]
@ayrat555 

Here is the transaction trace https://gist.github.com/vbaranov/985280b2f52756a103cefc3ec1419ec5 from Geth node

Could you test it against Blockscout indexer for Geth?

**Comment by ayrat555** [comment]
@vbaranov I'm on it. Thanks

**Comment by ayrat555** [comment]
@vbaranov @FuZuK We need json rpc trace attached to the description. Because we're using custom tracer
```
[
  {
    "jsonrpc": "2.0",
    "id": 1,
    "result": [
      {
        "type": "call",
        "callType": "call",
        "from": "0x6aa641b2f91d4c822107cb08313922b9e912bc90",
        "to": "0x31a240648e2baf4f9f17225987f6f53fceb1699a",
        "input": "0x3971ee420000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001400000000000000000000000016e8c215102aa079eca9d5ac184c211cb20fba9900000000000000000000000016e94e2d18df20fa5c2a2a7c51006492fb8b734600000000000000000000000016e96a8bf7d6519ba2f246e794ebbad51a870bc100000000000000000000000016e9931e8b3e8cf5515b180be460bf980aad056200000000000000000000000016e9a9938d81e2d63e78b65219a0ab4a8bca649500000000000000000000000016ea1f673e01419ba9af51365b88138ac492489a00000000000000000000000016ea4702410c2854dea0d2f753a0e75cd42ba4af00000000000000000000000016eabf434ce0df1388801c6d99e50abf3c79f85200000000000000000000000016eb154cd1bb6be83f9a476cf2d549938dbe430700000000000000000000000016eb1d09fba78b94a73b30a935fc8367de97ee4700000000000000000000000016eb39afd1e559d2088406ac5e6a2d37bd50bc6a00000000000000000000000016ebfe8387b462fd182e3aeca81e925956d09d9200000000000000000000000016ec085cb9f86e12044d5fcb8c874704d3f7d74100000000000000000000000016ec11b70a190b22d2fcbc6c849ffa1e97a4609f00000000000000000000000016ec2b83210a27cd686c36e5a04b2a43f6364f2100000000000000000000000016ec672039a8515a16b3e0195068fc8630f3ed2200000000000000000000000016ec68b8697e20cfb9beb49215d463deed49082500000000000000000000000016ec701f2005986237ef280d4d50249119d25d8a00000000000000000000000016ec845a42050ac9c95e82eae38f411fd276c85a00000000000000000000000016ecdf1c6b2fca4ee9cdd1a087a67867f24f01a8",
        "output": "0x",
        "traceAddress": [],
        "value": "0x0",
        "gas": "0x3d188",
        "gasUsed": "0x2ea18"
      },
```

**Comment by FuZuK** [comment]
> @vbaranov @FuZuK We need full JSON RPC trace attached to the description. Because we're using custom tracer
> 
> ```
> [
>   {
>     "jsonrpc": "2.0",
>     "id": 1,
>     "result": [
>       {
>         "type": "call",
>         "callType": "call",
>         "from": "0x6aa641b2f91d4c822107cb08313922b9e912bc90",
>         "to": "0x31a240648e2baf4f9f17225987f6f53fceb1699a",
>         "input": "0x3971ee420000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001400000000000000000000000016e8c215102aa079eca9d5ac184c211cb20fba9900000000000000000000000016e94e2d18df20fa5c2a2a7c51006492fb8b734600000000000000000000000016e96a8bf7d6519ba2f246e794ebbad51a870bc100000000000000000000000016e9931e8b3e8cf5515b180be460bf980aad056200000000000000000000000016e9a9938d81e2d63e78b65219a0ab4a8bca649500000000000000000000000016ea1f673e01419ba9af51365b88138ac492489a00000000000000000000000016ea4702410c2854dea0d2f753a0e75cd42ba4af00000000000000000000000016eabf434ce0df1388801c6d99e50abf3c79f85200000000000000000000000016eb154cd1bb6be83f9a476cf2d549938dbe430700000000000000000000000016eb1d09fba78b94a73b30a935fc8367de97ee4700000000000000000000000016eb39afd1e559d2088406ac5e6a2d37bd50bc6a00000000000000000000000016ebfe8387b462fd182e3aeca81e925956d09d9200000000000000000000000016ec085cb9f86e12044d5fcb8c874704d3f7d74100000000000000000000000016ec11b70a190b22d2fcbc6c849ffa1e97a4609f00000000000000000000000016ec2b83210a27cd686c36e5a04b2a43f6364f2100000000000000000000000016ec672039a8515a16b3e0195068fc8630f3ed2200000000000000000000000016ec68b8697e20cfb9beb49215d463deed49082500000000000000000000000016ec701f2005986237ef280d4d50249119d25d8a00000000000000000000000016ec845a42050ac9c95e82eae38f411fd276c85a00000000000000000000000016ecdf1c6b2fca4ee9cdd1a087a67867f24f01a8",
>         "output": "0x",
>         "traceAddress": [],
>         "value": "0x0",
>         "gas": "0x3d188",
>         "gasUsed": "0x2ea18"
>       },
> ```

Isn't that a complete trace?
https://gist.github.com/vbaranov/985280b2f52756a103cefc3ec1419ec5/raw/0721a81fb72bc38ee1cda74291b1fdbbad441d04/0x1f17794ca72a172e060bcc1e50dec9656c739095b35d647084f0fd00be5ef116.trace.json

**Comment by ayrat555** [comment]
@FuZuK @vbaranov I think I found why we're not fetching these transactions. It's because of https://github.com/poanetwork/blockscout/pull/1305.  and we have them indexed on production because PR by Luke was created after they were indexed

**Comment by FuZuK** [comment]
> @FuZuK @vbaranov I think I found why we're not fetching these transactions. It's because of #1305. and we have them indexed on production because PR by Luke was created after they were indexed

Is it a bug in the current context? I mean the transaction 0x1f17794ca72a172e060bcc1e50dec9656c739095b35d647084f0fd00be5ef116. Because etherscan has internal transactions for this transaction.

**Comment by ayrat555** [comment]
> we have them indexed on production because PR by Luke was created after they were indexed
This statement is wrong. 

On production we use parity and for parity we fetch internal transactions block by block. So we import all internal transactions for parity. As for geth we fetch internal transactions for each transaction one by one. And for token transfer transactions, we set internal_transactions_indexed_at so they're not fetched. We can make this logic optional if you want.
I'll make a PR
