### ISSUE TITLE
missing elixir in dependencies list

### ISSUE THREAD

**Issue by SCBuergel** [poanetwork/blockscout#2759]
I am running the [manual deployment](https://poanetwork.github.io/blockscout/#/manual-deployment) on latest MacOS and running into `mix: command not found` in step 6. The [requirements](https://poanetwork.github.io/blockscout/#/requirements) section of the documentation makes it seem like elixir is automatically installed via `brew install erlang` but that is not the case. In my case I needed another `brew install elixir`.

**Comment by vbaranov** [comment]
@SCBuergel we will compliment installation instruction. Thank you.

**Comment by vbaranov** [comment]
Prerequisites section has been updated: `brew install erlang` step added. https://app.gitbook.com/@poa/s/blockscout/for-developers/information-and-settings/requirements
