### ISSUE TITLE
Display wrong miner when using geth and Clique consensus

### ISSUE THREAD

**Issue by crasker** [poanetwork/blockscout#2775]
*Wrong miner when using geth and Clique consensus*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): 
Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]
Elixir 1.9.1 (compiled with Erlang/OTP 22)
* Operating System: ubuntu 18.04
* Blockscout Version/branch:  master at 1c99df345498c308b28ce45b2960cad07d25f7bd

### Steps to reproduce

*Deploy blockscout with private chain using geth and Clique consensus*

### Expected behaviour

*Real miner of the block*

### Actual behaviour

*0x000...00*

**Comment by crasker** [comment]
I think blockscout should decode the real miner from the extradata within the block in Clique chains

**Comment by hadv** [comment]
I think they already did for it https://blockscout.com/eth/rinkeby/blocks/5260218/transactions

but the source code in other branch, not in the master branch though

**Comment by crasker** [comment]
> I think they already did for it https://blockscout.com/eth/rinkeby/blocks/5260218/transactions
> 
> but the source code in other branch, not in the master branch though

thanks! looks great! I will check this branch

**Comment by crasker** [comment]
@hadv that brance not useable, still print 0x0000 in block miner

**Comment by hadv** [comment]
@crasker I not sure which branch but they must do somewhere, Rinkeby is the clique 

https://blockscout.com/eth/rinkeby/

**Comment by hadv** [comment]
might be this rinkeby production branch https://github.com/poanetwork/blockscout/tree/production-rinkeby

**Comment by crasker** [comment]
@hadv Yes this branch is used by rinkeby, but can not be used in my private Clique chain, still print 0x000..0, seems like this branch can only used by rinkeby, i am not sure.

**Comment by vbaranov** [comment]
@crasker there is a similar issue https://github.com/poanetwork/blockscout/issues/1990. Please check
https://github.com/poanetwork/blockscout/issues/1990#issuecomment-494396365
and
https://github.com/poanetwork/blockscout/issues/1990#issuecomment-497279428

**Comment by crasker** [comment]
@vbaranov #1990 fix my problem, thanks!
