### ISSUE TITLE
Issues Parsing Local Geth Client with Blockscout Makefile

### ISSUE THREAD

**Issue by YazzyYaz** [poanetwork/blockscout#2795]
I am running [MultiGeth](https://github.com/multi-geth/multi-geth) a version of Ethereum Geth with support for ETC.

My configuration for running Multigeth are the following:
```
geth --kotti --rpc --rpcapi "eth,web3,net,clique,debug" --rpcaddr=0.0.0.0 --rpccorsdomain=* --ws --wsapi "eth,web3,net,clique,debug" --wsaddr=0.0.0.0 --wsorigins=* --syncmode=full --gcmode=archive --maxpeers=20
```

I can verify that the RPC address works when I run this curl command:
```
$ curl --data '{"method":"eth_getBlockByNumber","params":["latest", false
],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://localhost:8545

{"jsonrpc":"2.0","id":1,"result":{"difficulty":"0x1","extraData":"0x42433a524420417574686f7269747900000000000000000
000000000000000001ad5fcd982e707d9407e1e78fe28a6297f68ae6ff037f0ded08cf6110ed0668d3b088f5e5c19ffe0474174664d733a2ff7
3defc2dc2bfedbeaf3562172b6b9c500","gasLimit":"0x7a1200","gasUsed":"0x0","hash":"0x03bdf404c6518aeaf87ec4dc07734cdae
533ed8eb2d601fe1e00334626180928","logsBloom":"0x0000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","miner":"0x00
00000000000000000000000000000000000000","mixHash":"0x00000000000000000000000000000000000000000000000000000000000000
00","nonce":"0x0000000000000000","number":"0x159596","parentHash":"0x760836ec8c98e053b9eb6c5740dc5570d76de09c7cd9f2
1d9f014c3679254142","receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","sha3Uncles
":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","size":"0x261","stateRoot":"0x81e3ec9e1f27b2
6397c523ee036678c29224068da688c8a907f0abe9eb15d5d4","timestamp":"0x5dae3f51","totalDifficulty":"0x21a3a3","transact
ions":[],"transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","uncles":[]}}
```
I run the Makefile with the following commands:
```
ETHEREUM_JSONRPC_HTTP_URL=http://localhost:8545 ETHEREUM_JSONRPC_WS_URL=ws://localhost:8546 ETHEREUM_JSONRPC_TRACE_URL=http://localhost:8545 COIN=ETC ETHEREUM_JSONRPC_VARIANT=geth sudo make start
```
The error I'm getting is the following (it spits out so many times)
```
2019-10-21T23:39:56.827 fetcher=block_catchup [error] Task #PID<0.2755.0> started from Indexer.Block.Catchup.BoundInt
ervalSupervisor terminating                                                                                          
** (FunctionClauseError) no function clause matching in EthereumJSONRPC.HTTP.HTTPoison.json_rpc/3              
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/http/httpoison.ex:11: EthereumJSONRPC.HTTP.HTTPoison.json_rpc(nil, ["{\""
, [[] | "id"], "\":", "0", ",\"", [[] | "jsonrpc"], "\":", [34, [[] | "2.0"], 34], ",\"", [[] | "method"], "\":", [34
, [[] | "eth_getBlockByNumber"], 34], ",\"", [[] | "params"], "\":", [91, [34, [[] | "latest"], 34], 44, "false", 93]
, 125], [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]])                                 
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/http.ex:29: EthereumJSONRPC.HTTP.json_rpc/2                              
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/request_coordinator.ex:86: anonymous fn/3 in EthereumJSONRPC.RequestCoord
inator.perform/4                                                                                                     
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/request_coordinator.ex:106: EthereumJSONRPC.RequestCoordinator.trace_requ
est/2                                                                                    
    (ethereum_jsonrpc) lib/ethereum_jsonrpc.ex:280: EthereumJSONRPC.fetch_block_number_by_tag/2                      
    (indexer) lib/indexer/block/catchup/fetcher.ex:349: Indexer.Block.Catchup.Fetcher.latest_block/1                 
    (indexer) lib/indexer/block/catchup/fetcher.ex:76: Indexer.Block.Catchup.Fetcher.task/1                          
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
Function: &Indexer.Block.Catchup.Fetcher.task/1                                                                      
    Args: [%Indexer.Block.Catchup.Fetcher{block_fetcher: %Indexer.Block.Fetcher{broadcast: :catchup, callback_module:
 Indexer.Block.Catchup.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http:
 EthereumJSONRPC.HTTP.HTTPoison, url: nil, method_to_url: [eth_getBalance: nil, trace_block: nil, trace_replayTransac
tion: nil], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: Ethe
reumJSONRPC.Parity], receipts_batch_size: 250, receipts_concurrency: 10}, blocks_batch_size: 10, blocks_concurrency: 
10, memory_monitor: Indexer.Memory.Monitor}]     
```

I know it's related to this https://github.com/poanetwork/blockscout/issues/1413

But I can't seem to figure out why it can't communicate with my geth node. My geth node RPC endpoint is responding to me.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System: Debian 9
* Blockscout Version/branch: Latest Version via Dockerfile and Makefile

I'm running this on a Google Cloud VM Instance.
Machine Type: n1-standard-2 (2 vCPUs, 7.5 GB memory)

### Steps to reproduce

I've described the steps I've done above.

### Expected behaviour

Blockscout should be able to parse my MultiGeth node

### Actual behaviour

It's not able to communicate with it.

**Comment by YazzyYaz** [comment]
My Multi-Geth node isn't a public RPC, but I've demonstrated it works locally via the Curl command above.

I've run into this same issue when running Parity as well. So, my thoughts are it's not a problem unique to the client I'm using specifically.

My parity command was the following:
```
parity --chain=kotti --ws-interface all --ws-apis="web3","eth","net","parity","pubsub","
traces" --ws-origins all --ws-hosts all --jsonrpc-apis="web3","eth","net","parity","pubsub","traces" --tracing=on --fat-db=on --pruning=archive --jsonrpc-cors all --jsonrpc-hosts all --jsonrpc-interface all --mode active
```

I ran the Makefile with the following command:
```
ETHEREUM_JSONRPC_HTTP_URL=http://localhost:8545 ETHEREUM_JSONRPC_WS_URL=ws://localhost:8546
ETHEREUM_JSONRPC_TRACE_URL=http://localhost:8545 
COIN=ETC ETHEREUM_JSONRPC_VARIANT=parity sudo make start
```

It results in the same error as above.

**Comment by ayrat555** [comment]
@YazzyYaz can you try `ETHEREUM_JSONRPC_VARIANT=geth` ? Also by the error message, it looks like `ETHEREUM_JSONRPC_HTTP_URL` is not set. are you sure the app can access env vars?

**Comment by YazzyYaz** [comment]
@ayrat555 I have it as `ETHEREUM_JSONRPC_VARIANT=geth` in here. I'll repaste it for clarity:
```
ETHEREUM_JSONRPC_HTTP_URL=http://localhost:8545 ETHEREUM_JSONRPC_WS_URL=ws://localhost:8546 ETHEREUM_JSONRPC_TRACE_URL=http://localhost:8545 COIN=ETC ETHEREUM_JSONRPC_VARIANT=geth sudo make start
```

The parity information is to indicate that neither parity nor geth seem to be communicating with Makerfile script.

I also have the `ETHEREUM_JSONRPC_HTTP_URL` set in both geth and parity examples shown here.

Let me echo the env vars for you:
```
$ echo $ETHEREUM_JSONRPC_HTTP_URL
http://localhost:8545
```

**Comment by vbaranov** [comment]
@YazzyYaz 

First of all, I'd suggest using the latest master branch for compilation because of https://github.com/poanetwork/blockscout/pull/2799 merged there (it can indirectly contribute to your issue)

The second thing that there are some missing necessary parameters of Ethereum client launches.
In the case of Multi-Geth, at least `txpool` is missing. Blockscout uses it to display pending transactions list. The suggested parameters for Geth-based clients are described here https://app.gitbook.com/@poa/s/blockscout/for-developers/information-and-settings/client-settings-parity-geth-ganache#geth-client.
In the case of Parity, your launch command looks good. Anyways, the suggested parameters for Parity client you can find here https://app.gitbook.com/@poa/s/blockscout/for-developers/information-and-settings/client-settings-parity-geth-ganache#parity-client.

Thirdly, if you use geth and connect to the chain with Clique consensus algorithm you should provide `export BLOCK_TRANSFORMER=clique` ENV variable for Blockscout launch. So, the full minimal list of env vars for Kotti BS instance launch with Makefile:
```
ETHEREUM_JSONRPC_HTTP_URL=http://localhost:8545 ETHEREUM_JSONRPC_WS_URL=ws://localhost:8546 ETHEREUM_JSONRPC_TRACE_URL=http://localhost:8545 COIN=ETC ETHEREUM_JSONRPC_VARIANT=geth BLOCK_TRANSFORMER=clique make start
```

If the error will still appear try to use 127.0.0.1 instead of localhost in ENV vars. If this also will not help you can directly set the endpoints in the config file:
for Geth/Multi-Geth: https://github.com/poanetwork/blockscout/blob/master/apps/explorer/config/prod/geth.exs
for Parity: https://github.com/poanetwork/blockscout/blob/master/apps/explorer/config/prod/parity.exs
I created a Gist how it should look for Geth case https://gist.github.com/vbaranov/cee45ab438cc2b25a98eb8e96fa1b16c.

Btw, I successfully launched Kotti BS instance on Multi-Geth archive node on Mac OS.

My command line to launch Kotti archive node:
```
multi-geth --kotti --rpc --rpcapi "eth,web3,net,clique,debug,shh,txpool" --rpcaddr=0.0.0.0 --rpccorsdomain=* --ws --wsapi "eth,net,web3,network,debug,txpool" --wsaddr=0.0.0.0 --wsport=8546 --wsorigins=* --syncmode=full --rpcvhosts=* --gcmode=archive --maxpeers=20 --datadir ./
```

Blockscout source is from master branch on commit https://github.com/poanetwork/blockscout/commit/bfb8fd03452cf4681195e3f6ab5722226ffe4131 and the command line to run docker container:
```
ETHEREUM_JSONRPC_HTTP_URL=http://host.docker.internal:8545 ETHEREUM_JSONRPC_WS_URL=ws://host.docker.internal:8546 ETHEREUM_JSONRPC_TRACE_URL=http://host.docker.internal:8545 COIN=ETC ETHEREUM_JSONRPC_VARIANT=geth BLOCK_TRANSFORMER=clique make start
```

*Note*: for Mac OS I should use `host.docker.internal` instead of localhost as indicated here https://github.com/poanetwork/blockscout/tree/master/docker#how-to-use-

![Screenshot 2019-10-23 at 14 10 54](https://user-images.githubusercontent.com/4341812/67390618-b2d19780-f5a5-11e9-8301-f8022cb05fa4.png)
![Screenshot 2019-10-23 at 15 00 30](https://user-images.githubusercontent.com/4341812/67390728-e14f7280-f5a5-11e9-9891-5078958ef07a.png)


The full log of application:
```
MacBook-Pro-Viktor:docker viktor$ ETHEREUM_JSONRPC_HTTP_URL=http://host.docker.internal:8545 ETHEREUM_JSONRPC_WS_URL=ws://host.docker.internal:8546 ETHEREUM_JSONRPC_TRACE_URL=http://host.docker.internal:8545 COIN=ETC ETHEREUM_JSONRPC_VARIANT=geth make start
==> Checking for blockscout image blockscout_prod
==> Image exist. Using blockscout_prod
==> Checking PostrgeSQL container
==> PostgreSQL Already started
==> Starting blockscout
2019-10-23T11:18:10.572 application=tzdata [info] tzdata release in place is from a file last modified Tue, 26 Mar 2019 05:40:14 GMT. Release file on server was last modified Wed, 11 Sep 2019 19:35:17 GMT.
2019-10-23T11:18:11.370 application=que [info] [Que] Booting Que
2019-10-23T11:18:11.531 application=que [info] [Que] Booting Server Supervisor for Workers
2019-10-23T11:18:13.017 application=tzdata [info] Tzdata has updated the release from 2019a to 2019c
2019-10-23T11:18:20.640 application=phoenix [info] Running BlockScoutWeb.Endpoint with cowboy 2.6.3 at https://localhost:4000
2019-10-23T11:18:20.645 application=phoenix [error] Could not find static manifest at "/opt/app/_build/prod/lib/block_scout_web/priv/static/cache_manifest.json". Run "mix phx.digest" after building your static files or remove the configuration from "config/prod.exs".
2019-10-23T11:18:22.657 application=plug request_id=FdBCmtFjctSVv9oAAFOx [info] GET /
2019-10-23T11:18:25.606 application=plug request_id=FdBCmtFjctSVv9oAAFOx [info] Sent 200 in 2948ms
2019-10-23T11:18:26.670 application=phoenix [info] CONNECT BlockScoutWeb.UserSocket
  Transport: :websocket
  Connect Info: %{}
  Parameters: %{"locale" => "en", "vsn" => "2.0.0"}
2019-10-23T11:18:26.719 application=phoenix [info] Replied BlockScoutWeb.UserSocket :ok
2019-10-23T11:18:26.793 application=plug request_id=FdBCm8fiZIEyf88AAM6C [info] GET /market_history_chart
2019-10-23T11:18:26.799 application=plug request_id=FdBCm8g9X_3VlmsAAM6i [info] GET /recent_transactions
2019-10-23T11:18:26.799 application=plug request_id=FdBCm8hE4-bFnGYAAM6y [info] GET /chain_blocks
2019-10-23T11:18:26.887 application=plug request_id=FdBCm8fiZIEyf88AAM6C [info] Sent 200 in 94ms
2019-10-23T11:18:27.406 application=plug request_id=FdBCm8hE4-bFnGYAAM6y [info] Sent 200 in 607ms
2019-10-23T11:18:27.741 application=plug request_id=FdBCnABlI6psLVgAANTC [info] GET /site.webmanifest
2019-10-23T11:18:28.190 application=plug request_id=FdBCnABlI6psLVgAANTC [info] Sent 404 in 449ms
2019-10-23T11:18:28.523 application=plug request_id=FdBCm8g9X_3VlmsAAM6i [info] Sent 200 in 1723ms
2019-10-23T11:18:28.606 application=phoenix [info] JOIN "exchange_rate:new_rate" to BlockScoutWeb.ExchangeRateChannel
  Transport:  :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{}
2019-10-23T11:18:28.614 application=phoenix [info] Replied exchange_rate:new_rate :ok
2019-10-23T11:18:28.616 application=phoenix [info] JOIN "addresses:new_address" to BlockScoutWeb.AddressChannel
  Transport:  :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{}
2019-10-23T11:18:28.640 application=phoenix [info] Replied addresses:new_address :ok
2019-10-23T11:18:28.640 application=phoenix [info] JOIN "blocks:new_block" to BlockScoutWeb.BlockChannel
  Transport:  :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{}
2019-10-23T11:18:28.649 application=phoenix [info] Replied blocks:new_block :ok
2019-10-23T11:18:28.649 application=phoenix [info] JOIN "transactions:new_transaction" to BlockScoutWeb.TransactionChannel
  Transport:  :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{}
2019-10-23T11:18:28.656 application=phoenix [info] Replied transactions:new_transaction :ok
2019-10-23T11:18:28.656 application=phoenix [info] JOIN "blocks:indexing" to BlockScoutWeb.BlockChannel
  Transport:  :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{}
2019-10-23T11:18:28.660 application=phoenix [info] Replied blocks:indexing :ok
```

*Note 1*: I also suggest just in case to remove the corresponding docker images (`postgres` and `blockscout_prod`) and launch the migration `make migrate` before starting the container if you will run on the same machine, that you did before.

*Note 2*: the archive node should be fully synced in order to make Blockscout explorer work in a proper way

**Comment by YazzyYaz** [comment]
I found out why there was an issue with communicating with the clients.

Basically, whenever one uses `sudo` with the Makefile/Docker, it causes this error of not being able to communicate with the node.

I fixed it by following the steps here to allow Docker to run without sudo on new instances: https://www.digitalocean.com/community/questions/how-to-fix-docker-got-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket

I also ran into this issue after: https://github.com/poanetwork/blockscout/issues/2308

My fix for it was to add the `queue_target` and `queue_interval` on this file: https://github.com/poanetwork/blockscout/blob/7315441af6a711ebcdd06cadeebcb8e462e76db3/apps/explorer/config/prod.exs

A gist example of what I did:
https://gist.github.com/YazzyYaz/fb157daa94a57b35c9b288abc8ec425e

I'm not sure why the original bug I encountered happens when running sudo with Docker/Makerfile

**Comment by vbaranov** [comment]
I added the note to the `make start` command regarding `sudo` to the documentation https://docs.blockscout.com/for-developers/information-and-settings/docker-integration-local-use-only#env-variables

**Comment by dbale-altoros** [comment]
sorry, where should I execute the make start command ?
I always get 
make: *** No rule to make target 'start'.  Stop.
I cannot find any start script/file
