### ISSUE TITLE
POA Core: Unable to deploy infra using ansible

### ISSUE THREAD

**Issue by thekevinbrown** [poanetwork/blockscout#2798]
### Environment
Haven't set up the environment yet

### Steps to reproduce

Follow the steps here:

https://github.com/blockscout/docs/blob/master/for-developers/ansible-deployment/deploying-the-blockscout-infrastructure.md

### Expected Behaviour

Environment is created in our AWS account

### Actual Behaviour

```
$ ~/Library/Python/2.7/bin/ansible-playbook deploy_infra.yml 
[WARNING]: Unable to parse /Users/kevin/development/blockscout-terraform/hosts as an inventory source

[WARNING]: No inventory was parsed, only implicit localhost is available

[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [Prepare infrastructure] *************************************************************************************************************
skipping: no hosts matched

PLAY RECAP ********************************************************************************************************************************
```

Having not used Ansible or Terraform before, I'm not sure what hosts I need to put in that file. I don't have any hosts yet, that's why I'm running the command, to create the infra, no?

Any help would be much appreciated.

**Comment by vbaranov** [comment]
@thekevinbrown Blockscout terraform deployment moved to a separate repository https://github.com/poanetwork/blockscout-terraform. Please follow this guide to deploy infrastructure https://github.com/poanetwork/blockscout-terraform#deploying-the-infrastructure
