### ISSUE TITLE
xDAI transaction is down

### ISSUE THREAD

**Issue by mgarciap** [poanetwork/blockscout#2815]
This page has been down for several days:
https://blockscout.com/poa/xdai/address/0xa13d45301207711b7c0328c6b2b64862abfe9b7a/transactions

![image](https://user-images.githubusercontent.com/201871/67684058-3c4fe380-f971-11e9-8cd9-ba6d471faddd.png)

**Comment by vbaranov** [comment]
Sorry about that. Fixed by extra resources allocation.
