### ISSUE TITLE
Ethereum Mainnet: API to fetch contract balance is returning 503 error

### ISSUE THREAD

**Issue by nitika-goel** [poanetwork/blockscout#2823]
We have been using a Blockscout API available at   https://blockscout.com/eth/mainnet/api?module=account&action=eth_get_balance&address={{address}}. However, the API started throwing a 503 error today. Could you please resolve this or point me to a working alternative?

### Steps to reproduce
Go to the following sample link via any browser :  https://blockscout.com/eth/mainnet/api?module=account&action=eth_get_balance&address=0xc0a47dFe034B400B47bDaD5FecDa2621de6c4d95

### Expected Behaviour
Return balance of ethereum address

### Actual Behaviour
Returning 503 error

**Comment by igorbarinov** [comment]
BlockScout mainnet synced
