### ISSUE TITLE
Ethereum Classic: header data not working

### ISSUE THREAD

**Issue by TokenHash** [poanetwork/blockscout#2836]
when checking an account it doesn't calculate the balance

https://blockscout.com/etc/mainnet/address/0x69f0da9ac5196e8817af39a2f1e0d43209946039/transactions

**Comment by vbaranov** [comment]
@TokenHash it calculates fine for me

<img width="1174" alt="Screenshot 2019-11-05 at 11 51 06" src="https://user-images.githubusercontent.com/4341812/68192579-94ff2c00-ffc2-11e9-8f90-38b993a569a8.png">

What is wrong in your case?
