### ISSUE TITLE
Get balance of ETH account at a particular block

### ISSUE THREAD

**Issue by nitika-goel** [poanetwork/blockscout#2840]
We have been using a Blockscout API available at https://blockscout.com/eth/mainnet/api?module=account&action=eth_get_balance&address={{address}}&block={{blockno}} to fetch account balance of an ethereum address at a specified block.

I am unable to work out a similar API in the new API stack. Have tried https://api.blockchair.com/ethereum/dashboards/address/0x1B541c2dC0653FD060E8320D2F763733BA8Cffe3?q=block_id(7809928) but doesn't work.

### Steps to reproduce

Visit link https://api.blockchair.com/ethereum/dashboards/address/0x1B541c2dC0653FD060E8320D2F763733BA8Cffe3?q=block_id(7809928) via any browser

### Expected behaviour

Should return balance of account at the given block

### Actual behaviour

Returns latest balance

**Comment by vbaranov** [comment]
@nitika-goel 

We removed the redirect to Blockchair for ETH Mainnet. You can use https://blockscout.com/eth/mainnet/api?module=account&action=eth_get_balance&address={{address}}&block={{blockno}} as usual. Sorry, for the inconvenience.
