### ISSUE TITLE
(MatchError) no match of right hand side value: {:error, :econnrefused}

### ISSUE THREAD

**Issue by puneet-khushwani-eth** [poanetwork/blockscout#2847]
We have a local setup where we are trying to run Blockscout for one of our private POA based chains. 

geth is running via the below command and is in sync with our blockchain

```
ethereum/client-go:v1.9.5 --networkid 1405 --datadir ./chain_data --port 31405 --rpc --rpcaddr 0.0.0.0 --rpcvhosts=* --rpccorsdomain=* --rpcapi eth,net,web3,network,debug,txpool,admin,personal,shh,clique --rpcport 8545 --ws --wsaddr 0.0.0.0 --wsport 8546 --wsapi eth,net,web3,network,debug,txpool,admin,personal --wsorigins=* --gcmode=archive --syncmode=full
```

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): using the docker file from code to install dependencies
* Operating System: `macos`
* Blockscout Version/branch: `master` 

### Steps to reproduce

```
ETHEREUM_JSONRPC_HTTP_URL=http://127.0.0.1:8545 ETHEREUM_JSONRPC_WS_URL=ws://127.0.0.1:8546 ETHEREUM_JSONRPC_TRACE_URL=http://127.0.0.1:8545 COIN=OST ETHEREUM_JSONRPC_VARIANT=geth BLOCK_TRANSFORMER=clique NETWORK='Ethereum Network' SUBNETWORK=Core make start
```

### Expected behaviour

Blockscout should be able to parse our blockchain and show blocks and txs on `http://127.0.0.1:4000`

### Actual behaviour

getting continuous errors below and chain is not being parsed.

```
2019-11-07T15:18:03.576 fetcher=block_catchup [error] Task #PID<0.945.0> started from Indexer.Block.Catchup.BoundIntervalSupervisor terminating
** (MatchError) no match of right hand side value: {:error, :econnrefused}
    (indexer) lib/indexer/block/catchup/fetcher.ex:349: Indexer.Block.Catchup.Fetcher.latest_block/1
    (indexer) lib/indexer/block/catchup/fetcher.ex:76: Indexer.Block.Catchup.Fetcher.task/1
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Indexer.Block.Catchup.Fetcher.task/1
    Args: [%Indexer.Block.Catchup.Fetcher{block_fetcher: %Indexer.Block.Fetcher{broadcast: :catchup, callback_module: Indexer.Block.Catchup.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://127.0.0.1:41405", http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, blocks_batch_size: 10, blocks_concurrency: 10, memory_monitor: Indexer.Memory.Monitor}]
2019-11-07T15:18:03.577 application=indexer fetcher=block_catchup [error] Catchup index stream exited with reason ({{:badmatch, {:error, :econnrefused}}, [{Indexer.Block.Catchup.Fetcher, :latest_block, 1, [file: 'lib/indexer/block/catchup/fetcher.ex', line: 349]}, {Indexer.Block.Catchup.Fetcher, :task, 1, [file: 'lib/indexer/block/catchup/fetcher.ex', line: 76]}, {Task.Supervised, :invoke_mfa, 2, [file: 'lib/task/supervised.ex', line: 90]}, {Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 35]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}). Restarting
```

**Comment by ayrat555** [comment]
@puneet-khushwani-eth can you please try localhost instead of `127.0.0.1`?

**Comment by puneet-khushwani-bits** [comment]
@ayrat555 even with localhost it gives same behaviour

```
ETHEREUM_JSONRPC_HTTP_URL=http://localhost:41405 ETHEREUM_JSONRPC_WS_URL=ws://localhost:51405 ETHEREUM_JSONRPC_TRACE_URL=http://localhost:41405 COIN=OST ETHEREUM_JSONRPC_VARIANT=geth BLOCK_TRANSFORMER=clique NETWORK='Ethereum Network' SUBNETWORK=Core make start
```

**Comment by puneet-khushwani-bits** [comment]
@ayrat555 I initially thought that this might be because we are starting to process a chain which already has 2868087 blocks. It has too much to do and does a lot of stuff in parallel and ends up failing. 
But I get the same error even when use `FIRST_BLOCK=2868011` (~80 blocks old)  in the command.

**Comment by puneet-khushwani-eth** [comment]
I also tried with a new chain which has ~ 100 blocks but get the same error on it also.

**Comment by puneet-khushwani-eth** [comment]
@ayrat555 any lead on this ?

**Comment by puneet-khushwani-eth** [comment]
@ayrat555 I ran the code locally without docker using instructions given `https://docs.blockscout.com/for-developers/manual-deployment` with the same geth node, it works fine 💯. Looks like there is some problem with the docker thing.

**Comment by vbaranov** [comment]
As for the Docker setup, if you are on Mac OS, you should use *host.docker.internal* instead of *localhost*. For instance:

```
export ETHEREUM_JSONRPC_HTTP_URL=http://host.docker.internal:8545
```

As stated in the docs for Blockscout Docker integration https://docs.blockscout.com/for-developers/information-and-settings/docker-integration-local-use-only

>mac/Windows: Docker provides a special URL -  host.docker.internal - that is available in the container and routed to your local machine. 
Linux: Docker is starting using --network=host and all services are available on localhost
