### ISSUE TITLE
getblockreward api returns Something went wrong

### ISSUE THREAD

**Issue by luckyyang** [poanetwork/blockscout#2848]
### Environment

Use postman to do the api test

### Steps to reproduce

Use postman to get https://blockscout.com/poa/core/api?module=block&action=getblockreward&blockno=11897954

### Expected behaviour

Should return the reward info for block
### Actual behaviour

```
{
    "status": "0",
    "result": null,
    "message": "Something went wrong."
}
```

**Comment by vbaranov** [comment]
@luckyyang fixed. Just for your information, in case you going to fix this in the custom chain, you need to import spec file of the chain. In the case of POA Core:
```
EMISSION_FORMAT="POA"
CHAIN_SPEC_PATH="https://raw.githubusercontent.com/poanetwork/poa-chain-spec/core/spec.json"
```

Reference to ENV vars set: https://docs.blockscout.com/for-developers/information-and-settings/env-variables

**Comment by luckyyang** [comment]
@vbaranov Is there any guide for how to generate this spec file?

**Comment by vbaranov** [comment]
It is a Chain spec for Parity Ethereum client:
https://wiki.parity.io/Chain-specification

**Comment by luckyyang** [comment]
Got it, thanks!

**Comment by Drunken-Dragon** [comment]
Hi @vbaranov looks like we face exactly the same problem and I did not want to duplicate a closed issue.

We use Blockscout 3.5.1 and we also use the chain spec file for our custom chain, but when calling the API
we get 500 error and "Something went wrong" message.

Do you have any suggestions what else can we check/modify in on our side to fix this?
