### ISSUE TITLE
Contract info disappeared after re-deploy with docker

### ISSUE THREAD

**Issue by luckyyang** [poanetwork/blockscout#2849]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Use official docker config file specified in Makefile
* Operating System: Ubuntu 18
* Blockscout Version/branch: master, commit 6bd4038

### Steps to reproduce
1. Go to branch elaeth of our repo https://github.com/cyber-republic/blockscout
2. Change Makefile config: https://github.com/cyber-republic/blockscout/blob/elaeth/docker/Makefile
3. Run `make start` to deploy
4. Check the contract we deployed before https://explorer.elaeth.io/address/0x4ba3125005796fc05a39bb60b94df2601f6bb6ca/

### Expected behaviour

Able to see contract tokens, internal transactions, code, and to read contract

### Actual behaviour
* **Unable** to see contract tokens, internal transactions, code
* Code tab disappeared totally

Before deployment:
![image](https://user-images.githubusercontent.com/1963646/68469493-3e5d5080-0255-11ea-9b7c-0acf33692879.png)

After deployment:
![image](https://user-images.githubusercontent.com/1963646/68469556-5f25a600-0255-11ea-8346-8c7453f650e5.png)

**Comment by vbaranov** [comment]
@luckyyang could you clarify what did you do after `Before deployment:`? If before some actions you were seen verified code of contract and after them - no, then it means to me, that something or someone cleared the table `smart_contracts` in your DB. Btw, If you run `docker migrate` it will drop DB. Didn't you do that?

Anyways, you can fix this manually by setting `consensus` to false for the block where the smart-contract was created and restarting the application. Blockscout indexer will re-fetch that block and parse its transactions correctly.

**Comment by luckyyang** [comment]
@vbaranov `Before deployment`: I removed docker containers and images. 

Actually I just run one command
```shell
docker stop blockscout; docker rm blockscout; docker rmi blockscout_prod; docker stop postgres; docker rm postgres; docker rmi postgres; make start
```

Would that command cleared the table `smart_contracts`? I did not do 'docker migrate'.

Manually by setting `consensus` to false maybe a way to fix it, but I do not want to do it every time after deployment.

**Comment by vbaranov** [comment]
>Would these commands cleared the table smart_contracts?

Actually, it shouldn't. I cannot reproduce this behaviour.

**Comment by luckyyang** [comment]
Weird. Any guide for how to connect the DB from a client app? I could take a look at the data.

**Comment by luckyyang** [comment]
I manually set consensus to false and restart the docker container, did not resolve my issue with following commands. I found the `smart_contract` table is empty.
```
docker stop blockscout; 
docker rm blockscout; 
docker stop postgres; 
docker rm postgres; 

make start;
```

**Comment by luckyyang** [comment]
From the chat in https://gitter.im/poanetwork/blockscout# with Victor:

smart_contracts table is not filled by the application. It contains the data for verified smart-contracts which can be provided by users

internal_transactions table should be filled by the internal transactions indexer if blockchain, you index, contains internal transactions and your archive node is fully synchronized. Check if you have any errors in the application logs

> Checked the DB found fetched_coin_balance value is NULL in addresses table.

This is possible if balance update originated from the internal transaction but your instance didn’t index that internal transaction for some reason yet

recommended Geth config https://docs.blockscout.com/for-developers/information-and-settings/client-settings-parity-geth-ganache#geth-client

Blockscout cannot index internal transactions if the node is not in the archive node. 

It is gone because you have no internal transaction in the DB for that creation
We do not use Docker config in production. it was created by community. What we use is Terraform - ansible deployment https://docs.blockscout.com/for-developers/ansible-deployment

VPS configuration:
just for acquaintance, close to these parameters Blockscout is using for Mainnet instance https://github.com/poanetwork/blockscout/issues/2013#issuecomment-495189456

**Comment by luckyyang** [comment]
Close this issue, since it should be ok after we run the instance in archive mode
