### ISSUE TITLE
Run migrations when performing `make start` with an existing postgres docker container

### ISSUE THREAD

**Issue by varasev** [poanetwork/blockscout#2852]
When I perform `make start` in `docker` directory and Postgres container already exists, sometimes (when DB structure is changed) I see an error (for example, `column ... does not exist`).

Let's add `migrate` step to the `start` step in `docker/Makefile` so that migrations would be run automatically when performing `make start` command.

**Comment by worldbagtour** [comment]
test-projects/degate-0.1.0_2012-04-22_1639_SC14421CVF_dect.zip.ac

**Comment by worldbagtour** [comment]
test-projects/degate-0.1.0_2012-04-22_1639_SC14421CVF_dect.zip.ac`[test-projects/degate-0.1.0_2012-04-22_1639_SC14421CVF_dect.zip.acapps/block_scout_web/assets/css/app.scss](https://blockchain)

**Comment by worldbagtour** [comment]
`test-projects/degate-0.1.0_2012-04-22_1639_SC14421CVF_dect.zip.acapps/block_scout_web/assets/css/app.scss`

**Comment by worldbagtour** [comment]
``
