### ISSUE TITLE
Contracts deployed on genesis file not have "code" tab 

### ISSUE THREAD

**Issue by helderjnpinto** [poanetwork/blockscout#2860]
The problem here is the contracts that exist in genesis file are deployed as beggining of all state the blockchain, so there is a problem the explorer detects that x Address is of type of contract but not have "code" tab for verification of contract but in the logs tab i can access the verification page but this stay "loading" forever after i submit my contract code.

If i deploy manually the contract, i successfully can verify the contract, but if the contract starts on genesis its not possible causing this error: 

```
2019-11-14T12:24:39.634 application=plug request_id=FdcG_UR8UIDPiocAD72B [info] POST /verify_smart_contract/contract_verifications
2019-11-14T12:24:39.637 application=que [info] [Que] Queued new Job for Explorer.SmartContract.PublisherWorker
2019-11-14T12:24:39.638 application=que [info] [Que] Starting Job # 8 with Explorer.SmartContract.PublisherWorker
2019-11-14T12:24:39.638 application=plug request_id=FdcG_UR8UIDPiocAD72B [info] Sent 204 in 3ms
2019-11-14T12:24:46.351 [error] Task #PID<0.4998.4> started from #PID<0.5568.0> terminating
** (FunctionClauseError) no function clause matching in Explorer.Chain.Data.to_string/1
    (explorer) lib/explorer/chain/data.ex:65: Explorer.Chain.Data.to_string(nil)
    (explorer) lib/explorer/smart_contract/verifier.ex:67: Explorer.SmartContract.Verifier.compare_bytecodes/3
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (explorer) lib/explorer/smart_contract/publisher.ex:29: Explorer.SmartContract.Publisher.publish/3
    (explorer) lib/explorer/smart_contract/publisher_worker.ex:13: Explorer.SmartContract.PublisherWorker.perform/1
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<3.104694414/0 in Que.Job.perform/1>
    Args: []
2019-11-14T12:24:46.352 application=que [info] [Que] Failed Job # 8 with Explorer.SmartContract.PublisherWorker
2019-11-14T12:25:04.646 application=indexer fetcher=block_catchup first_block_number=17375 last_block_number=0 missing_block_count=0 shrunk=false [info] Index already caught up.

```

### Steps to reproduce
Run a blockchain node with genesis that contains contracts for deployment, in the current case i'm using Hyperledger besu.  

### Expected behaviour

Have a successfull verification of contract on genesis.
### Actual behaviour

Stay loading forever after submit
![image](https://user-images.githubusercontent.com/12281088/68861269-223d3180-06e3-11ea-98c1-e66839cae3dd.png)

**Comment by helderjnpinto** [comment]
I added manually the code in postgres database, now tab code appears, but i can't verify the code say 'Bytecode does not match, please try again.'

**Comment by ayrat555** [comment]
@helderjnpinto  can you please give a snippet of genesis file where contracts are described?

**Comment by vbaranov** [comment]
@helderjnpinto does it work as expected with that fix https://github.com/poanetwork/blockscout/pull/2875?

**Comment by helderjnpinto** [comment]
> n you please give a snippet of genesis file where contracts are described?

yes, so the Besu genesis is like this. https://gist.github.com/helderjnpinto/e1f84a1b710d7b34a2a52a8c56fc0bdf

**Comment by helderjnpinto** [comment]
So with the last fix 2875 i get this result, detect name of ERC20, in logs tab exist a verify contract link but when i click give internal  server error.

![image](https://user-images.githubusercontent.com/12281088/70342661-64264700-184d-11ea-8e0f-cc8aee5f53f2.png)

**Comment by helderjnpinto** [comment]
i saw that genesis @chain_spec is different from besu genesis, i will close this issue.
