### ISSUE TITLE
COIN environment variable appears to work no more

### ISSUE THREAD

**Issue by weilbith** [poanetwork/blockscout#2867]
I recently merged locally the upstream of tag `v2.1.0-beta` into my fork. Since then it appears that my `$COIN` environment variable has no impact anymore. Before I was able to see the custom value of this variable as unit for the values of transactions, balances and rewards. Now there is everywhere simply `Ether`. How can I make it work again to use a custom coin name? I saw that the whole balance calculation has changed a lot. Unfortunately I have no clue about Elixir and can only hardly understand how the structure of this project work.

### Environment

* Elixir & Erlang/OTP versions: Docker image (`Elixir 1.9.0 (compiled with Erlang/OTP 22)`)
* Operating System: Docker image (
* Blockscout Version/branch: `v2.1.0-beta`

### Steps to reproduce

I have an [example branch](https://github.com/weilbith/blockscout/tree/v2.1.0-beta_issue-example). It includes an additional commit on top of the `v2.1.0-beta` tag. This commit adds an example `docker/.env` file. Also the `docker/Makefile` has been "fixed". It now make use of more environment variables which should be supported and also add the `.env` file to the blockscout Docker container. So the following commands should do the demonstration:

```sh
$ git clone git@github.com:weilbith/blockscout.git
$ git checkout v2.1.0-beta_issue_example
$ cd docker
$ set -a; source .env; set +a
$ make start
```

By the above configuration in the `.env` file, it expects a Parity node at `localhost:8545`. Adjust it in prehand if this does not fit your test environment.
The result is, that opening the explorer at `localhost:4000` in the webbrowser, all values are by `Ether`. Already on the landing page the block reward and the transaction values can be seen.

I had also a test without Docker, which result into the same problem.

The over set environment variables do work. I also tried once to change the logo by such variable and it got applied. So it appears like the 

### Expected behaviour

Instead of `Ether` the content of the `COIN` environment variable should be used. In the above mentioned example branch it would be `MTC`.

### Actual behaviour

It always displays `Ether`.

Additionally this is the top of the blockscout log (`docker logs blockscout | head -n 6`). Not sure if this helps anyways.

```
2019-11-20T10:27:46.544 application=tzdata [info] tzdata release in place is from a file last modified Tue, 26 Mar 2019 05:40:14 GMT. Release file on server was last modified Wed, 11 Sep 2019 19:35:17 GMT.
2019-11-20T10:27:48.258 application=que [info] [Que] Booting Que
2019-11-20T10:27:48.383 application=que [info] [Que] Booting Server Supervisor for Workers
2019-11-20T10:27:48.817 application=tzdata [info] Tzdata has updated the release from 2019a to 2019c
2019-11-20T10:27:50.275 application=phoenix [info] Running BlockScoutWeb.Endpoint with cowboy 2.6.3 at https://localhost:4000
2019-11-20T10:27:50.275 application=phoenix [error] Could not find static manifest at "/opt/app/_build/prod/lib/block_scout_web/priv/static/cache_manifest.json". Run "mix phx.digest" after building your static files or remove the configuration from "config/prod.exs".
```

---

Thanks for your help in advance! :pray:

**Comment by vbaranov** [comment]
@weilbith follow the chapter "Displayed Coin Symbol" in this guide https://forum.poa.network/t/faq-how-can-i-customize-coin-symbol/1875

**Comment by weilbith** [comment]
Okay, I don't understand how this works in exact. It seems like there are two different uses of the `$COIN` variable. First in `/apps/explorer/config/config.exs` (`coin: System.get_env("COIN") || "POA",`) and then `apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po`. The last one seam to do the work if I add a custom `msgstr` for `msgid "Ether"`. I figured out that this was working before, because the `msgstr` was set to `POA` and the Dockerfile has a substitution command from `POA` to `$COIN`. Unfortunately has the default `POA` value been removed. So the substitution does nothing anymore and it remains empty. Was this a mistake or has it been removed intentionally?
Anyways, what is the first usage for the `coin` in `config.exs` then for? What does it affect?

**Comment by vbaranov** [comment]
`COIN` variable is for retrieving of the exchange rate for the coin to display market capitalization in the chart on the main page (ref https://docs.blockscout.com/for-developers/information-and-settings/env-variables).

Docker setup is not something we use in production and it was created by the community. Anyways, I encourage you to propose the changes to the Dockerfile to use a `POA` fallback there. It looks reasonable for consistency.

**Comment by weilbith** [comment]
Okay, cool. Thanks for the input!
