### ISSUE TITLE
Fail to fetch Internal Transactions

### ISSUE THREAD

**Issue by mgarciap** [poanetwork/blockscout#2879]
I keep getting this error on https://blockscout.com/poa/xdai/address/0xa13d45301207711b7c0328c6b2b64862abfe9b7a/internal_transactions

![image](https://user-images.githubusercontent.com/201871/69651249-8d292980-104e-11ea-8c9c-c6c6197aa666.png)

**Comment by vbaranov** [comment]
Fixed
