### ISSUE TITLE
function Plug.Cowboy.Translator.translate/4 is undefined (module Plug.Cowboy.Translator is not available)

### ISSUE THREAD

**Issue by orlax** [poanetwork/blockscout#2903]
I am trying to set up the explorer with my private network, followed all instructions and resolved many other errors that were popping up but this one I haven't found a way to solve:

2019-12-02T20:47:12.954 [error] Failure while translating Erlang's logger event
** (UndefinedFunctionError) function Plug.Cowboy.Translator.translate/4 is undefined (module Plug.Cowboy.Translator is not available)
    (plug_cowboy) Plug.Cowboy.Translator.translate(:debug, :error, :report, {{:erl_prim_loader, :file_error}, 'File operation error: emfile. Target: /home/ubuntu/blockscout/_build/dev/lib/plug_cowboy/ebin/Elixir.Plug.Cowboy.Translator.beam. Function: get_file. Process: code_server.'})
    (logger) lib/logger/erlang_handler.ex:104: Logger.ErlangHandler.translate/6
    (logger) lib/logger/erlang_handler.ex:97: Logger.ErlangHandler.translate/5
    (logger) lib/logger/erlang_handler.ex:27: anonymous fn/3 in Logger.ErlangHandler.log/2
    (logger) lib/logger.ex:862: Logger.normalize_message/2
    (logger) lib/logger.ex:687: Logger.__do_log__/3
    (kernel) logger_backend.erl:51: :logger_backend.call_handlers/3
    (kernel) logger_backend.erl:38: :logger_backend.log_allowed/2
    (kernel) logger_server.erl:351: :logger_server.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
Erlang/OTP 22 [erts-10.5.6] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1]
Elixir 1.9.0 (compiled with Erlang/OTP 21)

* Operating System:
Ubuntu 18.04 

* Blockscout Version/branch: 
origin/master' . 545b28267754ded928b848e3527daa8dba42803a

### Steps to reproduce
clone current version of blockscout, follow configuration steps for manual deployment as described here: [https://docs.blockscout.com/for-developers/manual-deployment](https://docs.blockscout.com/for-developers/manual-deployment)

### Expected behaviour

It should run and allow me to inspect my network. 

### Actual behaviour
The error crashes and the program exits. 

this is my first time dealing with an erlang/elixir app so please, please help me.

**Comment by vbaranov** [comment]
@orlax I'd suggest using the latest stable release of Blockscout: https://github.com/poanetwork/blockscout/releases/tag/v2.1.1-beta

And you need to upgrade Elixir version up to `1.9.1` and use `Erlang/OTP 22` as indicated in the current requirements https://docs.blockscout.com/for-developers/information-and-settings/requirements

**Comment by orlax** [comment]
hello @vbaranov  thank you for looking into this. 

I found some thread that recommended using Elixir on a 1.9.0 version, following your recommendation I downloaded the 2.1.1-beta and re-did the manual deployment steps but the error remains:

```
2019-12-03T19:34:30.760 [error] Failure while translating Erlang's logger event
** (UndefinedFunctionError) function Plug.Cowboy.Translator.translate/4 is undefined (module Plug.Cowboy.Translator is not available)
    (plug_cowboy) Plug.Cowboy.Translator.translate(:debug, :error, :report, {{:erl_prim_loader, :file_error}, 'File operation error: emfile. Target: /home/ubuntu/blockscout-beta/blockscout-2.1.1-beta/_build/dev/lib/plug_cowboy/ebin/Elixir.Plug.Cowboy.Translator.beam. Function: get_file. Process: code_server.'})
    (logger) lib/logger/erlang_handler.ex:104: Logger.ErlangHandler.translate/6
    (logger) lib/logger/erlang_handler.ex:97: Logger.ErlangHandler.translate/5
    (logger) lib/logger/erlang_handler.ex:27: anonymous fn/3 in Logger.ErlangHandler.log/2
    (logger) lib/logger.ex:862: Logger.normalize_message/2
    (logger) lib/logger.ex:687: Logger.__do_log__/3
    (kernel) logger_backend.erl:51: :logger_backend.call_handlers/3
    (kernel) logger_backend.erl:38: :logger_backend.log_allowed/2
    (kernel) logger_server.erl:351: :logger_server.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

the steps I followed were these ones:  

```
setup the configurations on "apps/explorer/config/dev.secret.exs" and apps/block_scout_web/config/dev.secret.exs" with correct Postgres users / password. 

mix do deps.get, local.rebar --force, deps.compile, compile

Install Node.js dependencies
cd apps/block_scout_web/assets; npm install && node_modules/webpack/bin/webpack.js --mode production; cd -
cd apps/explorer && npm install; cd -

Enable HTTPS in development. The Phoenix server only runs with HTTPS.

cd apps/block_scout_web
mix phx.gen.cert blockscout blockscout.local; cd -

Add blockscout and blockscout.local to your /etc/hostsEnable 

cd apps/block_scout_web
mix phx.gen.cert blockscout blockscout.local; cd -

Add blockscout and blockscout.local to your /etc/hosts

mix phx.server
```

my env variables are configured to point towards my running node. 

this is my version now:

Erlang/OTP 22 [erts-10.5.6] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1]
Elixir 1.9.1 (compiled with Erlang/OTP 21)
ubuntu 18.04 on aws. 

if it helps there is another error that appears prior to this one: 

```
** (Mix) Could not start application block_scout_web: BlockScoutWeb.Application.start(:normal, []) returned an error: shutdown: failed to start child: Absinthe.Subscription
    ** (EXIT) shutdown: failed to start child: Absinthe.Subscription.ProxySupervisor
        ** (EXIT) an exception was raised:
            ** (UndefinedFunctionError) function Absinthe.Subscription.ProxySupervisor.start_link/3 is undefined (module Absinthe.Subscription.ProxySupervisor is not available)
                (absinthe) Absinthe.Subscription.ProxySupervisor.start_link(BlockScoutWeb.Endpoint, BlockScoutWeb.Endpoint.Registry, 2)
                (stdlib) supervisor.erl:379: :supervisor.do_start_child_i/3
                (stdlib) supervisor.erl:365: :supervisor.do_start_child/2
                (stdlib) supervisor.erl:349: anonymous fn/3 in :supervisor.start_children/2
                (stdlib) supervisor.erl:1157: :supervisor.children_map/4
                (stdlib) supervisor.erl:315: :supervisor.init_children/2
                (stdlib) gen_server.erl:374: :gen_server.init_it/2
                (stdlib) gen_server.erl:342: :gen_server.init_it/6
                (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

but this gets resolved if I run the build commands again: 
mix do deps.get, local.rebar --force, deps.compile, compile

I think that there is something wrong with how the packages are getting installed? but really have no idea.

**Comment by vbaranov** [comment]
@orlax try to increase the number of opened at the same time files in `/etc/systemd/system.conf`

Increase the number:
```
DefaultLimitNOFILE=40000
```

Restart Elixir application after that.

**Comment by orlax** [comment]
Hey @vbaranov I edited my sytem.conf file and rebooted the machine, redid the manual configuration steps but the error remains the same... 

things I have found:

If I try to access my machines port 4000 it starts to load and says:

`2019-12-04T16:47:16.733 [warn] Ranch acceptor reducing accept rate: out of file descriptors`

a bunch of times but nothing actually appears on the web browser, after killing the mix process with ctrl+c and trying to restart it another error appears: 

`** (Mix) Could not start application block_scout_web: BlockScoutWeb.Application.start(:normal, []) returned an error: shutdown: failed to start child: BlockScoutWeb.Endpoint
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function Phoenix.LiveReloader.Socket.child_spec/1 is undefined (module Phoenix.LiveReloader.Socket is not available)
            (phoenix_live_reload) Phoenix.LiveReloader.Socket.child_spec([endpoint: BlockScoutWeb.Endpoint])
            (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
            (phoenix) lib/phoenix/endpoint/supervisor.ex:56: Phoenix.Endpoint.Supervisor.init/1
            (stdlib) supervisor.erl:295: :supervisor.init/1
            (stdlib) gen_server.erl:374: :gen_server.init_it/2
            (stdlib) gen_server.erl:342: :gen_server.init_it/6
            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3`

but once again running the build commands again seems to fix this and back to my original error. This reaffirms my belief that something is happening with this mix.exs files and the way the modules are getting installed. 

Is someone able to reproduce this error? starting a new blockscout project on a ubuntu 18.04 machine? 

as I am on a tight schedule I might have to just move on to another ethereum block explorer solution, but just for my own sake, I would like to know what is happening and why isn't this working. 

thank you for you assistance, I really, really aprecciate it.

**Comment by vbaranov** [comment]
@orlax which set of env variables did you set from the list https://docs.blockscout.com/for-developers/information-and-settings/env-variables?

**Comment by orlax** [comment]
@vbaranov good day, running a printenv on my machine gives me these variables: 

ETHEREUM_JSONRPC_HTTP_URL=localhost:8545
COIN=ETH
ETHEREUM_JSONRPC_WS_URL=ws://localhost:8545
ETHEREUM_JSONRPC_VARIANT=geth
ETHEREUM_JSONRPC_TRACE_URL=localhost:8545

**Comment by vbaranov** [comment]
@orlax and what is running on `localhost:8545` ?

**Comment by orlax** [comment]
that would be my private ethereum node this is the .service file for that process: 
`
[Unit]
Description=Ethereum Patacoin go client

[Service]
Type=simple
ExecStart=/usr/bin/geth --datadir="/home/ubuntu/patacoin-eth/ethdata" --networkid 52293 --nodiscover --rpc --rpcaddr 0.0.0.0 --rpcvhosts=ec2-35$
Restart=always
RestartSec=1
User=ubuntu

[Install]
WantedBy=default.target

`

**Comment by orlax** [comment]
@vbaranov that would be my private ethereum node, this is the .service file: 

```
[Unit]
Description=Ethereum Patacoin go client

[Service]
Type=simple
ExecStart=/usr/bin/geth --datadir="/home/ubuntu/patacoin-eth/ethdata" --networkid 52293 --nodiscover --rpc --rpcaddr 0.0.0.0 --rpcvhosts=***********.ca-central-1.compute.amazonaws.com  --rpcport "8545" --rpccorsdomain "http://**********ca-central-1.compute.amazonaws.com" --rpcapi "eth,net,web3,miner,debug,personal,rpc,admin,txpool"  --gcmode=archive --syncmode full
Restart=always
RestartSec=1
User=ubuntu

[Install]
WantedBy=default.target
```

**Comment by vbaranov** [comment]
@orlax you didn't open websockets. I guess this is the root cause of your issue. You should follow this config for Geth https://docs.blockscout.com/for-developers/information-and-settings/client-settings-parity-geth-ganache#geth-client or you should remove `ETHEREUM_JSONRPC_WS_URL=ws://localhost:8545` environment variable if you don't want to use websockets for some reason

**Comment by orlax** [comment]
@vbaranov that was it! oh, men, it feels nice to know what the cause was. 

hope this thread helps other people that might find this situation, thank you deeply for your help.
