### ISSUE TITLE
FunctionClauseError: no function clause matching in EthereumJSONRPC.quantity_to_integer/1

### ISSUE THREAD

**Issue by Lsquared13** [poanetwork/blockscout#2923]
Trying to run the application results in a blockscout that never loads blocks and an error that reads `FunctionClauseError: no function clause matching in EthereumJSONRPC.quantity_to_integer/1`(log screenshot at bottom of issue)

I'm hoping for some help understanding the root cause of the issue so I have an idea how to debug this.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Erlang/OTP 21 ; Elixir 1.9.4 (compiled with Erlang/OTP 20)
* Operating System: Amazon Linux 2
* Blockscout Version/branch: master

### Steps to reproduce

- Use ansible to generate terraform configuration
- Manually apply terraform configuration
- Follow instructions in terraform output for manual deployment, using [my fork](https://github.com/Eximchain/blockscout) as the source

### Expected behaviour

The application should work and load blocks

### Actual behaviour

The application never shows any blocks. Using `journalctl` to read the logs shows a FunctionClauseError

<img width="1440" alt="Screen Shot 2019-12-17 at 4 49 19 PM" src="https://user-images.githubusercontent.com/4107447/71040676-24851800-20f5-11ea-9154-97614b06a170.png">

**Comment by vbaranov** [comment]
@Lsquared13 master branch doesn't support Elixir 1.9.4 yet. If you want to utilize this version I'd suggest merging https://github.com/poanetwork/blockscout/pull/2873 into your branch.

**Comment by Lsquared13** [comment]
@vbaranov could you confirm the latest version of elixir that master branch supports?  I tried using `v1.9.1` (which is what it looks like that PR is upgrading from) and I still have the same error. Going down to `v1.8.2` seems to give me build problems

**Comment by vbaranov** [comment]
Elixir `v1.9.1` and `Erlang/OTP 22` are what you should use for the master branch or the latest release.

**Comment by vbaranov** [comment]
What is the engine of the archive node, you use to configure Blockscout?

**Comment by Lsquared13** [comment]
I'm on `Erlang/OTP 21` if that could be an issue, but I'm now on elixir `v1.9.1`

> What is the engine of the archive node, you use to configure Blockscout?

I'm not entirely sure what you're asking, but the JSONRPC node that the explorer is supposed to load blocks from is running `geth` rather than `parity` (and yes I have `ETHEREUM_JSONRPC_VARIANT=geth`), if that answers your question.

**Comment by vbaranov** [comment]
Did you configure Geth client properly in order to use it as an archive node? Take a look https://docs.blockscout.com/for-developers/information-and-settings/client-settings-parity-geth-ganache#geth-client

**Comment by vbaranov** [comment]
>I'm on Erlang/OTP 21

Consider to upgrade

**Comment by Lsquared13** [comment]
I'm on `Erlang/OTP 22` now and I tried adding `--syncmode=full` and `--gcmode=archive` to my options and still having the same error

**Comment by tonnypham94** [comment]
Could you help me find the way to get 2000 KETH? I know its a big amount of KETH but my team have to get it to test ours code because we have to create more users. Thank you very much!
My address: 0x93ada4ba1c6eab6fa83f366952a81b1a5d711ad4

**Comment by Lsquared13** [comment]
I figured this out.  I was using a proxy that for some reason didn't parse the requests being generated by blockscout as a valid JSONRPC request.  My proxy was returning error messages with a `null` id, and blockscout simply doesn't expect to deal with a `null` id in a response, since it shouldn't be returning `null` ids.  Connecting directly to a node fixed the issue.

I am curious what exactly those requests looked like that would make my proxy have issues while `curl` commands work fine, but my issue is resolved.
