### ISSUE TITLE
Ethereum Mainnet: <Issue Title>

### ISSUE THREAD

**Issue by daovii99** [poanetwork/blockscout#2935]
0x1eE4F18417894c4662daca80eDd22393aC32E0B8

### Environment
* Elixir Version: 1.9.1
* Erlang Version: 22
* BlockScout Version: v3.0.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 5.1.1; F1w) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.93 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
@daovii99 what is your issue?
