### ISSUE TITLE
Layout issues (gaps of empty space) with Firefox

### ISSUE THREAD

**Issue by d10r** [poanetwork/blockscout#2966]
When browsing Blockscout in Firefox, I recently (probably since Blockscout v2) see gaps of empty space which don't exist in Chrome.

The most pronounced case is in the address view.
Example screenshot:
![image](https://user-images.githubusercontent.com/5479136/72885843-ffde1a80-3d08-11ea-8801-2337ed651b3a.png)

When resizing the window, the gap doesn't go away, even when elements re-arrange due to the responsive layout. In fact, the gap is shown in Mobile Firefox on Android too.

In Chrome, the same page looks like this:
![image](https://user-images.githubusercontent.com/5479136/72885994-46337980-3d09-11ea-8c63-e95f532b1b81.png)

There's also a gap in the transaction view.  
Firefox:
![image](https://user-images.githubusercontent.com/5479136/72886444-1cc71d80-3d0a-11ea-8f71-71868291ac16.png)

Chrome:
![image](https://user-images.githubusercontent.com/5479136/72886486-2c466680-3d0a-11ea-834f-a1deccaf2a9c.png)

I'm currently not aware of other cases.

I observe the issue in Firefox 72 on Linux.  
Turning off all tracking blockers didn't make a difference.

**Comment by vbaranov** [comment]
Fixed and deployed
