### ISSUE TITLE
Incorrect "Token Transfer" displayed if tokens were burnt by the transaction

### ISSUE THREAD

**Issue by akolotov** [poanetwork/blockscout#2970]
If a transaction performs burning of tokens by sending them to the address 0, this will be considered as token transfer operation. It will confuse users. Example of the transaction: https://blockscout.com/poa/xdai/tx/0x1dbd14d65e2bbfa388120f3b601004972310b44090f4d1227d46db6297c52eb5/token_transfers

**Comment by vbaranov** [comment]
@akolotov BlockScout now recognizes and displays proper titles in case of token minting and burning

<img width="388" alt="Screenshot 2020-04-09 at 13 24 38" src="https://user-images.githubusercontent.com/4341812/78885786-da3df300-7a65-11ea-8f14-c7200df725a5.png">

<img width="1081" alt="Screenshot 2020-04-09 at 13 24 47" src="https://user-images.githubusercontent.com/4341812/78885781-d90cc600-7a65-11ea-81ce-5aaef358fab8.png">
