### ISSUE TITLE
`make start` crashes after a few days of analysing enormous blockchain 

### ISSUE THREAD

**Issue by significance** [poanetwork/blockscout#2976]
Hey, we're running a docker instance of Blockscout using `docker/make start` for our testnet. The testnet is running Clique with a 1s block time and 26,701,154 blocks and counting. Everything seems to go well with Blockscout (although it never quite catches up to current blocks) and then eventually the process falls over and throws an error whit attempts to restart it.

I do realise the docker isn't suggested to run the application in production but thought it may be useful for you to see the logs and perhaps provide some insight into whether there is a simple (eg. more resources, recommended deployment) solution, whether our blockchain is simply to big/fast to be supported or if it is neither of the above and something else entirely.

Logs are included below, the first is the crash output followed by output on attempted restart.

Many thanks for your wonderful app! 😄 

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): docker -> bitwalker/alpine-elixir-phoenix:1.9.0
* Operating System: Linux noordung-blockscout 4.15.0-51-generic #55-Ubuntu x86_64 
 GNU/Linux / 8GB RAM / Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz x 4
* Blockscout Version/branch: v2.1.1-beta

### Steps to reproduce

Configure for Noordung blockchain, wait for sync.

### Expected behaviour

Should sync.

### Actual behaviour

Does not quite sync, then crashes.

[blockscout.log](https://github.com/poanetwork/blockscout/files/4118085/blockscout.log)
[blockscout2.log](https://github.com/poanetwork/blockscout/files/4118086/blockscout2.log)

https://blockscout.noordung.fairdatasociety.org/

**Comment by vbaranov** [comment]
@significance what is archive node powered by? what is the set of ENV vars did you configure for Blockscout?

**Comment by significance** [comment]
hey, thanks for response - looks like...

```
export COIN=ETH
export ETHEREUM_JSONRPC_VARIANT=geth
export ETHEREUM_JSONRPC_HTTP_URL=http://127.0.0.1:8545
export ETHEREUM_JSONRPC_WS_URL=wss://127.0.0.1:8545
```

**Comment by vbaranov** [comment]
@significance 
An incorrect port is configured for `ETHEREUM_JSONRPC_WS_URL` since you opened websockets on `8546`, not `8545`. This is why no new blocks appear in the UI.

Also, `ETHEREUM_JSONRPC_TRACE_URL` is missing. Enable it for txs tracing.
You said this chain works on Clique consensus, right? If so you should set `BLOCK_TRANSFORMER=clique`. I urge you to familiarize yourself with all available environment variables https://docs.blockscout.com/for-developers/information-and-settings/env-variables.

**Comment by significance** [comment]
great, thanks for this, i'll adjust the settings and get back to you if still experiencing problems

**Comment by vbaranov** [comment]
@significance did you have a chance to update your instance? btw, have you tried to migrating to 3.0.0 release https://github.com/poanetwork/blockscout/releases/tag/v3.0.0-beta ? If not, I encourage to try. It contains the changes in the fetcher, which is experiencing the issues in your case.

**Comment by vbaranov** [comment]
Please re-open if the issue still presents
