### ISSUE TITLE
Transaction Details

### ISSUE THREAD

**Issue by 1Success** [poanetwork/blockscout#2977]
*Describe your issue here.*
Transaction Details
0x710b459d7c1886f8a3e0d540540f6be85b1f72f360ff5760f1002d20f8834398
0x3c1Db9610573505B10813b70be38851a0cAc0d5c → 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
Contract Call
Success
20 hours ago (January-26-2020 11:03:00 PM +-5 UTC)
Verify with other Explorers:
Blockchair.com
https://blockchair.com/ethereum/transaction/0x710b459d7c1886f8a3e0d540540f6be85b1f72f360ff5760f1002d20f8834398
Etherscan.io
https://etherscan.io/tx/0x710b459d7c1886f8a3e0d540540f6be85b1f72f360ff5760f1002d20f8834398
Etherchain.org
https://www.etherchain.org/tx/0x710b459d7c1886f8a3e0d540540f6be85b1f72f360ff5760f1002d20f8834398
Block Number
9361732
Block Confirmations
5,324
Nonce
60
TX Fee
0.0001336317 ETH ($0.022764 USD)
Transaction Speed
6.9 seconds
Raw Input
Hex (Default)

### Environment
* Elixir Version: 1.9.1
* Erlang Version: 22
* BlockScout Version: v3.0.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
@1Success could you elaborate what is your issue?

**Comment by 1Success** [comment]
I submit my order but never went through and I was charger for the gas and the transaction , and this is the details

**Comment by 1Success** [comment]
Transaction Details
0x710b459d7c1886f8a3e0d540540f6be85b1f72f360ff5760f1002d20f8834398
0x3c1Db9610573505B10813b70be38851a0cAc0d5c → 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
Contract Call
Success
2 days ago (January-26-2020 11:03:00 PM +-5 UTC)
Verify with other Explorers:
Blockchair.com
https://blockchair.com/ethereum/transaction/0x710b459d7c1886f8a3e0d540540f6be85b1f72f360ff5760f1002d20f8834398
Etherscan.io
https://etherscan.io/tx/0x710b459d7c1886f8a3e0d540540f6be85b1f72f360ff5760f1002d20f8834398
Etherchain.org
https://www.etherchain.org/tx/0x710b459d7c1886f8a3e0d540540f6be85b1f72f360ff5760f1002d20f8834398
Block Number
9361732
Block Confirmations
12,611
Nonce
60
TX Fee
0.0001336317 ETH ($0.023527 USD)
Transaction Speed
6.9 seconds
Raw Input
Hex (Default)

**Comment by vbaranov** [comment]
Issue doesn't relate to explorer
