### ISSUE TITLE
Contract verification redirects to 404

### ISSUE THREAD

**Issue by iFA88** [poanetwork/blockscout#2992]
Sadly i can not verificate a simple contract which deployed to the ETC blockchain:
https://blockscout.com/etc/mainnet/address/0xae42cf9974fd6585a33eaf4cc5955ae894d74047/contracts
During verification i'm redirected to https://blockscout.com/etc/mainnet/verify_smart_contract/contract_verifications and got 404 error.

**Contract details:**
solidity 0.4.26
optimisation enabled with 200 runs
default EVM

**Constructor data:**
```
0x000000000000000000000000f69dbe784862957a2ccbd6d8d89c1e951ba20394000000000000000000000000610e3b4e804b367c182c5fc4d65d09c089723389
```

**Source code:**
https://gist.github.com/iFA88/0c735721b1a261b2368c3c1473079634

**Comment by vbaranov** [comment]
@iFA88 Issue resolved by managing HAProxy config. I successfully verified your contract. Sorry for the inconveniences.
