### ISSUE TITLE
Ethereum Classic: Verify contract code not working

### ISSUE THREAD

**Issue by resilience-me** [poanetwork/blockscout#2997]
*Describe your issue here.*

Verification of this contract fails,
https://blockscout.com/etc/mainnet/address/0xf1411b29353f980834d41f3b0c0eafc710da0cdb/contract_verifications/new

It gives a 404 error, "Page not found. The requested path was not found on BlockScout. "

### Environment
* Elixir Version: 1.9.1
* Erlang Version: 22
* BlockScout Version: v3.0.0-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

You can use the contract source code here (hex transaction data payload) and try and verify it yourselves.
https://blockscout.com/etc/mainnet/tx/0xf2385241e84444ffa002c1e8cb15c11deea8d8db6b1674007d76195ad2cfbd49/internal_transactions

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
@resilience-me issue with verification has been resolved by fixing HAProxy config blockscout/haproxy-config#12. Sorry for the inconveniences. I verified your contract.

**Comment by resilience-me** [comment]
np. Just posted for the platform overall, blockscout is the block explorer I tend to use for Ethereum, thanks for providing it. The contract is a very quick implementation of a system I've worked on for 5 years, and, probably has one or two bugs, I'm writing a second implementation now but wanted to have the first as a public reference implementation (it is indexed to private key "pseudonympairs" so can easily find it. )
