### ISSUE TITLE
404 on xDai verification page

### ISSUE THREAD

**Issue by okwme** [poanetwork/blockscout#3004]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System:
* Blockscout Version/branch: 

### Steps to reproduce
Submitting a contract verification on xdai blockexplorer results in a "Page not found".
This can aslo be done by just making a blank verification submission.

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
@okwme it should be fixed now. You can try to verify.
