### ISSUE TITLE
Adjust token transfer constant

### ISSUE THREAD

**Issue by weilbith** [poanetwork/blockscout#3041]
Hey there,
I have a quite theoretical question. I'm experimenting around with a not standardized token. Before recent features have been introduced, it was still recognized as a token within the Blockscout explorer. Now it has slightly changed and does not work anymore for new deployments.
The only thing I can think of is that the `Transfer` event has changed its signature. I saw that within the `indexer` app implementation, it compares the first log entry with the hashed signature stored in the `TokenTransfer.constant()` ([here](https://github.com/poanetwork/blockscout/blob/aec6774c14e1524b4381ffef7134c15d2d3f9e70/apps/indexer/lib/indexer/transform/token_transfers.ex#L18)).
Since this is not a standard token, I would not ask for adoption. Such seems to be quite complicated (I saw [this PR](https://github.com/poanetwork/blockscout/pull/3008/files)). So I ask myself if it would already work out if I adjust that signature hash within my own fork. Would this then work or is the whole processing of tokens more complicated? The first three parameter of the `Transfer` event are the same as for ERC20 tokens. The additional data must not be indexed. It is more about making these token contracts better visible, searchable and list transfers.
Unfortunately I can't try this approach locally at the moment. Therefore I would like to ask you if you think this could work or if that is simply not possible without a mature extension of the code?
Thank you so much for your help!

**Comment by vbaranov** [comment]
@weilbith If the `Transfer` event changed its signature than I suppose it changed the interface, right? In this case, you also need to change parser function too https://github.com/poanetwork/blockscout/blob/aec6774c14e1524b4381ffef7134c15d2d3f9e70/apps/indexer/lib/indexer/transform/token_transfers.ex#L36 to be compliant with a new event interface.

**Comment by weilbith** [comment]
Hmm yes I think it is not so easy. And maybe not a good idea at all. I think we
need to think about a major update like in the referenced PR. Thanks for you
help anyways.
