### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by larayusuf** [poanetwork/blockscout#3045]
Sir, 
A friend send some etheruem classic to me 
I cannot access it because the account was open on luno platform. They don't accept any other cryptocurrency apart from etheruem on there platform. 
I wrote to them they told me so below is the letter I sent to luno And reply they sent to me. 
Please how can I access this coin and use I need solution thanks. 

Hi Yakubu

At Luno we only support Ethereum.

As a result, our system does not possess or have access to the unsupported cryptocurrency that got transferred to your Luno Wallet in error. We are entirely unable to access or recover these funds.

You can read more about common accidental cryptocurrency sends here:
https://www.luno.com/help/en/articles/11000080120

We sympathise with your unfortunate situation, but as outlined in detail above, we are regrettably not in a position to assist you.

Kind regards,
Robynne
Luno Customer Success Team

￼

On Mon, Mar 2, 2020 at 9:29 AM <support@luno.com> wrote:

On Mon, Mar 2, 2020 at 9:29 AM <> wrote:

Sir,
My friend was supposed to send etheruem to my luno address below
0xB3c5A50f3dCaB4964e4f826a131e028209DE2F77.

SHe is knot too familiar with cryptocurrency she sent etheruem classic instead of etheruem.
And I understand that another cryptocurrency cannot be transfered to my luno address.
Please I need help for this transaction to be reverse to the sender so that the correct etheruem can be send to me please.
Below is the link This link will confirm the transfer
https://classic.etccoopexplorer.com/address/0xB3c5A50f3dCaB4964e4f826a131e028209DE2F77/transactions.
I need the this transaction to be reverse.
Thanks.

￼

**Comment by vbaranov** [comment]
@larayusuf Blockscout doesn't possess accounts private keys. Since the account was created through the wallet, only wallet's support could help you.
