### ISSUE TITLE
Failed to decode input data for a function that uses a `bytes` parameter

### ISSUE THREAD

**Issue by varasev** [poanetwork/blockscout#3049]
Example transaction: https://blockscout.com/poa/sokol/tx/0xb66adc3751ea816f89c7263b2e85a633c1004f44fa44b84274362b54b6d41575/internal_transactions

It calls a `commitHash` function of the [Randomness contract](https://blockscout.com/poa/sokol/address/0x8f2b78169B0970F11a762e56659Db52B59CBCf1B/contracts).

The input parameters are:

`bytes32 _numberHash` = `0x020fa7d0e7d1c4ceab9ec32e69567eae73a792de9bcf24d69d16f53848134f95`

`bytes _cipher` = `0x0468348515eb361b0bc80c0d423ab15e4cc677b3803b56ae531c91fa3101df8fe4576c86a562ebc8c177a3cf9f2780486b7be7412039983207a456e84a7c5c17a2b115f85b2add7894174645d038b181e9e7dc550408713b682bbeec469f8053c33eb952a38f39baf9dd3b28e36d718fba3ead6be636ebe66ce8dfbc2eaf55ef52cf53d762918605cee5449be066aa1f47`

But Blockscout displays `Failed to decode input data` error for the transaction:

![image](https://user-images.githubusercontent.com/33550681/76427928-078f7680-63be-11ea-8d3e-9e6cb792a40d.png)

**Comment by varasev** [comment]
Now, it correctly decodes tx input data, but I'd propose to align values to the left: when I open the page https://blockscout.com/poa/sokol/tx/0xb66adc3751ea816f89c7263b2e85a633c1004f44fa44b84274362b54b6d41575/internal_transactions I don't see the value of `_numberHash` until I scroll to the right (because the second parameter `_cipher` has a lot of bytes).

![image](https://user-images.githubusercontent.com/33550681/77068542-dc2d0d00-69f7-11ea-9c26-02873c4f1ed2.png)

![image](https://user-images.githubusercontent.com/33550681/77068578-ee0eb000-69f7-11ea-85df-7cc05e1e614c.png)

**Comment by vbaranov** [comment]
Displaying also fixed - horizontal scroll will not appear anymore.
