### ISSUE TITLE
Unable to update my blocks it's blank please go with given url https://blockchain.nimbus-t.com/accounts#

### ISSUE THREAD

**Issue by rajnishtech** [poanetwork/blockscout#3052]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System:
* Blockscout Version/branch: 

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Wrong Node.js version is used. Related thread is here https://gitter.im/poanetwork/blockscout?at=5e6a3838a2ccef3232eb7bd0

**Comment by vbaranov** [comment]
@rajnishtech were you able to re-build front-end assets with the required version of Node.js (12.x, currently) ?
