### ISSUE TITLE
Not able to verify source code of contract in ETC

### ISSUE THREAD

**Issue by patidarmanoj10** [poanetwork/blockscout#3059]
*Describe your issue here.*
Not able to verify source code of contract in ETC. After entering all data correctly, I click on verify & publish button but it show waiting indicator forever. 
### Environment
ETC

**Comment by isentropy** [comment]
I have the exact same issue. We use the docker images at Streamr. 

Reverting to older commit 9037ece644f8557e4d01eefda25c4608bb4f69da fixes the problem.

**Comment by vbaranov** [comment]
Contract verification feature has been repaired on ETC instance of Blockscout. Thanks for the patience.
