### ISSUE TITLE
Inconsistent Parameter on the Details of Transaction History: TRANSACTION SPEED

### ISSUE THREAD

**Issue by geoinheritance** [poanetwork/blockscout#3072]
*Describe your issue here.*
I recently noticed that the parameter called TRANSACTION SPEED is inconsistent in the details of both SENT AND RECEIVED transaction histories. The TRANSACTION SPEED is displayed in some transactions, in other transactions the TRANSACTION SPEED is not displayed when we tried to view MORE DETAILS of our Token on POA Core network using Trust Wallet.

PLEASE NOTE THAT THE DISPLAY OF "TRANSACTION SPEED"  NEED TO BE RESTORED QUICKLY AT ALL COSTS BECAUSE IT IS OUR SELLING POINT FOR THE MAJOR USE CASE OF OUR TOKEN ON THE POA NETWORK, AND IT CRITICAL TO THE GROWTH OF POA COMMUNITY.

### Environment
* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System:
* Blockscout Version/branch: 

In the Trust Wallet installed on
![YES_TransactionSpeed](https://user-images.githubusercontent.com/39395850/79057377-e342e600-7c58-11ea-9ad1-63e8b2736985.jpg)

Android OS of a 4G smart phone.

### Steps to reproduce
*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

Just use Trust wallet on an Android phone to receive and send any amount of a Token created on POA Core network. 

After the confirmation, explore the history by clicking on a either SENT or RECEIVED.

Then click MORE DETAILS to view additional details including Transaction History.

### Expected behaviour
*Tell us what should happen.*

The Transaction Details should follow the below sequence:

Block Number
Block Confirmations
Nonce
TX Fee
Transaction Speed
Raw Input

### Actual behaviour
*Tell us what happens instead.*

Block Number
Block Confirmations
Nonce
TX Fee
<missing info>
Raw Input

![YES_TransactionSpeed](https://user-images.githubusercontent.com/39395850/79057383-f5248900-7c58-11ea-9909-ce3b1c16a342.jpg)
![NO_TransactionSpeed](https://user-images.githubusercontent.com/39395850/79057394-0bcae000-7c59-11ea-8809-27d291e83747.jpg)

**Comment by vbaranov** [comment]
@geoinheritance transaction speed is not stored on-chain. It is calculated if Blockscout got that transaction from pending tx pool before it has been mined. But it cannot be reliably done for 100% of transactions in a short time-frame because of the speed of blocks appearance. I can offer you instead of showing no speed for such transactions, show that speed of transaction is less or equal than a current average block time:

<img width="294" alt="Screenshot 2020-05-22 at 15 27 59" src="https://user-images.githubusercontent.com/4341812/82667893-66386280-9c41-11ea-8096-980c9c663754.png">

Let me know if this is suitable for you and I will prepare a change.

**Comment by geoinheritance** [comment]
Thanks for your belated reply.

It is ok. Go and implement it. Please, let me know when it is executed.

Secondly, I need your team to create a pseudo exchange platform and related
API that all tokens created on POA platform can use to set price in dollars
and GET price for the token to show on their platform of wallets including
Trust wallets. this will support our ongoing project on DeFi on POA Core
adoption. The base

If you need details on this innovative idea that will enhance POA Main
Network adoption, please let us chat on Telegram; t.me/A_JamesO
