### ISSUE TITLE
fetcher=block_uncle count=10 [error] Task Indexer.Fetcher.UncleBlock

### ISSUE THREAD

**Issue by kunpoolsion** [poanetwork/blockscout#3074]
After deployment I have a recurrent error, every 3 or 4 miliseconds.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
Erlang/OTP 21 [erts-10.3.5.10] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
Elixir 1.10.0 (compiled with Erlang/OTP 21)
* Operating System: Centos 7.7
* Blockscout Version/branch: 3.1.1
* Node: v12.16.2
* Postgresql: 10.12
* Network: Pirl

### Steps to reproduce

After fresh install and start phx.server the error will start coming.

### Expected behaviour

Sync normally.

### Actual behaviour

Everything looks running cool but these errors:
`2020-04-14T04:10:22.067 fetcher=block_uncle count=10 [error] Task Indexer.Fetcher.UncleBlock started from #PID<0.15414.188> terminating
** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Block.elixir_to_params/1
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/block.ex:194: EthereumJSONRPC.Block.elixir_to_params(%{"difficulty" => 318658722408, "extraData" => "0x5069726c50504c4e532f326d696e657273", "gasLimit" => 8000000, "gasUsed" => 21000, "hash" => "0xc91df39cc5cd859e24a13d9bbb800e945027f283612ace7d1641ceed27e36fcb", "logsBloom" => "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "miner" => "0x00d29bfdf5f8d2d0466da4b948f37692ca50867a", "mixHash" => "0x0af5397d5d50ab1e5cd51aba76402d421f3298b1326cb6289a9ce0ff44926fd5", "nonce" => "0x484028e37ee7e675", "number" => 5701812, "parentHash" => "0xb27eaa1344354e2aaf21cdcf65f640b3ccadac0ad855ad92332f91768e310847", "receiptsRoot" => "0xbed0382dce83c67cb68e9dab45a8cc4b9b8bc8e0f2e2b14a97b4b07ebe1b4b74", "sha3Uncles" => "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347", "size" => 535, "stateRoot" => "0x889d47e23d9a89171a225d4176e42d6d00dd14d5c5da9890b5c63d8bf5cd5708", "timestamp" => ~U[2020-02-03 05:04:26Z], "transactionsRoot" => "0xe25e5c4866ae2858c67aff196722be258f62523cfb0cf5274255ced302fc7297", "uncles" => []})
    (elixir 1.10.0) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/blocks.ex:51: EthereumJSONRPC.Blocks.from_responses/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc.ex:464: EthereumJSONRPC.fetch_blocks_by_params/3
    (indexer 0.1.0) lib/indexer/fetcher/uncle_block.ex:84: Indexer.Fetcher.UncleBlock.run/2
    (elixir 1.10.0) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.0) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.8.2.3) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Indexer.BufferedTask.log_run/1
    Args: [%{batch: [{<<183, 174, 193, 97, 65, 169, 245, 165, 231, 104, 231, 241, 38, 81, 146, 141, 114, 118, 250, 68, 236, 105, 28, 119, 127, 83, 82, 120, 74, 11, 226, 130>>, 0}, {<<127, 26, 82, 162, 129, 142, 146, 131, 151, 59, 169, 69, 148, 88, 254, 253, 143, 47, 71, 50, 90, 143, 105, 53, 109, 243, 65, 225, 59, 21, 13, 154>>, 0}, {<<33, 66, 181, 48, 63, 201, 153, 99, 138, 183, 166, 230, 66, 116, 245, 154, 143, 67, 52, 88, 49, 10, 189, 113, 149, 218, 26, 246, 37, 112, 9, 143>>, 0}, {<<216, 43, 236, 210, 234, 138, 221, 183, 228, 144, 191, 59, 65, 140, 227, 142, 162, 225, 38, 129, 251, 63, 116, 94, 13, 59, 200, 68, 125, 146, 183, 83>>, 1}, {<<67, 25, 218, 140, 247, 50, 196, 55, 102, 67, 168, 93, 35, 180, 57, 91, 157, 110, 231, 95, 16, 61, 125, 143, 108, 112, 1, 93, 135, 197, 193, 3>>, 0}, {<<115, 163, 203, 238, 158, 221, 250, 27, 213, 214, 78, 76, 169, 106, 252, 43, 89, 229, 108, 66, 153, 207, 170, 86, 116, 7, 21, 68, 240, 166, 222, 150>>, 0}, {<<156, 30, 176, 217, 112, 136, 48, 161, 178, 125, 206, 208, 175, 14, 230, 198, 149, 93, 208, 55, 26, 94, 66, 137, 101, 88, 118, 33, 165, 237, 58, 37>>, 0}, {<<86, 101, 150, 137, 75, 29, 195, 22, 3, 215, 64, 100, 86, 111, 201, 72, 36, 42, 95, 16, 66, 169, 91, 107, 227, 241, 207, 218, 240, 188, 24, 226>>, 0}, {<<24, 6, 87, 176, 123, 21, 208, 153, 52, 91, 142, 206, 205, 204, 134, 42, 137, 236, 7, 224, 222, 143, 215, 43, 201, 242, 49, 170, 138, 187, 179, 179>>, 0}, {<<193, 63, 250, 121, 235, 36, 81, 119, 163, 9, 42, 162, 5, 7, 137, 142, 78, 3, 113, 68, 100, 186, 242, 1, 102, 215, 46, 186, 122, 136, 190, 193>>, 1}], callback_module: Indexer.Fetcher.UncleBlock, callback_module_state: %Indexer.Block.Fetcher{broadcast: :uncle, callback_module: Indexer.Fetcher.UncleBlock, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://localhost:6588", http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, metadata: [fetcher: :block_uncle]}]`

**Comment by vbaranov** [comment]
@kunpoolsion what client and version are used on archive Ethereum node?

**Comment by kunpoolsion** [comment]
We are using geth (1.9.12), but a fork will happen in 2 days and will change to constantinople.
Didn´t check before posting, sorry, my mistake. 
Lets wait for the fork? I will post after if errors gone or anything else.
Thx

**Comment by vbaranov** [comment]
@kunpoolsion yes, please let me please know what will happen after the fork.

**Comment by kunpoolsion** [comment]
Sorry for delay, fork already done and node full synced from zero.
Still same errors
Any advice?

**Comment by kunpoolsion** [comment]
When starting to index token, the cpu usage is 100% always and reporting more errors than before, is not even capable of render the webpage

**Comment by kunpoolsion** [comment]
Any news on this issue?

**Comment by kunpoolsion** [comment]
Any advice, @vbaranov, will be appreciated ;)

**Comment by vbaranov** [comment]
@kunpoolsion it looks like your Geth node returns some extra fields from `eth_getBlockByHash` endpoint, which Blockscout doesn't expect. Please, provide a response from your archive node from this endpoint https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getblockbyhash for any existing in the chain block

**Comment by kunpoolsion** [comment]
Thx for reply
This is what I get:
`{"jsonrpc":"2.0","id":1,"result":{"difficulty":"0x24e3877d5a","extraData":"0x636f6d696e696e672e696f","gasLimit":"0x7a1200","gasUsed":"0x0","hash":"0x9aa22f329433b35d5c1bbed0f57d15276e129a478fa9127686482e6a582d8171","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","miner":"0x139f0470d4de7e2b3ff1fb7eecda9ec31d524509","mixHash":"0x7f5b96ac4ac0005f44650479af2c6530bb03f70018155a3e10bb2300273d2fcc","nonce":"0x197b100627d92545","number":"0x606801","parentHash":"0xadde88aee3a16b014e16cee19dcb71d14c280b43e7233787635aba01824d9f66","receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","size":"0x20f","stateRoot":"0xb5862be65a0657bcce459461bcdceb4870955eec481cf471cfaaf7a2f5231c3c","timestamp":"0x5ec7aa45","totalDifficulty":"0x136aa9bdb67a18821","transactions":[],"transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","uncles":[]}}`

**Comment by vbaranov** [comment]
Thanks. This response looks fine. Could you also post a response from this block `0xc91df39cc5cd859e24a13d9bbb800e945027f283612ace7d1641ceed27e36fcb`? From the initial logs you posted, response doesn't;t contain `totalDifficulty` param for it and this causes the issue.

**Comment by kunpoolsion** [comment]
weird, that hash is a transaction:
{"jsonrpc":"2.0","id":1,"result":null}

**Comment by kunpoolsion** [comment]
let me check the logs and take a new error

**Comment by kunpoolsion** [comment]
`2020-05-22T12:34:42.072 fetcher=block_uncle count=10 [error] Task Indexer.Fetcher.UncleBlock started from #PID<0.2179.26> terminating
** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Block.elixir_to_params/1
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/block.ex:194: EthereumJSONRPC.Block.elixir_to_params(%{"difficulty" => 379100814272, "extraData" => "0x5069726c50504c4e532f326d696e657273", "gasLimit" => 7999984, "gasUsed" => 0, "hash" => "0xe1276dcec898fd7a7b946669cd89ef241d64a4f3ae33db320c5ebead4065bd46", "logsBloom" => "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "miner" => "0x00d29bfdf5f8d2d0466da4b948f37692ca50867a", "mixHash" => "0x72d159cc93beb1f68f3d8d937064d9a7ae499864b15216053138465c79d9b4e4", "nonce" => "0x6a378bf4270ba5db", "number" => 5921391, "parentHash" => "0xe2a8fb8bc051728ded1b3284d482ba106bbb889bab0bc30045311b9956e6aa75", "receiptsRoot" => "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421", "sha3Uncles" => "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347", "size" => 533, "stateRoot" => "0x837efdb86f01a28c30744e733010aa1dadd4f70170e4952c67eb0deffa266efe", "timestamp" => ~U[2020-03-10 11:19:11Z], "transactionsRoot" => "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421", "uncles" => []})
    (elixir 1.10.0) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/blocks.ex:51: EthereumJSONRPC.Blocks.from_responses/2
    (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc.ex:454: EthereumJSONRPC.fetch_blocks_by_params/3
    (indexer 0.1.0) lib/indexer/fetcher/uncle_block.ex:84: Indexer.Fetcher.UncleBlock.run/2
    (elixir 1.10.0) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.0) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.9) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Indexer.BufferedTask.log_run/1
    Args: [%{batch: [{<<231, 126, 98, 227, 190, 20, 56, 216, 77, 142, 238, 115, 118, 229, 158, 70, 180, 74, 255, 173, 5, 101, 169, 195, 4, 191, 240, 48, 175, 76, 223, 24>>, 0}, {<<121, 115, 102, 152, 25, 169, 81, 201, 184, 39, 1, 34, 48, 19, 15, 1, 2, 183, 181, 198, 63, 185, 99, 55, 115, 90, 167, 173, 93, 17, 242, 205>>, 0}, {<<111, 170, 188, 9, 60, 97, 139, 102, 140, 135, 92, 208, 28, 42, 194, 195, 126, 31, 202, 182, 91, 68, 38, 24, 163, 84, 132, 90, 248, 9, 101, 171>>, 0}, {<<25, 210, 18, 202, 208, 207, 39, 132, 106, 180, 156, 239, 73, 213, 233, 167, 91, 8, 144, 80, 95, 213, 245, 209, 241, 149, 13, 31, 164, 166, 219, 196>>, 0}, {<<56, 1, 128, 25, 239, 78, 104, 105, 222, 191, 190, 127, 92, 94, 194, 184, 233, 102, 168, 90, 95, 89, 235, 107, 29, 36, 15, 181, 153, 181, 84, 44>>, 0}, {<<104, 230, 240, 25, 194, 41, 32, 157, 147, 248, 15, 121, 153, 114, 215, 41, 227, 63, 11, 53, 113, 247, 174, 20, 252, 109, 20, 60, 31, 70, 64, 55>>, 0}, {<<185, 21, 231, 94, 46, 105, 244, 25, 137, 88, 170, 92, 109, 208, 246, 199, 173, 194, 191, 84, 234, 179, 236, 125, 79, 155, 84, 167, 65, 150, 106, 17>>, 0}, {<<249, 71, 186, 154, 230, 78, 11, 46, 129, 223, 231, 185, 66, 115, 19, 142, 59, 111, 249, 37, 78, 145, 22, 182, 207, 216, 220, 62, 204, 60, 64, 99>>, 0}, {<<76, 79, 53, 49, 8, 224, 10, 9, 166, 255, 117, 177, 47, 97, 93, 25, 7, 52, 254, 99, 227, 43, 100, 242, 108, 234, 20, 40, 25, 83, 162, 188>>, 0}, {<<5, 121, 159, 20, 252, 223, 67, 34, 41, 208, 14, 29, 118, 242, 181, 64, 65, 246, 154, 13, 116, 111, 252, 199, 148, 59, 132, 20, 45, 101, 121, 78>>, 0}], callback_module: Indexer.Fetcher.UncleBlock, callback_module_state: %Indexer.Block.Fetcher{broadcast: :uncle, callback_module: Indexer.Fetcher.UncleBlock, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://localhost:6588", http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, metadata: [fetcher: :block_uncle]}]
`

In this case is a TX hash too

**Comment by vbaranov** [comment]
Thanks. No, they are not txs hashes. They are uncle blocks. Investigating...

**Comment by kunpoolsion** [comment]
True
Thx goes to you.
Do you need ip of the rpc?

**Comment by vbaranov** [comment]
It would be awesome if you can provide it for the time of the investigation.

**Comment by kunpoolsion** [comment]
Sent to your mail

**Comment by vbaranov** [comment]
Got it. Thanks. The fix is on the way

**Comment by kunpoolsion** [comment]
really appreciated

**Comment by vbaranov** [comment]
@kunpoolsion I created a fix https://github.com/poanetwork/blockscout/pull/3121 (branch `vb-block-responnse-without-total-difficulty`). Please try to apply it on your end and let me know if the issue is eliminated or not.

**Comment by kunpoolsion** [comment]
Thanks, applying
Will keep you informed

**Comment by kunpoolsion** [comment]
Works like charm.
Thanks so much
