### ISSUE TITLE
Can't verify token contract on Mainnet

### ISSUE THREAD

**Issue by varasev** [poanetwork/blockscout#3081]
I'm trying to verify this contract: https://blockscout.com/eth/mainnet/address/0x0Ae055097C6d159879521C384F1D2123D1f195e6/contracts

It's successfully [verified in etherscan](https://etherscan.io/address/0x0Ae055097C6d159879521C384F1D2123D1f195e6#code) but in Blockscout I get encoding constructor arguments error.

I tried either to fetch constructor arguments automatically and to manually enter them in as follows:

 ```
00000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000009bc4a93883c522d3c79c81c2999aab52e2268d030000000000000000000000003cfe51b61e25750ab1426b0072e5d0cc5c30aafa0000000000000000000000000218b706898d234b85d2494df21eb0677eaea91800000000000000000000000000000000000000000000000000000000000000055354414b4500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000055354414b45000000000000000000000000000000000000000000000000000000
```

It looks like the same issue as with `ex-abi`.

**Comment by vbaranov** [comment]
The fix https://github.com/poanetwork/blockscout/pull/3092 installed to Mainnet instance of Blockscout. I successfully verified contract https://blockscout.com/eth/mainnet/address/0x0Ae055097C6d159879521C384F1D2123D1f195e6/contracts
