### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by envymc1** [poanetwork/blockscout#3083]
*Describe your issue here.*
Transfer from my coinbase wallet to coinbase account over 5 hour ago saying its pending but not confirmed 
### Environment
* Elixir Version: 1.9.4
* Erlang Version: 22
* BlockScout Version: v3.0.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 9; SM-G950F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.117 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
How can I help you?

**Comment by envymc1** [comment]
My transfer of ETC from my coinbase wallet to my coinbase account hasn't cleared it's still pending and has since 8.45 last night

**Comment by vbaranov** [comment]
Do you see pending status when you open transaction page at Blockscout? There maybe different reasons why the chain does not accept your transfer. Blockscout is explorer. It doesn’t manage transactions.

**Comment by envymc1** [comment]
It saying can not find transaction history and say the block doesn't exist

**Comment by vbaranov** [comment]
Which block number?

**Comment by vbaranov** [comment]
@envymc1 I guess it is a question of time and Blocksout fetched missing block. Please re-open if it is still relevant by accompanying more details if the issue is with concrete block.
