### ISSUE TITLE
Ethereum Classic: ETC balance shows on blockscout but not in MEW

### ISSUE THREAD

**Issue by sky-rgb** [poanetwork/blockscout#3086]
ETC balance shows on blockscout but not in MEW wallet on MAC desktop or on iPhone app. Has anyone else had success resolving this problem or have suggestions on how to?

**Comment by vbaranov** [comment]
@sky-rgb did you see all Blockscout transactions which should be at the address at that time? Possibly, the latest transactions were not fetched by an explorer from the Ethereum node yet by that moment. The delay in fetching will be higher with more transactions in the block.

**Comment by vbaranov** [comment]
Please re-open if the issue still exists
