### ISSUE TITLE
Can't verify token contract on xDai

### ISSUE THREAD

**Issue by varasev** [poanetwork/blockscout#3090]
I'm trying to verify this contract: https://blockscout.com/poa/xdai/address/0xAb84415fBB0D35abc08dee250356F19Bc37aBaeA/contracts

But Blockscout tells there are `Wrong constructor arguments`.

I tried either to fetch constructor arguments automatically and to manually enter them in as follows:

```
000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000006400000000000000000000000000000000000000000000000000000000000000055354414b4500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000055354414b45000000000000000000000000000000000000000000000000000000
```

The source code is here: https://github.com/poanetwork/posdao-contracts/blob/d064ab7fcd5c695a4365cd8b24e84ff817e391ef/contracts/ERC677BridgeTokenRewardable.sol

**Comment by vbaranov** [comment]
@varasev could you please also indicate was optimization during compilation used or not?

**Comment by vbaranov** [comment]
And what is the contract name?

**Comment by varasev** [comment]
Yeah, sorry:

Contract name: ERC677BridgeTokenRewardable
Optimization enabled: true
Compiler version: v0.5.10+commit.5a6ea5b1
Optimization runs: 200
EVM Version: default

**Comment by vbaranov** [comment]
Contract verified https://blockscout.com/poa/xdai/address/0xAb84415fBB0D35abc08dee250356F19Bc37aBaeA/contracts with the fix https://github.com/poanetwork/blockscout/pull/3092. Decoded view for constructor arguments is not shown. I will address it in a separate PR.
