### ISSUE TITLE
xDai: <Issue Title>

### ISSUE THREAD

**Issue by CharlyCnS3** [poanetwork/blockscout#3102]
*Describe your issue here.*

Hi, I did this transaction, which says it has completed, but it doesn't reach my bitmex address.
Could you help me?
This transaction:

0x5644c0f63293f4eeba8bf2bdcc761b43f98788af83b43c2b70b877da9d9fbb62

### Environment
* Elixir Version: 1.10.2
* Erlang Version: 22
* BlockScout Version: v3.1.2-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Blockscout team unable to help with that. You should reach out bitmex team.
