### ISSUE TITLE
Omit 0x0 address from this list: https://blockscout.com/poa/xdai/accounts

### ISSUE THREAD

**Issue by GriffGreen** [poanetwork/blockscout#3103]
*Describe your issue here.*
<img width="1173" alt="Screen Shot 2020-05-09 at 9 01 18 PM" src="https://user-images.githubusercontent.com/14945613/81482580-56c81b00-9238-11ea-8191-deb9449fd2e4.png">

Would be great to omit the 0x0 address from this list: https://blockscout.com/poa/xdai/accounts

### Environment
* Elixir Version: 1.10.2
* Erlang Version: 22
* BlockScout Version: v3.1.2-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by igorbarinov** [comment]
we don't plan to remove it from the list of accounts because it's a legit address and keeps essential information.
The percentage calculation is messed because of this address. % is metadata and we can amend it. Do you think we should fix it and exclude 0x0 acc from it?

**Comment by vbaranov** [comment]
I removed balance percentage at xDai instance for burn address. Please let me know if I hurried-up.

**Comment by vbaranov** [comment]
I am closing this issue for now. If it is still actual please re-open.
