### ISSUE TITLE
Ethereum Classic: getBlockReward returns 500

### ISSUE THREAD

**Issue by Mrostgaard** [poanetwork/blockscout#3107]
The endpoint:
?module=block&action=getblockreward&blockno={blockNumber}

for any blockNumber returns 500

example: 

curl -X GET "https://blockscout.com/etc/mainnet/api?module=block&action=getblockreward&blockno=10383916" -H "accept: application/json"

### Environment
* Elixir Version: 1.9.4
* Erlang Version: 22
* BlockScout Version: v3.0.0-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:75.0) Gecko/20100101 Firefox/75.0`

### Steps to reproduce

visit endpoint: 

https://blockscout.com/etc/mainnet/api?module=block&action=getblockreward&blockno=10383916

### Expected Behaviour
returns something like: 
{
  "message": "OK",
  "result": {
    "blockMiner": "0x13a06d3dfe21e0db5c016c03ea7d2509f7f8d1e3",
    "blockNumber": "2165403",
    "blockReward": "5314181600000000000",
    "timeStamp": "1472533979",
    "uncleInclusionReward": null,
    "uncles": null
  },
  "status": "1"
}

### Actual Behaviour

returns: 
{"status":"0","result":null,"message":"Something went wrong."}

**Comment by vbaranov** [comment]
BlockRewad API endpoint repaired by setting the path to chain spec.

**Comment by Donquih0te** [comment]
The problem appeared again

**Comment by vbaranov** [comment]
> The problem appeared again

@Donquih0te this API endpoint from ETC instance works fine.
