### ISSUE TITLE
LUKSO L14: <Issue Title>

### ISSUE THREAD

**Issue by srd23** [poanetwork/blockscout#3109]
*Describe your issue here.*

### Environment
* Elixir Version: 1.10.2
* Erlang Version: 22
* BlockScout Version: v3.1.2-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by srd23** [comment]
nasıl olcak bu işler

**Comment by srd23** [comment]
bu aldığım lyx ler ne olcak

**Comment by srd23** [comment]
bu aldığımız lyx ler ne olacak

**Comment by srd23** [comment]
blok onaylaması nasıl yapılıyo

**Comment by vbaranov** [comment]
Describe your issue in English
