### ISSUE TITLE
Energy Web Chain: <I send EWT tokens to my ETH address, did not know they are not ERC 20 tokens> 

### ISSUE THREAD

**Issue by transstar** [poanetwork/blockscout#3116]
Hi, I send EWT tokens to my ETH address and now I am not sure how to get them back. 

Below is my wallet information so they are sitting in wallet "0xa6391cD91F5a3c2667fb1C487D097E8a29e64936" which is my ETH wallet, but I have no way of sending them to the right now since my ledger does not recognize this as a account on the app. 

Transaction Details

0x67cd5e5acd1bd5b4efb8434e4932ebbe263f862ef0e001e1e621b85615743a5b

0xa0B00A719512293beA1b3B6735eceA5e45fD47b4 → 0xa6391cD91F5a3c2667fb1C487D097E8a29e64936
Transaction
Success
2 hours ago (May-18-2020 08:51:10 PM +-7 UTC)
Block Number
5765763
Block Confirmations
1,575
Nonce
189
TX Fee
0.000000000000021 EWT (Less than $0.000001 USD)
Transaction Speed
13.1 seconds

Can you please advice me how to get these tokens back, thank you.

**Comment by vbaranov** [comment]
Connect to EWT Ethereum JSON RPC endpoint (if any public one is available) in MetMask/MyCrypto/MEW/... unlock your account using your private key and send them back. The question doesn't relate to BlockScout, though
