### ISSUE TITLE
RSK: not sync with mainnet, may need update your RSK version to latest

### ISSUE THREAD

**Issue by lcgogo** [poanetwork/blockscout#3135]
*Describe your issue here.*

### Environment
* Elixir Version: 1.10.2
* Erlang Version: 22
* BlockScout Version: v3.1.2-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:76.0) Gecko/20100101 Firefox/76.0`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
@lcgogo RSK instance is syncing again.

**Comment by lcgogo** [comment]
> @lcgogo RSK instance is syncing again.

Thanks!
