### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by alisaf44** [poanetwork/blockscout#3138]
*Describe your issue here.*

### Environment
* Elixir Version: 1.9.1
* Erlang Version: 22
* BlockScout Version: v3.0.0-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 13_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by alisaf44** [comment]
I send my ethereum classic to my ethereum address and it pending

**Comment by vbaranov** [comment]
Wait until transaction will be confirmed

**Comment by alisaf44** [comment]
I never received it and it’s saying complete

**Comment by alisaf44** [comment]
This is so frustrating I worked hard on building it up at a good price
