### ISSUE TITLE
Chiliz: <Issue Title>

### ISSUE THREAD

**Issue by tapan50** [poanetwork/blockscout#3139]
386/5000
On April 16 the mobile 0x0cbfa5836f4bb0c0b03919cf215810dcedcf7595 I transferred to this address from the socios 10 juve but when I search I have sent the wrong place gönderildi.kod address the https://explorer.chiliz.com/tx/0x1e8b891d33570c0588f51a5fe56fd56e34b49a74d48215ec66236e72e88c6aee/token_transfers 10 juve görüyorum.b I have sent again can you send to socios

**Comment by vbaranov** [comment]
@tapan50 You should contact Chiliz team for that. This issue tracker for the issues with explorer itself.
