### ISSUE TITLE
Blockscout doesn't detect internal transaction

### ISSUE THREAD

**Issue by APshenkin** [poanetwork/blockscout#3141]
*Describe your issue here.*

### Steps to reproduce

https://blockscout.com/eth/mainnet/tx/0xe8445ec6ceea20448292549bb57662fd737d348a92b25da074f45f48f28bfcaf/internal_transactions

blockscout don't see internal transactions for this tx

but etherscan does
https://etherscan.io/tx/0xe8445ec6ceea20448292549bb57662fd737d348a92b25da074f45f48f28bfcaf

### Expected behaviour
internal transaction appears

### Actual behaviour
No internal transaction

**Comment by vbaranov** [comment]
Target block has been processed finally

<img width="1167" alt="Screenshot 2020-06-05 at 18 10 37" src="https://user-images.githubusercontent.com/4341812/83892859-e7224e80-a757-11ea-8e65-f4f15d2ad759.png">
