### ISSUE TITLE
Energy Web Chain: Txn not showing up on Etherscan.io

### ISSUE THREAD

**Issue by sidray88** [poanetwork/blockscout#3147]
*My transaction TXN hash: 0x322e9e828075cbacd61138c2b6d9e186fc047660eafba0f71d5fa42e0fd71b27 isn't showing up on Etherscan.io or any other but shows up on the block explorer here:

https://explorer.energyweb.org/tx/0x322e9e828075cbacd61138c2b6d9e186fc047660eafba0f71d5fa42e0fd71b27/internal_transactions

Can you please tell me what's going on here? 

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Every chain should have different chainID. Etherscann is the explorer for ETH Mainnet with chain ID = 1 https://ethereum.stackexchange.com/questions/17051/how-to-select-a-network-id-or-is-there-a-list-of-network-ids/17101#17101. Energyweb chain has a different chain ID. Mentioned transaction was made when connected to Energyweb chain.
