### ISSUE TITLE
Energy Web Chain: <Issue Title>

### ISSUE THREAD

**Issue by suleimansultan81** [poanetwork/blockscout#3148]
##*Unable to add the EWT address to Trezor*

### Environment
* Elixir Version: 1.10.2
* Erlang Version: 22
* BlockScout Version: v3.1.1-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:77.0) Gecko/20100101 Firefox/77.0`

### Steps to reproduce

*When adding the EWT address to Trezor, it mentions the version of Trezor 2.31 has some sort of compatibility issue.*

### Expected Behaviour

*It should have added the address to Trezor and it fails.*

### Actual Behaviour

*Fails to add.*

**Comment by vbaranov** [comment]
Wrong place to ask. This is Blockscout issues tracker.
