### ISSUE TITLE
Energy Web Chain: <Issue Title>

### ISSUE THREAD

**Issue by RGordo3** [poanetwork/blockscout#3151]
Hi,

I transferred this transaction - https://explorer.energyweb.org/address/0x7d4D4cE8592F6df8A6A38da5B56f3Dd61f71bD51/transactions
From Liquid Exchange to "MyEtherWallet" My address (0x7d4D4cE8592F6df8A6A38da5B56f3Dd61f71bD51)

I was under the impression they were an ERC-20 token. But I dont think they are?
This Transaction does not appear in my wallet, are the Lost? is there anyway I can transfer them to my ledger nano?
Or are they gone forever? I would appreciate any help.

Kind regards,

Ryan 

### Environment
* Elixir Version: 1.10.2
* Erlang Version: 22
* BlockScout Version: v3.1.1-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by igorbarinov** [comment]
You should switch the network in MEW/MyCrypto/MetaMask to the EWF chain. Please ask EWF team for support if you don't know how to do i.

**Comment by RGordo3** [comment]
Hi Igor,

Thanks for the reply.

Where can I contact the EWF team?

Thanks,

Ryan

________________________________
