### ISSUE TITLE
Docker on Windows 10 

### ISSUE THREAD

**Issue by Damianbv** [poanetwork/blockscout#3155]
When you start to run docker on windows 10 you will get the following error:
"exec: \"C:/Program Files/Git/usr/bin/sh\": stat C:/Program Files/Git/usr/bin/sh: no such file or directory": unknown.

### Environment

* Operating System: Windows 10
* Blockscout Version/branch:  Latest

### Steps to reproduce

Run:  make start

C:\Program Files\Docker\Docker\resources\bin\docker.exe: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"C:/Program Files/Git/usr/bin/sh\": stat C:/Program Files/Git/usr/bin/sh: no such file or directory": unknown.
make: *** [Makefile:265: start] Error 127

### Expected behaviour

Run the docker image

### Actual behaviour

Shows an error

### Solution

change the following file:  docker\Makefile 
Line: 238
From:  $(DOCKER_IMAGE) /bin/sh -c "echo $$MIX_ENV && mix do ecto.create, ecto.migrate"
To: $(DOCKER_IMAGE) //bin/sh -c "echo $$MIX_ENV && mix do ecto.create, ecto.migrate"

Line: 268
From: $(DOCKER_IMAGE) /bin/sh -c "mix phx.server"
To: $(DOCKER_IMAGE) //bin/sh -c "mix phx.server"

**Comment by vbaranov** [comment]
@Damianbv it would be awesome if you could create a PR with the changes.

**Comment by Damianbv** [comment]
@vbaranov I think it would be better to maybe add it as a fix into the readme file, as it can break on any other OS.

**Comment by vbaranov** [comment]
@Damianbv good idea. Docker setup for Blockscout is described here https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/docker-integration-local-use-only.md. If you'd like can make a PR there. Or we will add a note there later.
