### ISSUE TITLE
MyEthWallet

### ISSUE THREAD

**Issue by RGordo3** [poanetwork/blockscout#3156]
Hi, 

Could anyone help me switch networks on MyEtherWallet to the EWF chain?

I need to do this to get access to this transfer I made.
https://explorer.energyweb.org/address/0x7d4D4cE8592F6df8A6A38da5B56f3Dd61f71bD51/transactions
Thanks

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System:
* Blockscout Version/branch: 

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Contact MyEtherWallet team for that
