### ISSUE TITLE
Failed to connect postgres

### ISSUE THREAD

**Issue by qianjin** [poanetwork/blockscout#3158]
docker run --network=host -e ETHEREUM_JSONRPC_HTTP_URL=http://localhost:6666  blockscout/blockscout-eth:3.2.0

application=db_connection [error] Postgrex.Protocol (#PID<0.812.0>) failed to connect: ** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) role "viktor" does not exist

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System: Linux
* Blockscout Version/branch: docker 3.2.0

**Comment by vbaranov** [comment]
@qianjin You should provide `DATABASE_URL` as well. I've updated docs to mark it as required param https://docs.blockscout.com/for-developers/information-and-settings/env-variables
