### ISSUE TITLE
Read Proxy tab shows nothing

### ISSUE THREAD

**Issue by varasev** [poanetwork/blockscout#3163]
I deployed, verified, and initialized the following contracts on xDai today, but `Read Proxy` tab doesn't work for the proxies for some reason. Getters work fine in `myetherwallet`.

### SubredditPoints_v0
Implementation address: 0xEf168ab46f01e1FfC769E002AbCd3B7D408fC905
Proxy address: 0xA2494ad52fD656d31F56A1EE84C3234732Bb95de

### Distributions_v0
Implementation address: 0x75F8AfAf61DC5e49e756b9d4B305d374bcd5DC01
Proxy address: 0x20Cc4dcA900f7D79EDD6F706A2287476c2ab0626

### Subscriptions_v0
Implementation address: 0x4a1Da45A337b439259F16b0Bf545E914077fb48A
Proxy address: 0x7C7F7D6f66a0d8C1a4F8A10562a5C5443B852781

**Comment by vbaranov** [comment]
@varasev "Read proxy" feature introduced in this PR https://github.com/poanetwork/blockscout/pull/3157. I just added a note there what are requirements to enable this feature for the clarification:

 > *Note*: in order to enable this feature both proxy and implementation contracts should be verified inn Blockscout and proxy contract should have "implementation" getter with the address of current implementation.

Proxy contracts, which you mentioned, as far as I can see don't have such getter.

**Comment by varasev** [comment]
These are openzeppelin proxy contracts that only allow its owner to use proxy getters (see [`ifAdmin`](https://github.com/OpenZeppelin/openzeppelin-sdk/blob/v2.8.2/packages/lib/contracts/upgradeability/BaseAdminUpgradeabilityProxy.sol#L52) modifier in the proxy source code). So, the `implementation()` getter exists, but closed by that modifier.

The contracts I deployed on xDai are the same as Reddit's points contracts deployed on Rinkeby and listed in https://www.reddit.com/r/ethereum/comments/hbjx25/the_great_reddit_scaling_bakeoff/

To retrieve implementation address, Blockscout should look to [`implementation slot`](https://github.com/OpenZeppelin/openzeppelin-sdk/blob/v2.8.2/packages/lib/contracts/upgradeability/BaseUpgradeabilityProxy.sol#L24) defined in [EIP-1967](https://eips.ethereum.org/EIPS/eip-1967).

For example, `AdminUpgradeabilityProxy` for the `SubredditPoints_v0` implementation contract in Rinkeby: https://rinkeby.etherscan.io/address/0xdf82c9014f127243ce1305dfe54151647d74b27a#readProxyContract - `etherscan` uses `EIP-1967` to retrieve address of the implementation:

![image](https://user-images.githubusercontent.com/33550681/85764172-0b9d9500-b71e-11ea-9597-96d3ffee26e8.png)
