### ISSUE TITLE
Contract Verification not working - "Constructor arguments do not match, please try again."

### ISSUE THREAD

**Issue by Xychun** [poanetwork/blockscout#3167]
Trying to verify the following smart contract

Etherscan URL: https://kovan.etherscan.io/address/0x6515f581c53a82a46EBe9a90EE03a0f942493ef9#code
Contract Name: Assets
Compiler Version: v0.6.7+commit.b8d736ae
Optimization Enabled: Yes with 1337 runs
Source Code: See Link above

Constructor Arguments:
`000000000000000000000000d98b22e7463af0689ebfe59c509e85861f8367290000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000004`

### Steps to reproduce

Trying to verify at https://mumbai-explorer.matic.today/address/0x4B8ba192690deB87cD1BB15B5430231D844f6d0d/contract_verifications/new

![Screen Shot 2020-06-28 at 2 46 27 PM](https://user-images.githubusercontent.com/4007073/85947961-2ce4c800-b94e-11ea-8e18-619571c44e98.png)

### Expected behaviour

The contract should verify with these values

### Actual behaviour

error

**Comment by vbaranov** [comment]
@Xychun As far as I can see from the bottom of the main page, you are using version 3.1.1 of Blockscout. Try upgrade to https://github.com/poanetwork/blockscout/releases/tag/v3.1.3-beta. There are multiple enhancements and fixes of the contract verification process.

**Comment by vbaranov** [comment]
@Xychun did version upgrade resolve your issue?

**Comment by Xychun** [comment]
> @Xychun did version upgrade resolve your issue?

It's not my block explorer. Waiting for the upgrade myself. Will let you know. Thanks :)

**Comment by Xychun** [comment]
> @Xychun did version upgrade resolve your issue?

Solved the issue. Thanks :)

**Comment by heri16** [comment]
> > @Xychun did version upgrade resolve your issue?
> 
> Solved the issue. Thanks :)

Hey @Xychun , I'm facing a similar issue with no luck. Could you elaborate how you got it solved?
