### ISSUE TITLE
what the fuck!!!!!!!!!  Shit-like deployment

### ISSUE THREAD

**Issue by m3shine** [poanetwork/blockscout#3172]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System:
* Blockscout Version/branch: 

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by igorbarinov** [comment]
@m3shine what's happened?
