### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by Tria0214** [poanetwork/blockscout#3189]
*Describe your issue here.*
i did not receive the Eth that i send to my Go Wallet account but it was deducted to my trust wallet eth account
### Environment

* Elixir Version: 1.9.1
* Erlang Version: 22
* BlockScout Version: v3.0.0-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 13_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Doesn't relate to explorer
