### ISSUE TITLE
Error querying graphql

### ISSUE THREAD

**Issue by antoineherzog** [poanetwork/blockscout#3208]
*Describe your issue here.*

### Steps to reproduce

Query 

# Write your query or mutation here
{transaction(hash:"0xdf2220ae59b18f5b35614f899085e4bb912a4bceae9543b75576b06ca62e055c") { 
    
          id
          blockNumber
          hash
          gas
          status
          value
          fromAddressHash
          toAddressHash
          blockNumber 
  				internalTransactions{edges{node{gasUsed}}}
  
  
  
  				
    }
  }

### Expected behaviour

I should get internal transactions

### Actual behaviour

I got "Internal server error"

**Comment by vbaranov** [comment]
@antoineherzog I will process internal server error for sure. But in order to get internal transactions, you need to indicate how many you want to get. So you need to provide *first* or *last, count* param/s. For instance, like this:

```
{transaction(hash:"0xdf2220ae59b18f5b35614f899085e4bb912a4bceae9543b75576b06ca62e055c") {

      id
      blockNumber
      hash
      gas
      status
      value
      fromAddressHash
      toAddressHash
      blockNumber 
			internalTransactions(first: 100){edges{node{gasUsed}}}



			
}
}
```
