### ISSUE TITLE
Energy Web Chain: <Issue Title> Contract Call Issue

### ISSUE THREAD

**Issue by CSadler92** [poanetwork/blockscout#3213]
*Describe your issue here.*
So I recently sent my EWT to EWTB on Metamask and it says my block number 6957093 in on a contract call. Did I get scammed? I sent the transaction 3 hours ago. Has this happened to anyone else?

### Environment
* Elixir Version: 1.9.1
* Erlang Version: 22
* BlockScout Version: v3.1.1-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
https://forum.poa.network/t/token-stuck-ewt-to-ewtb/3619/3
