### ISSUE TITLE
Energy Web Chain: Sent EWT to an EWTB wallet (ERC20) in TrustWallet 

### ISSUE THREAD

**Issue by davisdon86** [poanetwork/blockscout#3218]
Yesterday, July 31st, I sent a coin to the incorrect Wallet.  I am hoping you I can retrieve the coin/funds. 

1.The Coin that was sent was EWT

2.It was sent to an EWT(bridged) wallet on TrustWallet. 

4.Transaction ID:
0xd3795b915f3fe25abb20a5bbb09840f31385d71b78b0019b48857e6763237682

I was unaware that the EWTb meant that the token had to be bridged to an ERC20 in order to store it in my wallet. Currently, I have not received my coins and it is stuck on the blockchain. Please help!

Thank You So Much,

### Environment
* Elixir Version: 1.9.1
* Erlang Version: 22
* BlockScout Version: v3.1.1-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 13_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by igorbarinov** [comment]
Please contact EWB team at https://t.me/energyweb or https://www.energyweb.org/contact/ 

BlockScout and TokenBridge are open-source tools used by EWF. Unfortunately, we can't solve your token issues.
