### ISSUE TITLE
Mordor: unable to verify contract

### ISSUE THREAD

**Issue by 0xAnonymous** [poanetwork/blockscout#3222]
*Describe your issue here.*

Unable to verify contracts. 0x3727A8811Cf5EAe738357AA746bF17f31B844853 has deployed this code with solidity 0.6.6, istanbul and no optimizations.

```
contract A {
    uint Test;
}
```

### Environment
* Elixir Version: 1.9.4
* Erlang Version: 22
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:79.0) Gecko/20100101 Firefox/79.0`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
@0xAnonymous could you try again?

**Comment by 0xAnonymous** [comment]
I've tried dozens of times with different contracts. Can't get it to work. [This one](https://blockscout.com/etc/mainnet/address/0xC12402638F13555cb035086037b0e6bdE40d2BA5/contract_verifications/new) (blockscout) is for example the same code as [this one](https://ropsten.etherscan.io/address/0xc12402638f13555cb035086037b0e6bde40d2ba5#code
) (etherscan), if you want to give it a try.

**Comment by vbaranov** [comment]
@0xAnonymous Is your issue with mordor testnet explorer or with ETC mainnet explorer? You put Mordor inn the title. I thought about Mordor testnet.

**Comment by 0xAnonymous** [comment]
@vbaranov Yes it was with mordor test net. But I also tried now on the ETC mainnet and it doesn't work either. It might be that I'm doing something obvious wrong, but I've been able to verify contracts over blockscout in the past. Idk.

**Comment by vbaranov** [comment]
@0xAnonymous I was able to deploy and verify this contract on Sokol https://blockscout.com/poa/sokol/address/0xf49980372EDFDBF29Dff681cAcf875DDF38146DF/contracts using your gist https://gist.github.com/0xAnonymous/8d93d20ac056b45e2ba2d5455cc2024b. The verification is straightforward by using this guide https://docs.blockscout.com/for-users/smart-contract-interaction/verifying-a-smart-contract. Possibly, you're trying to verify with the wrong metadata. If you are sure with the metadata please post it here.

**Comment by 0xAnonymous** [comment]
It verified now on the etc mainnet. https://blockscout.com/etc/mainnet/address/0x86387a84bC8B33Dd240B2C82699a7e8f6299Ca64/contracts. For some reason previously when I published contracts I'd extract just the hexadecimal bytecode, now I published the whole bytecode object (as copy pasted from remix.ethereum.org), maybe that's why it didn't work before. Idk.
