### ISSUE TITLE
Ethereum Classic: <the amount of confirmations is way to much, min of 3000 to 11000. so anywhere between 12-36 hrs>

### ISSUE THREAD

**Issue by schwarten42** [poanetwork/blockscout#3225]
*Describe your issue here.*

### Environment
* Elixir Version: 1.10.2
* Erlang Version: 22
* BlockScout Version: v3.0.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Please provide more details.
- For which do transaction you too many confirmations?
- How many confirmations do you expect?

**Comment by vbaranov** [comment]
I am closing this because of no response.
