### ISSUE TITLE
Site is down for Ethereum mainnet 

### ISSUE THREAD

**Issue by pi0neerpat** [poanetwork/blockscout#3229]
https://blockscout.com/eth/mainnet

`503 Service Unavailable`

**Comment by vbaranov** [comment]
Sorry about that. ETH Mainnet instance is not supported anymore.

**Comment by pi0neerpat** [comment]
booooooooooooooooooooooo

**Comment by igorbarinov** [comment]
> booooooooooooooooooooooo

we had a Gitcoin grant for the Mainnet instance but it was not successful 
https://gitcoin.co/grants/854/blockscout-blockchain-explorer

After we shut down the instance we put the indexed database into backup. If you know someone who is up to spend a thousand dollars a month to host it please let us know. We will share the DB and help with the setup.
It worked well with ETC which is hosting their instances themselves via ETC Cooperative and covering all hosting expenses.

**Comment by pi0neerpat** [comment]
That's very thoughtful, thank you for mentioning this! Shame the grant didn't get support. When it comes down to it, I guess people are just willing to trust etherscan

**Comment by pi0neerpat** [comment]
> a thousand dollars a month
How large is the DB? Also, sorry for the dumb question- but I'm assuming it can't be run without a db, and just make a web3 query on-the-fly?

**Comment by vbaranov** [comment]
> How large is the DB?

~ 3 - 4 Tb.


> Also, sorry for the dumb question- but I'm assuming it can't be run without a db, and just make a web3 query on-the-fly?

There is no such mode in Blockscout. It can be like you're saying for instance for searching of transaction or block. But I think it would be impossible to get on-fly, history of balances, transactions, logs for address taking into account you need to request each previous block to get such history.

**Comment by pi0neerpat** [comment]
> It can be like you're saying for instance for searching of transaction or block

That's all I really care about. I may run an archive node for another project, so hosting a limited-feature blockscout is definitely in the cards.

Or at the very least, maybe a less-expensive community version of blockscout could be stood up. Either way, there needs to be more explorer alternatives.... badly.

Thank you for your help!
