### ISSUE TITLE
TraceTransaction Parser panicking on specific transaction

### ISSUE THREAD

**Issue by juliankoh** [poanetwork/blockscout#3234]
Hi! I'm using blockscout's tracer [here](https://github.com/poanetwork/blockscout/blob/master/apps/ethereum_jsonrpc/priv/js/ethereum_jsonrpc/geth/debug_traceTransaction/tracer.js) to do traceTransaction in geth. When tracing [this](https://ropsten.etherscan.io/tx/0x5dd7db84a5fc90e001b13e08392aa31e8c0cfeeba31f3c199eb4f1e166cdd146) transaction, I get the following error: 

`Error{Code:0, Message:"method handler crashed", Retriable:false, Details:map[string]interface {}(nil)}`

cc @vbaranov 

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System: Mac OSX
* Blockscout Version/branch: master

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

Simply use the tracer [here](https://github.com/poanetwork/blockscout/blob/master/apps/ethereum_jsonrpc/priv/js/ethereum_jsonrpc/geth/debug_traceTransaction/tracer.js) and [this txhash](https://ropsten.etherscan.io/tx/0x5dd7db84a5fc90e001b13e08392aa31e8c0cfeeba31f3c199eb4f1e166cdd146) as inputs to geth's `debug_traceTransaction`. It should panic and return the same error. 

### Expected behaviour

We should be able to parse the traces of this transaction.

### Actual behaviour

Panics instead of successfully parsing.

**Comment by vbaranov** [comment]
@juliankoh could you please post here the response of `debug_traceTransaction` request for mentioned tx from Ropsten or ETH Mainnet?
