### ISSUE TITLE
Energy Web Chain: EternalStorageProxy (0xb838–60a303)

### ISSUE THREAD

**Issue by sevrence22** [poanetwork/blockscout#3241]
I processed my EWT to EWTB transaction @ 1225pm and after 3 hours the transaction still has yet to hit my metamask account. I noticed that the transaction was sent to this EternalStorageProxy (0xb838–60a303) 

### Environment
* Elixir Version: 1.10.2
* Erlang Version: 22
* BlockScout Version: v3.1.1-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.* I am unsure how to reproduce this issue. I do know that I accidentally exited the 0/8 Transaction processing screen, however I never canceled the transaction in metamask.

### Expected Behaviour

Normally, especially after paying a high gas fee, the transaction processes rather quickly and is available nearly immediately. 

### Actual Behaviour

This time the tokens seem to be left in a limbo state and have not been added to my account.
![Capture](https://user-images.githubusercontent.com/69699292/90297275-d28ec080-de42-11ea-9bf7-e884c57e3ad0.PNG)

**Comment by vbaranov** [comment]
https://github.com/poanetwork/blockscout/issues/3232#issuecomment-671725035
