### ISSUE TITLE
Energy Web Chain: <Issue Title>

### ISSUE THREAD

**Issue by Ronsta60** [poanetwork/blockscout#3242]
Hi Details Requested are Below.

Coin name:   Energy Web Token EWT
Deposit amount:  468.315723
Transaction TxID ( Hash ID )   0xd9ac891de771176c44c2c713fd3fe594cad1a682fe1c5223aa71fc019ebc8715
The wrong address that was deposited to by mistake (incorrect one):   0xEA4d8226cf55517d9aa2D98502790839BBD2f3B9
The correct address you would like to deposit to:  0x7f5B40080f8E3E489108d8680B36Ceb9410C91E8

I sent the wrong Coin EWT to a Binance LINK address by mistake Instead of sending my LINK coins to this address.
I would like if possible for the transaction to be reversed as I realise the transaction will not show up in my wallet.
I also realise that Binance does not transact in the EWT coin.

If possible return the EWT to the original address:  0x7f5B40080f8E3E489108d8680B36Ceb9410C91E8

The transaction can be seen on the blockchain here:  https://explorer.energyweb.org/tx/0xd9ac891de771176c44c2c713fd3fe594cad1a682fe1c5223aa71fc019ebc8715/internal_transactions

Thank you for your assistance.

Regards Ron

**Comment by igorbarinov** [comment]
Hi, please contact EWF support for this question https://t.me/energyweb
We are just developers of the explorer in this case.
