### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by folly6** [poanetwork/blockscout#3243]
*Describe your issue here.*
I didn't see my crypto( Etherum classic) in my coin base and I transferred from my coin base (wallet) to my coin base and it as confirmed successful but I haven't seen it yet in my coin base and it as confirmed (7,456) blocks. Please do something
### Environment
* Elixir Version: 1.10.2
* Erlang Version: 22
* BlockScout Version: v3.0.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 8.0.0; Infinix X573) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by igorbarinov** [comment]
You should contact Coinbase support https://www.coinbase.com/
