### ISSUE TITLE
Energy Web Chain: <Issue Title>

### ISSUE THREAD

**Issue by bang95838** [poanetwork/blockscout#3244]
*Describe your issue here.*
For transaction ID 0x6ef3bb6f98d50626208a8d5fe2c3e7c1476ed6799052e2776a550ede79d47f1a

My withdrawal never arrived, please revert it back to the original wallet.
Thanks

### Environment
* Elixir Version: 1.10.2
* Erlang Version: 22
* BlockScout Version: v3.1.1-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.0 Mobile/14E304 Safari/602.1; KuCoin`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
https://github.com/poanetwork/blockscout/issues/3232#issuecomment-671725035
