### ISSUE TITLE
Ethereum Classic: <etc in coinbase is still pending after 40000 confirmation>

### ISSUE THREAD

**Issue by Zubairayub23** [poanetwork/blockscout#3246]
*sent from usa coinbase to Pakistan coinbase account and after 7 days its still pending .*

### Environment
* Elixir Version: 1.10.3
* Erlang Version: 22
* BlockScout Version: v3.3.1-beta

* User Agent: `Mozilla/5.0 (Linux; Android 9; LLD-L21) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by hamedtayeban22** [comment]
I have to send my blockian wallet bitcoin please helleme

در تاریخ پنجشنبه ۲۰ اوت ۲۰۲۰،‏ ۱۳:۰۷ Zubairayub23 <notifications@github.com>
نوشت:

**Comment by hamedtayeban22** [comment]
147bf706-d9c8-4784-babb-c4a6c70a4dfc

در تاریخ پنجشنبه ۲۰ اوت ۲۰۲۰،‏ ۱۳:۰۷ Zubairayub23 <notifications@github.com>
نوشت:
