### ISSUE TITLE
Energy Web Chain: Lost my EWT tokens to the trust wallet app

### ISSUE THREAD

**Issue by saqeralmusallam** [poanetwork/blockscout#3247]
*Describe your issue here.*

### Environment
* Elixir Version: 1.10.2
* Erlang Version: 22
* BlockScout Version: v3.1.1-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36 Edg/84.0.522.61`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
https://github.com/poanetwork/blockscout/issues/3232#issuecomment-671725035

**Comment by saqeralmusallam** [comment]
Thanks @vbaranov  I managed to recover my token thanks to the help of some people in the EWT group on telegram.
