### ISSUE TITLE
Unable to add smart contract code

### ISSUE THREAD

**Issue by aminlatifi** [poanetwork/blockscout#3248]
I have created a test smart contract on xDai, unfortunately cannot verify and publish the code!
I have deployed below smart contract on this address: 0xec5Bff64A3BCC0181088c664529C5C45a5DD1121

```
// SPDX-License-Identifier: GPL-3.0
pragma solidity >=0.4.16 <0.8.0;

contract CSTokenTest {

    event Donate(address indexed from, address indexed token, uint amount);
    
    address public authorizedKey;
    
    constructor(address _authorizedKey) public {
        require(_authorizedKey != address(0), "Authorized key cannot be empty");
        authorizedKey = _authorizedKey;
    }
    
    modifier onlyAuthorizedKey {
        require(msg.sender == authorizedKey, "Permission denied");
        _;
    }
    
    function Deposit(address from, address token, uint amount) onlyAuthorizedKey external {
        emit Donate(from, token, amount);
    }
}
```

I used both 0.6.12 and 0.7.0 solidity compiler, and this error is shown on blockscout `
Compiler version does not match, please try again.`

**Comment by vbaranov** [comment]
@aminlatifi you need to specify the exact version of compiler which you used during the compilation of a contract.

**Comment by aminlatifi** [comment]
> @aminlatifi you need to specify the exact version of compiler which you used during the compilation of a contract.

I used Remix IDE, tested both 0.6.12 and 0.7.0 solidity compiler versions.

![image](https://user-images.githubusercontent.com/5684607/91021906-ac6adc80-e609-11ea-9980-c9d07692f788.png)

**Comment by aminlatifi** [comment]
The last one which is deployed on 0xec5Bff64A3BCC0181088c664529C5C45a5DD1121 was compiled by 0.6.12

**Comment by vbaranov** [comment]
I verified your contract https://blockscout.com/poa/xdai/address/0xec5Bff64A3BCC0181088c664529C5C45a5DD1121/contracts. You compiled it without optimization and forgot to set *Optimization* to *No* during verification

<img width="388" alt="Screenshot 2020-08-24 at 11 46 21" src="https://user-images.githubusercontent.com/4341812/91023677-83dde500-e5ff-11ea-953b-864aa80e3751.png">

**Comment by aminlatifi** [comment]
> I verified your contract https://blockscout.com/poa/xdai/address/0xec5Bff64A3BCC0181088c664529C5C45a5DD1121/contracts. You compiled it without optimization and forgot to set _Optimization_ to _No_ during verification
> 
> <img alt="Screenshot 2020-08-24 at 11 46 21" width="388" src="https://user-images.githubusercontent.com/4341812/91023677-83dde500-e5ff-11ea-953b-864aa80e3751.png">

Thanks @vbaranov, but I didn't forget to set Optimization to No! Maybe I had to set something else

**Comment by aminlatifi** [comment]
> > I verified your contract https://blockscout.com/poa/xdai/address/0xec5Bff64A3BCC0181088c664529C5C45a5DD1121/contracts. You compiled it without optimization and forgot to set _Optimization_ to _No_ during verification
> > <img alt="Screenshot 2020-08-24 at 11 46 21" width="388" src="https://user-images.githubusercontent.com/4341812/91023677-83dde500-e5ff-11ea-953b-864aa80e3751.png">
> 
> Thanks @vbaranov, but I didn't forget to set Optimization to No! Maybe I had to set something else and I didn't. Should I fill the ABI too?

I found my mistake, didn't notice adding ABI encoded for constructor.

**Comment by vbaranov** [comment]
> I found my mistake, didn't notice adding ABI encoded of constructor arguments

or you could allow Blockscout to find constructor arguments automatically

<img width="376" alt="Screenshot 2020-08-24 at 13 20 31" src="https://user-images.githubusercontent.com/4341812/91033774-9b6f9a80-e60c-11ea-8f78-46db17dd6c8c.png">
