### ISSUE TITLE
Cannot use contract's getter with array argument

### ISSUE THREAD

**Issue by varasev** [poanetwork/blockscout#3255]
I'm trying to use `Read Proxy` tab and discovered the following bug: the `getRewardAmount` getter accepts an array as the first argument. I'm trying to pass different values (`[]`, `[1,2,3]`, `[1]`, `1,2,3`) to it but it shows an error

![image](https://user-images.githubusercontent.com/33550681/91177920-1a3c0480-e6ed-11ea-9e67-ae4ebf424b0f.png)

I passed `0x29CF39dE6d963D092c177a60ce67879EeA9910BB` as a second and third argument.

**Comment by varasev** [comment]
For an empty array I see the following error:

![image](https://user-images.githubusercontent.com/33550681/91630807-40a7bb80-e9dd-11ea-9d8b-db127a5f0086.png)

This can be checked on the page https://blockscout.com/poa/xdai/address/0x2DdB8A7541e6cAA50F74e7FACFF9Fe9da00e0A6c/read_proxy

**Comment by vbaranov** [comment]
@varasev Try white space as a workaround. I will address an empty string.

**Comment by vbaranov** [comment]
@varasev empty input value handled
