### ISSUE TITLE
(FunctionClauseError) no function clause matching in EthereumJSONRPC.quantity_to_integer/1

### ISSUE THREAD

**Issue by garyfoo88** [poanetwork/blockscout#3271]
<img width="1574" alt="Error1" src="https://user-images.githubusercontent.com/55524871/91795413-288ba280-ec50-11ea-90ce-973e3b80ab8d.png">

Hi, i know this issue has been raised before but I am still unable to resolve this issue. Please help. Thanks!

## Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.10.3-otp-22, erlang 22.3.4.5
* Operating System: MacOS
* Blockscout Version/branch: Latest

### Steps to reproduce

Followed instructions of manual deployment.

Using Kaleido RPC endpoint, all relevant env variables are set. 

Running mix phx.server gives me this error and no blocks are loaded in the application.

### Expected behaviour

The blocks should be loaded in the application

### Actual behaviour

No blocks are loaded in the application

**Comment by vbaranov** [comment]
@garyfoo88 
some counter questions:
1. What version of Blockscout do yo use?
2. Which engine is used for archive node: Geth, Open Ethereum smth else?
3. Is your archive node fully synced?

**Comment by garyfoo88** [comment]
Hi, i am using the latest version of blockscout, using Geth. The blocks are now finally showing, but new blocks and total blocks are not updated in real-time. When i refresh the page, the new blocks are updated but the total blocks remains the same. What could be the cause of this problem? Thanks for the help

**Comment by vbaranov** [comment]
You can manage how often to update blocks counter at the main page with `BLOCK_COUNT_CACHE_PERIOD` environment variable https://docs.blockscout.com/for-developers/information-and-settings/env-variables. The default value for this variable is 600 (in secs) = 10 minutes. Reduce the value if you want more frequent updates.

**Comment by garyfoo88** [comment]
Hi, Thanks for the prompt response. i changed the variable to 1, however i am still getting a delayed response of about 2 minutes. Furthermore, the blocks are not updated automatically and needs a page refresh to be updated(expected behaviour is shown in https://blockscout.com/poa/xdai/). Thank you for your time.

**Comment by vbaranov** [comment]
Do you see the appearance of new blocks tiles on the main page at the same time? Any errors in the Chrome dev console?

**Comment by garyfoo88** [comment]
no new blocks are loaded unless i reload the page(which updates to the latest block), no error in the dev console.

**Comment by garyfoo88** [comment]
i am currently using node 14.9.0 and yes, i do see messages as shown in the attached pic.
<img width="955" alt="ws" src="https://user-images.githubusercontent.com/55524871/92194944-6aaa2380-ee9e-11ea-9271-35fe4373f6c9.png">

**Comment by vbaranov** [comment]
https://docs.blockscout.com/for-developers/information-and-settings/requirements Node 14 is not supported. We support Node LTS releases. I would recommend to downgrade down to Node 12.x and re-build all front-end stuff from *10) step* of [Manual deployment guide](https://docs.blockscout.com/for-developers/manual-deployment). Also I would suggest clearing node_modules folder in both locations *./apps/block_scout_web/assets* and *./apps/explorer* before following steps in the manual.

**Comment by garyfoo88** [comment]
i have tried to redeploy blockscout with node 12.18.3 but the problem still persists

**Comment by vbaranov** [comment]
Can you provide RPC endpoint to reproduce the issue?

**Comment by garyfoo88** [comment]
ETHEREUM_JSONRPC_HTTP_URL=https://k0l4u70mcs:mqC5IJhcHn4XERUlcfTJg-PFofpY_0V-d5Dvk3Cfub8@k0c0eph44j-k0hmjs6ku4-rpc.kr0-aws.kaleido.io

ETHEREUM_JSONRPC_WS_URL=wss://k0l4u70mcs:mqC5IJhcHn4XERUlcfTJg-PFofpY_0V-d5Dvk3Cfub8@k0c0eph44j-k0hmjs6ku4-wss.kr0-aws.kaleido.io

**Comment by vbaranov** [comment]
Provided endpoints respond `%{"error" => %{"code" => -32003, "message" => "Rate limit"}, "jsonrpc" => "2.0"}` causing stuck indexer

**Comment by vbaranov** [comment]
@garyfoo88 Provided endpoints respond %{"error" => %{"code" => -32003, "message" => "Rate limit"}, "jsonrpc" => "2.0"} causing stuck indexer. This is the reason of your issue. You need to eliminate rate limit in order to make explorer work.

**Comment by garyfoo88** [comment]
I see, is there a work-around for it to work without removing the rate limit? if not, then this issue can be closed. Thanks for the help and patience.

**Comment by vbaranov** [comment]
No, it will not work if rate limits exist.
