### ISSUE TITLE
Energy Web Chain: <Issue Title> While converting EWT to EWTB using bridge.energyweb.org using my metamask accn, 

### ISSUE THREAD

**Issue by Timbyuto** [poanetwork/blockscout#3272]
*Describe your issue here.*

### Environment
* Elixir Version: 1.10.2
* Erlang Version: 22
* BlockScout Version: v3.1.1-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by Timbyuto** [comment]
The conversion appears to be a success, the problem is that according to the rate of block confirmations it will take 425 days to complete. Is this normal? Its not very convenient. Any tips on how to expedite or abort this situation? Many thanks
Here is the reference txn hash as displayed on energyweb.org: 0x03f8f87c24ed8a6a97dcdffe73023233f60106b2d605336a83e85a8c53bfd818

**Comment by vbaranov** [comment]
please contact EWF support for this question https://t.me/energyweb
