### ISSUE TITLE
Energy Web Chain: <Issue Title>

### ISSUE THREAD

**Issue by tonyw1960** [poanetwork/blockscout#3275]
HI 

I wanted to transfer my EWT into my Trust Wallet i provided the address from Trust Wallet but have just found out that trust wallet does not support EWT they have a coin EWTB which will not accept EWT's- can this be recalled and put back onto the Kucoin platform????

### Environment
* Elixir Version: 1.10.2
* Erlang Version: 22
* BlockScout Version: v3.1.1-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Reach out EWF support for this question https://t.me/energyweb
