### ISSUE TITLE
mix phx.gen.secret build error,** (Mix) Could not compile dependency :keccakf1600.

### ISSUE THREAD

**Issue by passionofvc** [poanetwork/blockscout#3280]
try to set up blockscout explorer local, but
mix phx.gen.secret run in build error, the keccakf1600 can not build in Erlang/OTP 23 and show linker error below.
```

usr/bin/ld: cannot find -lerl_interface 
collect2: error: ld returned 1 exit status

```

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):

```
$ elixir --version
Erlang/OTP 23 [erts-11.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.11.0-dev (bad2b25) (compiled with Erlang/OTP 23)


 $ erl --version
Erlang/OTP 23 [erts-11.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Eshell V11.0.3  (abort with ^G)
1>

```
* Operating System:
```
$ cat /etc/redhat-release
CentOS Linux release 7.8.2003 (Core)

```
* Blockscout Version/branch: 
git clone https://github.com/poanetwork/blockscout.git

### Steps to reproduce
according to
[https://docs.blockscout.com/for-developers/manual-deployment](https://docs.blockscout.com/for-developers/manual-deployment)

0. run postgresql in docker
1. git clone https://github.com/poanetwork/blockscout.git
2. cd blockscout
3. export DATABASE_URL=postgresql://user:password@localhost:5432/blockscout 
4. mix phx.gen.secret

```
$ mix phx.gen.secret
===> Compiling keccakf1600
make: Entering directory `/home/passionofvc/blockscout/deps/keccakf1600/c_src'
 LD     keccakf1600.so
/usr/bin/ld: cannot find -lerl_interface
collect2: error: ld returned 1 exit status
make: *** [/home/passionofvc/blockscout/deps/keccakf1600/c_src/../priv/keccakf1600.so] Error 1
make: Leaving directory `/home/passionofvc/blockscout/deps/keccakf1600/c_src'
===> Hook for compile failed!

** (Mix) Could not compile dependency :keccakf1600, "/home/passionofvc/.mix/rebar3 bare compile --paths /home/passionofvc/blockscout/_build/dev/lib/*/ebin" command failed. You can recompile this dependency with "mix deps.compile keccakf1600", update it with "mix deps.update keccakf1600" or clean it with "mix deps.clean keccakf1600"

```

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour
should give me secret key
and build should ok.

### Actual behaviour
build error, do not give me secret key.

**Comment by vbaranov** [comment]
@passionofvc We didn't test the explorer with the release of Erlang OTP and Elixir you mentioned.
I would recommend downgrading to *Erlang/OTP 22* and *Elixir 1.10.x* according to
https://docs.blockscout.com/for-developers/information-and-settings/requirements

**Comment by passionofvc** [comment]
@vbaranov 

try to get esl-erlang in
[https://github.com/poanetwork/blockscout-terraform/blob/33f68e816e36dc2fb055911fa0372531f0e956e7/modules/stack/libexec/init.sh#L134 ](https://github.com/poanetwork/blockscout-terraform/blob/33f68e816e36dc2fb055911fa0372531f0e956e7/modules/stack/libexec/init.sh#L134
)

but ERROR 404: Not Found.

```
$ wget http://packages.erlang-solutions.com/site/esl/esl-erlang/FLAVOUR_1_general/esl-erlang_21.0.5-1~centos~7_amd64.rpm
--2020-09-03 18:23:47--  http://packages.erlang-solutions.com/site/esl/esl-erlang/FLAVOUR_1_general/esl-erlang_21.0.5-1~centos~7_amd64.rpm
Resolving packages.erlang-solutions.com (packages.erlang-solutions.com)... 99.84.206.95, 99.84.206.47, 99.84.206.49, ...
Connecting to packages.erlang-solutions.com (packages.erlang-solutions.com)|99.84.206.95|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-09-03 18:23:47 ERROR 404: Not Found.
```

**Comment by vbaranov** [comment]
@passionofvc it is outdated commit. Use the master branch of this repo:

https://github.com/poanetwork/blockscout-terraform/blob/2a9879c9cbdcaf7bc2ba088011739a5fd71835b8/roles/main_infra/files/libexec/init.sh#L151-L152

**Comment by passionofvc** [comment]
@vbaranov 
thanks in finally, below work for me.

```
$ elixir --version
Erlang/OTP 22 [erts-10.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.10.4 (compiled with Erlang/OTP 21)
[yamada@CentOS7-Levias blockscout]$ erl --version
Erlang/OTP 22 [erts-10.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Eshell V10.4  (abort with ^G)
1>

$ mix -v
Erlang/OTP 22 [erts-10.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Mix 1.10.4 (compiled with Erlang/OTP 21)

```
