### ISSUE TITLE
Energy Web Chain: <Issue Title>

### ISSUE THREAD

**Issue by gustavo536** [poanetwork/blockscout#3304]
*Describe your issue here.*

Hi
I accidentally sent some ewt to an erc20 address
How can I recover them?

Here is the hash

https://explorer.energyweb.org/tx/0x1ff55bf5a0c57d3a565d8295e42effbdc25675c81fbb26d92adeb101b7e2a765/internal_transactions

### Environment
* Elixir Version: 1.9.1
* Erlang Version: 22
* BlockScout Version: v3.1.1-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 13_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Recipient address of tx hash you posted is EOA address, not a contract address.
