### ISSUE TITLE
Mainnet-v1: Blockscout cannot do 'write contract' methods for tokens 

### ISSUE THREAD

**Issue by admazzola** [poanetwork/blockscout#3305]
Cannot do any 'write contract' functions on this token:
https://explorer.matic.network/address/0x71B821aa52a49F32EEd535fCA6Eb5aa130085978/write_contract

They all error on the front end no matter what.  For example I cannot do an 'approve' of my tokens to another address.  The metamask window wont pop up when i click WRITE .   Im using: 

Metamask v8.08
Chrome 

### Environment
* Elixir Version: 1.10.3
* Erlang Version: 22
* BlockScout Version: v3.3.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by igorbarinov** [comment]
Hi, you should contact the Matic team on the issue.

They support a fork of BlockScout over there: https://github.com/maticnetwork/blockscout

Issues in the fork are not enabled by default. You should ask them to enable issues functionality using the instruction https://softwareengineering.stackexchange.com/a/179470 

After that, you can submit your issue and track the status of the issue in Matic's fork
