### ISSUE TITLE
xDai: Bridge from DAI to xDAI

### ISSUE THREAD

**Issue by Vurdal4ik** [poanetwork/blockscout#3306]
*Describe your issue here.*
Hi, I have bridged DAI from Ethereum network to xDai network (0x0137bb91ad499b1bdb9ba8995a6e8ad855bb5f2580afb4bed723aa08c5c47be9 - Transaction ID). Status - Success.
xDai was not received. Wallet - 0x72a25a4cc122620e9f634496034fe44c4860deb3
Please advice how can i solve this issue? 
Best regards,
Vjaceslav.
### Environment
* Elixir Version: 1.10.3
* Erlang Version: 22
* BlockScout Version: v3.3.2-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by igorbarinov** [comment]
Your transaction hit the daily limit on the xDai bridge and was processed at 0:00 UTC successfully.
