### ISSUE TITLE
Missing API calls that are desirable 

### ISSUE THREAD

**Issue by stevecarrol** [poanetwork/blockscout#3309]
I am building a graphical tool to monitor addresses and holders of tokens for xdai tokens

I would like to receive the total number of address holders for a token but there is not an API call that gives this endpoint. 

I would like to receive the top address holders for a token and their % of ownership.

I would like to receive the currently available supply for a token. 

### Environment

* Blockscout Version/branch: 

is it possible to gather these endpoints using other calls that are not intuitively obvious to me right now?

**Comment by vbaranov** [comment]
@stevecarrol 

> I would like to receive the total number of address holders for a token but there is not an API call that gives this endpoint.

> I would like to receive the top address holders for a token and their % of ownership.

Blockscout began to provide token holders API endpoint which was introduced in this PR https://github.com/poanetwork/blockscout/pull/3584 The response of API endpoint is an array of token holders addresses and balances of the token. Endpoint supports pagination. Both of the requested metrics in regards token holders can be derived using that API endpoint.

> I would like to receive the currently available supply for a token.

Token total supply is available through `tokensupply` API endpoint https://blockscout.com/poa/xdai/api-docs#token

A sample request:

```
https://blockscout.com/poa/xdai/api?module=stats&action=tokensupply&contractaddress=0x71850b7E9Ee3f13Ab46d67167341E4bDc905Eef9
```
