### ISSUE TITLE
how to bind the server IP to the domain name ？

### ISSUE THREAD

**Issue by YaakovHuang** [poanetwork/blockscout#3310]
I have manually deployed the project according to the document, and now I can access it through the IP address. because I am not familiar with the Elixir application, and I don’t know how to bind the server IP and domain name, how can I solve this problem? 

thanks

**Comment by vbaranov** [comment]
IP binding to Domain name doesn't relate to the language, which the application is written on. You need a configured DNS. As a first step, you maybe want to take a look to [DNS from Cloudflare](https://www.cloudflare.com/en-gb/dns/) or from other providers.
