### ISSUE TITLE
Autodetecting constructor arguments not available via contract verification API

### ISSUE THREAD

**Issue by agaw** [poanetwork/blockscout#3324]
Hello,

Autodetecting of constructor arguments for contract verification was added via this merge request:
https://github.com/poanetwork/blockscout/pull/2821/files

While this feature is available when attempting to verify a contract using the frontend - which displays an option to the user to autodetect constructor arguments (and sends a `autodetect_contructor_args` flag in the resulting request to the backend) - an equivalent configuration parameter does not appear to be available in the RPC API. 

Is there a workaround to enable autodetection of constructor arguments when verifying a contract via the RPC API?

**Comment by vbaranov** [comment]
@agaw `"autodetectConstructorArguments":"true"` parameter is now supported by `verify` API endpoint.
