### ISSUE TITLE
Token overview incorrect for xdai created tokens

### ISSUE THREAD

**Issue by olibaron** [poanetwork/blockscout#3336]
In some use cases, the token overview for xdai created tokens is incorrect. In this particular use case, the token contract is exactly the same as the WETH contract or the WxDAI contract. It seems that a withdraw is not properly updated in the user wallet account and the overview always shows the deposited value 

### Environment
Blockscout Version/branch: Production

### Steps to reproduce

Create a token contract like this one: https://blockscout.com/poa/xdai/address/0xa9631C6cD34B4F659F16bb549D4eA92eB21B6842

Deposit xdai and withdraw the same amount of xdai again

### Expected behaviour
The /tokens overview should become zero
Just like the overview on metamask

### Actual behaviour
The tokens overview still shows value. That value should be zero
https://blockscout.com/poa/xdai/address/0x1337870b2B14e043fB8D41DC95ab2dbC51A0f6d8/tokens

**Comment by vbaranov** [comment]
@olibaron I added on-demand token balance fetcher https://github.com/poanetwork/blockscout/pull/3525. The issue resolved with mentioned account.
