### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by nosshar** [poanetwork/blockscout#3340]
ETC main network reward is shown incorrect if requested via API.

### Environment
* Elixir Version: 1.10.3
* Erlang Version: 22
* BlockScout Version: v3.3.1-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36`

### Steps to reproduce

curl -X GET "https://blockscout.com/etc/mainnet/api?module=block&action=getblockreward&blockno=11376943" -H "accept: application/json"
or
https://blockscout.com/etc/mainnet/api?module=block&action=getblockreward&blockno=11376943

### Expected Behaviour

{
  result: {
    blockReward: "3200021000000000000"
  }
}

web3.fromWei('3200021000000000000', 'ether') -> 3.200021

### Actual Behaviour

{
  result: {
    blockReward: "5000021000000000000"
  }
}

web3.fromWei('5000021000000000000', 'ether') -> 5.000021

**Comment by vbaranov** [comment]
Fixed
