### ISSUE TITLE
[error] failed to fetch internal transactions for blocks

### ISSUE THREAD

**Issue by hadv** [poanetwork/blockscout#3348]
[error] failed to fetch internal transactions for blocks

```
2020-10-13T08:28:50.100 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: :closed
```

### Environment
* Elixir & Erlang/OTP versions (`elixir -version`): 1.10.3
* Operating System: Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-42-generic x86_64)
* Blockscout Version/branch:  3.3.2-beta

**Comment by vbaranov** [comment]
@HADV this error means that internal transactions fetcher failed to fetch internal transactions in the specific blocks range. But any fetcher will try to repeat collection further. If this error appears too often in the logs you can consider the next steps to mitigate it:
1. Increase spec of the DB server, application server, archive node server
2. Fine-tune batch size and concurrency for internal transactions fetcher https://github.com/poanetwork/blockscout/blob/master/apps/indexer/lib/indexer/fetcher/internal_transaction.ex#L23-L24. So, as a first step, you might want to decrease batch size. In the default setup, fetcher tries to fetch 10 blocks in a batch.
3. Configure monitoring from the data from *pending_transactions* table, which is used by that fetcher. If the count of elements there doesn't grow and it is close to 0, than you can assume that internal transactions fetcher is healthy.
