### ISSUE TITLE
xDai issue nft stuck

### ISSUE THREAD

**Issue by cockymiles** [poanetwork/blockscout#3361]
I just got some NFTs minted mint and attempted to have them sent from poap to my wallet thinking eth was all i needed. Well it says 0:xdai. I believe its tied up b/c I didn't have any xdai. Can this be fixed, i have the log info. I can get some xdai off uni but I'm not sure how to go about the rest or if its a done deal. If this can be rectified thatd be awsome thanks in advance*Describe your issue here.*

### Environment
* Elixir Version: 1.10.3
* Erlang Version: 22
* BlockScout Version: v3.3.3-beta

* User Agent: `Mozilla/5.0 (Linux; Android 10; SM-N960U Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/85.0.4183.101 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
You can use https://xdai-faucet.top/ faucet to get a tiny amount of xDai.
