### ISSUE TITLE
Energy Web Chain: <Issue Title>

### ISSUE THREAD

**Issue by Topdogg22** [poanetwork/blockscout#3364]
Hey All,
I sent my EWT from Bitmart exchange to my Nano Ledger ETH address.  I see the coins sitting in my wallet address: 0xA193A9E92F74802ebFB5A46f6cd7cF90B32c2C37
Do you know how i can move coins to my metamask EWT wallet or have them show in my Ledger?

### Environment
* Elixir Version: 1.9.1
* Erlang Version: 22
* BlockScout Version: v3.1.1-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Off-topic. Please reach out EWF support for this question https://t.me/energyweb
