### ISSUE TITLE
Mainnet: <did not recieve my tokens>

### ISSUE THREAD

**Issue by selinancy** [poanetwork/blockscout#3378]
*Describe your issue here.*
i didnt recieve my tokens, usdc even though its status is successful on your network <matic network order usdc>

kindly communicate on selinancy88@gmail.com
### Environment
* Elixir Version: 1.10.3
* Erlang Version: 22
* BlockScout Version: v3.3.3-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
This repository is for Blockscout explorer issues. Regarding Bridge questions, please, ask on [Forum](https://forum.poa.network/c/tokenbridge/25) or [Discord](https://discord.gg/mPJ9zkq)
