### ISSUE TITLE
xDAI - DAI Stuck in bridge

### ISSUE THREAD

**Issue by SonnyFuller** [poanetwork/blockscout#3379]
DAI Stuck in bridge. I have ETH on the Ethereum side. The xDAI says I just need to claim the tokens. However, it just sticks on the loading page for over the last 2 days. 

0x7d9febd9274fc713e9beac59ac1f7f5b804daa66c341ef1f28c2a53eff33386d

**Comment by vbaranov** [comment]
Out of topic. Please, ask your question in the [Forum](https://forum.poa.network/c/support/6)
