### ISSUE TITLE
xDai: <Issue Title>0x042d8bb1e2e481a73cba72d55bb194094854c8ca95d5f9aea2038993c3c1d6bb

### ISSUE THREAD

**Issue by cockymiles** [poanetwork/blockscout#3387]
*Describe your issue here.*didn't receive tockens wondering if I need to have them sent to another address or what. Hash 0x042d8bb1e2e481a73cba72d55bb194094854c8ca95d5f9aea2038993c3c1d6bb

### Environment
* Elixir Version: 1.10.3
* Erlang Version: 22
* BlockScout Version: v3.3.3-beta

* User Agent: `Mozilla/5.0 (Linux; Android 10; SM-N960U Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/85.0.4183.101 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
![Screenshot 2020-10-25 at 21 40 42](https://user-images.githubusercontent.com/4341812/97115905-c066b380-170a-11eb-83bf-2397ad65c8ef.png)

I see the tokens at the recipient's address
