### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by ScientiaLuxLucis** [poanetwork/blockscout#3388]
*Describe your issue here.*
Good afternoon I'm not sure if you can help in this situation but it seems as if somehow when sending 2 ETC to another individual's wallet the transaction  made a copy and sent 2 separate transactions under the same block number. Totaling 4 ETC sent and received p2p but only showing 2 ETC on the network.
### Environment
* Elixir Version: 1.10.3
* Erlang Version: 22
* BlockScout Version: v3.3.1-beta

* User Agent: `Mozilla/5.0 (Linux; Android 9; SM-G950U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.110 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by ScientiaLuxLucis** [comment]
![Screenshot_20201023-171535_Chrome](https://user-images.githubusercontent.com/72753844/97068777-a0af7e00-1598-11eb-81a7-ea95e49da8aa.jpg)
![Screenshot_20201023-171600_Coinbase](https://user-images.githubusercontent.com/72753844/97068778-a1481480-1598-11eb-8bc8-0b4018adf931.jpg)
![Screenshot_20201023-171610_Chrome](https://user-images.githubusercontent.com/72753844/97068779-a1481480-1598-11eb-87a0-fdb73d8b5bd3.jpg)
![Screenshot_20201023-171513_Coinbase](https://user-images.githubusercontent.com/72753844/97068780-a1481480-1598-11eb-9ebb-aade6425e65b.jpg)
![Screenshot_20201023-171523_Coinbase](https://user-images.githubusercontent.com/72753844/97068781-a1e0ab00-1598-11eb-9687-dac0e802677e.jpg)

**Comment by vbaranov** [comment]
I see in Blockscout that 4 ETC received by the recipient from 2 transactions as it should be:
https://blockscout.com/etc/mainnet/address/0xd2bCb6cA45fE9BAF147275766ffAc0dA3216614f/transactions

![Screenshot 2020-10-25 at 21 52 31](https://user-images.githubusercontent.com/4341812/97116157-6666ed80-170c-11eb-9d55-95d718a3061e.png)
