### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by chloe2901** [poanetwork/blockscout#3389]
*Describe your issue here.

I was trying to convert my ETC to US dollars however I accidently exchanged them for USDC. I then transferred them to my wallet then back to coinbase.  Thats where I am now but its been pending for 3 days.  How do I convert this into US dollars and then to deposit into my Paypal accoun?

Thanks,

Gary J Paccagnini  First Time user .
### Environment
* Elixir Version: 1.10.3
* Erlang Version: 22
* BlockScout Version: v3.3.1-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36 Edg/86.0.622.51`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
This issue tracker is for issues regarding Blockscout explorer itself.
