### ISSUE TITLE
Getting address balance and transactions through Blockscout's API

### ISSUE THREAD

**Issue by Eithcowich** [poanetwork/blockscout#3391]
I'm integrating xDAI DAOs to our dashboard at https://deepdao.io and trying to use the [Blockscout API](https://blockscout.com/poa/xdai/api-docs) for the DAO financial value. It seems like something is not aligned correctly.

Here's an example, regarding this address, 0xE3a89ed4956C4f7173418E4dEC2A77a5F60807DE

The transactions [here](https://blockscout.com/poa/xdai/address/0xE3a89ed4956C4f7173418E4dEC2A77a5F60807DE/transactions) show 4 txs, with a flow into the contract totaling 10k xDAI. 

When looking at the internal transactions by using the REST API, `action=txlistinternal` I get a huge number of calls, and the total value going out of the contract is 20k xDAI, which is impossible because it's larger than the total in. 

In addition there are several transactions which I know about and xDAI was transfered out of the contract, but are not recorded by the API. 

What am I missing?

**Comment by vbaranov** [comment]
I am closing this since discussion transferred to Forum https://forum.poa.network/t/getting-address-balance-and-transactions-through-blockscouts-api/4090
