### ISSUE TITLE
Incorrect Difficulty and Total Difficulty displayed for AuRa chains

### ISSUE THREAD

**Issue by varasev** [poanetwork/blockscout#3395]
Blockscout displays incorrect fields on block's page. Example for the block 12706000 on xDai:

`eth_getBlockByNumber` returns:

Difficulty: `340,282,366,920,938,463,463,374,607,431,768,211,454`
Total Difficulty: `4,323,627,754,097,444,116,765,637,762,028,046,894,426,622,359`

`Blockscout` for the same block shows:

Difficulty: `340,282,366,920,938,463,463,374,607,400,000,000,000`
Total Difficulty: `4,323,627,754,097,444,116,765,637,762,000,000,000,000,000,000`

**Comment by vbaranov** [comment]
Fixed
