### ISSUE TITLE
xDai: <Issue Title>

### ISSUE THREAD

**Issue by Izzyrose90** [poanetwork/blockscout#3410]
Hi there 

Ive sent my coins into blockscout by accident. How can i fix this problem i need my coins back. Csn you please out me out. 

Thanks*Describe your issue here.*

### Environment
* Elixir Version: 1.10.3
* Erlang Version: 22
* BlockScout Version: v3.3.3-beta

* User Agent: `Mozilla/5.0 (Linux; Android 10; SAMSUNG SM-G965F) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/12.1 Chrome/79.0.3945.136 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by Izzyrose90** [comment]
Please email me back

**Comment by vbaranov** [comment]
Blockscout is just an explorer. You cannot send coins into it.
