### ISSUE TITLE
Mainnet: <IssuI sent some EASY tokens to my Binance EASY wallet from Metamask from Matic Mainet. it appears that it never reached Ethereum chain.  transaction=0x485f09770e72e681275c4431c9605759c1c0a8e4414b51a507e913759cebe3f7 Title>

### ISSUE THREAD

**Issue by TickleTestTickle** [poanetwork/blockscout#3416]
*Describe your issue here.*

### Environment
* Elixir Version: 1.10.3
* Erlang Version: 22
* BlockScout Version: v3.3.3-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by TickleTestTickle** [comment]
Hope this goes to Matic Mainnet techs.  I sent EASY tokens from Matic Mainnet to EASY wallet on Binance, but tokens never showed.  although txn shows success in Matic explorer, but nothing in Ethereum explorer.  Please advise.

**Comment by vbaranov** [comment]
Matic support is in their fork https://github.com/maticnetwork/blockscout. Please ask there.
