### ISSUE TITLE
Blockscout fails to "Read Contract" view functions

### ISSUE THREAD

**Issue by drortirosh** [poanetwork/blockscout#3418]
The "Read Contract" on a deployed contract fails with no apparent reason

### Environment

https://blockscout.com/etc/kotti
* Blockscout Version/branch: currently deployed kotti blockscout (Version: v3.3.3-beta)

### Steps to reproduce

1. Open this URL:
https://blockscout.com/etc/kotti/address/0x28708de1d5c681427C3F36170929D31184C113B4/read-contract

This is a deployed GSN RelayHub on kotti network.
IT shows the contract code, ABI, but fails to show "read functions" (it does show "write functions") 

The same code, with the same ABI is deployed on other networks, and is visible through etherscan, 
e.g. on goerli:
https://goerli.etherscan.io/address/0x1F3d1C33977957EA41bEdFDcBf7fF64Fd3A3985e#readContract

### Expected behaviour

Should be able to see read-only values from view functions.
I can suspect it fails to parse some methods which use struct (ABIv2) parameters.
In such case, I'd expect it to skip just these methods, instead of not showing any method at all.

### Actual behaviour

displays "error"

**Comment by vbaranov** [comment]
Fix is ready. However, it is not applied to Kotti chain yet.

**Comment by drortirosh** [comment]
Is it applied on another network?
also, any ETA when it will be available on kotti?

**Comment by vbaranov** [comment]
> Is it applied on another network?

Currently applied on Sokol testnet and xDai

> also, any ETA when it will be available on kotti?

no ETA

**Comment by vbaranov** [comment]
Update installed to Kotti
