### ISSUE TITLE
Energy Web Chain: <Issue Title>

### ISSUE THREAD

**Issue by PayPaul1** [poanetwork/blockscout#3419]
*Describe your issue here.*

Hi, I tried withdrawing my EWT from KuCoin to my Coinbase Wallet, later finding out Coinbase Wallet only supports ERC-20 tokens and that EWT is not one.  Is there someway to retrieve my ETW funds?  I can see the transaction details in the energy web explorer.   Please advise, thanks!

### Environment
* Elixir Version: 1.9.1
* Erlang Version: 22
* BlockScout Version: v3.1.1-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.99 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by PayPaul1** [comment]
Hi, I tried withdrawing my EWT from KuCoin to my Coinbase Wallet, later finding out Coinbase Wallet only supports ERC-20 tokens and that EWT is not one. Is there someway to retrieve my ETW funds? I can see the transaction details in the energy web explorer. Please advise, thanks!

**Comment by vbaranov** [comment]
Please contact EWF support https://t.me/energyweb

**Comment by PayPaul1** [comment]
Thank you
