### ISSUE TITLE
getBlockReward returns 500

### ISSUE THREAD

**Issue by Donquih0te** [poanetwork/blockscout#3425]
HTTP GET to the request url http://explorer.energyweb.org/api?module=block&action=getblockreward&blockno=1111
returrns 500

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): 1.9.1
* Operating System: Linux Mint
* Blockscout Version/branch: 

### Steps to reproduce

visit endpoint:
http://explorer.energyweb.org/api?module=block&action=getblockreward&blockno=1111

### Expected behaviour

{
  "message": "OK",
  "result": {
    "blockMiner": "0x13a06d3dfe21e0db5c016c03ea7d2509f7f8d1e3",
    "blockNumber": "2165403",
    "blockReward": "5314181600000000000",
    "timeStamp": "1472533979",
    "uncleInclusionReward": null,
    "uncles": null
  },
  "status": "1"
}

### Actual behaviour

{"status":"0","result":null,"message":"Something went wrong."}

**Comment by vbaranov** [comment]
I suppose Energyweb explorer is hosted by EWF. We do not own it. I already sent instructions to you in Gitter https://gitter.im/poanetwork/blockscout?at=5fa15e88b4283c208a4187cb how to solve this issue. Please, reach out Energyweb team https://t.me/energyweb
