### ISSUE TITLE
xDai: <Issue Title>

### ISSUE THREAD

**Issue by ramzey6666** [poanetwork/blockscout#3426]
*Describe your issue here.*

### Environment
* Elixir Version: 1.10.3
* Erlang Version: 22
* BlockScout Version: v3.3.3-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36`

### Steps to reproduce

added too many transaction at ones (my swap cancel due to low balance so i added liquidity and try again problem started from there)

### Expected Behavior

*Tell us what should happen.* cancel all pending transactions

### Actual Behavior

*Tell us what happens instead.*to many transactions being added instead

**Comment by vbaranov** [comment]
I doubt Blockscout explorer support is the right place for this question.
