### ISSUE TITLE
Genesis parse error

### ISSUE THREAD

**Issue by iFA88** [poanetwork/blockscout#3427]
Greetings, sadly i have issue with the genesis file parsing. I got this error:
```
2020-11-02T17:09:38.351 [error] Task #PID<0.5262.0> started from Explorer.ChainSpec.GenesisData terminating
** (MatchError) no match of right hand side value: {:error, [#Ecto.Changeset<action: nil, changes: %{hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    (explorer 0.0.1) lib/explorer/chain_spec/genesis_data.ex:71: anonymous fn/2 in Explorer.ChainSpec.GenesisData.fetch_genesis_data/0
    (elixir 1.10.4) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.4) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: #Function<1.72970732/0 in Explorer.ChainSpec.GenesisData.fetch_genesis_data/0>
    Args: []
2020-11-02T17:29:37.881 [error] Task #PID<0.3427.0> started from Explorer.ChainSpec.GenesisData terminating
** (MatchError) no match of right hand side value: {:error, [#Ecto.Changeset<action: nil, changes: %{hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    (explorer 0.0.1) lib/explorer/chain_spec/genesis_data.ex:71: anonymous fn/2 in Explorer.ChainSpec.GenesisData.fetch_genesis_data/0
    (elixir 1.10.4) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.4) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: #Function<1.72970732/0 in Explorer.ChainSpec.GenesisData.fetch_genesis_data/0>
    Args: []
```
The genesis file: https://www.fusionsolutions.io/doc/ilctGenesis.json

OpenEthereum can parse the file without any problem.

My environment:
```
Erlang/OTP 23 [erts-11.1] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1]
Elixir 1.10.4 (compiled with Erlang/OTP 22)
Linux ip-172-31-40-116 4.19.0-12-cloud-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux
Blockscout 3.3.3-beta
```

**Comment by vbaranov** [comment]
@iFA88 The issue is because you didn't add `0x...` prefix to *constructor* property of precompiled contracts. Are you sure, that those contracts actually contain bytecode, that you set? From [OpenEthereum chain spec docs](https://openethereum.github.io/wiki/Chain-specification):

> contract constructor, similar to sending a transaction with bytecode "0x...": { "balance": "100000000000", "constructor": "0x..." }. The constructor bytecode is executed when the genesis is created and the code returned by the “constructor” is stored in the genesis state.

**Comment by iFA88** [comment]
OpenEthereum client works flawless with that genesis file. Currently have 3 validators and 3 nodes on my test network. But thanks for the tip i would apply 0x for the bytecode.

**Comment by vbaranov** [comment]
But possibly it could skip bytecode of contracts. I will leave the code unchanged since it is documented to use `0x` prefix. Please reopen if the genesis import issue will persist even with `0x`
