### ISSUE TITLE
Energy Web Chain: <Issue Title>

### ISSUE THREAD

**Issue by levicbrown** [poanetwork/blockscout#3429]
*Describe your issue here.*

Hi - I sent 2500 EWT to a Metamask wallet address within the last 60 days. My computer went down on me so I had to get a new computer and set up the Metamask wallet again. When I went to restore the seed file it wouldn't allow me on to my account saying it was invalid. I wrote this seed phrase down very carefully and multiple times. When I get on https://explorer.energyweb.org/ I can see my balance. Is there a way for me to access these funds? Please help!

### Environment
* Elixir Version: 1.10.3
* Erlang Version: 22
* BlockScout Version: v3.3.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Energyweb support is here https://t.me/energyweb
