### ISSUE TITLE
Energy Web Chain: <Issue Title>

### ISSUE THREAD

**Issue by levicbrown** [poanetwork/blockscout#3438]
*Describe your issue here.*
I sent some EWT to a Metamask wallet address in the last 90 days. My computer went down so I had to get a new computer and set up the Metamask wallet again. I was able to import my seed phrase to a metamask wallet account, however it shows 0 EWT tokens in the wallet. I can see the EWT tokens in the original metamask wallet address that I sent them to in  https://explorer.energyweb.org/  The addresses are different too. Why is this? How can I access my EWT Tokens?

### Environment
* Elixir Version: 1.10.3
* Erlang Version: 22
* BlockScout Version: v3.3.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Please contact EWF support https://t.me/energyweb
