### ISSUE TITLE
Problem with contract verification after upgrade from 3.1.1 to 3.3.3

### ISSUE THREAD

**Issue by GrzegorzMatuszakTSH** [poanetwork/blockscout#3441]
Last week we upgraded Blockscout from 3.1.1 to 3.3.0. After this change, we found that one contract stopped return data from `getAbi` endpoint. So we decided to upgrade Blockscout to 3.3.3 with the hope that it will fix the problem. It didn't help.

What is strange:

[Ewc endpoint ](https://explorer.energyweb.org/api?module=contract&action=getabi&address=0x34CfAC646f301356fAa8B21e94227e3583Fe3F5F) returns `result: null` now.
But [Blockscout](https://blockscout.com/poa/xdai/api?module=contract&action=getabi&address=0x34CfAC646f301356fAa8B21e94227e3583Fe3F5F) doesn't have any problems.

We went to [Blockscout contract page](https://blockscout.com/poa/xdai/address/0x34CfAC646f301356fAa8B21e94227e3583Fe3F5F/contracts) and this contract is verified. When we try to [verify it on Ewc side](https://explorer.energyweb.org/address/0x34CfAC646f301356fAa8B21e94227e3583Fe3F5F/contract_verifications/new) with data taken from Blockscout we get `Compiler version does not match, please try again`.

I checked variables - we don't have deprecations, also all migrations are executed.

No idea where is a problem. Could you help up with this?

### Environment

* Blockscout image https://hub.docker.com/layers/energyweb/blockscout-explorer/v3.3.3-beta/images/sha256-d7cbf8113e54bae680571c3232b3990ba5a9c4ff2a67931cdf1c0582e69c51a7?context=explore built from [Dockerfile](https://github.com/energywebfoundation/blockscout/blob/ewc_canon/Dockerfile) which is based on your [Dockerfile](https://github.com/energywebfoundation/blockscout/blob/ewc_canon/docker/Dockerfile)
* Parity 2.5.13
* Operating System:
18.04.4 LTS (GNU/Linux 5.3.0-1017-aws x86_64)
* Blockscout Version/branch: 
[3.3.3 -we have fork with minor style changes](https://github.com/energywebfoundation/blockscout/tree/ewc_canon)

### Steps to reproduce
- Go to https://explorer.energyweb.org/address/0x34CfAC646f301356fAa8B21e94227e3583Fe3F5F/contracts
- Contract is not verified (it was before the upgrade)
- Try to verify contract with data from [blockscout](https://blockscout.com/poa/xdai/address/0x34CfAC646f301356fAa8B21e94227e3583Fe3F5F/contracts)

### Expected behavior

Contract is verified

### Actual behavior

Error -  `Compiler version does not match, please try again`

**Comment by vbaranov** [comment]
@GrzegorzMatuszakTSH I verified that contract https://explorer.energyweb.org/address/0x34CfAC646f301356fAa8B21e94227e3583Fe3F5F/contracts. It, indeed, was compiled with the different version of the compiler.

Verified contracts are stored in `smart_contracts` table. Maybe, somehow, it cleared during the update? Didn't you start a new version of Blockscout on a new database instance? If that you lose all verified contracts since verified contracts are not part of the DB migrations, but rather data provided by users.

**Comment by GrzegorzMatuszakTSH** [comment]
Hi, @vbaranov thank you for your reply!
We use the same database. It looks like you described - we have only 19 rows now in the `smart_contracts` table, so probably something removed data from this table during the update.
Unfortunately, I'm not able to say which step did that :/

Do I understand correctly, that the only possible way to solve our problem is to verify manually everything?
And regarding the current problem, we're not able to just take data from Blockscout to verify stuff, we have to guess versions, am I right?

**Comment by vbaranov** [comment]
> Do I understand correctly, that the only possible way to solve our problem is to verify manually everything?

If you have no backup of DB/table, yes, you need manually verify.

> And regarding the current problem, we're not able to just take data from Blockscout to verify stuff, we have to guess versions, am I right?

Exact compiler version can be extracted from bytecode contract https://solidity.readthedocs.io/en/v0.7.4/metadata.html#

**Comment by GrzegorzMatuszakTSH** [comment]
Thank you for your explanation.
