### ISSUE TITLE
Blockscout gets stuck when parity returns error

### ISSUE THREAD

**Issue by GrzegorzMatuszakTSH** [poanetwork/blockscout#3451]
Hi, we got a report that our volta Blockscout stopped working correctly.
The last block which it showed was [9027389](https://volta-explorer.energyweb.org/blocks/9027389/transactions).
When I was searching logs I found in parity logs:
```
parity_1      | 2020-11-10 22:00:02 UTC Error serving connection: Error(BodyWrite, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })
```

So, it looks like thanks to Parity, Blockscout got stuck. 
This is not the first time when Blockscout got stuck (e.g. faced this problem for volta and Ewc 3 times in the last 7 days), but the first when I had time to investigate it.

I fixed the problem with a docker container restart.

I created a workaround - cron which restarts Blockscout each x minutes. I don't like this, so maybe you're able to find a permanent solution for that.

### Environment

* Blockscout image built from [Dockerfile](https://github.com/energywebfoundation/blockscout/blob/ewc_canon/Dockerfile) which is based on your [Dockerfile](https://github.com/energywebfoundation/blockscout/blob/ewc_canon/docker/Dockerfile)
* Parity 2.5.13
* Operating System:
18.04.4 LTS (GNU/Linux 5.3.0-1030-aws x86_64)
* Blockscout Version/branch: 
3.3.3 - we have fork with minor style changes

### Steps to reproduce

- Provoke parity error (Broken pipe)
- Check explorer main page

### Expected behaviour

Parity still works even with that error, so Blockscout should also try to continue work

### Actual behaviour

Blockscout shows data before parity errors instead of the newest.

**Comment by vbaranov** [comment]
@GrzegorzMatuszakTSH btw, do you have a receipt how to provoke Broken pipe error?

**Comment by GrzegorzMatuszakTSH** [comment]
Regarding the logs, the last time when `Broken pipe` error happened was during parity container restart.

Today we had again a problem with stucked Blockscout. We were experimenting with IPC mode, so I'm not sure if the source was the same.

We turned off IPC mode again and watch if it happens again.

**Comment by vbaranov** [comment]
@GrzegorzMatuszakTSH I summon you to try https://github.com/poanetwork/blockscout/releases/tag/v3.5.0-beta. It is more stable in Docker container, that 3.4.0. Please re-open if the issue still presents with 3.5.0.
