### ISSUE TITLE
xDai: <Issue Title> HI ,  MY CHAINLINK TOKEN STUCK 

### ISSUE THREAD

**Issue by jor8872** [poanetwork/blockscout#3452]
*Describe your issue here.*
xDai: <Issue Title> HI , I SEND MY CHAINLINK TOKEN FROM MY METAMASK ( XDAI CHAIN NETWORK ) TO MY ETH WALLET AT CRYPTO.COM , BUT UNFORTUNATLY WHEN IT DEALYED TO SHOW IN CRYPTO.COM WALLET I CONTACTED THE SUPPORT AND THEY TOLD ME THAT THEY DONT ACCEPT ANY TRANSACTIONS FROM XDAI NETWORK SO ITS STUCK , HOW CAN I GET MY CHAINLINK BACK , THANKS

### Environment
* Elixir Version: 1.10.3
* Erlang Version: 22
* BlockScout Version: v3.3.3-beta

* User Agent: `Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.193 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Open receiver address at MetaMask when connected to xDai. You should see the token there.

**Comment by jor8872** [comment]
> Open receiver address at MetaMask when connected to xDai. You should see the token there.

thanks for reply ,can you help me pls when i open metamask where should find the reciever and how can do with the chainlink which is out of metamask ?

**Comment by vbaranov** [comment]
You should import your account from crypto.com to MetaMask via private key or via seed phrase (do not post them here)

**Comment by jor8872** [comment]
but crypto.com they didnot recieve because they dont accept any transaction from xdai network , and i can see my chainlink stuck at blockscout

**Comment by jor8872** [comment]
its recieved midway at token proxy which i dont understand
