### ISSUE TITLE
Explorer internal server error when read contract

### ISSUE THREAD

**Issue by helderjnpinto** [poanetwork/blockscout#3455]
This issue is in @matic network explorer using blockscout, the team can't figure out what is happening, read interface give a internal server error but write interface not.

See here [transaction](https://mumbai-explorer.matic.today/address/0xB90547a6F35Fb7C9121967FDb5490bA08500E51E/read-contract)

Here is the reported matic issue, also has the link of transaction and contract verified code to reproduce the error.
[Issue Matic blockscout explorer](https://github.com/maticnetwork/blockscout/issues/14)

### Steps to reproduce

Verify the contract
Read contract interface using explorer

### Expected behaviour

Write interface works but read not

### Actual behaviour

Read interface give a Internal Server Error

**Comment by vbaranov** [comment]
@helderjnpinto Matic instance uses not the latest version of Blockscout. It worth to update to [3.4.0](https://github.com/poanetwork/blockscout/releases/tag/v3.4.0-beta). There were updates for "Read Contract" page.

**Comment by helderjnpinto** [comment]
@vbaranov thank you i will notify matic team, and give feedback
