### ISSUE TITLE
ewt to ledger wallet funds not received transition went threw

### ISSUE THREAD

**Issue by bashbyyy** [poanetwork/blockscout#3458]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System:
* Blockscout Version/branch: 

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by bashbyyy** [comment]
I tried sending my ewt to my wallet and it has not been received transition went threw is there any way to reverse the transaction back to the exchange ?

**Comment by vbaranov** [comment]
https://github.com/poanetwork/blockscout/issues/3232#issuecomment-671725035

> please contact https://www.energyweb.org/ on the topic
for example, their Telegram channel https://t.me/energyweb
