### ISSUE TITLE
xDai: Pending tx for 20 days. 

### ISSUE THREAD

**Issue by cryptopauls** [poanetwork/blockscout#3459]
I tried to do a transaction on Honeyswap on 27 Oct 2020. "Sorry, We are unable to locate this transaction Hash" has been showing on blockscout ever since and it's completely stopped my trading in Honeyswap. When i request metamask to cancel the tx, i get a "BigNumber Error." When i try to "speed up" it accepts it, but nothing happens. 

https://blockscout.com/poa/xdai/tx/0xbf412913e2fa37e2e73b85ce694d4252067e079b9fb351243003eeb3c8e7f789

Tx ID:  0xbf412913e2fa37e2e73b85ce694d4252067e079b9fb351243003eeb3c8e7f789

From: 0xb0E4B69A018B35102dc648F81542efB88744B5EF
To: 0x1C232F01118CB8B424793ae03F870aa7D0ac7f77

From: 0xb0E4B69A018B35102dc648F81542efB88744B5EF

To: 0x1C232F01118CB8B424793ae03F870aa7D0ac7f77
Transaction
Nonce
22
Amount
-0 XDAI
Gas Limit (Units)
10000000
Gas Price (GWEI)
?
Total
0
XDAI
Activity Log

Transaction created with a value of 0 xDai at 14:12 on 10/27/2020.

Transaction submitted with gas fee of 0 WEI at 14:12 on 10/27/2020.

 Environment
* Elixir Version: 1.10.3
* Erlang Version: 22
* BlockScout Version: v3.4.0-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
@cryptopauls which RPC endpoint did you set up for xDai in MetaMask?

**Comment by varasev** [comment]
@cryptopauls please also clarify what exactly gas price you set when retrying?

**Comment by cryptopauls** [comment]
https://xdai.poanetwork.dev

I've done a dozen successful transactions before this error occurred.

**Comment by cryptopauls** [comment]
155/10000000

**Comment by varasev** [comment]
@cryptopauls 

> 155/10000000

You mean 155 gas price and 10 000 000 gas limit?

Could you try to use `Reset Account` feature in MetaMask? Settings -> Advanced. And then try to send your transaction again with a proper gas price of 10 or 20 GWei and gas limit less than 10 000 000 (it's too much - some validators on xDai has `--tx-gas-limit` option set to less than 10 thousand).

**Comment by vbaranov** [comment]
I am closing this since no answer. @cryptopauls please reopen the issue if the problem still present.
