### ISSUE TITLE
Please Stole My ETC 18.14 Coin..

### ISSUE THREAD

**Issue by anandsbisht** [poanetwork/blockscout#3471]
Dear Sir / Madam...Please Help Me As I Did Mining Through Nano pool And Earn 18.14 ETC Coin And Transfer To ETC Wallet :

https://ethereumproject.github.io/etherwallet/

https://etc.ethermine.org/

Recently I Checked With Emerald Support And They Confirmed I Still Have 18.14 ETC Balance But Now I Checked With Them To Transfer To Robinhood or Coinbase Account..

They Said They Don't Know How. Now When We Access The Balance It Shows 0 Balance..

And They Send Me The Link..

	
https://receipt.emerald.cash/tx/0xef1bbd89057ae0a35ddf8000bdb6d0a6f9a4d665713564ab2c0bf92206d22d7a

Please Help If Somebody Can Let Me Know Who Got These Coin or Who Stole These Coin.. 

Thanking You..

ANAND

**Comment by vbaranov** [comment]
This issue tracker is for Blockscout - related questions. Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
