### ISSUE TITLE
Contract Call Success

### ISSUE THREAD

**Issue by PLURRULP** [poanetwork/blockscout#3472]
Hi there... can you tell me what does this mean? I got "**Transaction Success**" on every Transaction, but this last one I got "**Contract Call Success**". Why? Thank you!

**Comment by vbaranov** [comment]
Successfully mined transaction to contract which actually calls some of contract's method.

**Comment by PLURRULP** [comment]
Hi, thank you for the fast replay, what I need to know my wallet is on poloniex and I still didn't receive my ETC  that address in black square is my address on poloinex.. should I expect to get it soon or my ETC send to some other address (stolen)? Thank you once again!
 
    On Saturday, November 21, 2020, 01:10:43 PM GMT+1, Victor Baranov <notifications@github.com> wrote:  
 
 


Successfully mined transaction to contract which actually calls some of contract's method.
