### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by janartht** [poanetwork/blockscout#3478]
*Describe your issue here.*

### Environment
* Elixir Version: 1.10.3
* Erlang Version: 22
* BlockScout Version: v3.3.1-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 14_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

ETC HAS TO BE SENT TO MY COINBASE ACCOUNT 

### Actual Behaviour

The transaction is still pending

**Comment by vbaranov** [comment]
This issue tracker is for Blockscout - related questions. Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
