### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by Mustafa77-tech** [poanetwork/blockscout#3481]
*Describe your issue here.*
My payment is still pending Why
This is the link for the transaction why Unconfirmed is still pending
https://blockscout.com/etc/mainnet/tx/0x91020b2a14d6f8b88403567443470e63241b8849d4049c31d7ffb770e4f058c5/internal_transactions
![Screenshot_٢٠٢٠١١٢٣-١٩٢٨٤٤](https://user-images.githubusercontent.com/74837148/100160233-3869fa00-2ec0-11eb-9ef6-b7ca187df45c.png)
![Screenshot_٢٠٢٠١١٢٣-١٩٢٤٥٠](https://user-images.githubusercontent.com/74837148/100160253-4455bc00-2ec0-11eb-9c11-0023e7492406.png)

https://blockscout.com/etc/mainnet/tx/0x91020b2a14d6f8b88403567443470e63241b8849d4049c31d7ffb770e4f058c5/internal_transactions

### Environment
* Elixir Version: 1.10.3
* Erlang Version: 22
* BlockScout Version: v3.3.1-beta

* User Agent: `Mozilla/5.0 (Linux; Android 8.1.0; M762G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
