### ISSUE TITLE
Read Contract tab doesn't work for one of contracts

### ISSUE THREAD

**Issue by varasev** [poanetwork/blockscout#3488]
Example: https://blockscout.com/poa/xdai/address/0x5f849Fee27a1029fA5bDFA610677f95a82B47Eb8/read-contract

Probably, the reason is that this contract uses `pragma experimental ABIEncoderV2` - some its public getters (such as `getPriorities()` and `getMinGasPrices()`) return array of structs (tuples).

**Comment by vbaranov** [comment]
Fixed
