### ISSUE TITLE
could not compile dependency :ex_keccak

### ISSUE THREAD

**Issue by raychan3690** [poanetwork/blockscout#3499]
===> Compiling cowlib
===> Compiling cowboy
===> Compiling cowboy_telemetry
===> Compiling accept
==> ex_keccak
Compiling NIF crate :exkeccak (native/exkeccak)...
could not compile dependency :ex_keccak, "mix compile" failed. You can recompile this dependency with "mix deps.compile ex_keccak", update it with "mix deps.update ex_keccak" or clean it with "mix deps.clean ex_keccak"
** (ErlangError) Erlang error: :enoent
    (elixir 1.11.2) lib/system.ex:815: System.cmd("cargo", ["rustc", "--release"], [cd: "/home/ubuntu/besu-explorer/blockscout/deps/ex_keccak/native/exkeccak", stderr_to_stdout: true, env: [{"CARGO_TARGET_DIR", "/home/ubuntu/besu-explorer/blockscout/_build/dev/rustler_crates/exkeccak"}], into: %IO.Stream{device: :standard_io, line_or_bytes: :line, raw: false}])
    (rustler 0.21.1) lib/mix/tasks/compile.rustler.ex:59: Mix.Tasks.Compile.Rustler.compile_crate/1
    (elixir 1.11.2) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
    (rustler 0.21.1) lib/mix/tasks/compile.rustler.ex:15: Mix.Tasks.Compile.Rustler.run/1
    (mix 1.11.2) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.2) lib/mix/tasks/compile.all.ex:90: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.11.2) lib/mix/tasks/compile.all.ex:70: Mix.Tasks.Compile.All.compile/4
    (mix 1.11.2) lib/mix/tasks/compile.all.ex:57: Mix.Tasks.Compile.All.with_logger_app/2

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):Erlang/OTP 23 [erts-11.0.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe], Elixir 1.11.2 (compiled with Erlang/OTP 23)
* Operating System: Ubuntu 18.04
* Blockscout Version/branch: master

### Steps to reproduce

mix do deps.get, local.rebar --force, deps.compile, compile

### Expected behaviour

Should success

### Actual behaviour

*Tell us what happens instead.*
Have mix compile error on dependency:ex_keccak

**Comment by vbaranov** [comment]
@raychan3690 in order to compile `ex_keccak` package you need to have Rust compiler `rustc` installed https://www.rust-lang.org/tools/install.

The current list of prerequisites: https://docs.blockscout.com/for-developers/information-and-settings/requirements
