### ISSUE TITLE
Ethereum Classic: I didn't get my ETC on my deposit address 

### ISSUE THREAD

**Issue by Lecenje69** [poanetwork/blockscout#3512]
It says that the transaction is completed but i didn't get the ETC on my deposit address
Here is the link from the transaction details 
https://blockscout.com/etc/mainnet/tx/0xb6954b406e8e657171ee27b709eaafa3e375d4ddbf87086862aba7a173915d9d/internal_transactions
Can you help me with this?
Thank you

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
