### ISSUE TITLE
Missing internal_transactions_indexed_at in transactions table

### ISSUE THREAD

**Issue by zalam003** [poanetwork/blockscout#3520]
*Missing internal_transactions_indexed_at*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Erlang/OTP 23, Elixir 1.11.2
* Operating System: Ubuntu 18.04
* Blockscout Version/branch: v3.4.0-beta

### Steps to reproduce

Ran following on the database
```
=# SELECT COUNT(1) FROM blocks WHERE internal_transactions_indexed_at IS NULL and consensus;
ERROR:  column "internal_transactions_indexed_at" does not exist
LINE 1: SELECT COUNT(1) FROM blocks WHERE internal_transactions_inde..
```

### Expected behaviour

*Expect a result back.*

### Actual behaviour

Get the following error:
```
ERROR:  column "internal_transactions_indexed_at" does not exist
LINE 1: SELECT COUNT(1) FROM blocks WHERE internal_transactions_inde..
```

**Comment by vbaranov** [comment]
https://gitter.im/poanetwork/blockscout?at=5fd323e43dd3b251a4fc400a
> starting with release 3.0.0 https://github.com/poanetwork/blockscout/releases/tag/v3.0.0-beta there is no internal_transactions_indexed_at  field in the table internal_transactions  anymore. Nowadays, status of the internal transactions fetching is checked within pending_block_operations  table.
