### ISSUE TITLE
Internal transaction for missed blocks

### ISSUE THREAD

**Issue by zalam003** [poanetwork/blockscout#3524]
Blockscout polls internal transaction for blocks that were missed.  This is a unnecessary call / operation.  You should first check if data for a block exist before looking at the internal transaction for that block.

Indexer is failing to catch up blocks 420120 through 420111.  It has gone through all the blocks from current to genesis block.

```
2020-12-16T21:50:48.769 application=indexer fetcher=block_catchup first_block_number=420120 last_block_number=420111 step=receipts [error] failed to fetch: [%{code: -32602, data: %{block_hash: "0xc7186887e548420951ad7d9fffd22c40609298aa9ea13935ab922bc38e9a927a", block_number: 420112, from_address_hash: "0x0000000000000000000000000000000000000320", gas: 30000000, gas_price: 0, hash: "0xd033e329ae49a9ab0a6b50ac3330a1d5d48a21d7952d29bef06e45bea35c3fdc", index: 0, input: "0x228cb733", nonce: 420134, r: 0, s: 0, to_address_hash: "0x0000000000000000000000000000000000000300", transaction_index: 0, v: 800, value: 13700000000000000000}, message: "Not Found"}]. Retrying.
```

At other instances, it will poll and collect the internal transaction data for a block.  But since the block data is not present, it cannot commit the data.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
```
Erlang/OTP 23 [erts-11.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.11.2 (compiled with Erlang/OTP 21)
```
* Operating System:  Ubuntu 18.04
* Blockscout Version/branch:  v3.4.0-beta

### Steps to reproduce

* Checked web page and database to make sure there is data for the block:
```select * from blocks where number = 420120;```

### Expected behaviour

*Should have seen data for the block*

### Actual behaviour

*No data for the block that indexer was trying to populate*

**Comment by vbaranov** [comment]
@zalam003 you should try the latest version of the master branch. It contains a performance update for indexer https://github.com/poanetwork/blockscout/pull/3457. If it will not help, please re-open the issue with the new details. The latest version from a master branch shouldn't request internal transactions for not yet collected blocks. Internal transactions fetching is triggered by requesting of `pending_block_operations` table. And a new row for the block with specific hash in that table appears after that block is collected.

**Comment by zalam003** [comment]
@vbaranov I have downloaded the master branch from from about 4:00AM UTC Dec 18th.  I am running is at the moment.

I am running the following to check how many blocks I have left:
```
select count(*) from pending_block_operations where fetch_internal_transactions = true;
```
