### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by MaLoFr3ak** [poanetwork/blockscout#3528]
*Describe your issue here.*
I have been waiting for 3 separate withdrawal transfers from my COINBASE Wallet App to my COINBASE account. ETC IN THE AMOUNTS OF $10.00 $5.00 AND $5.00 . I received an email stating it may take up to 3,275 block confirmations it is well passed 17000 block confirmations. Please help me understand what is going on? Thank you best regards Mr Bravo
### Environment
* Elixir Version: 1.10.3
* Erlang Version: 22
* BlockScout Version: v3.3.1-beta

* User Agent: `Mozilla/5.0 (Linux; Android 10; LM-K500) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by MaLoFr3ak** [comment]
I would like to be able to access and sell my ETC for Cash and withdrawal my funds.

**Comment by vbaranov** [comment]
Reach out ETC team on their Discord https://discord.com/invite/hQs894U.
