### ISSUE TITLE
Ethereum Classic: <not able to send tokens>

### ISSUE THREAD

**Issue by samiralami** [poanetwork/blockscout#3529]
*Describe your issue here.*
I tried 3 times to transfer 4 tokens to my coinbase wallet and was unsuccessfull.  I tried to check on the transaction status, I get "Sorry, We are unable to locate this transaction Hash"
here is the latest transaction hash: 
0xfd9214f96c623ff639f11e8f272fd0fd85c5613c4dcc0fb120b4ca4373fbb2b5
### Environment
* Elixir Version: 1.10.3
* Erlang Version: 22
* BlockScout Version: v3.3.1-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*
I used "Ledger Live" to send tokens from my nano s.

### Expected Behaviour

my coin account should receive the tokens.  also, I should be able to track my transaction.

### Actual Behaviour
I cannot transfer Ethereum classic token.

**Comment by vbaranov** [comment]
Reach out ETC team on their Discord https://discord.com/invite/hQs894U.
