### ISSUE TITLE
Write contract functionality giving error on Ethereum Classic

### ISSUE THREAD

**Issue by Dan-UVC** [poanetwork/blockscout#3538]
Tag as requested @bobsummerwill

When trying to use the write contract functionality on blockscout I'm getting the following error saying Blockscout is for the ETH chain:

https://imgur.com/5GFseHU

The contract I'm using this on is: https://blockscout.com/etc/mainnet/address/0xd6dF0C579f2A65049a893fDaEC9fCE098CC19F87/write_contract

### Environment

Chrome/Firefox browser on Windows 10
Replicated when connected to the ETC Network with Metamask and Saturn Wallet

### Steps to reproduce

Go on above link, connect an ETC enabled browser wallet such as Metamask with custom RPC endpoint and try and interact with the contract.

### Expected behaviour

Interaction works

### Actual behaviour

Gives me an error saying Blockscout is for the ETH chain - see above screenshot

**Comment by vbaranov** [comment]
Instruction how to fix the issue has been sent to Ethereum Classic Cooperative representative.

**Comment by bobsummerwill** [comment]
Thanks, @vbaranov!
I will reply here when we are (hopefully) fixed.

**Comment by bobsummerwill** [comment]
@Dan-UVC The suggested changes have been made on the ETC mainnet BlockScout instance.
Please could you re-try and verify the fix?
Thank you!

**Comment by Dan-UVC** [comment]
Hi @bobsummerwill 

I see new features have popped up (like the 10^x feature) and shows the wallet as connected but the write buttons do nothing. When I click on them nothing happens. 

https://imgur.com/tOUrv42

Read contract appears to work but some of the naming conventions are lost. For example the function in the UVCX contract of:

function allInfoFor(address _user) public view returns (uint256 totalTokenSupply, uint256 totalTokensFrozen, uint256 userBalance, uint256 userFrozen, uint256 userDividends) {return (totalSupply(), totalFrozen(), balanceOf(_user), frozenOf(_user), dividendsOf(_user));}

Shows as this: https://imgur.com/iep7e5p

I.e. just a list of uint256 instead of giving the names of each item (I'm 99.999999% sure it used to give all the names).

Thanks!

**Comment by vbaranov** [comment]
@Dan-UVC
> When I click on them nothing happens whereas it used to load a tx for me to confirm.

try to re-connect to your wallet. I have no issues with write methods on ETC Blockscout instance and NiftyWallet. Wallet's tx popup appears in my case.

>function allInfoFor(address _user) public view returns (uint256 totalTokenSupply, uint256 totalTokensFrozen, uint256 userBalance, uint256 userFrozen, uint256 userDividends) {return (totalSupply(), totalFrozen(), balanceOf(_user), frozenOf(_user), dividendsOf(_user));}

As far as I can see, It is a read-only function and it is displayed at "Read contract" page. Your screenshot is for "Write contract" page.

**Comment by Dan-UVC** [comment]
@vbaranov 

Reconnecting the wallet worked - so I can now write the contract as expected. Thank you.

I still have the issue on the read contract where it doesn't give the names of the fields - just the uint256 status as per my previous screenshot. It would read out 

totalTokenSupply: number
totalFrozen: number
balanceOf: number
etc. etc.

instead it shows as per the screenshot

uint256: number
uint256: number
uint256: number
etc. etc.

I'm very sure it used to show the names of the fields previously rather than the result type.

**Comment by vbaranov** [comment]
> I still have the issue on the read contract where it doesn't give the names of the fields - just the uint256 status as per my previous screenshot. It would read out

@Dan-UVC I didn't find a piece of code in the history whether the names of contracts' methods' output parameters were displayed previously. Anyways, I implemented this in https://github.com/poanetwork/blockscout/pull/3603. It has been merged to master and hopefully will be added to ETC instance with the next release.
