### ISSUE TITLE
Ethereum Classic: <Can't send my etc from my nano>

### ISSUE THREAD

**Issue by 2rko** [poanetwork/blockscout#3539]
*Can't send my etc from my nano.*
Hi,
I would like to send my etc from my nano but the transaction is not displayed in the blockchain. I have been waiting for the confirmations for 1 week and still nothing. I tried again but it's always the same thing
transaction ID : 0x71bc473669f65ef57c64aa1be37f21c178faa8658402e8a8f2f6dc78b2e0e27e
 When i look in blockchain , this message appear : Sorry, We are unable to locate this transaction Hash

### Environment
* Elixir Version: 1.10.3
* Erlang Version: 22
* BlockScout Version: v3.3.1-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
