### ISSUE TITLE
Ethereum Classic: <the requested path was not found on blockscout>

### ISSUE THREAD

**Issue by tomars1017** [poanetwork/blockscout#3543]
I tried to transfer 490.990 etc from gate.io to coinbase on 12/20/2020
it's been 8-9days to complete 91,000 confirmations  but today the blockscout page for the etc is not found.
what should i do? can you advise?

page link below

https://blockscout.com/etc/mainnet/tx/0x7f20efe142e592af2bd43555afb7291c8ee42a6a38af5a52dd95a68371c14e0e/internal_transactions

### Environment
* Elixir Version: 1.11.0
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
