### ISSUE TITLE
Allow setting _PERIOD env vars at runtime

### ISSUE THREAD

**Issue by Legogris** [poanetwork/blockscout#3544]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): `Erlang/OTP 22 [erts-10.7.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1], Elixir 1.10.3 (compiled with Erlang/OTP 22)`
* Operating System: Linux
* Blockscout Version/branch: 3.5.0-beta

When trying to set any of the `*_PERIOD` environment variables, startup fails with e.g.:

```
    compile time:
    ** (ErlangError) Erlang error: "aborting boot"
        (elixir 1.11.0) Config.Provider.boot/2
    ERROR! the application :explorer has a different value set for key Explorer.Chain.Cache.TokenExchangeRate during runtime compared to compile time. Since this application environment entry was marked as compile time, this difference can lead to different behaviour than expected:
      * Compile time value was set to: [enabled: true, enable_consolidation: true, period: 3600000]
      * Runtime value was set to: [enabled: true, enable_consolidation: true, period: 31536000000]
    To fix this error, you might:
      * Make the runtime value match the compile time one
      * Recompile your project. If the misconfigured application is a dependency, you may need to run "mix deps.compile explorer --force"
      * Alternatively, you can disable this check. If you are using releases, you can set :validate_compile_env to false in your release configuration. If you are using Mix to start your system, you can pass the --no-validate-compile-env flag
```
Either `mix phx.server --no-validate-compile-env` and `mix --no-validate-compile-env phx.server` are not recognized.

Is there any reason to require recompilation for changing these vars or can this restriction be lifted?

Tried the following:
```
    ADDRESS_TOKENS_USD_SUM_CACHE_PERIOD = "31536000" // seconds: 1y (def 1h)
    ADDRESS_TRANSACTIONS_COUNTER_CACHE_PERIOD = "31536000" // seconds: 1y (def 1h)
    ADDRESS_TRANSACTIONS_GAS_USAGE_COUNTER_CACHE_PERIOD = "31536000" // seconds: 1y (def 1h)
    MARKET_HISTORY_CACHE_PERIOD = "31536000" // seconds: 1y (def 1h)
    TOKEN_EXCHANGE_RATE_CACHE_PERIOD = "31536000" // seconds: 1y (def 1h)
    TOKEN_TRANSFERS_COUNTER_CACHE_PERIOD = "31536000" // seconds: 1y (def 1h)
    TOKEN_HOLDERS_COUNTER_CACHE_PERIOD = "31536000" // seconds: 1y (def 1h)
```

**Comment by Legogris** [comment]
Is this a bug? Looking at https://docs.blockscout.com/for-developers/information-and-settings/env-variables, they are not marked as compile-time.

**Comment by vbaranov** [comment]
@Legogris Thanks for bringing this question. I didn't find a rationale for why those variables should be compilation - dependent. I softened restriction for them in this PR https://github.com/poanetwork/blockscout/pull/3569. So, it should be possible to set them without re-compilation of the application. If you could try that PR, I would appreciate your feedback about it.
