### ISSUE TITLE
Ethereum Classic: <Sent Ethereum Classic to Ethereum ledger wallet>

### ISSUE THREAD

**Issue by serenity-glitch** [poanetwork/blockscout#3550]
*Sent Ethereum Classic to Ethereum ledger wallet. Coinbase shows transaction completed with the required amount of confirmations, but coins have not arrived in Ethereum ledger wallet. Are they lost forever?*

### Environment
* Elixir Version: 1.11.0
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.

**Comment by serenity-glitch** [comment]
I do not have permission to submit a question to the ETC team. Yes, I am a
Discord member, but too new to submit question.

here is some more information on the situation:

Sent Ethereum Classic from Coinbase to my Ethereum address on my ledger.
Never showed up- i sent it to the wrong address. im a noob

When looking on Coinbase, says transaction is successful, so they wont help
me. Ledger support directs me back to Coinbase. On blockscout. shows the
transaction successful and gives addresses to and from and thst it was
successful. When I try to locate on Etherscan, cannot locate using either
address.
When I go back to the transaction on Coinbase and try to click on details,
now it gives me 404 error. Weird since I was able to screenshot the info
before showing successful transaction.
Help! Where do I find the transaction and relocate to the correct Ledger
Ethereum Classic address?
