### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by ilans-maker** [poanetwork/blockscout#3560]
Hello,

Could you please help me because I sent my ETC and they never arrived on my wallet. 

Could you please do something its been more than 3 weeks that i am waiting now.

0x8691c3f71c1d9b1dbac9f390d2e794302ec18a5f965722bffce19a3df36c2e94
Looking forward to hear from you 

Best regards,

### Environment
* Elixir Version: 1.11.0
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 10; SM-G780F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U

**Comment by ilans-maker** [comment]
First thing is Hello,

Second thing is thank you for not closing my request when you DID NOT solve
my problem..
Is this how you are treating your customer ?
Just giving me a discord where the verification level is anyway too high ?
So I cannot log in ?

Le lun. 11 janv. 2021 à 09:34, Victor Baranov <notifications@github.com> a
écrit :
