### ISSUE TITLE
add option to return more token holders per page

### ISSUE THREAD

**Issue by sirpy** [poanetwork/blockscout#3566]
currently page_size param might be used in the query to fetch token holders but the split_list_to_page is defaulting to 50
so always only 50 will be returned

btw is there another api/graphql way to fetch token holders?

https://github.com/poanetwork/blockscout/blob/52563b5a1c68a6299d27ba4f5d842d7aa3ddfc57/apps/block_scout_web/lib/block_scout_web/controllers/tokens/holder_controller.ex#L22

**Comment by vbaranov** [comment]
@sirpy making items per page configurable is not implemented yet https://github.com/poanetwork/blockscout/issues/3444. Thank you for the suggestion to make it through API endpoint.
