### ISSUE TITLE
Ethereum Classic : I did not recieved my ETC coins

### ISSUE THREAD

**Issue by navcr7** [poanetwork/blockscout#3568]
hello , I did not receive my ETC coins its showing pending from 2 days  please help

**Comment by vbaranov** [comment]
Hello, Blockscout explorer team cannot help with that.

**Comment by navcr7** [comment]
0x673ba59aceef492ff950fc314f9e06f5d5834a87dff9fbdfec8f2b3a1494d65a this is the transaction please help
