### ISSUE TITLE
xDai stake

### ISSUE THREAD

**Issue by Andrew-1983** [poanetwork/blockscout#3570]
Its not allowing me to attach a picture. just a link for it
![xdai pic get hub](https://user-images.githubusercontent.com/77361724/104666234-3cc4bf00-5688-11eb-81c2-6d60fbcc5325.PNG)

*Describe your issue here.*
I had bought some xdai stake thru honeyswap that the omni bridge is not allowing me to swap back out. It will show the 57 Stake that I own on the omni bridge but It will not allow me to change from main net over  to xdai or vice verca i think. I am just trying to figure out the best way to use my stake to collect my staking rewards. It seems that the system changed in the last couple months since i Used the omnibridge  and am just looking for the best way to collect my emissions on the stake that i won.. could you please walk m thru it I have gone thru the whole website but still cant figure it out. I thought you had to convert back out to Ethereum to stake. on the easy staking xdai chain deposits. if there is any other way of  doing it please let me know ok. Thank you so much it has me pretty stressed out. please contact me at acontre916@gmail.com thank you so very much

**Comment by vbaranov** [comment]
Hello, this repository is for issues/questions regarding Blocksout explorer. Please, ask your question in the forum https://forum.poa.network/c/support/xdai-support/34.
