### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by irenekonto** [poanetwork/blockscout#3579]
On January 12, 2021, I made a transfer from my husband's account from another digital currency exchange). Although I received a message from Coinbase "You just received 388.63339 ETC (€ 3,144.04 EUR) from an external Ethereum Classic account. It may take up to 3527 network confirmations before your Ethereum Classic is available to trade ",an incredible storm of emails/messages started between us...the transaction was done, it was not done, it is valid, it is not, it is the correct hash, it is not.
Yesterday they finally sent me a message that said: Hello ----
Thank you for the response.
The transactions are correct and it is complete, however it will not be credited to your account until it reaches 91,000 block confirmations.
You can find a list of the digital currencies we support and the minimum network confirmations needed for a transaction to complete here:
https://support.coinbase.com/customer/en/portal/articles/593836

We cannot expedited this transaction for unfortunately, please continue to monitor the status on the block explorer.Conclusions: although in the first message they said "It may take up to 3527 network confirmations ...", now they say "it will not be credited to your account until it reaches 91,000 block confirmations".
So, either Coinbase does not know what is happening to it, or ETC is one of the worst cryptocurrencies,one can invest.The bottom line is, that, right now, i can't move my coins and i am loosing money*.
Money that i need to pay my liabilities and also the € 3,144.04 now worth much less.*The investment I wanted to make with this money would have brought me an extra € 1000. (I will not mention the cryptocurrency, but Coinbase knows from my email what it was).
Today i see this (/blockscout.com/etc/):
 Transaction Details
0x0530f3e173728b29ddccce0d5990e2476ac1b8017847a4defe9c77c29bbe0fd8
0xb68884048CDd9f3d67A94c9586068c024d8679CA → 0x237a8f34a346B75c03eC830f198683E45936c5eb
Transaction Success 7 days ago (January-12-2021 02:17:02 PM +2 UTC)

Block Number
    11976509 

Block Confirmations
    43,129 

Nonce
    87230 

TX Fee
    0.00033075 ETC ($0.002768 USD) 

Transaction Speed
    <= 13.0 seconds 
and:
ETC Value
388.63339 ETC

$3,252.86 USD
Although the price at coinbase is €7.81(+4.88%)=€3.035=$3.672

Would you like to give me an explanation? 

### Environment
* Elixir Version: 1.11.0
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
ETC support is on Discord https://discord.com/invite/hQs894U
