### ISSUE TITLE
Mainnet: Tokens stock

### ISSUE THREAD

**Issue by Stefan-Crypto** [poanetwork/blockscout#3588]
Hi MATIC.

I made a transfer 23. Dec - of 2999 MATIC tokens from from METAmask to my Binance MATIC account.
https://explorer-mainnet.maticvigil.com/tx/0xfa66202c05f1affc409180b9aee18def71cb98767ba08891e80b8c5051fdc0e3/token-transfers

The problem is that when i was trying to stake my MATIC tokens, I did transfer the 2999 tokens from mainnet to Matic network within the metamask and then sent to Binance, they do not support that.
Binance the can help get them back but that will cost me 0.001 BTC (more the the tokens value)
I have also tried metamask support, but they say contact Binance - Binance say contact you or pay.

Please help me, this is 10% of my portfolio - so i am sad 🙁

https://explorer-mainnet.maticvigil.com/tx/0xfa66202c05f1affc409180b9aee18def71cb98767ba08891e80b8c5051fdc0e3/token-transfers

Metamask id: 0x38F14e4688E07792F47C1189f6034eBE408c1762

Sorry if this is the totally wrong place - but i cant find other contact place

Best regards
Stefan Marquardsen
Denmark
Stefan.tm@outlook.dk

**Comment by vbaranov** [comment]
Hi, there is no Matic support in the parent repository. Their application lives in the fork https://github.com/maticnetwork/blockscout.

**Comment by Stefan-Crypto** [comment]
So sorry, thanks

Hent Outlook til Android<https://aka.ms/ghei36>

________________________________
