### ISSUE TITLE
Ethereum Classic: Transaction ID Page Not Found

### ISSUE THREAD

**Issue by gampeart** [poanetwork/blockscout#3591]
On January 15, 2021 at 3:47pm eastern time, I initiated a transaction to send a number of Ethereum Classic from Ledger Live application o to a public key address on an exchange.  The status of the transaction is shown as "not confirmed".  

When I attempt to view the transaction at 
https://blockscout.com/etc/mainnet/tx/0x99ab128af0d40666c761eaac93e675e16b7073a7b8b4c6ca99f0f213e836bcd6/internal_transactions I am getting error, "Page not found. The requested path was not found on BlockScout" 

I am requesting to have this issue fixed on BlockScout so my transaction can complete and confirmed. 

Thank you,
Georgia

**Comment by vbaranov** [comment]
A transaction with mentioned above hash doesn't exist in the main chain. This is why Blockscout can't find a page for it. I also cannot find a transaction with that hash on alternative ETC explorers. Nothing can be done from Blockscout side in that case.
