### ISSUE TITLE
Mainnet: <Issue Title> Tokens stuck when tried to whidrawn from Matic to Ethereum networks

### ISSUE THREAD

**Issue by mdm3z** [poanetwork/blockscout#3596]
I wanted to withdrawn ETH from Matic to Ethereum networks. More than 1hr waiting and the only transaction I see is 

https://explorer-mainnet.maticvigil.com/tx/0xa718c7c3494306e24d355b5077be811814673fe1c1b157cf4d0d8fb9364c7307/token-transfers

my wallet address is 

0x1d0C1B3AEC6a5A8D5850f45D39a699F6CD47Ee36

Now I cannot see my funds!
Not on Matic and not on Ethereum networks.
I did try to finish required steps at 
https://wallet-v2.matic.network/
but it is still stuck on closing the checkpoint which is already more than 5 hrs!

Can You please do something about it?
Thanks in advance
![Screenshot_2021-02-01-09-19-36-457_io metamask](https://user-images.githubusercontent.com/78347161/106435904-be339400-6473-11eb-926b-50c675ec62da.jpg)

*Describe your issue here.*

### Environment
* Elixir Version: 1.11.0
* Erlang Version: 23
* BlockScout Version: v3.5.1-beta

* User Agent: `Mozilla/5.0 (Linux; Android 9; Redmi Note 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.93 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Matic support here. Try ask your question in https://github.com/maticnetwork/blockscout.
