### ISSUE TITLE
404 page for not found Block.

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#36]
If the user navigates to the Block details page for a block that we have not indexed or is in the future we should show the block details page with the message that this block has not been processed yet. 

### Example:

Both links below show the block details page for a block that is the future, as seen on Etherscan and BlockScout:

Etherscan:
https://etherscan.io/block/125127248

BlockScout:
https://www.blockscout.com/eth/mainnet/blocks/125127248/transactions

### Acceptance Criteria
The block details page for a block that we have not indexed yet or that is in the future should show no block related information, but just a message based on the following criteria:

- If the block number is below the tip of the chain, the message should be: 
    - "This block has not been processed yet".
- If the block number is above the tip of the chain, the message should be:
    - "Easy Cowboy! This block doesn't exist yet!"

The image below is an example of how that page should be for the first case:

![](https://i.imgur.com/HBPVVw4.png)

**Comment by gfreh** [comment]
@acravenho I've updated the description and added a suggestion for the block details page in the scenario described by this issue. WDYT?

**Comment by acravenho** [comment]
@gfreh I think that looks good. I'm not sure I understand the question. As far as differentiating the design, yes, we should have the design different so the user knows this block doesn't really exist yet.

**Comment by gfreh** [comment]
@acravenho By differentiating, I mean having a different message when the block is in the past, but we haven't indexed it yet vs. when the block is the future. Not sure if that makes sense, though 😅

**Comment by acravenho** [comment]
:thinking: Yes, you're right. That would make sense. It's pretty easy and inexpensive to run the query for the   tip of the chain. If below the tip we should provide the exact message that you have above.

**Comment by w-sanches** [comment]
I'll work on this one

**Comment by w-sanches** [comment]
@acravenho If i'm trying to access a not-indexed block by its hash, should I show that the block is not processed yet or that it does not exist?
I don't know if I can check if that hash is in the past or the future.

Example: https://blockscout.com/poa/core/blocks/0xf511fffa6403456a120edda6e1984a21e99ef2ca580f02f5367abc59bf16cddc/transactions
