### ISSUE TITLE
xDai: Missing STAKE!

### ISSUE THREAD

**Issue by sonnykaye** [poanetwork/blockscout#3604]
I transferred 113 STAKE from xdai to EthMainnet and they went to EternalStorageProxy.
Block #14379841
Tx Hash 0x9d27419134a72fcd5c03a04d49be457d94ae858648abdd5131e3596a6a049397

 What is this and why did they go there? How can i get them back with utmost urgency and why does this happen?
 
Thank you,
BC

### Environment
* Elixir Version: 1.10.4
* Erlang Version: 23
* BlockScout Version: v3.5.1-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36`

### Steps to reproduce

Not sure how to push up a branch to my fork.
Used OmniBridge and it sent them from
0x1c20551Bb64441BbD423A04Fc52C326FA9b37aF3
to EternalStorageProxy

### Expected Behaviour

Should have gone to my Eth Mainnet account
0x1c20551Bb64441BbD423A04Fc52C326FA9b37aF3

### Actual Behaviour

Went to EternalStorageProxy
Block #14379841

**Comment by igorbarinov** [comment]
You should press Execute here https://alm-xdai.herokuapp.com/100/0x9d27419134a72fcd5c03a04d49be457d94ae858648abdd5131e3596a6a049397
and pay fees for transfer. The actual transfer fee can be lower than the estimate.
