### ISSUE TITLE
xDai: <Issue Title>

### ISSUE THREAD

**Issue by ar2rg2019** [poanetwork/blockscout#3606]
Hi,
How do I cancel my transaction? 0x9a496818f8f78284a0a487f8a341bee0b5c5fceebe214785dd99b8f1a7ef5fe0
On UniSwap, Metamask it is VERY EASY and I can't find it on yours !!!
Second question?
I have info: "Wrong network
Please, connect your wallet to Mainnet. ''
How to change Mainnet, I'm connected via Metamask so I don't understand what's going on?
I don't like honeyswap.org :(
Best regards, Arthur

**Comment by vbaranov** [comment]
This is the issue tracker in regards Blockscout explorer. Try asking your question on the Forum https://forum.poa.network/c/support/xdai-support/34
