### ISSUE TITLE
Ethereum Classic: <Still in Pending Mode>

### ISSUE THREAD

**Issue by danieleweinberger** [poanetwork/blockscout#3608]
*I sent the coin from Ledger Wallet to Coinbase. Still pending after 17 hours. Please help. Thank you.*

### Environment
* Elixir Version: 1.11.0
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Sent from Ledger Wallet to Coinbase. 

*Has been in pending status for 17 hours.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
Regarding your question try to reach out ETC team, for instance, on their Discord https://discord.com/invite/hQs894U.
