### ISSUE TITLE
How does internationalization switch automatically?

### ISSUE THREAD

**Issue by mhxw** [poanetwork/blockscout#3609]
*Describe your issue here.*

How does internationalization switch automatically?

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System:
* Blockscout Version/branch: 3.5.1beta

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by mhxw** [comment]
I set it up this way, but it doesn't seem to achieve the effect of automatic switching.
- blockscout\apps\config\config.exs
```
config :block_scout_web, BlockScoutWeb.Gettext, locales: ~w(en zh), default_locale: "en"

config :ex_cldr,
   default_locale: "en",
   default_backend: BlockScoutWeb.Cldr
```
- blockscout\apps\block_scout_web\lib\block_scout_web\cldr.ex
```
  use Cldr,
      default_locale: "en",
      locales: ["en", "zh"],
      gettext: BlockScoutWeb.Gettext,
      generate_docs: false,
      precompile_number_formats: ["#,###", "#,##0.##################", "#.#%", "#,##0"],
      providers: [Cldr.Number, Cldr.Unit]
```
- blockscout\apps\block_scout_web\lib\block_scout_web\router.ex
```
  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug :put_secure_browser_headers
    plug Cldr.Plug.SetLocale,
         apps:    [cldr: BlockScoutWeb.Cldr, gettext: :global],
         from:    [:query, :path, :body, :cookie, :accept_language],
         param:   "locale",
         session_key: "cldr_locale"
    plug(BlockScoutWeb.CSPHeader)
  end
```
- add zh file
```
# Add zh directory and 2 files
# blockscout\apps\block_scout_web\priv\gettext\zh\LC_MESSAGES
```

**Comment by mhxw** [comment]
I solved this problem using the following approach.
- \blockscout\apps\block_scout_web\lib\block_scout_web\web_router.ex
Add this paragraph to this file
```
  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug :put_secure_browser_headers
    plug Cldr.Plug.SetLocale,
         apps:    [cldr: BlockScoutWeb.Cldr, gettext: :global],
         from:    [:query, :path, :body, :cookie, :accept_language],
         param:   "locale",
         session_key: "cldr_locale"
    plug(BlockScoutWeb.CSPHeader)
    plug(BlockScoutWeb.ChecksumAddress)
  end
```

**Comment by vbaranov** [comment]
Awesome @mhxw! Thanks for providing helpful details of the solution. We have never configured different locales for Blockscout. It sounds like other users should use the way you proposed in order to configure internationalization switching.
