### ISSUE TITLE
ATH: Explorer Days Behind

### ISSUE THREAD

**Issue by tristandemonspawn** [poanetwork/blockscout#3613]
Ath Explorer is days behind and transactions are not going through.

### Environment
* Elixir Version: 1.9.2
* Erlang Version: 22
* BlockScout Version: V1.0.0 - Atheios

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3835.0 Safari/537.36`

### Steps to reproduce

Look at the latest block times
### Expected Behaviour

Current blocks being processed

### Actual Behaviour

Not finding transactions that happened over the weekend.

**Comment by vbaranov** [comment]
We do not host Ath explorer. I am not familiar with the team who is the owner of that explorer. Probably you should ask atheios team. Which link do you mean btw?
