### ISSUE TITLE
Energy Web Chain: Transfer EWT to Ledger Live Nano X, balance issue

### ISSUE THREAD

**Issue by Tucker13** [poanetwork/blockscout#3619]
I transferred from KuCoin to Ledger Live and balance does not show. When I look up my address 0x024b2D1c34372CEc7B99925a8a48Df94f032f42e (Sent to address) it shows 0.09EWT however the transaction history 
https://explorer.energyweb.org/address/0x024b2D1c34372CEc7B99925a8a48Df94f032f42e/transactions
TXN Hash: 0x0f673e1f6fdff114cd84f6081c1ac0973fca8a0a56196f85250a6ca4634eff4d
Block #: 10156038

Shows that the transaction of 223.35.. EWT IN was successful. How do I populate or add EWT to my Ledger Live account, or how can I send it to another wallet so that I can keep track of it.

Thank you.

**Comment by Tucker13** [comment]
Sorry, I left out some details. The balance of 0.09EWT shows up on the EnergyWeb Wallet, the explorer information above is correct. I cannot access the tokens in Ledger Live or Energy Web Wallet.

**Comment by vbaranov** [comment]
I suppose you already moved them since balance decreased.

<img width="441" alt="Screenshot 2021-02-10 at 11 45 48" src="https://user-images.githubusercontent.com/4341812/107485959-86280180-6b95-11eb-8ad7-03b300f4ec2b.png">

**Comment by Tucker13** [comment]
Yes, some how refreshing the explorer updated the account (?), so I moved them to my metamask account, figuring it would be easier to keep track of. Hmm, now I cannot find the token contract address to add it, anyone happen to know it?

Thanks.

**Comment by Tucker13** [comment]
I found out how to incorporate MetaMask and Energy Web Wallet from this web address:

https://hsvgts.medium.com/energy-web-wallet-options-to-store-those-precious-ewt-db39adac56d4#:~:text=Connect%20to%20EnergyWeb%E2%80%99s%20remote%20RPC%20by%20adding%20a,Web%20Chain:%20%E2%80%9C246%E2%80%9D,%20as%20a%20Symbol%20put%20%E2%80%9CEWT%E2%80%9D.

1, Connecting Via Remote RPC & MetaMask
Note- Once You Have Followed The Steps Below For MetaMask The Actual Address Within MetaMask Will Be The Same Whether You Are On The ETH Network Or The EW Network, You Can Just Toggle Back And Forwards Between The Two Networks As You Like But The Address Does Not Change.
With this option you can either use an existing MetaMask account or create a new one and ensure you keep your seed words safe and remember your password.
If you do not have MetaMask installed its just a matter of installing the browser extension from the Chrome Web Store.
MetaMask
An Ethereum Wallet in your Browser
chrome.google.com
Connect to EnergyWeb’s remote RPC by adding a custom node to MetaMask. Go to Networks and click on “Custom RPC.
Image for post
Now go to Network and click on Add Network.
Now you can add EnergyWeb RPC or something similar as the name, https://rpc.energyweb.org/ as the RPC URL, enter the chainID of the Energy Web Chain: “246”, as a Symbol put “EWT”. Also add the URL of the Energy Web Chain blockexplorer: https://explorer.energyweb.org/. Now click on save to connect.
Your MetaMask should be connected to the Energy Web Chain now.
You can now send and receive EWT as you like from your MetaMask account.
![image](https://user-images.githubusercontent.com/49060075/107570147-96c29100-6c02-11eb-83ab-fbb2f9888bf5.png)
