### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by karastanov** [poanetwork/blockscout#3628]
*Describe your issue here.*

### Environment
* Elixir Version: 1.11.0
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1`

Hello. 
This money never hit my account still pending... pls help. 
0x8a604a19d5b3ba2e0b156420930ce92d6c95738593ddd8bf4570133969128060

**Comment by karastanov** [comment]
But it never went from pending status to complete on my end and my wallet never got credited for this transfer. Pls release it to my wallet. Thanks

**Comment by vbaranov** [comment]
This is the wrong place to ask. Here is the Blockscout explorer support. Ask your questions in ETC groups like this https://discord.com/invite/hQs894U.
