### ISSUE TITLE
Still pending in my receiving wallet 

### ISSUE THREAD

**Issue by karastanov** [poanetwork/blockscout#3629]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System:
* Blockscout Version/branch: 

Hello, 
Had transfer But it never went from pending status to complete on my end and my wallet never got credited for this transfer. Pls release it to my wallet. Thanks
U can see yourself that money never hit my wallet... my wallet info: 0x04E0265001C78dbd429F873ea615d722c9b42EEe

**Comment by vbaranov** [comment]
Please do not open
1. multiple identical issues
2. are not related to the Blockscout itself
or you will be banned.
