### ISSUE TITLE
Blockscout doesn't process my token metadata

### ISSUE THREAD

**Issue by Agilulfo1820** [poanetwork/blockscout#3633]
### Steps to reproduce

I created an ERC-721 Smart contract. Each token has a tokenUri which return the needed information of the token (name, image, etc.).
This is my smart contract: https://blockscout.com/poa/xdai/address/0x3c4c2B071b55f23f0A90169e4ABC3cFA2164F6D2/tokens/0x3E5d55162db958E6C00c59a6e81587C153E18f7b/token-transfers

This is the metadata response from the tokenUri (in staging version works only for token id 0, 1 and 2):
https://stageapi.genuino.world/nfturi/1

I used all the metadata needed from ERC-721 Metadata standards but I still cannot see the image of my token on Blockscout. E.g: https://blockscout.com/poa/xdai/tokens/0x3e5d55162db958e6c00c59a6e81587c153e18f7b/instance/1/token-transfers

### Expected behaviour

Token image is displayed instead of the controller placeholder.

### Actual behaviour

The controller placeholder is displayed instead of the image returned in the tokenUri.

Can please someone tell me what should I return inside the tokenUri endpoint in order to show the token image and name?

**Comment by Agilulfo1820** [comment]
I'm noticing that today (after 12h after posting this) I can see the metadata tab and image displayed. I did nothing from my part.

The only thing I'm thinking is that I first created the tokens and only after I updated the base token uri for the tokens, so maybe Blockscout just cached the previous response.

**Comment by vbaranov** [comment]
@Agilulfo1820 If Blockscout didn't get metadata for the first time, it will re-try the metadata retrieving again next time. But the time when it will happen again depends on how much tokens in the metadata retriever queue. Anyways, glad to hear that finally, images appear.

**Comment by ESNJS** [comment]
> tab and image displaye

Can you share the code to add the metadata to the contract?

**Comment by ESNJS** [comment]
@vbaranov I have an NFT that the tokenURI function returns directly the image URL, how can I modify the MetadataController so it does not try to parse JSON and just use directly the image URL.

**Comment by SalmanNoborderz** [comment]
Is there a way to manually force metadata refresh on blockscout?

I updated baseURI after minting tokens on a collection and have decreased the TOKEN_METADATA_UPDATE_INTERVAL to 30m but still it isn't updating the metadata

The contract is a upgradeable proxy with ERC721 implementation, the URI is updated in proxy storage
