### ISSUE TITLE
Energy Web Chain: Restore EWT from EWTB

### ISSUE THREAD

**Issue by Chiqui1234** [poanetwork/blockscout#3639]
Yeah, I'm a noob. I sended EWT which I bought in Hotbit to my EWTB (Energy Web Token Bridge) wallet in Trust Wallet. I'm desperate because it's my first try on crypto :(

[Here](https://explorer.energyweb.org/address/0x5Fc36617D36e804De039e1cb2fcb3308b8b91deB/transactions) you can clearly see the transaction to the wallet provided by Trust Wallet (EWTB). How to take posesion of my wallet? I tried [this](https://community.trustwallet.com/t/how-to-recover-funds-sent-to-a-wrong-public-address/145) and I selected ETH and EWT in the dropdown menu, but no luck (the private key only restores my ETH wallet, not EWTB lol).

Thanks for reading :D I think if the transaction was succeded like the EWT Explorer says, I can recover my crypto somehow

**Comment by vbaranov** [comment]
There is no support of EWT in the main Blockscout repository. Try to ask in their fork https://github.com/energywebfoundation/blockscout.
