### ISSUE TITLE
Ethereum Classic: <delay in receiving with successfully confirmed status at sender>

### ISSUE THREAD

**Issue by FAILZ2** [poanetwork/blockscout#3640]
![Screenshot_20210216-224016](https://user-images.githubusercontent.com/79174126/108166296-d8db4f00-70a8-11eb-9c55-8e0090ba8ee1.png)
*Describe your issue here.*
The status of the transaction is complete for sending address but remains pending in the receiving address
### Environment
* Elixir Version: 1.11.0
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (Linux; Android 6.0.1; 5056N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*
I shouldve received about 45 bucks 
### Actual Behaviour

*Tell us what happens instead.*
Delay in the transaction even tho the send address claims the transaction has been successfully confirmed
![Screenshot_20210216-224902](https://user-images.githubusercontent.com/79174126/108166593-40919a00-70a9-11eb-9e54-995de0e1890f.png)

**Comment by vbaranov** [comment]
You should ask wallet developers why the transaction is still pending.

**Comment by FAILZ2** [comment]
Thanks but i had figured out that it needed more confirmations then other
currencies
