### ISSUE TITLE
Ethereum Classic: <Issue Title>

### ISSUE THREAD

**Issue by nazdel90** [poanetwork/blockscout#3643]
*Describe your issue here.*

Transfer has not completed my ETC and it’s been pending for almost 24 hours. 

### Environment
* Elixir Version: 1.11.0
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

I should have my money by now 

### Actual Behaviour

*Tell us what happens instead.*

still pending

**Comment by vbaranov** [comment]
ETC chat is here https://discord.com/invite/hQs894U
