### ISSUE TITLE
Mainnet: <Issue Title> Lost matic tokens in transaction. Receiving wallet did not receive the 984 matic tokens sent

### ISSUE THREAD

**Issue by RobertChristianShaw** [poanetwork/blockscout#3658]
*Describe your issue here.* Receiving wallet did not receive the 984 matic tokens sent. If possible, return matic to sending address.
0x1b1aa4bb2dd5d700d605ff0654f02859a9ae47a1a73cc463f720ce2d3b164eae

### Environment
* Elixir Version: 1.11.0
* Erlang Version: 23
* BlockScout Version: v3.5.1-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Matic support in the main Blockscout repo.
