### ISSUE TITLE
xDai: <Transferred xDAI to ETH Address>

### ISSUE THREAD

**Issue by dinkarmane** [poanetwork/blockscout#3660]
*I transferred xDAI balance using xDAI chain from my MetaMask wallet. However, while doing the transfer the xDAI balance on xDAI Network was showing as ETH balance - this I believe was due to caching issue. I overlooked this issue and thought this transfer will seamlessly convert the xDAI balance and deposit to my Binance ETH address. This however, did not happen and my xDAI balance was taken out from my MetaMask wallet and is showing against my Binance ETH address which I cannot access.
See the address details here : *

### Environment
* Elixir Version: 1.10.4
* Erlang Version: 23
* BlockScout Version: v3.5.1-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36`

### Steps to reproduce

*Create MetaMask account and transfer some ETH. Link Uniswap to convert ETH to DAI and than DAI to xDAI by adding xDAI chain as Network to MetaMask. Switch between ETH Mainnet and xDAI network you will see xDAI balance as ETH balance. Either this caching error should be resolved to avoid confusion OR the transfer from xDAI address to ETH address should be reversed - I understand the transfer fee is lost but it doesn't make sense that the whole deposit is lost*

### Expected Behaviour

*Either this caching error should be resolved to avoid confusion OR the transfer from xDAI address to ETH address should be reversed - I understand the transfer fee is lost but it doesn't make sense that the whole deposit is lost.*

### Actual Behaviour

*xDAI balance was shown as ETH balance and while transfer in the background xDAI was transferred to my ETH address
[transactions_csv.xlsx](https://github.com/poanetwork/blockscout/files/6043093/transactions_csv.xlsx)
[Block 14666882 - xDai Explorer.pdf](https://github.com/poanetwork/blockscout/files/6043096/Block.14666882.-.xDai.Explorer.pdf)

*

**Comment by vbaranov** [comment]
Please ask your question at xDai official community channels https://www.xdaichain.com/media/social-media since it is not related to Blockscout explorer itself.
