### ISSUE TITLE
xDai: <Issue Title>

### ISSUE THREAD

**Issue by ChiDinh97** [poanetwork/blockscout#3679]
*Describe your issue here.*

### Environment
* Elixir Version: 1.10.4
![z2358919654342_d118ec648eaba21eb8cdc1ea30386c55](https://user-images.githubusercontent.com/29404943/109760489-55ca0500-7c21-11eb-9c9c-440f1321c752.jpg)

* Erlang Version: 23
* BlockScout Version: v3.5.1-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by igorbarinov** [comment]
Thanks, that's the expected behavior of the faucet
