### ISSUE TITLE
im tranfering token back to eth but is rootmanager errror token not marred can you help please,,https://explorer-mainnet.maticvigil.com/tx/0x5f195a3ee505e03805a241cc5253b0fd813d5ba140195bc74b127f21b27f70c2/token-transfers

### ISSUE THREAD

**Issue by johnjapes** [poanetwork/blockscout#3681]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System:
* Blockscout Version/branch: 

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no support of Matic here
