### ISSUE TITLE
Unable to verify contracts: return error in verification if address doesn't exist instead infinite progress bar

### ISSUE THREAD

**Issue by KaamilW** [poanetwork/blockscout#3685]
From the GUI perspective contract verification process is slow and either fails (bytcode does not match etc) or hangs forever.
It is agnostic of the contract type, I have tried verifying different contracts and behavior is always similar. 
It doesnt matter whether it is the first time or next, further attempts.

**Whenever it hangs -> blockscout logs show this kind of error:**

```blockscout_1  | 2021-03-05T07:17:41.998 application=plug request_id=FmlhD9P-VuHQxcUAGvTH [info] POST /verify_smart_contract/contract_verifications
blockscout_1  | 2021-03-05T07:17:41.999 application=que [info] [Que] Queued new Job for Explorer.SmartContract.PublisherWorker
blockscout_1  | 2021-03-05T07:17:41.999 application=que [info] [Que] Starting Job # 5 with Explorer.SmartContract.PublisherWorker
blockscout_1  | 2021-03-05T07:17:42.000 application=plug request_id=FmlhD9P-VuHQxcUAGvTH [info] Sent 204 in 2ms
blockscout_1  | 2021-03-05T07:17:52.981 [error] Task #PID<0.22068.25> started from #PID<0.22588.9> terminating
blockscout_1  | ** (Ecto.ConstraintError) constraint error when attempting to insert struct:
blockscout_1  | 
blockscout_1  |     * smart_contracts_pkey (unique_constraint)
blockscout_1  | 
blockscout_1  | If you would like to stop this constraint violation from raising an
blockscout_1  | exception and instead add it as an error to your changeset, please
blockscout_1  | call `unique_constraint/3` on your changeset with the constraint
blockscout_1  | `:name` as an option.
blockscout_1  | 
blockscout_1  | The changeset defined the following constraints:
blockscout_1  | 
blockscout_1  |     * smart_contracts_address_hash_index (unique_constraint)
blockscout_1  | 
blockscout_1  |     (ecto 3.5.5) lib/ecto/repo/schema.ex:688: anonymous fn/4 in Ecto.Repo.Schema.constraints_to_errors/3
blockscout_1  |     (elixir 1.11.0) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
blockscout_1  |     (ecto 3.5.5) lib/ecto/repo/schema.ex:673: Ecto.Repo.Schema.constraints_to_errors/3
blockscout_1  |     (ecto 3.5.5) lib/ecto/repo/schema.ex:654: Ecto.Repo.Schema.apply/4
blockscout_1  |     (ecto 3.5.5) lib/ecto/repo/schema.ex:262: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
blockscout_1  |     (ecto 3.5.5) lib/ecto/multi.ex:646: Ecto.Multi.apply_operation/5
blockscout_1  |     (elixir 1.11.0) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
blockscout_1  |     (ecto 3.5.5) lib/ecto/multi.ex:630: anonymous fn/5 in Ecto.Multi.apply_operations/5
blockscout_1  | Function: #Function<3.79678554/0 in Que.Job.perform/1>
blockscout_1  |     Args: []
blockscout_1  | 2021-03-05T07:17:52.982 application=que [info] [Que] Failed Job # 5 with Explorer.SmartContract.PublisherWorker
```

Apart from that we also observe Database related errors :
`DBConnection.ConnectionError) connection not available and request was dropped from queue` and index.fetcher errors that appear from time to time. (however I am not sure whether this is relevant) - I can share those other errors if needed (or open another issue - what would be your recommendation?)

### Environment

* Blockscout image https://hub.docker.com/layers/energyweb/blockscout-explorer/v3.5.1-beta-volta/images/sha256-c4b162d1c5aa4adf51a19d6b5fb451091bdf086f1bc34026704f77453cde92b8?context=explore built from [Dockerfile](https://github.com/energywebfoundation/blockscout/blob/volta_canon/docker/Dockerfile) which is based on your [Dockerfile](https://github.com/poanetwork/blockscout/blob/master/docker/Dockerfile)
* Explorer: [volta-explorer ](https://volta-explorer.energyweb.org/)
* Parity 2.5.13
* Operating System: Ubuntu 18.04.4 LTS , c5.2xlarge
* Postgress version: 11.9, m5.xlarge

### Steps to reproduce

Try to Verify e.g. https://volta-explorer.energyweb.org/address/0x7D5fbC56f3Dd85CBCA489e805d3ae53a41138c29/contract_verifications/new

**Data**
Name: WrappedNative
Include nightly builds: No
Compiler: 0.5.17
EVM: Default
Optimization: No
Code:
```pragma solidity ^0.5.15;


// From: https://etherscan.io/address/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2#code
contract WrappedNative {
    string public name;
    string public symbol;
    uint8  public decimals = 18;

    event  Approval(address indexed src, address indexed guy, uint wad);
    event  Transfer(address indexed src, address indexed dst, uint wad);
    event  Deposit(address indexed dst, uint wad);
    event  Withdrawal(address indexed src, uint wad);

    mapping (address => uint) public  balanceOf;
    mapping (address => mapping (address => uint)) public allowance;

    constructor(string memory _name, string memory _symbol)
        public
    {
        name = _name;
        symbol = _symbol;
    }

    function()
        external
        payable
    {
        deposit();
    }

    function deposit()
        public
        payable
    {
        balanceOf[msg.sender] += msg.value;
        emit Deposit(msg.sender, msg.value);
    }

    function withdraw(uint wad)
        public
    {
        require(balanceOf[msg.sender] >= wad, "Insufficient funds");
        balanceOf[msg.sender] -= wad;
        msg.sender.transfer(wad);
        emit Withdrawal(msg.sender, wad);
    }

    function totalSupply()
        public
        view
        returns (uint)
    {
        return address(this).balance;
    }

    function approve(address guy, uint wad)
        public
        returns (bool)
    {
        allowance[msg.sender][guy] = wad;
        emit Approval(msg.sender, guy, wad);
        return true;
    }

    function transfer(address dst, uint wad)
        public
        returns (bool)
    {
        return transferFrom(msg.sender, dst, wad);
    }

    function transferFrom(address src, address dst, uint wad)
        public
        returns (bool)
    {
        require(balanceOf[src] >= wad, "Insufficient funds");

        if (src != msg.sender && allowance[src][msg.sender] != uint(-1)) {
            require(allowance[src][msg.sender] >= wad, "Insufficient funds");
            allowance[src][msg.sender] -= wad;
        }

        balanceOf[src] -= wad;
        balanceOf[dst] += wad;

        emit Transfer(src, dst, wad);

        return true;
    }
}
```

Try to fetch constructor arguments automatically: Yes

### Expected behaviour

Verification is quick & successful (if proper data is supplied). 

Would you kindly please take a look and advice what might be the issue? We already tried tweaking several different configuration options however without any success... we are kind of in a dark right now.

### Actual behaviour

Contract is not verified, "loading..." hangs forever.

**Comment by KaamilW** [comment]
Hey @vbaranov - could you please take a look? Any hint might be useful.

**Comment by GrzegorzMatuszakTSH** [comment]
Stuff related to the constraint error should be improved -> when validation fails then the UI should show information with an error instead of showing infinitive pending.

**Comment by vbaranov** [comment]
> Just an update - i have tried to run an query over the smart_contracts table to check whether the contract address that is to be verified is present there (as this suggests the error) however the does not have that particular entry.

yes, seems that is the reason of the verification issue: the transaction that created that address is not indexed for some reason.

> Stuff related to the constraint error should be improved -> when validation fails then the UI should show information with an error instead of showing infinitive pending.

good idea, PRs are welcome.

**Comment by KaamilW** [comment]
> > Just an update - i have tried to run an query over the smart_contracts table to check whether the contract address that is to be verified is present there (as this suggests the error) however the does not have that particular entry.
> 
> yes, seems that is the reason of the verification issue: the transaction that created that address is not indexed for some reason.
> 

Actually the transaction is indexed (in the transaction table). However the error suggests that hash of contract address is already present in smart_contract table while it actually isn't. @vbaranov  do you have any ideas what could we do to fix that?

Please lets not mix this issue with improvement suggested by @GrzegorzMatuszakTSH  as this is different topic. Here the goal is to be able to verify contracts - not enhance UI.

**Comment by vbaranov** [comment]
> However the error suggests that hash of contract address is already present in smart_contract table while it actually isn't.

Could you post your select query here?

**Comment by KaamilW** [comment]
First I checked whether an example, already verified smart contract is present in address_name and smart_contracts tables:

```SELECT encode(address_hash::bytea, 'hex') FROM public.address_names where address_hash like decode('db8b4264b1777e046267b4cc123f0c9e029ceb2c', 'hex')```

```SELECT encode(address_hash::bytea, 'hex') FROM public.smart_contracts where address_hash like decode('db8b4264b1777e046267b4cc123f0c9e029ceb2c', 'hex')```

Result is a single line with a contract address.

Then i checked the contract i wanted to verify:

```SELECT encode(address_hash::bytea, 'hex') FROM public.address_names where address_hash like decode('2580a5937BA4E7Fc9D93810487032375F32d5BCa', 'hex')```
```SELECT encode(address_hash::bytea, 'hex') FROM public.smart_contracts where address_hash like decode('2580a5937BA4E7Fc9D93810487032375F32d5BCa', 'hex')```

No results.

I have also checked whether the transaction is indexed for that contract:

```SELECT * from public.transactions where created_contract_address_hash like decode('2580a5937BA4E7Fc9D93810487032375F32d5BCa', 'hex')```

It finds an entry.

**Comment by KaamilW** [comment]
We have tried downgrading blockscout to 3.4.0 -> issue persists.
We reverted back to 3.5.1 and upgraded postgress to 12.5 -> issue persists.

@vbaranov

**Comment by vbaranov** [comment]
@KaamilW 

A hint: you can check whether an address hash exists in the table faster without using `like` operator like this:
```
SELECT EXISTS(SELECT 1 FROM smart_contracts WHERE address_hash='\x2580a5937BA4E7Fc9D93810487032375F32d5BCa');
```

Regarding your issue:

1. Try the updates from the master branch of the main repo. They are in a pre-release state.
2. Double-check, that you didn't change the smart contracts's publisher in your fork. It should match this code https://github.com/poanetwork/blockscout/blob/master/apps/explorer/lib/explorer/smart_contract/publisher.ex
3. What is the result of this query
```
SELECT * FROM addresses WHERE address_hash='\x2580a5937BA4E7Fc9D93810487032375F32d5BCa');
```?
4. Also, what is your `smart_contracts` table structure? Please post the result of `\d smart_contracts` from psql

**Comment by KaamilW** [comment]
Hey @vbaranov  - thanks for the hint for postgress!

As for the issue, I managed to solve it at the beginning of the week.

In general the issue was with postgress smart_contracts table indeed -> the sequence number was out of sync with the current highest id number in that table... and it makes sense actually as it seems that every verification want to add the entry to that table, and this sequence number (from my understanding) determines what should be the next entry id. And as sequence number was much lower than the actual highest id, it was throwing an error becouse it wanted to write to the table with an id that was already occupied. 

To solve it, i just increased the sequence id number to match the highest id in the table. 

The issue is also described e.g. here: https://stackoverflow.com/questions/244243/how-to-reset-postgres-primary-key-sequence-when-it-falls-out-of-sync

Now, we are able to verify new contracts, however it seems that we struggle with old contracts deployed via truffle, every time we try to verify, there is "bytecodes does not match" . [It seems to be truffle related .](https://github.com/trufflesuite/truffle-compile/issues/77). I am going to double check that whether it is indeed the case and if yes, open a separate issue for that. Just one question here, @vbaranov  have you encounter these kind of issues with truffle deployed contracts?

**Comment by vbaranov** [comment]
Glad to hear that you ultimately resolved the issue with the DB. Let me close the current issue. Regarding Truffle issue, no, I haven't been aware of this problem with old contracts. Thnx for the link.
