### ISSUE TITLE
Mainnet: Deposited 456 MATIC to Binance. They "didnt recive it" because it was not send by ERC-20.

### ISSUE THREAD

**Issue by M3OWWW** [poanetwork/blockscout#3699]
Hey, a while ago I was trying to trade my MATIC for something else by depositing on Binance. After some time i still didnt have any money on their site. After contacting support they told me that is my fault because i used "wallet on Metamask named Matic Mainnet with is not ERC-20," And money is gone and I can do nothing about it. My question is if i sent them by using my eth address to their eth address is it ERC-20? Is it my fault? I got this MATIC from MATIC giveaway, Can i get it back somehow? https://explorer-mainnet.maticvigil.com/tx/0xf78d7788c81771e4e2e8bf6ac4dd128786f006f716b702a331e9488bdc5da029/internal-transactions

### Environment
* Elixir Version: 1.11.0
* Erlang Version: 23
* BlockScout Version: v3.5.1-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

Tell me if im right. Help me solve it with Binance or try to get my Matic back. 

### Actual Behaviour

Right now, Nothing.

**Comment by vbaranov** [comment]
Matic support is not here. Try their fork.
