### ISSUE TITLE
Address 404 page

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#37]
We're currently showing a 404 page if the address is not in our DB. Instead, we should be showing the address page with a 0 balance. The address exists, we either did not update the balance yet or the address has not balance.

### Example 
The two links below point to the same address on ETH Mainnet (`0x6937cb25eb54bc013b9c13c47ab38eb63edd1493`) as seen on Etherscan and BlockScout.

**Etherscan:**
https://etherscan.io/address/0x6937cb25eb54bc013b9c13c47ab38eb63edd1493

**BlockScout:**
https://www.blockscout.com/eth/mainnet/address/0x6937cb25eb54bc013b9c13c47ab38eb63edd1493

### Acceptance Criteria
The address page for an address that is not in our DB should look like the following:
- Address' coin balance should be zero.
- Address' USD balance should be zero.
- Address' transactions count should be zero.
- The transactions tab should load with a gray area and a message: `There are no transactions for this address.`
- The tokens tab should load with a gray area and a message: `There are no tokens for this address.`
- The internal transactions tab should load with a gray area and a message: `There are no internal transactions for this address.`

**Comment by jimmay5469** [comment]
I'm updating this as I don't believe a 404 page is the right approach. I believe what we should actually show is a 0 balance Address with no transactions to/from it.

**Comment by acravenho** [comment]
@jimmay5469 That's correct. A user should see the full page with 0 balances.

**Comment by Lokraan** [comment]
I can handle this issue.

**Comment by Lokraan** [comment]
Have you guys already started working on it? @acravenho

**Comment by acravenho** [comment]
@Lokraan No, we haven't started working on this yet. That would be great!

**Comment by Lokraan** [comment]
@acravenho 

I have a solution that utilizes this function to get addresses:
```elixir
def find_or_insert_address_from_hash(%Hash{byte_count: unquote(Hash.Address.byte_count())} = hash) do
    case Chain.hash_to_address(hash) do
      {:ok, address} ->
        {:ok, address}

      {:error, :not_found} ->
        Chain.create_address(%{hash: to_string(hash)})

      :error ->
        :error
    end
  end
```

As a result of this `AddressView.contract?/1` throws an error because the created address has this: `smart_contract: #Ecto.Association.NotLoaded<association :smart_contract is not loaded>`. I am able to solve this by setting `smart_contract` to `:nil` in the by passing the value into the changeset, but I was wondering why `contract_code` gets set to `:nil` when `smart_contract` doesn't?

```
%Explorer.Chain.Address{__meta__: #Ecto.Schema.Metadata<:loaded, "addresses">, contract_code: nil, contracts_creation_internal_transaction: #Ecto.Association.NotLoaded<association :contracts_creation_internal_transaction is not loaded>, fetched_coin_balance: nil, fetched_coin_balance_block_number: nil, hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<203, 188, 213, 172, 134, 249, 165, 14, 19, 49, 54, 51, 178, 98, 225, 111, 105, 90, 144, 195>>}, inserted_at: #DateTime<2018-10-13 02:14:20.341184Z>, names: #Ecto.Association.NotLoaded<association :names is not loaded>, smart_contract: #Ecto.Association.NotLoaded<association :smart_contract is not loaded>, token: #Ecto.Association.NotLoaded<association :token is not loaded>, updated_at: #DateTime<2018-10-13 02:14:20.341192Z>}
```
