### ISSUE TITLE
Ethereum Classic: <Stuck In Limbo How To Move These Tokens>

### ISSUE THREAD

**Issue by TGSSource** [poanetwork/blockscout#3703]
*Describe your issue here.*

### Environment
* Elixir Version: 1.11.0
* Erlang Version: 23
* BlockScout Version: v3.5.0-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.86 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*
My ETC were sent to what I thought was the address to another exchange.  These have been sitting there and I don't know how to reverse this, or withdrawl them.  Thank you for your help.  
![image](https://user-images.githubusercontent.com/60139843/110969248-ecbf4d00-8304-11eb-9173-6cde57ae3763.png)

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
You should ask exchange about that.

**Comment by TGSSource** [comment]
Thank you for your reply.  Which exchange would I ask the one I sent from?
Thank you very much.
