### ISSUE TITLE
 Mainnet: <Lost successful transaction>

### ISSUE THREAD

**Issue by ingpop** [poanetwork/blockscout#3706]
My $MATIC Tokens were sent from Metamask BSC to Binance and the transaction was a success but the tokens were not deposited in the Binance account. 

I am trying to get onto Binance support with no luck for over 24hrs now. The TXID is 0x19154b531ec86139008f792b38c74e51f9bf91ca2e6ab19ba975258df3157bea

Can anyone please help?

Cheers

### Environment
* Elixir Version: 1.11.0
* Erlang Version: 23
* BlockScout Version: v3.5.1-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.86 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by ingpop** [comment]
why closed with no response please? 

Github is where the submit a ticket link on the matic explorer goes...so just following links. 

Please advise.

**Comment by vbaranov** [comment]
There is no Matic support here
