### ISSUE TITLE
xDai: <PermaPending>

### ISSUE THREAD

**Issue by bennydlowkey** [poanetwork/blockscout#3718]
It seems i initiated a swap that was too complex for the exchange. I converted Bao.cx to xDai in one step instead of going through BAO-WETH-xDAI and it didn't seem to work out to well. i attempted to initiate a new trade with extra gwei to override said previous trade but that hasn't seemed to help. now i'm stuck on what seems to be a permapending. any help would be extremely appreciated. my apologies for any disturbances 

### Environment
* Elixir Version: 1.11.3
* Erlang Version: 23
* BlockScout Version: v3.5.1-beta

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36`

### Steps to reproduce

Attempt to swap BAO.cx to xDAI on Baoswap with .01 gwei if you dare

### Expected Behaviour

BAO.cx should convert into xDAI

### Actual Behaviour

Permapending Sadness

**Comment by vbaranov** [comment]
This is the tracker for Blokcscout related issues. Please try to ask your question at https://discord.gg/mPJ9zkq.
