### ISSUE TITLE
Mainnet: <Issue Title>

### ISSUE THREAD

**Issue by TBev13** [poanetwork/blockscout#3725]
*Describe your issue here.*

I was trying to buy WETH to purchase a ZED Horse in Matic Open Sea... It says you must first buy ETH and send it to your Matic wallet. Which I did successfully and have the transaction #. When it got to the matic wallet I could not find a way within the wallet to turn the ETH into WETH so I went to withdraw it back to my MetMask. It has been 5 hours and it still has yet to "find a check point". I just want my ETH returned to my MetaMask

### Environment
* Elixir Version: 1.11.0
* Erlang Version: 23
* BlockScout Version: v3.5.1-beta

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
There is no Matic support here. Try to ask at their fork https://github.com/maticnetwork/blockscout.
