### ISSUE TITLE
Mumbai: error when trying to verify and publish GSN contracts

### ISSUE THREAD

**Issue by amirhabibzadeh** [poanetwork/blockscout#3726]
When I tried to verify and publish contracts on Mumbai, I got this error: 
`There was an error compiling your contract: Duplicate experimental feature name.`
and after that, I removed this pragma from the contract I got this error: `There was an error compiling your contract: This type is only supported in ABIEncoderV2. Use "pragma experimental ABIEncoderV2;" to enable the feature.`
these contracts are verified on other networks, what can I do to fix this?
Thanks in advance

### Environment
* Elixir Version: 1.11.0
* Erlang Version: 23
* BlockScout Version: v3.5.1-beta

* User Agent: `Chrome/88.0.4324.150`

### Steps to reproduce
Stakemanger contract: 
Deployed contract on Mumbai: [https://explorer-mumbai.maticvigil.com/address/0xAf125437DcC14E692e7b7BC931CE7922910Afb15/contracts](https://explorer-mumbai.maticvigil.com/address/0xAf125437DcC14E692e7b7BC931CE7922910Afb15/contracts)

Deployed contract and verified version on Etheruem mainnet: [https://etherscan.io/address/0xcAA46E3a5D2c3c07A0C4F7723c7977c3e643C2B1#contracts](https://etherscan.io/address/0xcAA46E3a5D2c3c07A0C4F7723c7977c3e643C2B1#contracts)

StakeManager contract on GitHub: [https://github.com/opengsn/gsn/blob/v2.0.1/contracts/StakeManager.sol](https://github.com/opengsn/gsn/blob/v2.0.1/contracts/StakeManager.sol)

flatten version of StakeManager i tried to verify: [https://gist.github.com/amirhabibzadeh/52c73b2b091fd5fc7893a10458baeb03](https://gist.github.com/amirhabibzadeh/52c73b2b091fd5fc7893a10458baeb03)

### Expected Behaviour

Do the job and verify!

### Actual Behaviour

Shows an error!

**Comment by vbaranov** [comment]
There is no Polygon support here. Please try to ask at their fork https://github.com/maticnetwork/blockscout
