### ISSUE TITLE
I have a transaction stuck on the chain for a day, can you help me find out what is the reason, not a fee issue, this is blockchain information 

### ISSUE THREAD

**Issue by paipaipaipai** [poanetwork/blockscout#3727]
I have a transaction stuck on the chain for a day, can you help me find out what is the reason, not a fee issue, this is blockchain information https://blockscout.com/xdai/mainnet/tx/0x4c620b414d37639736209fed3cc567c6e72a8516b104f65a5f338f681665a03c/internal-transactions

**Comment by paipaipaipai** [comment]
I have a transaction stuck on the chain for a day, can you help me find out what is the reason, not a fee issue, this is blockchain information https://blockscout.com/xdai/mainnet/tx/0x4c620b414d37639736209fed3cc567c6e72a8516b104f65a5f338f681665a03c /internal-transactions

**Comment by vbaranov** [comment]
Wallet, you're trying to send funds from, has no funds to transfer https://blockscout.com/xdai/mainnet/address/0x2475Dcd4Fe333bE814Ef7C8f8CE8A1E9B5FcDEA0/transactions
