### ISSUE TITLE
Add mined blocks count to miner (validator) address page overview

### ISSUE THREAD

**Issue by Stamates** [poanetwork/blockscout#385]
There's some perceived value to seeing how active a miner address has been (number of blocks mined) especially for POW chains.

### Expected behaviour

* Show the number of blocks mined / validated in the overview section of a miner / validator address page
Use `0x23468db7f4b8ff4924b0709ab7ae0971b3bc8d28` as an example.

**Comment by Lokraan** [comment]
I am currently working on this issue.

**Comment by acravenho** [comment]
@Lokraan Great, thanks for the support 👍

**Comment by Lokraan** [comment]
Update on my progress.
I was able to get all of the validations to appear, but they aren't updated when a new validation for the address occurs which is what I'm currently working on.

https://s8.postimg.cc/l6kmpsuj9/validations.png

**Comment by Lokraan** [comment]
How would I get the consensus method of the chains.

**Comment by acravenho** [comment]
You just need to use gettext and everything else will take care of itself.

**Comment by Lokraan** [comment]
https://postimg.cc/gallery/1sncqmpyq/
