### ISSUE TITLE
Contributor sees Tokens Transferred on the Transaction Details page

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#386]
When a token transfer takes place, the contributor should see a new row on the transactions details page with the `to`, `from`, `number of tokens`, and `symbol` of the tokens transferred.

` From 0x9a4a90e2732f3fa4087b0bb4bf85c76d14833df1To 0x4cf9216f42d46d86bfb1f0516210bc3695a8fa27for  20,000 ($1,604.94) QKC`

### Steps to reproduce

Here is an example of Etherscan of this in action: https://etherscan.io/tx/0x1f382c65a776476f4fa701d6b3a1d27b2c851ec7d03c235760836571dac614d4

### Expected behaviour

- If a token transfer took place the example above should display. If not, this row should not be visible. 
- If more than one transfer took place in that transaction, all of them should be displayed.
- When clicking on the Token Symbol/Name in the Tx details page, should redirect to the Token/Address Details page

### Out of Scope
- Conversions to USD

### Task breakdown
- [x] Load token transfers in the query that fetch the transaction
    - Could we reuse it from #75? 
- [x] Add to the page the list of tokens transfers that took place with:
    - To address, from address, amount of tokens and the token symbol.
    - Use the correct style for addresses that are contracts

**Comment by gfreh** [comment]
Hi @katibest and @arthurra! 

The objective of this issue is to display the Token Transfers info in the Tx Details page (we believe this PR https://github.com/poanetwork/poa-explorer/pull/451 is going to change that page too). 

We've just started it, but we are not sure what is the best place to display that info in the page. One detail we need to be aware of is that more than one token transfer might take place in the same transaction. 

Do you have any suggestions for us on what is the best place to display that info?

**Comment by Lucasnar** [comment]
Talking with @feliperenan, I understood better the query from #75 and we don't need to reuse it here; the query change for this issue is different and much simpler than what he had to do.

**Comment by gfreh** [comment]
I've been testing this issue and everything seems to be fine. Below are some scheenshots:

ERC-20 Token Transfer:
<img width="1120" alt="screen shot 2018-08-15 at 09 03 47" src="https://user-images.githubusercontent.com/1440642/44147572-077b10f4-a06b-11e8-9c42-ba506297eef5.png">

ERC-721 Token Transfer:
<img width="1126" alt="screen shot 2018-08-15 at 09 03 00" src="https://user-images.githubusercontent.com/1440642/44147584-11180dce-a06b-11e8-9423-69dfe6108323.png">

Multiple ERC-20 Token Transfers in a single Parent Tx:
![screen shot 2018-08-14 at 18 56 17](https://user-images.githubusercontent.com/1440642/44147605-22f139bc-a06b-11e8-86f6-96cabd69a4f7.png)

Links are working fine, as well as edge cases like when the Token has no symbol or decimals associated to it.

I believe we can move this to ready for acceptance. @acravenho do you want to take a look before @Lucasnar merge it?
