### ISSUE TITLE
Parse input data to contract

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#407]
On the transaction details page we should be parsing the input data according to the `MethodID`. Here is an example below:

Looking at this transaction on `sokol`: `0xf5eae34b00c786e6cc35db10f569cba298c535bef8ac6e297ca05236dbbf711f` we can see it has input data of

```
0xa00715520000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004
```

The method = `0xa0071552` = `sellItem(uint256,uint256,uint256,uint256)`

Here are the 4 variables:
1) 0000000000000000000000000000000000000000000000000000000000000020
2) 0000000000000000000000000000000000000000000000000000000000000007
3) 0000000000000000000000000000000000000000000000000000000000000000
4) 0000000000000000000000000000000000000000000000000000000000000004

All input data can be parsed in this manner.

Here is how it should look: https://sokol.poaexplorer.com/txid/search/0xf5eae34b00c786e6cc35db10f569cba298c535bef8ac6e297ca05236dbbf711f

**Comment by vbaranov** [comment]
I am closing this issue because the decoded view of contract call has been added as a part of this issue https://github.com/poanetwork/blockscout/issues/1029
