### ISSUE TITLE
pending transaction fetcher task exited due to :noproc. 

### ISSUE THREAD

**Issue by KronicDeth** [poanetwork/blockscout#416]
Pending transaction fetcher keeps erroring and restarting

### Steps to reproduce

Index Sokol using #411 

### Expected behaviour

Pending transaction fetcher keeps fetching new transactions without errors

### Actual behaviour

```
pending transaction fetcher task exited due to :noproc. 
```

keeps being printed every few 10s of seconds.

**Comment by acravenho** [comment]
I no longer see this error. This may have been a node issue.
