### ISSUE TITLE
Design cleanup for contract page and read/verify contract

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#448]
The following pages need some design cleanup:
- [x] contract page
- [x] read smart contract page
- [x] verify smart contract page

**Comment by jimmay5469** [comment]
I am removing `mockup for ERC-721 support (#463)` from the list above as we can just track the mockup work for that on #463 itself.

**Comment by jimmay5469** [comment]
I am removing `Include a Token details page (#486) @katibest @arthurra Please ping me when you start work here. I would like to discuss adding 1 more type field (ERC20 or ERC721)` from the list above. I created #524 to track this work.

**Comment by jimmay5469** [comment]
I am removing `Adds API docs page with 'try it' UI #499` from the list above. I created #525 to track this work.

**Comment by jimmay5469** [comment]
I am renaming this issue to only deal with the 3 contract checklist items left in the list above.
