### ISSUE TITLE
Provide ERC-721 UI Support

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#463]
The completion of #447 adds support for [ERC-721](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-721.md) tokens for the indexer. The frontend requires support as well for our v1 release. Here is a list of required pages and locations for ERC-721 support:

- [ ] Account details page - dropdown tab
- [ ] Account details page - transactions tab - token transfer list (type and tokenid)
- [ ] Account details page - tokens tab
- [ ] Token details page - overview section
- [ ] Transaction details page - (type and tokenid)

**Comment by gfreh** [comment]
Hey, @acravenho! I've added below the status of each of the check-list items:

- Account details page: Dropdown tab (*IN PROGRESS* - issue #50)
- Account details page: Transactions tab - token transfer list (*DONE* - issue #494)
- Account details page: Tokens tab (*TO DO*)
- Token details page (*DONE* - issue #51 )
- Transaction details page (*IN PROGRESS* - issue #386)

Based on that, it seems that the only item we haven't started yet is the `Account details page: Tokens tab`, which I believe we could implement with #410. 

In this scenario, I believe we could close this issue. WDYT?

**Comment by jimmay5469** [comment]
I added `team:contributor` to this as well so we can track the work for the mockup described in https://github.com/poanetwork/poa-explorer/issues/448.

**Comment by gfreh** [comment]
@jimmay5469 we're going to close this issue. Do you prefer us to let it open and just remove `team:developer` label?

**Comment by acravenho** [comment]
https://docs.opensea.io/docs/2-adding-metadata

**Comment by vbaranov** [comment]
The storage and display of NFT tokens metadata were added in the frame of the referenced issues ☝️
