### ISSUE TITLE
DopeRaiders ERC721 Token Inventory

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#502]
During indexing when a new DopeRaiders token is discovered/minted we should provide token attributes such as the following:
- narcoName,
- weedTotal,
- cokeTotal,
- skills,
- consumables,
- genes,
- homeLocation,
- level,
- cooldowns,
- id,
- stats

Here is the function for the above stats:

```
function getNarco(uint256 _id)
  public
  view
  returns(
    string  narcoName,
    uint256 weedTotal,
    uint256 cokeTotal,
    uint16[6] skills,
    uint8[4] consumables,
    string genes,
    uint8 homeLocation,
    uint16 level,
    uint256[6] cooldowns,
    uint256 id,
    uint16[9] stats
  );
```

### Contract Address: `0x698bf6943bab687b2756394624aa183f434f65da`

<details>
 <summary>Contract ABI for DistricsCore</summary>
 [{"constant":true,"inputs":[],"name":"narcoCore","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_narcoId","type":"uint256"},{"name":"_total","type":"uint16"}],"name":"updatCokeTotal","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"travelPrice","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_index","type":"uint256"},{"name":"_name","type":"string"},{"name":"_hasMarket","type":"bool"}],"name":"createNamedDistrict","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"coreAddress","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_id","type":"uint256"}],"name":"getDistrict","outputs":[{"name":"exits","type":"uint256[6]"},{"name":"hasMarket","type":"bool"},{"name":"prices","type":"uint256[24]"},{"name":"isStocked","type":"bool[24]"},{"name":"weedPot","type":"uint256"},{"name":"cokePot","type":"uint256"},{"name":"weedAmountHere","type":"uint256"},{"name":"cokeAmountHere","type":"uint256"},{"name":"name","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_spread","type":"uint256"}],"name":"setSpreadPercent","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"tokenContractAddresses","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_fee","type":"uint256"}],"name":"setDevFeePercent","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[],"name":"unpause","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"devFeePercent","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[],"name":"withdrawFees","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_index","type":"uint256"},{"name":"_weedSupply","type":"uint256"},{"name":"_cokeSupply","type":"uint256"}],"name":"initializeSupply","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"marketItems","outputs":[{"name":"id","type":"uint256"},{"name":"itemName","type":"string"},{"name":"skillAffected","type":"uint8"},{"name":"upgradeAmount","type":"uint8"},{"name":"levelRequired","type":"uint8"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_hijackerId","type":"uint256"},{"name":"_victimId","type":"uint256"}],"name":"hijack","outputs":[],"payable":true,"stateMutability":"payable","type":"function"},{"constant":false,"inputs":[{"name":"_address","type":"address"}],"name":"setNarcosCoreAddress","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"_narcoId","type":"uint256"}],"name":"getNarcoLocation","outputs":[{"name":"location","type":"uint8"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"paused","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_narcoId","type":"uint256"},{"name":"_total","type":"uint16"}],"name":"updateWeedTotal","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"isDopeRaiderDistrictsCore","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"pure","type":"function"},{"constant":false,"inputs":[{"name":"_price","type":"uint256"}],"name":"setTravelPrice","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"newContractAddress","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_lrp","type":"uint256"}],"name":"setLocalRevenuPercent","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"hijackPrice","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_v2Address","type":"address"}],"name":"setNewAddress","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_addresses","type":"address[6]"}],"name":"setTokenAddresses","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"_loc","type":"uint8"}],"name":"numberOfNarcosByDistrict","outputs":[{"name":"number","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_id","type":"uint256"},{"name":"_skillAffected","type":"uint8"},{"name":"_upgradeAmount","type":"uint8"},{"name":"_levelRequired","type":"uint8"},{"name":"_itemName","type":"string"}],"name":"configureMarketItem","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_index","type":"uint256"},{"name":"_exits","type":"uint256[6]"},{"name":"_prices","type":"uint256[24]"},{"name":"_isStocked","type":"bool[24]"}],"name":"configureDistrict","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_narcoId","type":"uint256"},{"name":"_exitId","type":"uint256"}],"name":"travelTo","outputs":[],"payable":true,"stateMutability":"payable","type":"function"},{"constant":false,"inputs":[],"name":"pause","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_narcoId","type":"uint256"},{"name":"_district","type":"uint256"},{"name":"_itemIndex","type":"uint256"},{"name":"_quantity","type":"uint256"}],"name":"buyItem","outputs":[],"payable":true,"stateMutability":"payable","type":"function"},{"constant":false,"inputs":[{"name":"_range","type":"uint256"}],"name":"setBustRange","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"owner","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_price","type":"uint256"}],"name":"setHijackPrice","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_district","type":"uint256"},{"name":"_splitW","type":"uint8"},{"name":"_splitC","type":"uint8"}],"name":"distributeRevenue","outputs":[],"payable":true,"stateMutability":"payable","type":"function"},{"constant":false,"inputs":[{"name":"_narcoId","type":"uint256"},{"name":"_district","type":"uint256"},{"name":"_itemIndex","type":"uint256"},{"name":"_quantity","type":"uint256"}],"name":"sellItem","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_price","type":"uint256"}],"name":"setAirLiftPrice","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"localRevenuePercent","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[],"name":"floatEconony","outputs":[],"payable":true,"stateMutability":"payable","type":"function"},{"constant":true,"inputs":[{"name":"_loc","type":"uint8"}],"name":"narcosByDistrict","outputs":[{"name":"narcosHere","type":"uint256[]"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_district","type":"uint256"},{"name":"_quantity","type":"uint256"}],"name":"increaseDistrictWeed","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"airLiftPrice","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_narcoId","type":"uint256"},{"name":"_index","type":"uint256"},{"name":"_newQuantity","type":"uint8"}],"name":"updateConsumable","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"_narcoId","type":"uint256"}],"name":"getNarcoHomeLocation","outputs":[{"name":"location","type":"uint8"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_district","type":"uint256"},{"name":"_quantity","type":"uint256"}],"name":"increaseDistrictCoke","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"currentDevFees","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"districts","outputs":[{"name":"weedPot","type":"uint256"},{"name":"weedAmountHere","type":"uint256"},{"name":"cokePot","type":"uint256"},{"name":"cokeAmountHere","type":"uint256"},{"name":"hasMarket","type":"bool"},{"name":"name","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"newOwner","type":"address"}],"name":"transferOwnership","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"spreadPercent","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"bustRange","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[],"payable":false,"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":true,"name":"location","type":"uint8"},{"indexed":true,"name":"narcoId","type":"uint256"}],"name":"NarcoArrived","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"location","type":"uint8"},{"indexed":true,"name":"narcoId","type":"uint256"}],"name":"NarcoLeft","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"narcoId","type":"uint256"},{"indexed":false,"name":"confiscatedWeed","type":"uint16"},{"indexed":false,"name":"confiscatedCoke","type":"uint16"}],"name":"TravelBust","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"hijacker","type":"uint256"},{"indexed":true,"name":"victim","type":"uint256"},{"indexed":false,"name":"stolenWeed","type":"uint16"},{"indexed":false,"name":"stolenCoke","type":"uint16"}],"name":"Hijacked","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"hijacker","type":"uint256"},{"indexed":true,"name":"victim","type":"uint256"}],"name":"HijackDefended","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"hijacker","type":"uint256"},{"indexed":true,"name":"victim","type":"uint256"},{"indexed":false,"name":"escapeLocation","type":"uint8"}],"name":"EscapedHijack","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"newContract","type":"address"}],"name":"ContractUpgrade","type":"event"},{"anonymous":false,"inputs":[],"name":"Pause","type":"event"},{"anonymous":false,"inputs":[],"name":"Unpause","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"previousOwner","type":"address"},{"indexed":true,"name":"newOwner","type":"address"}],"name":"OwnershipTransferred","type":"event"}]

</details>

Other stats can be indexed from this function

```
function getLevel(uint256 _narcoId) public view returns (uint16 rank){

    /*
      dealsCompleted = 0; // dealsCompleted
      weedGrowCompleted = 1; // weedGrowCompleted
      cokeRefineCompleted = 2; // refineCompleted
      attacksSucceeded = 3; // attacksSucceeded
      defendedSuccessfully = 4; defendedSuccessfully
      raidsCompleted = 5; // raidsCompleted
      escapeHijack = 6; // escapeHijack
      travel = 7; // travelling
    */

        rank =  (narcos[_narcoId].stats[0]/12)+
                 (narcos[_narcoId].stats[1]/4)+
                 (narcos[_narcoId].stats[2]/4)+
                 (narcos[_narcoId].stats[3]/6)+
                 (narcos[_narcoId].stats[4]/6)+
                 (narcos[_narcoId].stats[5]/1)+
                 (narcos[_narcoId].stats[7]/12)
                 ;
    }

```

such as:

- dealsCompleted
- weedGrowCompleted
- cokeRefineCompleted
- attacksSucceeded
- defendedSuccessfully
- raidsCompleted
- escapeHijack
- travel
    
### Contract Address: `0x11c4469d974f8af5ba9ec99f3c42c07c848c861c`

<details>
 <summary>Contract ABI for DistricsCore</summary>
[{"constant":true,"inputs":[],"name":"promoCreatedCount","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_to","type":"address"},{"name":"_tokenId","type":"uint256"}],"name":"approve","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"ceoAddress","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_cost","type":"uint256"}],"name":"setPersonalisationCost","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"implementsERC721","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"pure","type":"function"},{"constant":true,"inputs":[],"name":"totalSupply","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_narcoId","type":"uint256"}],"name":"getRemainingCapacity","outputs":[{"name":"capacity","type":"uint16"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"districtContractAddress","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_from","type":"address"},{"name":"_to","type":"address"},{"name":"_tokenId","type":"uint256"}],"name":"transferFrom","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_newCEO","type":"address"}],"name":"setCEO","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"personalisationCost","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_newCOO","type":"address"}],"name":"setCOO","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"_id","type":"uint256"}],"name":"getNarco","outputs":[{"name":"narcoName","type":"string"},{"name":"weedTotal","type":"uint256"},{"name":"cokeTotal","type":"uint256"},{"name":"skills","type":"uint16[6]"},{"name":"consumables","type":"uint8[4]"},{"name":"genes","type":"string"},{"name":"homeLocation","type":"uint8"},{"name":"level","type":"uint16"},{"name":"cooldowns","type":"uint256[6]"},{"name":"id","type":"uint256"},{"name":"stats","type":"uint16[9]"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_narcoId","type":"uint256"}],"name":"growWeed","outputs":[],"payable":true,"stateMutability":"payable","type":"function"},{"constant":false,"inputs":[{"name":"_narcoId","type":"uint256"},{"name":"_startingPrice","type":"uint256"},{"name":"_endingPrice","type":"uint256"},{"name":"_duration","type":"uint256"}],"name":"createSaleAuction","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[],"name":"unpause","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"gen0CreationLimit","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_address","type":"address"}],"name":"setDistrictAddress","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_narcoId","type":"uint256"},{"name":"_genes","type":"string"},{"name":"_name","type":"string"}],"name":"updateNarco","outputs":[],"payable":true,"stateMutability":"payable","type":"function"},{"constant":true,"inputs":[],"name":"paused","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[],"name":"withdrawBalance","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"_tokenId","type":"uint256"}],"name":"ownerOf","outputs":[{"name":"owner","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_narcoId","type":"uint256"},{"name":"_genes","type":"string"},{"name":"_name","type":"string"}],"name":"recruitNarco","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"newContractAddress","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_address","type":"address"}],"name":"setSaleAuctionAddress","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"_owner","type":"address"}],"name":"balanceOf","outputs":[{"name":"count","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_v2Address","type":"address"}],"name":"setNewAddress","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_genes","type":"string"},{"name":"_name","type":"string"}],"name":"createGen0Auction","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"districtsCore","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"respectRequiredToRecruit","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"changeIdentityNarcoRespect","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_respect","type":"uint256"}],"name":"setChangeIdentityNarcoRespect","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_genes","type":"string"},{"name":"_name","type":"string"},{"name":"_owner","type":"address"}],"name":"createPromoNarco","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[],"name":"pause","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"_narcoId","type":"uint256"}],"name":"getLevel","outputs":[{"name":"rank","type":"uint16"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_narcoId","type":"uint256"},{"name":"_index","type":"uint256"},{"name":"_new","type":"uint256"}],"name":"setCooldown","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_narcoId","type":"uint256"}],"name":"refineCoke","outputs":[],"payable":true,"stateMutability":"payable","type":"function"},{"constant":false,"inputs":[{"name":"_narcoId","type":"uint256"},{"name":"_add","type":"bool"},{"name":"_total","type":"uint16"}],"name":"updateCokeTotal","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[],"name":"withdrawAuctionBalances","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"symbol","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_cost","type":"uint256"}],"name":"setGrowCost","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"refineCost","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_to","type":"address"},{"name":"_tokenId","type":"uint256"}],"name":"transfer","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"gen0EndingPrice","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"gen0StartingPrice","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"cooAddress","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"promoCreationLimit","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"gamePaused","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"narcoIndexToApproved","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_respect","type":"uint256"}],"name":"setRespectRequiredToRecruit","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_narcoId","type":"uint256"},{"name":"_index","type":"uint256"},{"name":"_new","type":"uint8"}],"name":"updateConsumable","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_narcoId","type":"uint256"},{"name":"_index","type":"uint256"},{"name":"_new","type":"uint16"}],"name":"updateSkill","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_id","type":"uint256"},{"name":"_narcoName","type":"string"},{"name":"_weedTotal","type":"uint16"},{"name":"_cokeTotal","type":"uint16"},{"name":"_skills","type":"uint16[6]"},{"name":"_consumables","type":"uint8[4]"},{"name":"_genes","type":"string"},{"name":"_homeLocation","type":"uint8"},{"name":"_stats","type":"uint16[9]"},{"name":"_recoveryAddress","type":"address"}],"name":"recoverNarco","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"growCost","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"saleAuction","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_narcoId","type":"uint256"},{"name":"_add","type":"bool"},{"name":"_total","type":"uint16"}],"name":"updateWeedTotal","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"gen0AuctionDuration","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"gen0CreatedCount","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_cost","type":"uint256"}],"name":"setRefineCost","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"_owner","type":"address"}],"name":"narcosByOwner","outputs":[{"name":"ownedNarcos","type":"uint256[]"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_narcoId","type":"uint256"},{"name":"_index","type":"uint256"}],"name":"incrementStat","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"narcoIndexToOwner","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[],"payable":false,"stateMutability":"nonpayable","type":"constructor"},{"payable":true,"stateMutability":"payable","type":"fallback"},{"anonymous":false,"inputs":[{"indexed":true,"name":"narcoId","type":"uint256"},{"indexed":false,"name":"yield","type":"uint256"}],"name":"GrowWeedCompleted","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"narcoId","type":"uint256"},{"indexed":false,"name":"yield","type":"uint256"}],"name":"RefineCokeCompleted","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"from","type":"address"},{"indexed":true,"name":"to","type":"address"},{"indexed":true,"name":"tokenId","type":"uint256"}],"name":"Transfer","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"owner","type":"address"},{"indexed":true,"name":"approved","type":"address"},{"indexed":true,"name":"tokenId","type":"uint256"}],"name":"Approval","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"owner","type":"address"},{"indexed":false,"name":"narcoId","type":"uint256"},{"indexed":false,"name":"genes","type":"string"}],"name":"NarcoCreated","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"newContract","type":"address"}],"name":"ContractUpgrade","type":"event"}]
</details>

**Comment by KronicDeth** [comment]
Support for this will need to be much more generic than just DopeRaiders token support as it will otherwise take a lot of work to support the special features of each token and additionally not all people using the Explorer will care about DopeRaiders.

At a minimum, we likely need to keep support for each Token in a separate context/namespace and allow for these additional things that need to be indexed to be pluggable.

**Comment by KronicDeth** [comment]
Blocked by #484
