### ISSUE TITLE
Deploy Sokol mockup

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#518]
As we get closed to launch I would like to deploy both `core` and `sokol` explorers. To do so we should finish the `sokol` mockups and move them to master.

- [ ] finish sokol mockups
- [ ] move sokol css to master
- [ ] create logos for core and master so they can be interchanged

**Comment by jimmay5469** [comment]
I believe this has been taken care of, feel free to reopen or create another issue if something is missing.
