### ISSUE TITLE
Improve flaky live update integration tests

### ISSUE THREAD

**Issue by jimmay5469** [poanetwork/blockscout#522]

**Comment by KronicDeth** [comment]
From https://circleci.com/gh/poanetwork/poa-explorer/17218, it's not a simple timing issue.  Having the flaky tests retry every 100ms and wait until the test timeout (60s) still had the flaky tests fail in some situations.  This could indicate an underlying bug in the code or tests beyond timing issues.

**Comment by jimmay5469** [comment]
We are going to work #403 which needs to happen anyways and may have an impact on this issue. Following the conclusion of that we will re-assess what needs to happen for this issue to be resolved.
