### ISSUE TITLE
Design cleanup for token details page

### ISSUE THREAD

**Issue by jimmay5469** [poanetwork/blockscout#524]
Design cleanup for: Include a Token details page (#486) 

@katibest @arthurra Please ping me when you start work here. I would like to discuss adding 1 more type field (ERC20 or ERC721)

**Comment by katibest** [comment]
Contract Links!

**Comment by arthurra** [comment]
@acravenho It looks like this may have been completed #448. Can you provide any details on what, if anything, needs to be done for this issue?

**Comment by acravenho** [comment]
@arthurra Here is an example page for a token: https://core-alpha.poaexplorer.com/en/tokens/0x11c4469d974f8af5ba9ec99f3c42c07c848c861c

- [ ] We need to list the token type (ERC-20 or ERC-721)
- [ ] Cleanup on the token cards. We probably should make them identical to the address page
- [ ] Anything else that looks off to you.
