### ISSUE TITLE
Reduce the height of token transfer transaction cards

### ISSUE THREAD

**Issue by jimmay5469** [poanetwork/blockscout#529]
See #478 for some ideas. We need to alter the design to make the approach taken in #478 simpler.

**Comment by arthurra** [comment]
![transfer-transaction-tiles-02](https://user-images.githubusercontent.com/1641169/44050986-9bc2de42-9f06-11e8-8304-973d07b9b52b.png)

**Comment by katibest** [comment]
Single transfer tile:
![transfer-transaction-tiles-03](https://user-images.githubusercontent.com/20226535/44357870-42028d00-a481-11e8-81a1-8fe527258ba0.png)

**Comment by Stamates** [comment]
##Samples to use:
* Address with 50+ transactions / internal_transactions: `0xc40cdf254a4a35498aa84f35e9842c110729a2a0`
* Block with 50+ transactions: `1402784`
* Transactions with 50+ internal_transactions: `0x037f9d9e5abe501c620280306d6fb31cff1f1f71a397eeef8069329563aa45cc`
* Transactions with 50+ token_transfers and logs: `0xd38254bb9653ff5be479a31775a00f6be4cbfdb2e32737d41df488e0406952b8`
