### ISSUE TITLE
Unsupported Decoding type for Read Smart Contract

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#533]
While attempting to interact with a function for contract `0x698bf6943bab687b2756394624aa183f434f65da` on `core`, I found that we had several unsupported decoding types. 

```
[ getDistrict method Response ] 
 uint256[6] : Unsupported decoding type: {:array, {:uint, 256}, 6}  bool : Unsupported decoding type: {:array, {:uint, 256}, 6}  uint256[24] : Unsupported decoding type: {:array, {:uint, 256}, 6}  bool[24] : Unsupported decoding type: {:array, {:uint, 256}, 6}  uint256 : Unsupported decoding type: {:array, {:uint, 256}, 6}  uint256 : Unsupported decoding type: {:array, {:uint, 256}, 6}  uint256 : Unsupported decoding type: {:array, {:uint, 256}, 6}  uint256 : Unsupported decoding type: {:array, {:uint, 256}, 6}  string : Unsupported decoding type: {:array, {:uint, 256}, 6}
```

### Steps to reproduce

1. View the address `0x698bf6943bab687b2756394624aa183f434f65da`
2. Enter `1` in the function `getDistrict`

### Expected behaviour

This should display arrays of statistics.

### Actual behaviour

Unsupported decoding type

**Comment by alexgaribay** [comment]
It looks like this is an issue I introduced in to `:ex_abi`. It supports arrays but not when the array item count is provided.

**Comment by alexgaribay** [comment]
@acravenho Can you paste in the raw output of running that function using an ethereal client?

**Comment by alexgaribay** [comment]
What you say core, what's the node jsonrpc target host? https://sokol.poa.network?

**Comment by acravenho** [comment]
https://core.poa.network

**Comment by acravenho** [comment]
I can deploy the contract on `sokol` to make it easier.

**Comment by alexgaribay** [comment]
A PR has been added to `ex_abi` to fix the decoding issue.
poanetwork/ex_abi#7
