### ISSUE TITLE
Read smart contract first response repeats

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#535]
I verified a smart contract, provided an input and instead of providing multiple responses with different decode types I received the same response for every value.

<img width="1405" alt="screen shot 2018-08-10 at 12 51 19 am" src="https://user-images.githubusercontent.com/17620007/43939380-b804e806-9c37-11e8-8f96-03881dc06361.png">

### Steps to reproduce

1. Visit this smart contract: `0x11c4469d974f8af5ba9ec99f3c42c07c848c861c`
2. Enter `277` in the field for the function `getNarco`
3. View the results.

### Expected behaviour

I should have received corresponding to their type ` string uint256 uint256 uint16[6] uint8[4] string uint8 uint16 uint256[6] uint256 uint16[9]`

### Actual behaviour

Repeated responses.

**Comment by gfreh** [comment]
Duplicated with: https://github.com/poanetwork/blockscout/issues/337
