### ISSUE TITLE
Mobile view of the transactions page fix

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#536]
On the view all transactions page, the elements are overlapping and falling off the transaction card. The same transaction card on the account page is acting correctly. 

![screenshot_20180810-110356](https://user-images.githubusercontent.com/17620007/43946982-c4bcc858-9c54-11e8-9ac4-1c163bdb1bb4.png)

### Environment

* Operating System: Pixel 2 Standard Browser

### Steps to reproduce

1. View the transactions page from a mobile browser

### Expected behaviour

Elements should look like they appear on the account transactions tab

**Comment by arthurra** [comment]
This issue has been resolved by previous work.

<img width="248" alt="screen shot 2018-09-06 at 10 33 01 am" src="https://user-images.githubusercontent.com/1641169/45164463-8059b500-b1c0-11e8-8af7-0faed3a6bc15.png">
