### ISSUE TITLE
Show token transfers on the transaction tab of the block details page

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#543]
Currently, the block details page only shows `Contract Call` where there should be a token transfer. This should display similar to the all transactions page.

<img width="1127" alt="screen shot 2018-08-13 at 4 22 58 pm" src="https://user-images.githubusercontent.com/17620007/44056098-3745e784-9f15-11e8-9177-3c06366e8548.png">

### Steps to reproduce

1. View block #3477687 on `sokol`

### Expected behaviour

The contract call should show a token transfer.

**Comment by vbaranov** [comment]
<img width="1142" alt="Screenshot 2019-05-02 at 14 22 03" src="https://user-images.githubusercontent.com/4341812/57072256-bca8cb00-6ce5-11e9-9148-cc7ca70f7886.png">
