### ISSUE TITLE
Contributors sees token transfers on the home page

### ISSUE THREAD

**Issue by amandasposito** [poanetwork/blockscout#565]
### Description

As a Contributor visiting the `Home` page, when a `Token Transfer` takes place, instead of the `Contract Call` card, I want to see a new row on the transactions details page with the to, from, number of tokens, and symbol of the tokens transferred.

![screen shot 2018-08-17 at 15 34 42](https://user-images.githubusercontent.com/840531/44283282-3ec69180-a234-11e8-9410-2568c49fc520.png)

### Acceptance Criteria

* When a token transfer takes place the there should be a card with the following info:
  * to;
  * from;
  * number of tokens;
  * symbol of the tokens transferred.
* When more than one transfer took place in that transaction, all of them should be displayed;
* When clicking on the Token Symbol/Name in the Tx details page, should redirect to the Token/Address Details page;
* If the parent transaction has three token transfers than it should be shown three cards each one with a token transfer.

#### Examples

<img width="1085" alt="44147572-077b10f4-a06b-11e8-9c42-ba506297eef5" src="https://user-images.githubusercontent.com/840531/44283934-438c4500-a236-11e8-8672-0496d48b041a.png">

<img width="1085" alt="44147584-11180dce-a06b-11e8-9423-69dfe6108323" src="https://user-images.githubusercontent.com/840531/44283955-49822600-a236-11e8-9be9-cba39a57732d.png">

#### Questions

* Is this the correct layout to the token transfer card? Or should we use this one: 

![screen shot 2018-08-17 at 15 55 30](https://user-images.githubusercontent.com/840531/44284608-af6fad00-a238-11e8-9404-11ffbd02e59f.png)

**Comment by acravenho** [comment]
It should be the the card without the parent transaction.

**Comment by acravenho** [comment]
@gfreh @amandasposito 
## If POA value is sent
- display parent tx 
- display 1 token transfer similar to the bottom image

## If POA value is 0
- display only token transfer
![44357870-42028d00-a481-11e8-81a1-8fe527258ba0](https://user-images.githubusercontent.com/17620007/44370888-3aa3a980-a4aa-11e8-8574-47b41b545831.png)


## If POA value is 0 and more than 1 token transfer
- display one token transfer with a link to tx details with the number of token transfers
![44050986-9bc2de42-9f06-11e8-8304-973d07b9b52b](https://user-images.githubusercontent.com/17620007/44370894-4000f400-a4aa-11e8-8396-21e6d9d1a866.png)

**Comment by gfreh** [comment]
Once https://github.com/poanetwork/blockscout/pull/574 is closed, I'll close this issue too.
