### ISSUE TITLE
When a Contributor searches and the Hash is a Contract, navigate to the Contract details page.

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#57]

**Comment by vbaranov** [comment]
This is exactly how it is implemented in the current version of the application. The contract details page is a variety of account page. For instance, searching for `0x79f8ac29df70825e31d953acefbbf78a8272e0cd` will open contract details page https://blockscout.com/poa/core/address/0x79f8ac29df70825e31d953acefbbf78a8272e0cd/transactions

![Screenshot 2019-10-31 at 14 55 32](https://user-images.githubusercontent.com/4341812/67944859-8e516d00-fbee-11e9-9764-2674bc8c87c0.png)
