### ISSUE TITLE
API docs' CSS to support links in descriptions

### ISSUE THREAD

**Issue by sabondano** [poanetwork/blockscout#577]
👋 @katibest, @arthurra,

We'd like to be able to embed links into descriptions in the `/api_docs` page. Is it possible to change the `a` tag, in the line referenced below, for a `button` element without breaking the way it looks? I tried the change and it doesn't look great. This change is necessary to allow for a `a` tags within that element since we can't do nested `a` tags in HTML. Could you give us a hand with this 🙏?

https://github.com/poanetwork/blockscout/blob/5e8ac9fb49bc9ddcd11983fd6bc90e6be603c6cb/apps/block_scout_web/lib/block_scout_web/templates/api_docs/_action_tile.html.eex#L1

**Comment by katibest** [comment]
@sabondano Hey!! So I think I got it figured out. I'll add a fake link in on sa-api-gettoken-by-contractaddress brach. Is that cool?

**Comment by sabondano** [comment]
@acravenho yes 👍 . Links to token standards have been added in this PR: https://github.com/poanetwork/blockscout/pull/617
