### ISSUE TITLE
Partial Indexing

### ISSUE THREAD

**Issue by mewwts** [poanetwork/blockscout#585]
Hi,

In an effort to run against mainnet Infura I am looking at removing some of the data which is being indexed. For now I'm looking at indexing `blocks`, `transactions` and `logs`.

Is there any support for partial indexing like this?

If not, what's a good starting point to modify the code? I've tried removing the function calls that get the surplus data in the `blockfetcher` code, but it seems like writing to the database is tied up to having all the data in place. Any ideas?

Thanks!

**Comment by acravenho** [comment]
Hi @mewwts,

Unfortunately, we do not support this currently. Only indexing blocks, transactions, and logs does not provide a full state of the blockchain without tracing enabled (internal transactions). 

It would be very difficult to pull the code apart if you chose to go this route anyway to make this work.

**Comment by mewwts** [comment]
Thanks for clarifying @acravenho!
