### ISSUE TITLE
Duplicate realtime transactions

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#599]
On the transactions page, address page, and homepage transactions are being duplicated during the real-time event process.

### Environment

* Operating System: Linux/Mac

### Steps to reproduce

1. Deploy locally or in production
2. View address, transactions, or homepage

### Expected behaviour

n/a

### Actual behaviour

n/a

**Comment by jimmay5469** [comment]
It looks like this is no longer an issue after the the indexer connected to the blockchain socket.
