### ISSUE TITLE
Contributor sees Dropped/Replaced Transaction details.

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#60]
Many of the transactions we're seeing with a pending state are actually `replaced` transactions. Here is an example:
- [0x59561737884b98a2c058b22e02d26028947b989407b651a225063f9ac8ed85ce](https://blockscout.com/poa/core/tx/0x59561737884b98a2c058b22e02d26028947b989407b651a225063f9ac8ed85ce/internal_transactions) was sent with a `nonce` of 22109
- [0xdec23c5443e161fcb608135a409425aacec586296e937b02ec99317540f68f7e](https://blockscout.com/poa/core/tx/0xdec23c5443e161fcb608135a409425aacec586296e937b02ec99317540f68f7e/internal_transactions) was sent with a `nonce` of 22109

The second transaction, in this case, was collated and took the place of the first transaction. I think in this case we should provide a `failed` status and `dropped/replaced` error. 

A `dropped/replaced` transaction gets mined prior to another transaction with the same nonce.

1. Create a transaction
2. Create an identical transaction with the same nonce but with a higher gas price.
3. This will drop the first transaction once it gets mined.

**Comment by KronicDeth** [comment]
@acravenho can we get more details?  Is this for a transaction that was dropped because of a Reorg or some other form of dropped/replaced?

**Comment by acravenho** [comment]
This is for a transaction that gets mined prior to another transaction with the same nonce.

1. Create a transaction on Ethereum mainnet
2. Create an identical transaction on Ethereum mainnet with the same nonce but with a higher gas price.
3. This will drop the the first transaction once it gets mined.

Here is a good explanation:

https://etherscancom.freshdesk.com/support/solutions/articles/35000048526-transaction-dropped-replaced-

**Comment by KronicDeth** [comment]
We don't use `nonce` as part of any unique key for transactions.  Transaction collisions are based solely based on the `hash`, so if a new Transaction with the same `hash` appears, it will replace the old value.  Does `nonce` not affect the `hash`?  Do we need to support multiple transactions with the same hash?
