### ISSUE TITLE
GenServer Indexer.BlockFetcher.Realtime terminating

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#624]
**This issue has been resolved but is remaining open until we complete a future PR to add insecure Websocket connection for private networks. This seems to be a community demand**

Realtime indexer on Ethereum mainnet timeout issue.

```
14:51:12.912 [error] GenServer Indexer.BlockFetcher.Realtime terminating
** (stop) exited in: GenServer.call(Indexer.BlockFetcher.Realtime.WebSocket, {:subscribe, "newHeads", []}, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:924: GenServer.call/3
    (indexer) lib/indexer/block_fetcher/realtime.ex:47: Indexer.BlockFetcher.Realtime.handle_continue/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:388: :gen_server.loop/7
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:continue, {:init, [transport: EthereumJSONRPC.WebSocket, transport_options: [web_socket_options: %{web_socket: Indexer.BlockFetcher.Realtime.WebSocket}, web_socket: EthereumJSONRPC.WebSocket.WebSocketClient, url: "***redacted***"]]}}
State: %Indexer.BlockFetcher.Realtime{block_fetcher: %Indexer.BlockFetcher{broadcast: true, callback_module: Indexer.BlockFetcher.Realtime, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "***redacted***", method_to_url: [eth_getBalance: "***redacted***", trace_replayTransaction: "***redacted***"], http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant:EthereumJSONRPC.Parity], receipts_batch_size: 250, receipts_concurrency: 10}, subscription: nil}
14:51:17.914 [error] GenServer Indexer.BlockFetcher.Realtime terminating
** (stop) exited in: GenServer.call(Indexer.BlockFetcher.Realtime.WebSocket, {:subscribe, "newHeads", []}, 5000)
```

### Environment

* Operating System: Mac

### Steps to reproduce

1. Index Ethereum Mainnet

### Expected behaviour

This should provide a block/transactions every 15 seconds.

### Actual behaviour

It's currently timing out.

**Comment by jsvisa** [comment]
The default timeout of `Genserver.call/2` is 5 second, set it in the config file? @acravenho

**Comment by KronicDeth** [comment]
@acravenho have you been able to reproduce this?

**Comment by acravenho** [comment]
@KronicDeth Yes, this happens quite frequently on Ethereum Mainnet. There are a couple issues here. 

1. The realtime indexer falls behind by a few minutes, the Genesis indexer kicks in and indexes all the blocks between the tip of the chain and the last block indexed. The realtime indexer doesn't see this update and continues trying to catchup without success and falls further behind. This process repeats 

2. I'm not sure if 1. is related to the above errors but I do see this process repeating.

**Comment by nambrot** [comment]
Just ran into this as well, is there any recommended workaround?

**Comment by acravenho** [comment]
I'm checking the error logs on my build from last night and am not seeing this error any longer. 
@nambrot 
- What settings are you using on your node?
- How old is your build?

**Comment by nambrot** [comment]
Wow thanks for the quick response. We are using our own fork of geth with the following settings: `--port 30303 --rpc --rpcaddr 0.0.0.0 --rpcapi=eth,net,web3 --ws --wsaddr 0.0.0.0 --wsorigins=*`

I'm running of master that I just cloned this morning

**Comment by acravenho** [comment]
@nambrot We do support basic Geth support but I have not personally tested this in the last month. I'll try spinning up a Geth node and try to debug. We will be offering full Geth support (`debug_traceTransaction`) in our v2 release in the next few months.

**Comment by nambrot** [comment]
Yeah we definitely get the sense that geth is behind parity in terms of priority but that is ok, maybe we can contribute!

**Comment by nambrot** [comment]
Does this error strike you as Geth related however?

**Comment by acravenho** [comment]
That would be fantastic to have more contributions. POA Network is a Proof of Authority Network so our initial focus was always on Parity tech but we realized right away that there is a need for Geth support. It's on our roadmap to provide just as much support for Geth in the future.

This error strikes me as a node settings error more than a Geth/Parity issue but I won't know until I can provide exact settings that worked for me.

**Comment by nambrot** [comment]
Thanks! What specific settings are you looking for? Are there any pointers you can give me to help debug this?

**Comment by nambrot** [comment]
Ahh I think you mean the settings in the indexer?

```
  block_interval: 5_000,
  json_rpc_named_arguments: [
    transport: EthereumJSONRPC.HTTP,
    transport_options: [
      http: EthereumJSONRPC.HTTP.HTTPoison,
      url: System.get_env("ETHEREUM_JSONRPC_HTTP_URL") || "http://localhost:8545",
      http_options: [recv_timeout: 60_000, timeout: 60_000, hackney: [pool: :ethereum_jsonrpc]]
    ],
    variant: EthereumJSONRPC.Geth
  ],
  subscribe_named_arguments: [
    transport: EthereumJSONRPC.WebSocket,
    transport_options: [
      web_socket: EthereumJSONRPC.WebSocket.WebSocketClient,
      url: "ws://localhost:8546"
    ]
```

Yeah I realized that I have `ws` instead of `wss` since I just trying it out locally on my machine and dont have ssl setup, hopefully thats not it

**Comment by acravenho** [comment]
The realtime fetcher which failed utilizes Websockets to fetch the incoming blocks, transactions, tokens and balances. My initial thoughts are that a port isn't configured correctly in the config.

**Comment by nambrot** [comment]
I verified that the port is indeed open with https://www.npmjs.com/package/wscat

**Comment by acravenho** [comment]
Also, you should update the config in `apps/explorer/config/dev/geth.exs` and `apps/indexer/config/dev/geth.exs`

**Comment by nambrot** [comment]
Thank you for bearing with me. I did update config to the above settings to my local geth node. Fwiw, Catchup seems to work fine

**Comment by acravenho** [comment]
https://github.com/poanetwork/blockscout/blob/1ce4753de4d3df143b6bc8bf58ca0765101930de/apps/indexer/config/dev.exs#L14

https://github.com/poanetwork/blockscout/blob/1ce4753de4d3df143b6bc8bf58ca0765101930de/apps/explorer/config/dev.exs#L20

Change those lines to `geth` as well.

**Comment by nambrot** [comment]
I did!

**Comment by acravenho** [comment]
Nice! So catchup indexer works, just the realtime fetcher is failing. @KronicDeth is there anything that we're missing for the realtime indexer to work on `geth`?

**Comment by KronicDeth** [comment]
@nambrot it's the registered name of the process:

https://github.com/poanetwork/blockscout/blob/1ce4753de4d3df143b6bc8bf58ca0765101930de/apps/indexer/lib/indexer/block/realtime/supervisor.ex#L20-L33

**Comment by nambrot** [comment]
Ahh, that makes much more sense!

**Comment by nambrot** [comment]
Thanks for bearing with me. So if I understand correctly ( as I'm new to elixir )

In the Supervisor we are starting the `Indexer.Block.Realtime.WebSocket` (the module should be `EthereumJSONRPC.WebSocket.WebSocketClient`) and `Indexer.Block.Realtime.Fetcher` 

-in the fetcher we try to call subscribe on `EthereumJSONRPC`
https://github.com/poanetwork/blockscout/blob/1ce4753de4d3df143b6bc8bf58ca0765101930de/apps/indexer/lib/indexer/block/realtime/fetcher.ex#L46:L53

- that will read `:transport` from the geth config which is `EthereumJSONRPC.WebSocket`, and call subscribe on it with the `:transport_options`

- `EthereumJSONRPC.WebSocket#subscribe` calls `EthereumJSONRPC.WebSocketClient#subscribe`

- finally we actually start the websocket client at 
https://github.com/poanetwork/blockscout/blob/1ce4753de4d3df143b6bc8bf58ca0765101930de/apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/web_socket/web_socket_client.ex#L32:L56

That's presumably where I fail.

**Comment by acravenho** [comment]
@nambrot As you described above and I overlooked, you're using `ws` instead of `wss`. We do require secure Websockets to be used:

https://github.com/poanetwork/blockscout/blob/1ce4753de4d3df143b6bc8bf58ca0765101930de/apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/web_socket/web_socket_client.ex#L30-L38


Use the `-` between line numbers instead of `:`.

**Comment by nambrot** [comment]
I removed 
https://github.com/poanetwork/blockscout/blob/1ce4753de4d3df143b6bc8bf58ca0765101930de/apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/web_socket/web_socket_client.ex#L48-L54

and that seems like I received a successful subscription! Or at least I reach https://github.com/poanetwork/blockscout/blob/master/apps/indexer/lib/indexer/block/realtime/fetcher.ex#L50

Not getting any blocks, but getting some progress, and at least not that error message anymore!

**Comment by nambrot** [comment]
Just wanted to let you know that I have been able to get it to work! It's syncing blocks beautifully!

**Comment by acravenho** [comment]
That's fantastic! What did you do to fix the issue?

**Comment by KronicDeth** [comment]
If it is that, it seems like something else is probably wrong with the setup that talking to your node, it can't setup a websocket in 5 seconds.   You'd have to be experiencing really high network latency or if locally a lot of CPU load to not be to able to setup a websocket connection in 5 seconds.

You're using `ws` URL, but the code we wrote enforced `wss`, so you disabled, the `ws` check I'm assuming by changing the code, but I'm betting you left in


https://github.com/poanetwork/blockscout/blob/1ce4753de4d3df143b6bc8bf58ca0765101930de/apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/web_socket/web_socket_client.ex#L47-L55

so it is still trying to verify the server is secure when it's not.  Try taking out the `ssl` options and see if it works for you.

**Comment by nambrot** [comment]
Yeah that's what I did per https://github.com/poanetwork/blockscout/issues/624#issuecomment-426819218 and it worked!

**Comment by dwalintukan** [comment]
@nambrot did you have to do anything else other than remove the `ssl_verify:` and `socket_opts:` to disable the wss enforcement?

**Comment by nambrot** [comment]
As per the PR https://github.com/poanetwork/blockscout/pull/864/files, I did not

**Comment by dwalintukan** [comment]
@nambrot Thanks, its working as intended! I had to add some ws routing from Nginx.

**Comment by acravenho** [comment]
There should be no issue running `:insecure` Websockets. This issue was resolved in #864

**Comment by rjl493456442** [comment]
Hi, I try to run blockscout in docker container, the error log occurs:

```
Function: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3
    Args: [127070, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://localhost:8545", http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, false]
06:51:38.879 [error] Task #PID<0.6548.6> started from Indexer.Block.Realtime.Fetcher terminating
** (stop) exited in: :gen_server.call(Explorer.Repo.Pool, {:checkout, #Reference<0.3452034868.1585184770.68066>, true}, 5000)
    ** (EXIT) time out
    (stdlib) gen_server.erl:223: :gen_server.call/3
    (poolboy) src/poolboy.erl:55: :poolboy.checkout/3
    (db_connection) lib/db_connection/poolboy.ex:41: DBConnection.Poolboy.checkout/2
    (db_connection) lib/db_connection.ex:928: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:750: DBConnection.run/3
    (db_connection) lib/db_connection.ex:798: DBConnection.transaction/3
    (ecto) lib/ecto/repo/queryable.ex:23: Ecto.Repo.Queryable.transaction/4
    (explorer) lib/explorer/chain/import.ex:132: Explorer.Chain.Import.all/1
```

I test with latest master branch, could you please take a look? @acravenho

**Comment by hadv** [comment]
I still have the error when running on v1.3.4-beta release 

```
2019-03-02T08:28:48.393 fetcher=block_realtime [error] GenServer Indexer.Block.Realtime.Fetcher terminating
** (stop) exited in: GenServer.call(Indexer.Block.Realtime.WebSocket, {:subscribe, "newHeads", []}, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:924: GenServer.call/3
    (indexer) lib/indexer/block/realtime/fetcher.ex:69: Indexer.Block.Realtime.Fetcher.handle_continue/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:388: :gen_server.loop/7
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:continue, {:init, [transport: EthereumJSONRPC.WebSocket, transport_options: %EthereumJSONRPC.WebSocket{url: "ws://localhost:8546", web_socket: EthereumJSONRPC.WebSocket.WebSocketClient, web_socket_options: %EthereumJSONRPC.WebSocket.WebSocketClient.Options{event: nil, params: nil, web_socket: Indexer.Block.Realtime.WebSocket}}]}}
State: %Indexer.Block.Realtime.Fetcher{block_fetcher: %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://localhost:8545", http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, max_number_seen: nil, previous_number: nil, subscription: nil, timer: nil}
```

**Comment by peachwaravich** [comment]
Sorry now I got a problem on issue https://github.com/poanetwork/blockscout/issues/2531

![image](https://user-images.githubusercontent.com/36033754/62773666-ef284800-bacc-11e9-9f62-b628d64155e9.png)

How do I fixed it ?
