### ISSUE TITLE
"n Transactions has come in" causes the div container to break

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#625]
<img width="1140" alt="screen shot 2018-08-28 at 5 11 54 pm" src="https://user-images.githubusercontent.com/17620007/44751238-a0fd7d00-aae5-11e8-9466-754c599bd3a2.png">

Looking at the bottom of the transactions list, you'll see the bottom transaction card being pushed out of the container.

### Environment

* Operating System: Linux

### Steps to reproduce

1. Deploy `ropsten` or `mainnet`
2. Wait for 10+ transactions to come in a single block
3. View the bottom of the transactions list.

### Expected behaviour

This container should move with the transaction cards.

### Actual behaviour

The bottom transaction card is falling off the page.

**Comment by arthurra** [comment]
This issue has been resolved by previous work.

<img width="937" alt="screen shot 2018-09-06 at 11 30 09 am" src="https://user-images.githubusercontent.com/1641169/45168037-645a1180-b1c8-11e8-9265-814b0af84e5b.png">
