### ISSUE TITLE
Feature Request: URL consistency

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/blockscout#639]
In order to be consistent for Dapp devs,
it would be great if we could query tx like:
`URL/tx/hash`
in order to match etherchain, etherscan's URL schemes in order to remain existing support for URL builders in many other Dapps.

TX:
`tx/0x...`

Address:
`address/0x...` 

I think adding aliases would be very helpful

**Comment by acravenho** [comment]
## TODO
- [ ] - change `transactions/0x...` to `tx/0x...`
- [ ] - change `addresses/0x...` to `address/0x...`
