### ISSUE TITLE
Create an accounts page showing ordered list of all addresses

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#686]
We should create an accounts page that displays all addresses of the chain ordered by balance `ASC`. This list should include:

- [ ] address (with link to address page)
- [ ] coin balance
- [ ] name of the wallet if available
- [ ] USD value of the balance (if available)
- [ ] percentage of coins from total supply
- [ ] incremented number by order in the list
- [ ] the number of transactions for that wallet

Here is an example page from Etherscan: https://etherscan.io/accounts

**Comment by arthurra** [comment]
Kati and I set up a new route at `/top_addresses` and added a static representation of a top address tile.

**Comment by arthurra** [comment]
Kati and adjust the page layout and information hierarchy within the tiles.
