### ISSUE TITLE
Indexer.TokenFetcher: value too long for type character varying(255)

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#693]
The catchup indexer looks to be stuck at block `6077901` because of the below issue.

```
17:46:47.283 [error] Task #PID<0.24532.0> started from Indexer.TokenFetcher terminating
** (Postgrex.Error) ERROR 22001 (string_data_right_truncation): value too long for type character varying(255)
    (ecto) lib/ecto/adapters/sql.ex:554: Ecto.Adapters.SQL.struct/8
    (ecto) lib/ecto/repo/schema.ex:547: Ecto.Repo.Schema.apply/4
    (ecto) lib/ecto/repo/schema.ex:213: anonymous fn/14 in Ecto.Repo.Schema.do_insert/4
    (ecto) lib/ecto/repo/schema.ex:774: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
    (db_connection) lib/db_connection.ex:1374: DBConnection.transaction_nested/2
    (db_connection) lib/db_connection.ex:1234: DBConnection.transaction_meter/3
    (db_connection) lib/db_connection.ex:798: DBConnection.transaction/3
    (ecto) lib/ecto/multi.ex:421: Ecto.Multi.apply_operation/5
Function: #Function<4.71023014/0 in Indexer.BufferedTask.spawn_next_batch/1>
```

### Environment

* Operating System: Linux

### Steps to reproduce

1. Index Ethereum Mainnet
2. View errors.log
3. Looks like it's stuck at block number `6077901`

### Expected behaviour

n/a

### Actual behaviour

n/a

**Comment by alexgaribay** [comment]
Looks like a token's string name longer that 255 characters. We'd have to migrate the column to be a longer width. @acravenho, do you know if there's a length limit for a token's name off the top of your head?

**Comment by acravenho** [comment]
@alexgaribay I'm looking into a length limit. I'm also pulling that particular block to see what is actually given for the name. I'll provide my results soon.

**Comment by acravenho** [comment]
I don't see any odd token names in that block but this one `民宿通`.

**Comment by Lucasnar** [comment]
@acravenho, I am having trouble replicating the problem and finding that `民宿通` token. Do you have a link to that token or its hash for me to test it?

**Comment by acravenho** [comment]
@Lucasnar It's weird because I didn't see anything odd from any of the token transfers in that block `6077901`. `6077902` was the last block that could successfully index. Maybe it was getting stuck somewhere inside this block. I'll take a look.

**Comment by Lucasnar** [comment]
That was me. 😅

I wasn't able to replicate the issue using the tokens we got looking at the blocks. I queried the blockchain for all of them and was able to successfully save everything to the db, so in order to get the same error, I deployed a token with a long name. I'm working on a fix right now.
