### ISSUE TITLE
ETC-classic doesn't query for addresses

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/blockscout#695]
![image](https://user-images.githubusercontent.com/9360827/45325078-cbe3ca00-b504-11e8-9d9d-134796ac5160.png)

https://classic-alpha.poaexplorer.com/search?q=0x0039f22efb07a647557c7c5d17854cfd6d489ef3

**Comment by acravenho** [comment]
We have an upcoming issue covering this. In the future, addresses with a `0` ETH balance and no previous transactions will still display instead of showing a 404. This issue will be covered in the next few weeks.
