### ISSUE TITLE
Build throttling feature for the TokenBalanceFetcher

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#713]
There is no way to expect every project to have a beefy node to support our indexer speed. Building a throttling feature that will slowdown when `n` errors are encountered would be a great feature. 

A couple points to keep in mind. 
1. If we do slowdown the indexer, it should throttle up after `x` time. My concern here is that if we slowdown to a crawl because of a temporary issue with the node, the entire indexing process will be extremely slow for the entirety of the indexing process because of a temporary node issue.

**Comment by gfreh** [comment]
Hey, @acravenho! Is this still an issue? 

If I'm not wrong, we were waiting for some other issue to be solved. 🤔

**Comment by acravenho** [comment]
I think we can close this now. I'm watching @alexgaribay and @zachdaniel throttling feature which resolved the need for this.
