### ISSUE TITLE
Uncle support in the UI

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#745]
With the addition of #643 we need to add uncle support to the UI. On the block details page if a block included an uncle we should display this here along with the reward. Here is an example from Etherscan: 
https://etherscan.io/block/6348800

There can be more than 1 uncle included in a single block.

**Comment by arthurra** [comment]
@acravenho does this issue also include an Uncle detail page?

**Comment by acravenho** [comment]
@arthurra Yes, the uncle detail page would be very similar to our blocks detail page and would contain info similar to this: https://etherscan.io/uncle/0x824981c854016e83753ed86bb0f5f54cbe49e8753d3b03a4acc5630b38197619

Ideally, we would have a dropdown under the Blocks header for Uncles and would link to a page like this: https://etherscan.io/uncles

The same will be done very soon for block reorgs.

**Comment by arthurra** [comment]
**Uncle Details Mockup**
![uncle-details](https://user-images.githubusercontent.com/1641169/46103577-2a64a580-c19f-11e8-919e-61cf6c42c118.png)


**Uncle Index Mockup**
![uncle-index](https://user-images.githubusercontent.com/1641169/46103615-410afc80-c19f-11e8-991d-7cb563f7b8dd.png)

**Comment by acravenho** [comment]
@arthurra Looking good :+1: One thing which I should have mentioned before is that unlike Etherscan we are tracking the transactions for an uncle. Let's put the tabs down below just like a normal block. I'm not sure how it will look in the end but at least the mockup will be done for them.

**Comment by acravenho** [comment]
I think this is a good time also build in the dropdown under `Blocks` where it will say `Uncles`, and `Forked Blocks (Reorgs)`

**Comment by arthurra** [comment]
oh, right right right. Thanks for the feedback. Will do.
