### ISSUE TITLE
(Bug) Invalid balance

### ISSUE THREAD

**Issue by varasev** [poanetwork/blockscout#767]
We have a smart contract `EmissionFunds` which balance is increased every block (every 5 seconds): https://sokol.poaexplorer.com/address/search/0x523B6539Ff08d72A6C8Bb598Af95bF50c1EA839C

This contract is used for collecting [Increased Emission](https://github.com/poanetwork/RFC/issues/14). Parity engine tops up the balance of this contract on every block.

When I open the page on Blockscout to see its balance, it shows `0 POA`: https://blockscout.com/poa/sokol/address/0x523B6539Ff08d72A6C8Bb598Af95bF50c1EA839C

I think Blockscout doesn't take into account the balance that was accumulated not as a result of transactions.

**Comment by acravenho** [comment]
@varasev I'm trying to figure out where this emission is coming from or is it similar to the [spec.json emission](https://github.com/poanetwork/poa-network-consensus-contracts/blob/master/scripts/parity_setup/spec.json) and needs to be hardcoded?

Is there anyway else for us to track this emission without user input? If not, I'll get this fixed right away.

**Comment by varasev** [comment]
@acravenho The new POA coins are minted by Parity with BlockReward contract: https://wiki.parity.io/Block-Reward-Contract.html - there are no any transactions when minting in this way, so it cannot be tracked. But we can see the balance of the address with minted coins, e.g., using `web3.eth.getBalance`.

**Comment by acravenho** [comment]
@varasev Thank you for the issue. Since there is no way for us to track this we'll have to customize something for this type of `emission`. We should have something out next week.

Also, I'm unable to deploy to blockscout.com because of AWS limiting our account. The build that is currently at https://blockscout.com/poa/sokol is almost 1 month old. As soon as they answer my support ticket I will update the build.

**Comment by acravenho** [comment]
This issue will be resolved with `block_trace` to track all block rewards.

**Comment by acravenho** [comment]
@varasev This should get merged today :+1:

**Comment by varasev** [comment]
@acravenho Seems the changes are not on the blockscout.com yet because https://github.com/poanetwork/blockscout/pull/936 is still open?

**Comment by acravenho** [comment]
@varasev Yes, this is not on blockscout.com. Once it's merged I'll deploy to production. I'll update you when this occurs :+1:

**Comment by acravenho** [comment]
@varasev This is now being deployed to blockscout.com. Thank you for the issue :smile:

**Comment by varasev** [comment]
@acravenho Yes, I see it works now. Thanks!

**Comment by acravenho** [comment]
I'm seeing this error in the logs: 

`14:51:45.602 application=indexer [error] realtime indexer failed to fetch beneficiaries for block 5484473: "Error fetching block reward contract beneficiaries".  Block will be retried by catchup indexer.`

This could be related to #1066
