### ISSUE TITLE
Create a Count table for each address which runs async

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#768]
Count queries from Postgres are extremely slow. Instead of running these queries when a user loads an address page we need to run these async and create a table to store the following data:

- [x] transactions - async function runs when an address was used in a transaction
- [x] token transfer - runs when a token transfer took place between accounts
- [x] collated blocks - runs when an address was the miner of a block
- [ ] uncles - runs when an address received a reward from an uncle (issue #1091 )
- [ ] emission - runs when an address receives a reward for emission from a chain (issue #1149)

**Comment by amandasposito** [comment]
There are a couple of options we thought about how we can solve this problem:

### 1. Process the count info asynchronous

To have a `GenServer` that from time to time counts the addresses and updates the info at the Database.

There are some important points about this approach that need to be taken into consideration, like the way this counts would be done and the time interval between them so we don't end up overloading the database.

### 2. Consolidate the counts info and use async tasks to increment the counters

When we **do not** want to drop the database, the idea is to have some sort of mechanism that consolidates the count info once and updates the database; It would be an independent way to realize the count consolidation.

After having the info consolidate the idea is to map all the places that can trigger new countings and fire `async tasks` that will increment the count at the database level. This way we wouldn't need to run a counting task from time to time, and the info would be more accurate.

### Conclusion

We chose to continue with option 2

**Comment by gfreh** [comment]
Replicating a comment from Andrew at #854
### Slow Query Pages and Examples:

| Issue Type | Page | Example |
| --- | --- | --- |
| slow | Token Page | [Link](https://ethereum-alpha.poaexplorer.com/tokens/0xc16b542ff490e01fcc0dc58a60e1efdc3e357ca6) |
| slow | Token Holders | [Link](https://ethereum-alpha.poaexplorer.com/tokens/0xc16b542ff490e01fcc0dc58a60e1efdc3e357ca6/token_holders) |
| slow | Internal Transactions | [Link](https://ethereum-alpha.poaexplorer.com/address/0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5/internal_transactions) |
| inaccurate count | Address page |  [Link](https://ethereum-alpha.poaexplorer.com/address/0xc16b542ff490e01fcc0dc58a60e1efdc3e357ca6/transactions) |
| slow and inaccurate | Top Accounts Page | [Link](https://ethereum-alpha.poaexplorer.com/accounts) |
| inaccurate count | Homepage | [Link](https://ethereum-alpha.poaexplorer.com) |
| inaccurate count | Transactions Page | [Link](https://ethereum-alpha.poaexplorer.com/txs) |

**Comment by amandasposito** [comment]
The items missing in this issue were moved to separate issues, so I'm closing this one.
