### ISSUE TITLE
Token transfer indexer for ERC20 not importing correctly

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#771]
Please take a look here at this token transfer https://kovan-alpha.poaexplorer.com/tx/0x75c72b701eac71d32cdb93f4210a31e59226f67daf15b49315f43af83b515c8e/logs

This transaction has a single token transfer and should be transferring `0` tokens from this contract `0x8df7287914144d89adf44d8fdd0b72f4990fb2fc`. 

Instead, we're seeing this being transferred: `115792089237316195423570985008687907815158359570495456131559627975555089956886`

### Environment

* Operating System: Mac

### Steps to reproduce

1. Index Kovan
2. View tx `0x75c72b701eac71d32cdb93f4210a31e59226f67daf15b49315f43af83b515c8e`

### Expected behaviour

We should see a token transfer with the correct value.

### Actual behaviour

:boom:

**Comment by acravenho** [comment]
Here is another error on Ethereum Mainnet:

```
22:40:45.568 application=indexer [debug] <Elixir.Indexer.TokenBalance.Fetcher> Errors while fetching TokenBalances through Contract interaction: 
<address_hash: 0x273f7f8e6489682df756151f5525576e322d51a3, contract_address_hash: 0x0000000000000000000000000000000000000000, block_number: 6370084, error: (-32015) VM execution error.> 
<address_hash: 0x273f7f8e6489682df756151f5525576e322d51a3, contract_address_hash: 0x0000000000000000000000000000000000000000, block_number: 6370085, error: (-32015) VM execution error.> 
<address_hash: 0x273f7f8e6489682df756151f5525576e322d51a3, contract_address_hash: 0x0000000000000000000000000000000000000000, block_number: 6370086, error: (-32015) VM execution error.> 
```
Here is the actual log:

https://etherscan.io/tx/0xe54f2e76615f3967afe63ee54869218bad05f5c9b22634452abd22e065b9d692#eventlog

**Comment by alexgaribay** [comment]
For each of the Sokol transactions, they are definitely ERC-721 token transfers and not ERC-20. It looks like the logs page doesn't show the fourth topic of the logs so you aren't seeing the field for ERC-721 token IDs.

The errors from the console are due to it being transferred from the burn address somehow but the data in terms of token transfers is being indexed correctly.

**Comment by alexgaribay** [comment]
@acravenho Is this still an issue? Viewing all topics in the logs has already been merged in.

**Comment by acravenho** [comment]
This has been resolved from everything I can see.
