### ISSUE TITLE
All assets 404ing

### ISSUE THREAD

**Issue by prestonvanloon** [poanetwork/blockscout#784]
When I load http://myip:4000, all of the css and javascript assets 404.

### Environment

Dockerfile: 
https://gist.github.com/prestonvanloon/8e882e5d84f3904b3bd5f5242b525fd4

### Steps to reproduce

See the commands in this gist: https://gist.github.com/prestonvanloon/8e882e5d84f3904b3bd5f5242b525fd4

I also changed check_origin to false in config/prod.exs, but doesn't seem to make a difference.

### Expected behaviour

The assets load

### Actual behaviour

The assets do not load

**Comment by prestonvanloon** [comment]
I believe I have resolved this. There were two problems:

1) The elixir code must be compiled prior to installing npm deps since it depends on some generated code
1) There is a missing step in the instructions where you need to do `npm run deploy` to build the production assets.

**Comment by acravenho** [comment]
Thanks, @prestonvanloon. We'll make the necessary changes. We appreciate your feedback and debugging 😄
