### ISSUE TITLE
ERROR 23514 (check_violation): new row for relation "transactions" violates check constraint "error"

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#786]
```
23:55:19.210 application=db_connection [error] Postgrex.Protocol (#PID<0.13975.165>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.18641.438> exited: an exception was raised:
    ** (Postgrex.Error) ERROR 23514 (check_violation): new row for relation "transactions" violates check constraint "error"

    table: transactions
    constraint: error

Failing row contains (6094158, null, 850000, 6000200000, 120308, \x13ac79bbc989b9f197b7a3f475f2dd80e54fcdd320568dd483bf79cce5dabc..., 7, \x532219b5000000000000000000000000000000000000000000000000000000..., 2018-09-23 09:32:37.511419, 2767, 6438319342571079273262247491881838205916868775656446754405115293..., 4558585383855976376238500888452055256467875417504914754259047184..., 0, 37, 0, 2018-09-23 23:55:18.898505, 2018-09-23 23:55:18.898505, \x4a21fa5e4e9453ada8f2037212b8eec56a3bd5d9faac61cfd39ce7241561c0..., 6383914, \x91bba529a4e469758cd3832305586fd1e8161edd, \x64c0372ebc1f812398bf3e475117fd48d5efb035, null).
        (explorer) lib/explorer/repo.ex:58: anonymous fn/5 in Explorer.Repo.safe_insert_all/3
        (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
        (explorer) lib/explorer/chain/import.ex:837: Explorer.Chain.Import.insert_changes_list/2
        (explorer) lib/explorer/chain/import.ex:818: Explorer.Chain.Import.insert_transactions/2
        (ecto) lib/ecto/multi.ex:421: Ecto.Multi.apply_operation/5
        (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ecto) lib/ecto/multi.ex:411: anonymous fn/5 in Ecto.Multi.apply_operations/5
        (ecto) lib/ecto/adapters/sql.ex:576: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
23:55:47.348 [error] Task #PID<0.6976.438> started from Indexer.Block.Realtime.Fetcher terminating
** (WithClauseError) no with clause matching: {:error, :timeout}
    (indexer) lib/indexer/block/fetcher.ex:92: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer) lib/indexer/block/realtime/fetcher.ex:128: Indexer.Block.Realtime.Fetcher.fetch_and_import_block/2
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<12.57269569/0 in Indexer.Block.Realtime.Fetcher.start_fetch_and_import/3>
    Args: []
```

### Environment

* Operating System: Linux

### Steps to reproduce

Deploy ETH Mainnet

**Comment by sabondano** [comment]
I added this [issue](https://github.com/poanetwork/blockscout/issues/797) without realizing this one existed (#786)  which

**Comment by KronicDeth** [comment]
| Column                             | Value                                                                 |
|------------------------------------|-----------------------------------------------------------------------|
| `cumulative_gas_used`              | `6094158`                                                             |
| `error`                            | `null`                                                                |
| `gas`                              | `850000`                                                              |
| `gas_price`                        | `6000200000`                                                          |
| `gas_used`                         | `120308`                                                              |
| `hash`                             | `\x13ac79bbc989b9f197b7a3f475f2dd80e54fcdd320568dd483bf79cce5dabc...` |
| `index`                            | `7`                                                                   |
| `input`                            | `\x532219b5000000000000000000000000000000000000000000000000000000...` |
| `internal_transactions_indexed_at` | `2018-09-23 09:32:37.511419`                                          |
| `nonce`                            | `2767`                                                                |
| `r`                                | `6438319342571079273262247491881838205916868775656446754405115293...` |
| `s`                                | `4558585383855976376238500888452055256467875417504914754259047184...` |
| `status`                           | `0`                                                                   |
| `v`                                | `37`                                                                  |
| `value`                            | `0`                                                                   |
| `inserted_at`                      | `2018-09-23 23:55:18.898505`                                          |
| `updated_at`                       | `2018-09-23 23:55:18.898505`                                          |
| `block_hash`                       | `\x4a21fa5e4e9453ada8f2037212b8eec56a3bd5d9faac61cfd39ce7241561c0...` |
| `block_number`                     | `6383914`                                                             |
| `from_address_hash`                | `\x91bba529a4e469758cd3832305586fd1e8161edd`                          |
| `to_address_hash`                  | `\x64c0372ebc1f812398bf3e475117fd48d5efb035`                          |
| `created_contract_address_hash`    | `null`                                                                |

From this mapping, the `status` is `0`, which maps to `:error`, but the `error` field is `null` while `internal_transactions_indexed` is not `null`.

We've had similar issues with this constraint with fixes already, so I'm going to close this for now until i resurfaces.
