### ISSUE TITLE
When the Transaction runs out of gas, Developer sees notification box that the Transaction is out of gas.

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#79]

**Comment by vbaranov** [comment]
Example https://blockscout.com/poa/xdai/tx/0xd4b92a66eba98a4db59ea09a143ed3170a1fc54cecdefabe853616353ad1f024/internal_transactions

![Screenshot 2019-11-01 at 19 43 16](https://user-images.githubusercontent.com/4341812/68040840-33983e00-fce0-11e9-883e-73492f34d0df.png)
