### ISSUE TITLE
Can't open the Logs tab for Transactions that are Contract creation calls

### ISSUE THREAD

**Issue by gfreh** [poanetwork/blockscout#799]
If I visit the tx details page for a tx that created a contract, when I click on the `Logs` tab and internal server error is thrown. 

### Environment
- Localhost (on MacOS)
- Sokol (on sokol-alpha.poaexplorer.com)

### Steps to reproduce
1. Visit the tx details for a tx that created a contract, for instance: `0x9b044bd613dc1b4fb723188beb721e0633490d21f1820d60f46b7927b115d88c`.
   - [Sokol](https://sokol-alpha.poaexplorer.com/tx/0x67aeae30e55a6053e44e2d2149ec86a32c41158c25dc27945ca1b36ed3e45b13/internal_transactions)
   - [Localhost](http://localhost:4000/tx/0x67aeae30e55a6053e44e2d2149ec86a32c41158c25dc27945ca1b36ed3e45b13/logs)

2. Click in the `Logs` tab.

### Expected behavior
The `Logs` tab should be loaded.

### Actual behavior
An internal server error is thrown. 

The following screenshot describes the error as thrown in the localhost environment.

![screen shot 2018-09-25 at 11 12 33](https://user-images.githubusercontent.com/1440642/46020105-f3659580-c0b3-11e8-81fe-04d9cefebe1d.png)

**Comment by alexgaribay** [comment]
Yes.
