### ISSUE TITLE
TokenBalance Fetcher querying the burn address instead of the contract address

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#810]
This error is occuring every second on Ethereum Mainnet and periodically on all other chains.

```
00:57:07.636 [debug] <Elixir.Indexer.TokenBalance.Fetcher> Errors while fetching TokenBalances through Contract interaction: 
<address_hash: 0x508132af713459c57a403a18a8f42a9b83c170c0, contract_address_hash: 0x0000000000000000000000000000000000000000, block_number: 4713135, error: (-32015) VM execution error.> 

00:57:07.638 [debug] <Elixir.Indexer.TokenBalance.Fetcher> Errors while fetching TokenBalances through Contract interaction: 
<address_hash: 0x508132af713459c57a403a18a8f42a9b83c170c0, contract_address_hash: 0x0000000000000000000000000000000000000000, block_number: 4713138, error: (-32015) VM execution error.> 

00:57:07.652 [debug] <Elixir.Indexer.TokenBalance.Fetcher> Errors while fetching TokenBalances through Contract interaction: 
<address_hash: 0x24a90f96747941ea47c105fce71cca3704eec45e, contract_address_hash: 0x0000000000000000000000000000000000000000, block_number: 3438081, error: (-32015) VM execution error.> 

```

These errors are for the following transactions:
https://sokol-alpha.poaexplorer.com/tx/0x156845881f467dce644459a34ae825a8e95849a50da79f557956e368d9be9140/token_transfers

https://sokol-alpha.poaexplorer.com/tx/0xeee24cf3ac9bce3ec56f3325a1d8204df6be58cfd28245c7ad1bb2efd13e8795/token_transfers

https://sokol-alpha.poaexplorer.com/tx/0x156845881f467dce644459a34ae825a8e95849a50da79f557956e368d9be9140/token_transfers

### Environment

* Operating System: Linux

### Steps to reproduce

1. Indexer fetching ERC721 tokens.
2. It appears to be using `0x0000000000000000000000000000000000000000` to query the token contract instead of the correct contract address.

**Comment by gfreh** [comment]
Just some more clues to whoever is going to work on this issue:

Looking at the transactions you've provided, it seems that the log message might be wrong. Using the first one as an example, we have:

```
address_hash: 0x508132af713459c57a403a18a8f42a9b83c170c0, contract_address_hash: 0x0000000000000000000000000000000000000000
```
But actually, if we look at the transaction, the contract address hash is `0x508132af713459c57a403a18a8f42a9b83c170c0` and the address for which we are probably trying to retrieve the balance is the burn address.

**Comment by feliperenan** [comment]
We are inverting the keys when we log the error. See:

https://github.com/poanetwork/blockscout/blob/a03e268439050d730cf6bc98c74650eb81c0fafe/apps/indexer/lib/indexer/token_balances.ex#L65

The error always happens when I try to fetch this token balance.

```Elixir
iex(1)> Explorer.Token.BalanceReader.get_balance_of("0x24a90f96747941ea47c105fce71cca3704eec45e", "0x0000000000000000000000000000000000000000", 4097656)
{:error, "(-32015) VM execution error."}
```

I will open a PR to fix the log issue. But I'm not sure about what we have to do with this error 🤔.

**Comment by feliperenan** [comment]
Just complementing the answer above. If I use another address hash, it doesn't throw the error.

```Elixir
iex(3)> Explorer.Token.BalanceReader.get_balance_of("0x24a90f96747941ea47c105fce71cca3704eec45e", "0x6937cb25eb54bc013b9c13c47ab38eb63edd1493", 4097656)
{:ok, 0}
```

**Comment by gfreh** [comment]
We've just tested this against the ERC-721 token I've created before, and we could reproduce the problem. The source code is available at: [0x17dffeb1b44754cb66df570e6b8c9d0f862cb5b3](https://sokol-alpha.poaexplorer.com/address/0x17dffeb1b44754cb66df570e6b8c9d0f862cb5b3/contracts)

Analysing the code, we noticed that the `balanceOf` function requires that the address for the query to be different from the burn address, as seen in the snippet below.

```
/**
 * @dev Returns the number of NFTs owned by `_owner`. NFTs assigned to the zero address are
 * considered invalid, and this function throws for queries about the zero address.
 * @param _owner Address for whom to query the balance.
 */
function balanceOf(address _owner) external view returns(uint256) {
    require(_owner != address(0));
    return ownerToNFTokenCount[_owner];
}
```

The code for the contract I got from https://github.com/0xcert/ethereum-erc721, but it seems that other ERC-721 implementations have that `require` call before returning the balance ([Zeppelin](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC721/ERC721.sol#L60), for instance), we just don't know exactly why. 

Do you have any idea, @acravenho?

**Comment by acravenho** [comment]
@feliperenan @gfreh I'm still doing more research to find a definitive answer but it makes sense for me that it operates this way. If a token is sent to `0x0000000...` it is meant to be deleted. By not allowing us to fetch a balance from this address effectively does this. I wouldn't be opposed to not checking the balance of the burn address for ERC-721 tokens. 

Do you think this is a good solution?

**Comment by feliperenan** [comment]
I think we can go if this solution, it would avoid a lot of requests since we try to fetch the balance again when it fails.

Is there some case that a user wants to check the token balance for the burn address in the ERC-721? 🤔 Because it won't be possible anymore after we do that.

**Comment by acravenho** [comment]
I can live with the burn address not having a balance for ERC721. I can't think of any situation but the community may provide feedback at some point if they feel otherwise.
