### ISSUE TITLE
Support for Parity 2.0

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#818]
We are currently experiencing certain issues regarding unstable versions of Parity < 2.0. With this being said, trying to use Parity 2.0 with BlockScout gives the following error:

`WS Error <Http(Token)>: Invalid byte where token is required.`

### Environment

* Parity: 2.0
* Operating System: Linux

### Steps to reproduce

1. Upgrade the Parity node to > 2.0
2. Start the indexer and view the error.

**Comment by yograterol** [comment]
any update here?

**Comment by acravenho** [comment]
@yograterol We're not experiencing any issues with Parity 2.x. We've tested many versions and are having no issues.

**Comment by yograterol** [comment]
I tested Parity 2.1.3 and got `token is required` I could test with Parity 2.0.x

**Comment by yograterol** [comment]
![image](https://user-images.githubusercontent.com/3322886/47198278-f8270d80-d330-11e8-8cd9-c88c84fa4894.png)

**Comment by acravenho** [comment]
Please share your settings of your node. We now have quite a few 2.06, 2.08, and 2.13 that have no issues connecting. 

```
[websockets]
max_connections = 1000
apis = ["web3","eth","net","parity", "pubsub", "traces"]
```

**Comment by yograterol** [comment]
It was running just to test with the follow settings allowing all:

`--ws-interface all --ws-apis all --ws-origins all --ws-hosts all --jsonrpc-apis all --tracing=on --fat-db=on --pruning=archive --jsonrpc-cors all --jsonrpc-hosts all --jsonrpc-interface all --mode active`

**Comment by acravenho** [comment]
Please define just `"web3","eth","net","parity", "pubsub", "traces"`. I'm thinking that some type of validation is required when you have `personal, signer, parity_accounts, secretstore` enabled.

**Comment by yograterol** [comment]
got it. I will try it.

**Comment by yograterol** [comment]
@acravenho this work properly.

The main issue is when I try to connect to Parity WS with secure connection `wss`.

The issue could be closed.

**Comment by acravenho** [comment]
@yograterol That's great to hear :sweat_smile:
