### ISSUE TITLE
Consolidate Transactions count info in the Address Page

### ISSUE THREAD

**Issue by gfreh** [poanetwork/blockscout#854]
Related to #768 

As a user, I want to navigate to the Address details page and see the number of `transactions` sent by address with an approximate value.

### Acceptance Criteria
- The transactions count in the address details shows how many transactions the address has sent, which is equal to the nonce of the last indexed transaction for that address.
- The transactions count must be consolidated by address.

**Comment by acravenho** [comment]
@gfreh @amandasposito 

### Slow Query Pages and Examples:

| Issue Type | Page | Example |
| --- | --- | --- |
| slow | Token Page | https://ethereum-alpha.poaexplorer.com/tokens/0xc16b542ff490e01fcc0dc58a60e1efdc3e357ca6 |
| slow | Token Holders | https://ethereum-alpha.poaexplorer.com/tokens/0xc16b542ff490e01fcc0dc58a60e1efdc3e357ca6/token_holders |
| slow | Internal Transactions | https://ethereum-alpha.poaexplorer.com/address/0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5/internal_transactions |
| inaccurate count | Address page |  https://ethereum-alpha.poaexplorer.com/address/0xc16b542ff490e01fcc0dc58a60e1efdc3e357ca6/transactions |
| slow and inaccurate | Top Accounts Page | https://ethereum-alpha.poaexplorer.com/accounts |
| inaccurate count | Homepage | https://ethereum-alpha.poaexplorer.com |
| inaccurate count | Transactions Page | https://ethereum-alpha.poaexplorer.com/txs |

**Comment by Lokraan** [comment]
This is also an issue with validation counts.

**Comment by Lokraan** [comment]
What's the timeframe that you need this problem finished by? This issue relates to the issues that I'm currently working on (#735) and I would be willing to work on this in order to solve everything in one fell swoop (including token counts).

**Comment by acravenho** [comment]
@Lokraan We have a few team members that are currently working on this issue. There is a PR open now #867 for token counts and other counts will be done tomorrow and Monday. If you would like to do the validation counts in the format that @amandasposito is using in the PR that would help.

**Comment by Lokraan** [comment]
@acravenho Ok I'll start working on that, thank you.

**Comment by acravenho** [comment]
Awesome, thanks for the help :smiley:

**Comment by acravenho** [comment]
The only issue I see with the acceptance criteria is that the transaction count should be exact if we're now grabbing the `nonce`.
