### ISSUE TITLE
Create neutral template and logo as default BlockScout template

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#860]
The default template for BlockScout should not be themed as POA and instead should be colored a neutral color and the Favicon should be updated to become the logo as well.

**Comment by arthurra** [comment]
<img width="777" alt="screen shot 2018-11-06 at 2 33 06 pm" src="https://user-images.githubusercontent.com/1641169/48088848-0d28eb00-e1d1-11e8-9355-a3cca985e7a4.png">

**Comment by arthurra** [comment]
## BlockScout Theme: Option 1
![blockscout_theme_1](https://user-images.githubusercontent.com/1641169/48090385-be7d5000-e1d4-11e8-8ab2-7d691541f230.png)

**Comment by arthurra** [comment]
BlockScout Theme: Option 2
![blockscout_theme_2](https://user-images.githubusercontent.com/1641169/48090425-d9e85b00-e1d4-11e8-9d6a-cadd2376e34c.png)

**Comment by arthurra** [comment]
BlockScout Theme: Option 3
![blockscout_theme_3](https://user-images.githubusercontent.com/1641169/48090439-ed93c180-e1d4-11e8-958c-058469ec97f8.png)
