### ISSUE TITLE
Improve Internal Transactions listing performance

### ISSUE THREAD

**Issue by gfreh** [poanetwork/blockscout#872]
## Description
Listing Internal Transactions for some specific Addresses with lots of Txs is very slow.

## Steps to Reproduce
Visit one of the examples below.
 
### Ethereum Mainnet: 
https://ethereum-alpha.poaexplorer.com/address/0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5/internal_transactions

The first time you visit this tab, it takes lots of seconds to load, but the following ones it loads faster (possibly due to some CDN).

### Sokol: 
https://www.blockscout.com/poa/sokol/address/0x95426f2bc716022fcf1def006dbc4bb81f5b5164/internal_transactions

For this one, it's even worst because the query takes so much time to load that it times out in the CDN. Also, it returns no result at all if you run the query directly in the DB. That happens because we only list internal transactions that are not of the type `call` or that have siblings.

**Comment by Lokraan** [comment]
I am willing to work on this issue if no one has started to.

The solutions I am thinking of are to:
* Directly store the transaction ids somewhere (database, :ets table) then query the database for those ids.
* Optimize the current queries.

After reading around I think the solution could entail something like this http://engineering.liefery.com/2018/02/27/the-mysterious-query.html

**Comment by amandasposito** [comment]
@acravenho @Lokraan Sure, we need to optimize those queries. 

There is a `count` in this page query that may be one of the reasons for the performance issue.

But I'm missing the point about why store the transaction ids somewhere may help with this problem. 🤔

**Comment by amandasposito** [comment]
@Lokraan Have you already started working on this issue? 

This is the next issue in our priority list, I'll pull it right now to work on this.

**Comment by Lokraan** [comment]
The only changes I've made so far is this: 
```elixir
 @spec where_transaction_has_multiple_internal_transactions(Ecto.Query.t()) :: Ecto.Query.t()
  def where_transaction_has_multiple_internal_transactions(query) do
    where(
      query,
      [internal_transaction, transaction],
      internal_transaction.type != ^:call or
        fragment(
          """
            EXISTS
              (SELECT 1
              FROM internal_transactions AS sibling
              WHERE sibling.transaction_hash = ?)
          """,
          transaction.hash
        )
    )
  end
```

This didn't work and failed two tests: 
```
 test transaction_to_internal_transactions/1 excludes internal transaction of type call with no siblings in the transaction (Explorer.ChainTest)
     test/explorer/chain_test.exs:1549
     Expected truthy, got false
     code: assert Enum.empty?(result)
...
  2) test address_to_internal_transactions/1 excludes internal transactions of type `call` when they are alone in the parent transaction (Explorer.ChainTest)
     test/explorer/chain_test.exs:1427
     Expected truthy, got false
     code: assert Enum.empty?(Chain.address_to_internal_transactions(address))
```

This is because `EXISTS` returns true if the subquery inside it returns null, to solve it I changed the fragment to:
```sql
fragment(
          """
          (SELECT COUNT(sibling.id)
          FROM internal_transactions AS sibling
          WHERE sibling.transaction_hash = ?
          LIMIT 2
          )
          """,
          transaction.hash
        ) > 1
```
