### ISSUE TITLE
Token Transfer card duplicated in the Account's Transaction List

### ISSUE THREAD

**Issue by gfreh** [poanetwork/blockscout#883]
In the Account's Transactions tab, the Token Transfer card is duplicated when the parent transaction has multiple Token Transfers in it.

### Environment
* Locally 
* Sokol (www.blockscout.com/poa/sokol)

### Steps to reproduce
1. Visit the transactions list for the account: `0x6937cb25eb54bc013b9c13c47ab38eb63edd1493`: 
   - [Locally](http://localhost:4000/address/0x6937cb25eb54bc013b9c13c47ab38eb63edd1493/transactions)
   - [Sokol](https://www.blockscout.com/poa/sokol/address/0x6937cb25eb54bc013b9c13c47ab38eb63edd1493/transactions)
2. Search for the following transaction hash: `0xbed5592df6107bc8475ea92b91178823d4c1772aaa1b34381ce5c3f2b43dc7eb`

### Expected behaviour

There should be only one Token Transfer card per transaction hash.

### Actual behaviour

There are two cards for that transaction hash, with the same token transfers in both of them. Notice that both cards are identical, card, although the token transfers in it might be sorted differently.

![screen shot 2018-10-08 at 15 58 23](https://user-images.githubusercontent.com/1440642/46628409-da2d0200-cb13-11e8-9725-059b421009fa.png)

**Comment by vbaranov** [comment]
Release 2.0.0 installed to Sokol instance. Issue resolved.
