### ISSUE TITLE
Blockscout.com have a 3 minutes delay for eth mainnet blocks

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/blockscout#892]
![image](https://user-images.githubusercontent.com/9360827/46695065-5cc0ca80-cbc3-11e8-9b0e-a913f1983c4e.png)

Great progress! But I noticed that issue and i think the screenshot is self explanatory.

**Comment by acravenho** [comment]
Thanks. We're aware of the delay. It's something that will be worked on over time to optimize the catchup indexer and realtime indexer.

**Comment by igorbarinov** [comment]
Also, the deployed instance for Ethereum main network is still performing initial indexing.

**Comment by rstormsf** [comment]
@igorbarinov 
I thought it's live
![image](https://user-images.githubusercontent.com/9360827/46706719-d91ad400-cbea-11e8-890c-ffaeb1e0e5f5.png)

**Comment by acravenho** [comment]
We're working on providing a better user experience during this indexing stage by providing the user with an indexing bar showing that indexing is still in process. I'm closing this issue for #899
