### ISSUE TITLE
Blockscout sokol missed blocks to process

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/blockscout#894]
It's been 59 minutes since blockscout on sokol doesn't process my transactions:

![image](https://user-images.githubusercontent.com/9360827/46706554-fdc27c00-cbe9-11e8-85e9-5dcb7b7e8da9.png)

https://blockscout.com/poa/sokol/address/0xcf02856827109d4c68c33210566d71442c6b9d77/transactions

For example: 

I have a tx from blockscount with nonce 240 which still shows as pending.
While tx from same account with nonce 244 shows as confirmed.

![image](https://user-images.githubusercontent.com/9360827/46706617-4e39d980-cbea-11e8-992b-1fbfe8edfd75.png)

also loading same tx hash in etherchain-light explorer, shows the tx as processed(mined)
https://sokol-explorer.poa.network/tx/0x41cd2a9279ec0a054cfe691a0c84a495af97ad1fff5328aac6fda05ff9beafa8
vs
https://blockscout.com/poa/sokol/tx/0x41cd2a9279ec0a054cfe691a0c84a495af97ad1fff5328aac6fda05ff9beafa8/internal_transactions

**Comment by acravenho** [comment]
1. We're aware of the skipping blocks and we have a dev looking into this sudden issue. There is a process in place that checks for skipped blocks 3 separate times in 500ms intervals after receiving the `newHeads` subscription. This is check is failing or the node is failing (check logs)

2. After a full index any skipped block will be picked up by the catchup indexer in 1 minute intervals. 

3. This issue will remain open until skipped blocks are resolved.

**Comment by acravenho** [comment]
This is the error from the logs:

```
05:42:45.628 application=indexer [error] realtime indexer failed to fetch receipts for block 4980695: [%{code: -32602, data: %{block_hash: "0xac530cb31e909336fb6e6fd761bfa8b8623966012372fc7d690661ef1aea6c14", block_number: 4980695, from_address_hash: "0x95426f2bc716022fcf1def006dbc4bb81f5b5164", gas: 21000, gas_price: 1000000000, hash: "0x94a5dcc1cde9f9e22e7f65c1089d2228b582321a3f059fd24c34a950898ce152", index: 0, input: "0x", nonce: 303247, r: 69118547879708179791065428742523057202470650967803113235108907077785001970443, s: 54153004861025551521153591678730982037409145164054958054998469013603407393802, to_address_hash: "0xe797a1da01eb0f951e0e400f9343de9d17a06bac", v: 27, value: 20000000000}, message: "Not Found"}].  Block will be retried by catchup indexer.
```
The node either didn't sync the receipts yet or the data is corrupted. 

Upgrading to Parity 2.* should resolve this.
