### ISSUE TITLE
Contract Verification on private network fails with Internal server error

### ISSUE THREAD

**Issue by abcoathup** [poanetwork/blockscout#895]
Contract Verification on private network fails with Internal server error.
Unclear if this is supported, a software defect or an issue with config/setup.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.7.3 (compiled with Erlang/OTP 20)
* Operating System: Ubuntu 16.04.5 LTS
* Private network: Azure PoA consortium https://docs.microsoft.com/en-au/azure/blockchain/templates/ethereum-poa-deployment

### Steps to reproduce

Setup BlockScout using following instructions with setup script.
https://github.com/Azure-Samples/blockchain/blob/master/ledger/template/ethereum-on-azure/technology-samples/blockscout/README.md

Deploy contract: https://github.com/Azure-Samples/blockchain/tree/master/ledger/template/ethereum-on-azure/performance-benchmarking

In BlockScout navigate to Contract Address (from Contract Creation transaction)

Navigate to Code tab and press Verify & Publish button
http://[private network BlockScout]/address/[contract address]/contract_verifications/new

### Expected behaviour

Verify & Publish should display a form to provide the contract details to verify

### Actual behaviour

Web page only shows:
Internal server error

**Comment by acravenho** [comment]
@abcoathup Thank you for reporting the issue. I think the issue might be with your Erlang Version. `21.05` is what is currently required. Can you please upgrade and try again?

**Comment by abcoathup** [comment]
I assume that Erlang is up to date.

The full version output is:
`admin@blockscout:~$ elixir --version`
`Erlang/OTP 21 [erts-10.1] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]`

`Elixir 1.7.3 (compiled with Erlang/OTP 20)`

Attempting to show the minor version:
`admin@blockscout:~$ erl -eval '{ok, Version} = file:read_file(filename:join([code:root_dir(), "releases",` `erlang:system_info(otp_release), "OTP_VERSION"])), io:fwrite(Version), halt().' -noshell`
`21.1`

**Comment by marius3000** [comment]
Check if you have SECRET_KEY_BASE environment variable defined. AFAIK it should be a random string

**Comment by acravenho** [comment]
`mix phx.gen.secret` will generate the `SECRET_KEY_BASE`. It should be 64 bytes.

**Comment by vbaranov** [comment]
@abcoathup could you please try contract verification with the latest Blockscout release: we made a lot of enhancements regarding the verification since your issue posted. If the issue is reproducible again please reopen the issue
