### ISSUE TITLE
BlockScout crashes from time to time on Kovan

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/blockscout#896]
![image](https://user-images.githubusercontent.com/9360827/46711777-a381e500-cc02-11e8-89eb-beb6f7d40a13.png)

https://blockscout.com/eth/kovan/address/0x0039f22efb07a647557c7c5d17854cfd6d489ef3/transactions

Can't confirm the steps, sometimes when I go to home page, enter my eth address, hit Enter and then...it crashes. 
If I go directly using URL, it works

**Comment by acravenho** [comment]
This occurs usually when there are no available connections on the instance. I'll look to deploy with a larger instance if this continues.

**Comment by acravenho** [comment]
Timeouts and other performance improvements have occurred fixing this issue
