### ISSUE TITLE
Remove localhost from API docs

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/blockscout#897]
![image](https://user-images.githubusercontent.com/9360827/46711984-ad581800-cc03-11e8-912f-454b50217e0a.png)

**Comment by acravenho** [comment]
Fixed, being deployed in the next few hours

**Comment by KronicDeth** [comment]
@acravenho it would probably be best if the load balancer was setup to send a header with the correct external root URL that everything can use.  It should be able to add that in the same section that rewrites the URLs in the load balancer config.

**Comment by acravenho** [comment]
Fixed on all deployments
