### ISSUE TITLE
Total count of Token addresses are not correct on Kovan network

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/blockscout#898]
![image](https://user-images.githubusercontent.com/9360827/46712194-a8e02f00-cc04-11e8-9f54-2329c2eca6d9.png)

https://blockscout.com/eth/kovan/address/0x0039f22efb07a647557c7c5d17854cfd6d489ef3/transactions
https://kovan.etherscan.io/address/0x0039f22efb07a647557c7c5d17854cfd6d489ef3

**Comment by acravenho** [comment]
This chain is still indexing, internal transactions, tokens, and token balances.  There is no bug here unless it's fully indexed and the count is still not accurate.
