### ISSUE TITLE
Contract Address Pending

### ISSUE THREAD

**Issue by aristt** [poanetwork/blockscout#913]
*Describe your issue here.*

### Environment

Erlang/OTP 21 [erts-10.1] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1] [hipe]

Elixir 1.7.3 (compiled with Erlang/OTP 20)

Ubuntu 16.04.3 LTS

Quorum: Geth/v1.7.2-stable-99a83767/linux-amd64/go1.9.3

Consensus: IBFT

### Issue

Everything seems to work fine on my Quorum environment, except
- transactions showing up as not validated (but they are validated)
- contract addresses not shown (instead, the label "Contract Address Pending" is shown)

*Tell us what happens instead.*
![image](https://user-images.githubusercontent.com/13457276/46801641-844a9b00-cd5b-11e8-8e1b-b0007e06398c.png)

**Comment by acravenho** [comment]
Gethv1.7.2 appears to be pre-Byzantium which did not provide `status` fields on transactions. The only accurate method to determine a transaction status is to check for errors in the internal transactions. We currently do not support debug_tracetransaction in Geth and cannot derive the status or contract creation address.

**Comment by aristt** [comment]
Thanks @acravenho. The issue then will be fixed when Quorum will be rebased with Geth 1.8.

**Comment by d4nd** [comment]
I'm facing this very issue with Geth 1.8.3 Istanbul network.

**Comment by acravenho** [comment]
@d4nd This has been resolved by #998. I'm running Geth locally with no issues currently. Can you please elaborate on what you're experiencing. There is also a PR to be merged shortly adding support for Geth internal transactions.

**Comment by d4nd** [comment]
May I report this in a new issue or it's okay doing it here?

If I may:
- Every transaction are: "(Awaiting internal transactions for status)"
- There's a info on page header that states: " Indexing Tokens - We're indexing this chain right now. Some of the counts may be inaccurate."

But theses scenario never changes.

**Comment by acravenho** [comment]
Until the internal transactions, PR (#998) is merged that message will persist. You can manually remove the message by removing the lines here:

https://github.com/poanetwork/blockscout/blob/3571c61bbeb1c09c482ca1121fa473faac4eff42/apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex#L24-L33

**Comment by d4nd** [comment]
Oh, I see. Thank you.

And about the transaction status? I'm running go-ethereum 1.8.3 and there is no transaction's status fields.

**Comment by acravenho** [comment]
If you're running BlockScout on a chain that is pre-Byzantium there is no `status` output which is why we can't determine the `status` of the transaction without fetching the internal transactions :+1:

**Comment by acravenho** [comment]
Just have to wait for #1072 to merge and then the internal transactions will all be fetched removing this message.
