### ISSUE TITLE
Color Scheme and Logo for new Networks

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#922]
Colors and Logos for  Tobalaba, Expanse, Musicoin, Ellaism, Easthub, and Social.

**Comment by arthurra** [comment]
@acravenho I'm having trouble tracking down any resources for Easthub and Social. Can you provide some links or material that might point me in the right direction?

**Comment by acravenho** [comment]
@arthurra 

Ether Social - https://ethersocial.network/
Easthub - It was easthub.io (ignore for now)
GoChain -  https://gochain.io/
WanChain - https://wanchain.org/
TomoChain - https://tomochain.com/
Pirl - https://pirl.io/en

**Comment by arthurra** [comment]
![tobalaba](https://user-images.githubusercontent.com/1641169/47096276-d593d800-d1fc-11e8-93b1-4112b7cc8f3d.png)

**Comment by arthurra** [comment]
![expanse](https://user-images.githubusercontent.com/1641169/47096943-47b8ec80-d1fe-11e8-9895-91311faff217.png)

**Comment by arthurra** [comment]
![musicoin](https://user-images.githubusercontent.com/1641169/47098306-f9591d00-d200-11e8-86ad-026e254efe49.png)

**Comment by arthurra** [comment]
![musicoin](https://user-images.githubusercontent.com/1641169/47098798-e5fa8180-d201-11e8-9032-5825d75e664e.png)

**Comment by arthurra** [comment]
![ellaism](https://user-images.githubusercontent.com/1641169/47104396-5360df00-d20f-11e8-93a7-a1db015d1cb6.png)

**Comment by arthurra** [comment]
![social](https://user-images.githubusercontent.com/1641169/47108449-ac357500-d219-11e8-9085-8e7a00151fdf.png)

**Comment by arthurra** [comment]
![gochain](https://user-images.githubusercontent.com/1641169/47113688-aba3db00-d227-11e8-9ee4-81140db7aee0.png)

**Comment by arthurra** [comment]
![tomochain](https://user-images.githubusercontent.com/1641169/47115227-e9a2fe00-d22b-11e8-97c0-7edbc43fbc69.png)

**Comment by acravenho** [comment]
@pashagonchar  Do you have any changes that you would like to see on these color and logo mockups?

**Comment by arthurra** [comment]
![pirl](https://user-images.githubusercontent.com/1641169/47115675-4bb03300-d22d-11e8-8fad-ae0a52e2a84a.png)

**Comment by yograterol** [comment]
@arthurra We're syncing blockscout with CLO too, we will use blockscout as main explorer.

**Comment by acravenho** [comment]
@yograterol We'll have your theme ready early this week. Thanks for your support :+1:

**Comment by arthurra** [comment]
![callisto](https://user-images.githubusercontent.com/1641169/47366791-64e13580-d6ac-11e8-8109-95edfb83b4e6.png)

**Comment by acravenho** [comment]
@yograterol What do you think about the color scheme?
