### ISSUE TITLE
Dai <> xDai balances are not being calculated

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#932]
When `Dai` is sent from Ethereum to the `xDai` chain, the value transfer is not occurring in the parent transaction or the internal transaction, therefore the receiving address is not having its balance checked.

To fix this, we need to monitor the logs for a first topic of `0x3c798bbcf33115b42c728b8504cff11dd58736e9fa789f1cda2738db7d696b2a`. This hash shows the coin transfer function of the bridged coin. The `to` and `from` addresses are the second and third topic respecitvely. 

The `data` field is the amount being transferred to the receiving address.

**Comment by feliperenan** [comment]
More info about the issue:

In this transaction: https://blockscout.com/poa/dai/tx/0x1d5066d30ff3404a9306733136103ac2b0b989951c38df637f464f3667f8d4ee/logs

The DAI network is minting coins and we don't procces it properly. Today, we only can see it looking at the log: 

```
Address: 0x867305d19606aadba405ce534e303d0e225f9556

Topics
[0] 0x3c798bbcf33115b42c728b8504cff11dd58736e9fa789f1cda2738db7d696b2a
[1] 0x0000000000000000000000009a4a90e2732f3fa4087b0bb4bf85c76d14833df1
[2] 0x0000000000000000000000007301cfa0e1756b71869e93d4e4dca5c7d0eb0aa6

Data: 0x0000000000000000000000000000000000000000000000001bc16d674ec80000
```

It means that we should have a internal transaction where:

to_address is: `0x9a4a90e2732f3fa4087b0bb4bf85c76d14833df1`
from_address is: `0x7301cfa0e1756b71869e93d4e4dca5c7d0eb0aa6`
data: the value transfered enconded

As we don't process it, we don't update the Address balance properly (even we don't index that address if he appears only in this transaction). 

We need to:
* We should not create an internal transaction for this. This is a minted coin which is performed on the VM level from the smart contract.
* We should create the address if it does not exist.
* There is no transaction so no values need to be updated.
* We should run this address through the CoinBalance fetcher though.
