### ISSUE TITLE
Query optimization on the address page

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#947]
Here are a few addresses that `blockscout.com/eth/mainnet` is having issues loading. By clicking on the page multiple times the speed does increase loading the page faster but this is not the optimal user experience.

- [0x2a0c0dbecc7e4d658f48e01e3fa353f44050c208](https://blockscout.com/eth/mainnet/address/0x2a0c0dbecc7e4d658f48e01e3fa353f44050c208/transactions)
- [0x0681d8Db095565FE8A346fA0277bFfdE9C0eDBBF](https://blockscout.com/eth/mainnet/address/0x0681d8Db095565FE8A346fA0277bFfdE9C0eDBBF/transactions)
- [0x564286362092d8e7936f0549571a803b203aaced](https://blockscout.com/eth/mainnet/address/0x564286362092d8e7936f0549571a803b203aaced/transactions)
- [0xfbb1b73c4f0bda4f67dca266ce6ef42f520fbb98](https://blockscout.com/eth/mainnet/address/0xfbb1b73c4f0bda4f67dca266ce6ef42f520fbb98/transactions)
- [0x3f5ce5fbfe3e9af3971dd833d26ba9b5c936f0be](https://blockscout.com/eth/mainnet/address/0x3f5ce5fbfe3e9af3971dd833d26ba9b5c936f0be/transactions)

### Environment

* Operating System: Linux

### Steps to reproduce

Visit any of the links above. Some of the pages do not load at all.

### Expected behaviour

1. 1-2 second load times.

### Actual behaviour

:boom:

**Comment by brwatanabe** [comment]
All those listed addresses are now fully loading and taking around 4 to 8 seconds to load each one. A new address was found that is not loading at all and we are now looking at.

* 0xf11601553a4ad20cc9792b408983fe155d17ba74

**Comment by amandasposito** [comment]
@acravenho Do you think we can close this issue? Maybe after the PR #1079 is deployed 🤔

**Comment by acravenho** [comment]
Yes, I just deployed @fvictorio changes and they're working well on Mainnet :+1:
