### ISSUE TITLE
Geth token contract and token balances not working correctly

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#964]
When a token identified on Rinkeby, no information is being imported into the token table. 

1. Either there is a node issue which is causing us to not receive the data.
2. Our `eth_call` is not set up correctly for Geth. I doubt this is the case, but I have not tested it.

Rinkeby node: https://rinkeby.infura.io
Internal Rinkeby node: check Slack

**Comment by alexgaribay** [comment]
It looks like geth requires two arguments to be provided to `eth_call`. For parity, it looks like the 2nd argument is implicit with the value of `"latest"` meaning the most recent data available. If we default the 2nd argument to be `"latest"` in code, everything looks to be working as expected.
