### ISSUE TITLE
Geth Clique blocks always mined by 0x000

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#968]
In order to find the miner for Geth Clique blocks, we must use `clique.getSignersAtHash('0x86837f148f096f1ce53463ecb4acf3d99bae0b2f0297dacbb6d33fcfdb7c04d9')`. 

It also appears that we may be able to extract the signer from the `extraData` field. https://github.com/ethereum/EIPs/issues/225

**Comment by alexgaribay** [comment]
It seems that there is a way to extract it but it require translating [Go's implementation](https://github.com/ethereum/go-ethereum/issues/15651#issuecomment-379877201) to Elixir. Briefly looking at the code, it looks like we might need to capture more field about the block to perform what we need for generating some hashes.

**Comment by acravenho** [comment]
Thanks Alex, we do receive the `extraData` during our `eth_getBlockByHash` call to Geth. We should be able to parse the `signer` address from this signature.

**Comment by APshenkin** [comment]
If it helps, there is also JS implementation
https://github.com/ethereum/go-ethereum/issues/17454#issuecomment-414975770
