### ISSUE TITLE
Open the code tab by default for verified smart-contract

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#979]
It would be nice if the `code` tab will be opened by default for already verified before smart-contract while opening the address of smart-contract:

![screen shot 2018-10-24 at 13 43 16](https://user-images.githubusercontent.com/4341812/47425375-d1cefb00-d792-11e8-87d7-1288d42d116e.png)

**Comment by acravenho** [comment]
We could do this but do you think this is the desired experience for most users?

**Comment by vbaranov** [comment]
I just thought that it will emphasise more, that smart-contract has been verified. Because a check mark on the `Code` tab is visually pale. But, scarcely, it will be the desired experience for most users. Thus, I'm gonna to close it.

**Comment by acravenho** [comment]
I'll go ahead and create another issue to make the `Code` tab more visible for verified contracts.
