### ISSUE TITLE
Address is not recognized as a contract address

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#980]
`0xd4543fe1ded1637768516a3ef35614f91f715370` is not recognized as a smart-contract address in Ropsten blockchain. I do not see the bytecode of it and I am not able to verify it.

### Environment

* BlockScout link: https://blockscout.com/eth/ropsten
* Operating System: Mac OS

### Steps to reproduce

- Open https://blockscout.com/eth/ropsten/address/0xd4543fe1ded1637768516a3ef35614f91f715370
- Or search specified address from the main link of BlockScout for Ropsten

### Expected behaviour

- Open https://blockscout.com/eth/ropsten/address/0xd4543fe1ded1637768516a3ef35614f91f715370
- There is a `code` tab on the contract address page

### Actual behaviour

- Open https://blockscout.com/eth/ropsten/address/0xd4543fe1ded1637768516a3ef35614f91f715370
- There is NO a `code` tab on the contract address page

**Comment by vbaranov** [comment]
The same issue is for address `0x445b4c58113c784640a978cfe39b0065118b91a5` in Ethereum Mainnet

**Comment by acravenho** [comment]
Thank you for the issue. 

These chains have not finished indexing. Internal transactions are fetched and run async and will take several weeks to finish. We can run the indexer much faster but we do not have nodes that can handle these requests. This is a painful process but there isn't much we can do at this time. Sorry for the inconvenience.
