### ISSUE TITLE
Opening of transaction's page causes "Internal server error"

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#981]
https://blockscout.com/poa/core/tx/0xcecf588ee1aa99d7a4299562e49b692f7cc02a40dec1e07b93c1f5eb8d83b053/internal_transactions

The opening of this transaction's page causes "Internal server error"

This contract https://blockscout.com/poa/core/address/0x6f4aadbb17789b4f5e9e97d456dc4e01b117ccb3/transactions was created with this transaction

### Environment

* Blockchain: POA Core
* Operating System: Mac OS

### Steps to reproduce

- open https://blockscout.com/poa/core/tx/0xcecf588ee1aa99d7a4299562e49b692f7cc02a40dec1e07b93c1f5eb8d83b053/internal_transactions

### Expected behaviour

- open https://blockscout.com/poa/core/tx/0xcecf588ee1aa99d7a4299562e49b692f7cc02a40dec1e07b93c1f5eb8d83b053/internal_transactions
- page is opened

### Actual behaviour

- open https://blockscout.com/poa/core/tx/0xcecf588ee1aa99d7a4299562e49b692f7cc02a40dec1e07b93c1f5eb8d83b053/internal_transactions
- "Internal server error" on the page

**Comment by acravenho** [comment]
Yes, sorry. We have a very large migration happening in the background from this PR: https://github.com/poanetwork/blockscout/pull/928. This was started about 25 minutes ago and will probably take another hour or so.

**Comment by vbaranov** [comment]
Oh, it seems the tx's page works now. Can be closed.

**Comment by acravenho** [comment]
Wow, that was quick. It took 3 hours yesterday on `sokol`. I'm glad it didn't take too long :smile:
