### ISSUE TITLE
There is no `prev` button in the pagination of the list of txs

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#982]
There are maximum 50 transactions are displayed on the account page.
If I have more then 100 transactions, and I am at the last page, where 101+ txs, I cannot return to the page with 51 - 100 txs in one click.

The solution would be to add left `prev/newer` button for pagination

![screen shot 2018-10-24 at 20 36 14](https://user-images.githubusercontent.com/4341812/47450337-a87f9080-d7cd-11e8-9f64-6c5af7b8ab38.png)

**Comment by acravenho** [comment]
@vbaranov We have a future issue for infinite scroll and is the reason the pagination is setup in this fashion. I can see if we can provide a `previous` button until that issue is completed.

**Comment by vbaranov** [comment]
#1930
