### ISSUE TITLE
Add ability to not index entire blockchain

### ISSUE THREAD

**Issue by APshenkin** [poanetwork/blockscout#992]
*Describe your issue here.*
This is enhancement proposal.

For several projects you don't need the entire blockchain indexing. You may need only last month or year or n numbers of blocks. It will be cool to add ability to set block or date from where start block indexing. This will reduce amount of disk used for several projects and also speed up syncing. e.g. you want to take transaction only from last month. If you will be able to set limit setting, than you will reduce disk size, CPU usage and indexing will be very fast

**Comment by acravenho** [comment]
@APshenkin I like this idea. We should be able to get this done soon.

**Comment by naheed** [comment]
this would be a welcome feature and help reduce costs.

**Comment by vbaranov** [comment]
This feature has been already implemented here: https://github.com/poanetwork/blockscout/pull/1611

In order to start indexing from a specific block define `FIRST_BLOCK` ENV var which the number of a first block from where you would like to start indexing.

**Comment by igorbarinov** [comment]
@vbaranov let's add it to the installation instruction somewhere

**Comment by vbaranov** [comment]
I added the aforementioned ENV var to the supported list: https://forum.poa.network/t/faq-environment-variables/1814

**Comment by greatdex** [comment]
Is this done?
