### ISSUE TITLE
API txlist sort list by value

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#995]
Feature request by a partner to sort the `txlist` API endpoint by `value` or `block_number`

cc: @sabondano

**Comment by vbaranov** [comment]
Sorting by `block_number` is available in `txlist` API endpoint

<img width="1103" alt="Screenshot 2020-04-10 at 16 27 54" src="https://user-images.githubusercontent.com/4341812/78994257-455ff600-7b48-11ea-831f-e019415998da.png">
